"""WebLayerMixin — templates for main.py, schemas.py, dependencies.py, exceptions.py, routes.py."""

from __future__ import annotations

from .spec import FieldSpec
from ._types import _PY_TYPES


class WebLayerMixin:
    """Generates the FastAPI-facing layer: app entrypoint, schemas, deps, routes."""

    def _main(self) -> str:
        pg_import = "from .database import engine\nfrom .models import Base\n" if self.s.is_sql else ""
        pg_create = (
            ("    async with engine.begin() as conn:\n        await conn.run_sync(Base.metadata.create_all)\n")
            if self.s.is_sql
            else ""
        )
        pg_dispose = "    await engine.dispose()\n" if self.s.is_sql else ""

        mongo_import = "from .database import init_db, close_db\n" if self.s.is_mongo else ""
        mongo_init = "    await init_db()\n" if self.s.is_mongo else ""
        mongo_close = "    await close_db()\n" if self.s.is_mongo else ""

        ping_import = "from .database import ping_db\n" if self.s.is_sql else "from .database import ping_db\n"

        return f'''\
"""
{self.cls} Microservice — auto-generated by MonkeyBrain Codegen.
DO NOT EDIT — regenerate from spec instead.
"""
from __future__ import annotations

import logging
import os
from contextlib import asynccontextmanager

from fastapi import FastAPI, Request
from fastapi.middleware.cors import CORSMiddleware
from fastapi.responses import JSONResponse

{pg_import}{mongo_import}{ping_import}
from .routes import router
from .exceptions import ServiceError

logger = logging.getLogger("{self.n}")

@asynccontextmanager
async def lifespan(app: FastAPI):
{pg_create}{mongo_init}    logger.info("{self.cls} service started")
    yield
{pg_dispose}{mongo_close}    logger.info("{self.cls} service stopped")


app = FastAPI(
    title="{self.cls} Service",
    description={self.s.description!r},
    version={self.s.version!r},
    lifespan=lifespan,
    openapi_tags=[{{"name": "{self.s.domain}", "description": "Operations for {self.cls}"}}],
)

app.add_middleware(
    CORSMiddleware,
    allow_origins=os.environ.get("CORS_ORIGINS", "*").split(","),
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

app.include_router(router, prefix="/{self.tbl}", tags=["{self.s.domain}"])


@app.exception_handler(ServiceError)
async def service_error_handler(request: Request, exc: ServiceError) -> JSONResponse:
    return JSONResponse(status_code=exc.status_code, content={{"detail": exc.detail}})


@app.get("/health", tags=["Health"])
async def health() -> dict:
    db_ok = await ping_db()
    status = "healthy" if db_ok else "degraded"
    return {{"status": status, "service": "{self.n}", "version": {self.s.version!r}, "db": db_ok}}


@app.get("/metrics", tags=["Health"])
async def metrics() -> dict:
    return {{"service": "{self.n}", "version": {self.s.version!r}}}
'''

    # ------------------------------------------------------------------
    # schemas.py
    # ------------------------------------------------------------------

    def _schemas(self) -> str:
        imports = self._schema_imports()
        base_fields = self._schema_fields(patch=False)
        patch_fields = self._schema_fields(patch=True)
        ts_response = ""
        if self.s.timestamps:
            ts_response = "    created_at: datetime\n    updated_at: datetime\n"
        sd_response = ""
        if self.s.soft_delete:
            sd_response = "    deleted_at: Optional[datetime] = None\n"

        id_type = "str" if self.s.is_mongo else "UUID"

        return f'''\
"""Pydantic schemas — request validation and response serialisation."""
from __future__ import annotations

{imports}

class {self.cls}Base(BaseModel):
{base_fields}

class {self.cls}Create({self.cls}Base):
    pass


class {self.cls}Update({self.cls}Base):
    pass


class {self.cls}Patch(BaseModel):
{patch_fields}

class {self.cls}Response({self.cls}Base):
    id: {id_type}
{ts_response}{sd_response}
    model_config = ConfigDict(from_attributes=True)


class {self.cls}ListResponse(BaseModel):
    items: list[{self.cls}Response]
    total: int
    limit: int
    offset: int
    has_more: bool
'''

    def _schema_imports(self) -> str:
        types_needed = {f.type for f in self.s.fields}
        lines = [
            "from typing import Any, Optional",
            "from pydantic import BaseModel, ConfigDict, Field",
        ]
        if "datetime" in types_needed or self.s.timestamps or self.s.soft_delete:
            lines.append("from datetime import datetime")
        if "uuid" in types_needed or (self.s.is_sql and not self.s.is_mongo):
            lines.append("from uuid import UUID")
        if "decimal" in types_needed:
            lines.append("from decimal import Decimal")
        if any(f.enum for f in self.s.fields):
            lines.append("from typing import Literal")
        return "\n".join(lines)

    def _schema_fields(self, patch: bool) -> str:
        lines = []
        for f in self.s.fields:
            py_type = self._field_python_type(f)
            validators = self._field_validators(f)
            default_part = ""
            if patch:
                py_type = f"Optional[{py_type}]"
                if validators:
                    default_part = f" = Field(default=None, {validators})"
                else:
                    default_part = " = None"
            elif f.default is not None:
                val = repr(f.default)
                default_part = f" = Field(default={val}" + (f", {validators}" if validators else "") + ")"
            elif not f.required or f.nullable:
                if validators:
                    default_part = f" = Field(default=None, {validators})"
                else:
                    default_part = " = None"
            elif validators:
                default_part = f" = Field({validators})"

            desc = f"  # {f.description}" if f.description else ""
            lines.append(f"    {f.name}: {py_type}{default_part}{desc}")

        return "\n".join(lines) if lines else "    pass"

    def _field_python_type(self, f: FieldSpec) -> str:
        if f.enum:
            literals = ", ".join(repr(e) for e in f.enum)
            return f"Literal[{literals}]"
        return _PY_TYPES.get(f.type, "str")

    def _field_validators(self, f: FieldSpec) -> str:
        parts = []
        if f.gt is not None:
            parts.append(f"gt={f.gt}")
        if f.lt is not None:
            parts.append(f"lt={f.lt}")
        if f.ge is not None:
            parts.append(f"ge={f.ge}")
        if f.le is not None:
            parts.append(f"le={f.le}")
        if f.min_length is not None:
            parts.append(f"min_length={f.min_length}")
        if f.max_length is not None:
            parts.append(f"max_length={f.max_length}")
        if f.regex is not None:
            parts.append(f"pattern={f.regex!r}")
        if f.description:
            parts.append(f"description={f.description!r}")
        return ", ".join(parts)

    # ------------------------------------------------------------------
    # dependencies.py
    # ------------------------------------------------------------------

    def _dependencies(self) -> str:
        auth = self.s.auth
        pg_session = "from .database import get_db\n" if self.s.is_sql else ""

        if not auth.enabled or auth.type == "none":
            auth_dep = f'''\
async def get_current_user() -> None:
    """Auth disabled — all endpoints are public."""
    return None
'''
        elif auth.type == "bearer":
            auth_dep = f"""\
from jose import JWTError, jwt
import sys as _sys

_SECRET = os.environ.get({auth.secret_env!r}, "").strip()
if not _SECRET:
    print(
        "FATAL: {auth.secret_env} is not set or is empty. "
        "Set it in your environment or .env file before starting this service.",
        file=_sys.stderr,
    )
    _sys.exit(1)
_ALGORITHM = "HS256"


async def get_current_user(authorization: str = Header(default="")) -> str:
    if not authorization.startswith("Bearer "):
        raise HTTPException(status_code=401, detail="Missing or invalid Authorization header")
    token = authorization.removeprefix("Bearer ").strip()
    try:
        payload = jwt.decode(token, _SECRET, algorithms=[_ALGORITHM])
        subject: str = payload.get("sub", "")
        if not subject:
            raise HTTPException(status_code=401, detail="Invalid token payload")
        return subject
    except JWTError as exc:
        raise HTTPException(status_code=401, detail=str(exc)) from exc
"""
        else:  # api_key
            auth_dep = f"""\
_API_KEY = os.environ.get({auth.api_key_env!r}, "").strip()


async def get_current_user(x_api_key: str = Header(alias={auth.api_key_header!r}, default="")) -> str:
    if not _API_KEY:
        raise HTTPException(status_code=503, detail="API key auth is not configured on this server")
    if x_api_key != _API_KEY:
        raise HTTPException(status_code=403, detail="Invalid API key")
    return "api-key-user"
"""

        pg_dep = (
            f"""\
from sqlalchemy.ext.asyncio import AsyncSession
{pg_session}
async def get_session() -> AsyncSession:  # type: ignore[return]
    async for session in get_db():
        yield session
"""
            if self.s.is_sql
            else ""
        )

        pagination_default = self.s.pagination.default_limit
        pagination_max = self.s.pagination.max_limit

        return f'''\
"""FastAPI dependencies — auth, pagination, DB session."""
from __future__ import annotations

import os

from fastapi import Depends, Header, HTTPException, Query
{pg_dep}

class Pagination:
    def __init__(
        self,
        limit: int = Query(default={pagination_default}, ge=1, le={pagination_max}),
        offset: int = Query(default=0, ge=0),
    ) -> None:
        self.limit = limit
        self.offset = offset


{auth_dep}
'''

    # ------------------------------------------------------------------
    # exceptions.py
    # ------------------------------------------------------------------

    def _exceptions(self) -> str:
        return f'''\
"""Domain exception hierarchy."""


class ServiceError(Exception):
    def __init__(self, detail: str, status_code: int = 400) -> None:
        self.detail = detail
        self.status_code = status_code
        super().__init__(detail)


class NotFoundError(ServiceError):
    def __init__(self, resource: str = "{self.cls}") -> None:
        super().__init__(f"{{resource}} not found", status_code=404)


class ConflictError(ServiceError):
    def __init__(self, detail: str = "Resource already exists") -> None:
        super().__init__(detail, status_code=409)


class ValidationError(ServiceError):
    def __init__(self, detail: str) -> None:
        super().__init__(detail, status_code=422)
'''

    # ------------------------------------------------------------------
    # routes.py
    # ------------------------------------------------------------------

    def _routes(self) -> str:
        db_import = (
            "from .dependencies import get_session\nfrom sqlalchemy.ext.asyncio import AsyncSession\n"
            if self.s.is_sql
            else ""
        )
        id_type = "str" if self.s.is_mongo else "UUID"
        id_import = "" if self.s.is_mongo else "from uuid import UUID\n"

        auth_dep = "_ = Depends(get_current_user), " if self.s.auth.enabled else ""
        db_param = "db: AsyncSession = Depends(get_session), " if self.s.is_sql else ""

        list_db_comma = "db, " if self.s.is_sql else ""
        single_db = ", db" if self.s.is_sql else ""

        return f'''\
"""FastAPI router — full CRUD for {self.cls}."""
from __future__ import annotations

from fastapi import APIRouter, Depends, status
{id_import}{db_import}
from .crud import (
    create_{self.n},
    get_{self.n},
    list_{self.tbl},
    update_{self.n},
    patch_{self.n},
    delete_{self.n},
)
from .dependencies import Pagination, get_current_user
from .exceptions import NotFoundError
from .schemas import (
    {self.cls}Create,
    {self.cls}Update,
    {self.cls}Patch,
    {self.cls}Response,
    {self.cls}ListResponse,
)

router = APIRouter()


@router.post(
    "",
    response_model={self.cls}Response,
    status_code=status.HTTP_201_CREATED,
    summary="Create {self.cls}",
)
async def create(
    data: {self.cls}Create,
    {db_param}{auth_dep}
) -> {self.cls}Response:
    return await create_{self.n}({list_db_comma}data)


@router.get(
    "",
    response_model={self.cls}ListResponse,
    summary="List {self.cls}s",
)
async def list_all(
    pagination: Pagination = Depends(),
    {db_param}
) -> {self.cls}ListResponse:
    items, total = await list_{self.tbl}({list_db_comma}limit=pagination.limit, offset=pagination.offset)
    return {self.cls}ListResponse(
        items=items,
        total=total,
        limit=pagination.limit,
        offset=pagination.offset,
        has_more=(pagination.offset + pagination.limit) < total,
    )


@router.get(
    "/{{{self.n}_id}}",
    response_model={self.cls}Response,
    summary="Get {self.cls}",
)
async def get_one({self.n}_id: {id_type}{single_db}) -> {self.cls}Response:
    obj = await get_{self.n}({list_db_comma}{self.n}_id)
    if obj is None:
        raise NotFoundError()
    return obj


@router.put(
    "/{{{self.n}_id}}",
    response_model={self.cls}Response,
    summary="Replace {self.cls}",
)
async def update(
    {self.n}_id: {id_type},
    data: {self.cls}Update,
    {db_param}{auth_dep}
) -> {self.cls}Response:
    obj = await update_{self.n}({list_db_comma}{self.n}_id, data)
    if obj is None:
        raise NotFoundError()
    return obj


@router.patch(
    "/{{{self.n}_id}}",
    response_model={self.cls}Response,
    summary="Partial update {self.cls}",
)
async def patch(
    {self.n}_id: {id_type},
    data: {self.cls}Patch,
    {db_param}{auth_dep}
) -> {self.cls}Response:
    obj = await patch_{self.n}({list_db_comma}{self.n}_id, data)
    if obj is None:
        raise NotFoundError()
    return obj


@router.delete(
    "/{{{self.n}_id}}",
    status_code=status.HTTP_204_NO_CONTENT,
    summary="Delete {self.cls}",
)
async def delete(
    {self.n}_id: {id_type},
    {db_param}{auth_dep}
) -> None:
    deleted = await delete_{self.n}({list_db_comma}{self.n}_id)
    if not deleted:
        raise NotFoundError()
'''
