import asyncio
import json
from src.monkey_brain.kernel.models.plan import PlanResponse, PlanRequest
from src.monkey_brain.kernel.models.graph import CanonicalGraph


def test_plan_serialization():
    # Simulate a graph generated by the planner
    graph_dict = {
        "graph_id": "test_graph_123",
        "graph_type": "execution",
        "nodes": [{"id": "n1", "name": "Test Node"}],
        "edges": [],
        "execution_order": [["n1"]],
        "state": {},
    }

    # Simulate payload fields
    steps = graph_dict["nodes"]
    intent_dict = {"intent": "test_intent", "confidence": 1.0, "workload_id": "test"}
    intent_ir_dict = {"id": "ir_1", "type": "intent_ir"}

    # Instantiate the PlanResponse like the API route does
    response = PlanResponse(
        graph=graph_dict,
        run_id="run_123",
        target="execute",
        question="How to test this?",
        workload_id="test_workload",
        steps=steps,
        answer="I have created a plan.",
        grounding_confidence=0.95,
        low_grounding=False,
        user_id="user_test",
        elapsed_ms=10.0,
        intent=intent_dict,
        intent_ir=intent_ir_dict,
        graph_id=graph_dict["graph_id"],
        graph_type=graph_dict["graph_type"],
        nodes=graph_dict["nodes"],
        edges=graph_dict["edges"],
    )

    response_json = response.model_dump()

    # Assertions to ensure Pydantic preserves the fields
    assert "steps" in response_json, "steps was dropped by Pydantic!"
    assert response_json["steps"] == steps, "steps value mismatched!"
    assert "intent" in response_json, "intent was dropped by Pydantic!"
    assert response_json["intent"] == intent_dict, "intent value mismatched!"
    assert response_json["answer"] == "I have created a plan.", "answer was dropped!"
    assert response_json["workload_id"] == "test_workload", "workload_id was dropped!"

    assert "graph" in response_json
    assert response_json["graph"]["graph_id"] == "test_graph_123"

    print("✅ test_plan_serialization passed! Fields are successfully preserved in PlanResponse.")


if __name__ == "__main__":
    test_plan_serialization()
