"""LLM Explorer — generates candidate workflows using LLM.

The LLM is an exploration mechanism, not the execution policy.

Flow:
  LLM generates candidate workflows (exploration)
  Policy evaluates and selects (exploitation)

As experience increases, execution converges toward reinforcement learning.
"""

from __future__ import annotations

import json
from dataclasses import dataclass, field
from typing import Any
from uuid import uuid4

from src.monkey_brain.kernel.plan.workload.workload import Workload, WorkloadStep


@dataclass
class WorkflowCandidate:
    """A candidate workflow generated by the LLM."""

    candidate_id: str = field(default_factory=lambda: f"wf-{uuid4().hex[:8]}")
    name: str = ""
    description: str = ""
    steps: list[dict[str, Any]] = field(default_factory=list)
    estimated_cost: float = 1.0
    estimated_latency_ms: float = 100.0
    confidence: float = 0.5
    source: str = "llm"
    metadata: dict[str, Any] = field(default_factory=dict)


class LLMExplorer:
    """LLM-based workflow exploration.

    The LLM generates candidate workflows.
    The Policy selects which workflow to execute.

    As experience increases, execution converges toward reinforcement learning.
    LLM is used for exploration, not exploitation.
    """

    def __init__(self):
        self._candidates: list[WorkflowCandidate] = []
        self._llm_calls = 0
        self._total_tokens = 0
        self._lemon = None

    def set_lemon(self, lemon) -> None:
        self._lemon = lemon

    def generate_candidates(
        self,
        question: str,
        intent: str,
        context: dict[str, Any] | None = None,
    ) -> list[WorkflowCandidate]:
        """Generate candidate workflows using LLM.

        In production, this calls the LLM to generate workflows.
        For now, returns predefined candidates based on intent.
        """
        candidates = self._generate_from_intent(intent, context or {})

        self._llm_calls += 1

        if self._lemon:
            self._lemon.counter("llm.explorer.calls")
            self._lemon.histogram("llm.explorer.candidates", len(candidates))

        self._candidates.extend(candidates)
        return candidates

    def _generate_from_intent(
        self,
        intent: str,
        context: dict[str, Any],
    ) -> list[WorkflowCandidate]:
        """Generate candidates based on intent.

        For ETASS intents, calls Claude with the available Broca agents and SOMA charts
        to generate a dynamic agent-based step plan.  All other intents use the
        predefined capability-based candidates.
        """
        if intent in ("sittingface_pipeline", "etass", "cognitive_os"):
            return self._generate_etass_candidates(context)
        return self._predefined_candidates(intent)

    def _generate_etass_candidates(self, context: dict[str, Any]) -> list[WorkflowCandidate]:
        """Use PromptCompilerAgent + ModelBackend to generate the ETASS step plan.

        All model calls go through the Prompt Compiler — never direct API calls.
        The compiler injects domain ontology, agent catalog, and reasoning strategy.
        """
        import logging, re

        logger = logging.getLogger("llm_explorer.etass")

        goal = context.get("goal", "Run the full ETASS cognitive OS pipeline for monkeypatched")

        # Build ETASSSpec for this exploration call
        try:
            from etass.specification import ETASSSpec

            spec = ETASSSpec(
                workload="etass",
                goal=goal,
                domain=context.get("domain", "software_engineering"),
                bounded_context=context.get("bounded_context", ""),
                reasoning="chain_of_thought",
                outputs=["JSON candidates list with agent step sequences"],
            )
        except Exception as exc:
            logger.warning("[etass_explorer] ETASSSpec build failed: %s", exc)
            return [self._default_etass_candidate({})]

        # Compile the spec into a StructuredPromptIR
        try:
            from broca.agents.prompt_compiler import PromptCompilerAgent
            import asyncio

            compiler = PromptCompilerAgent()
            loop = asyncio.get_event_loop()
            if loop.is_running():
                import concurrent.futures

                with concurrent.futures.ThreadPoolExecutor(max_workers=1) as pool:
                    fut = pool.submit(asyncio.run, compiler.handle({"spec": spec}))
                    result = fut.result(timeout=30)
            else:
                result = loop.run_until_complete(compiler.handle({"spec": spec}))
            ir = result.payload.get("prompt_ir")
        except Exception as exc:
            logger.warning("[etass_explorer] PromptCompiler failed: %s", exc)
            ir = None

        if ir is None:
            return [self._default_etass_candidate({})]

        # Append step-generation instruction to the compiled prompt. The
        # agent catalog itself is already embedded in ir.compiled_prompt
        # (PromptCompilerAgent._assemble() includes it as its own section
        # whenever non-empty) -- "the catalog above" below refers to that,
        # not a separate injection here.
        step_prompt = (
            f"{ir.compiled_prompt}\n\n"
            "---\n"
            "Generate 2-3 candidate step sequences for this goal. "
            "Each step must reference an agent by its exact key from the catalog above.\n"
            "Reply JSON only:\n"
            '{"candidates": [{"name": str, "description": str, '
            '"steps": [{"name": str, "agent": str}], "confidence": float}]}'
        )

        system_prompt = (
            "You are the ETASS LLM Explorer. You generate candidate agent step sequences "
            "from compiled ETASSSpec prompts. Reply with valid JSON only."
        )

        try:
            from src.monkey_brain.kernel.execute.provider.model_backend import (
                get_backend,
            )

            backend = get_backend()
            # ModelBackend.complete() is now async (see model_backend.py's
            # module docstring) -- this method itself is sync and called
            # from both sync and already-async contexts (kernel/fix/
            # policy/policy.py sync; kernel/plan/intents/predicates/
            # sittingface_*.py async), so bridge to the coroutine rather
            # than converting this whole (separate, ETASS-specific) call
            # chain to async -- unlike the Ollama actor-tick path this
            # session's Warehouse Worker investigation diagnosed, nothing
            # here was found to need genuine cancellation; this preserves
            # the exact prior blocking behavior, nothing more.
            import asyncio

            try:
                asyncio.get_running_loop()
            except RuntimeError:
                raw = asyncio.run(backend.complete(step_prompt, system=system_prompt, max_tokens=1024))
            else:
                import concurrent.futures

                with concurrent.futures.ThreadPoolExecutor(max_workers=1) as pool:
                    raw = pool.submit(
                        asyncio.run,
                        backend.complete(step_prompt, system=system_prompt, max_tokens=1024),
                    ).result()
            self._total_tokens += 1024  # approximate; real token count tracked in backend.stats()
            m = re.search(r"\{.*\}", raw, re.DOTALL)
            data = json.loads(m.group(0)) if m else {}
            candidates = []
            for c in data.get("candidates", []):
                candidates.append(
                    WorkflowCandidate(
                        name=c.get("name", "etass_pipeline"),
                        description=c.get("description", ""),
                        steps=c.get("steps", []),
                        estimated_cost=2.0,
                        estimated_latency_ms=5000.0,
                        confidence=c.get("confidence", 0.7),
                        source="prompt_compiler",
                    )
                )
            if candidates:
                return candidates
        except Exception as exc:
            logger.warning("[etass_explorer] ModelBackend call failed: %s — using default", exc)

        return [self._default_etass_candidate({})]

    def _default_etass_candidate(self, agent_catalog: dict) -> WorkflowCandidate:
        """Deterministic fallback ETASS pipeline when Claude is unavailable."""
        steps = [
            {"name": "pre_governance", "agent": "governance"},
            {"name": "compile_and_generate", "agent": "codegen"},
            {"name": "unit_testing", "agent": "unit_testing"},
            {"name": "static_analysis", "agent": "static_analysis"},
            {"name": "commit_changes", "agent": "source_control"},
            {"name": "create_pr", "agent": "pull_request"},
            {"name": "human_review", "agent": "human_review"},
            {"name": "post_governance", "agent": "governance"},
            {"name": "collect_evidence", "agent": "operational_evidence"},
            {"name": "evolve_charts", "agent": "chart_evolution"},
        ]
        # Only include steps whose agents are actually registered
        if agent_catalog:
            steps = [s for s in steps if s["agent"] in agent_catalog]
        return WorkflowCandidate(
            name="etass_default",
            description="Full ETASS pipeline: governance → codegen → test → commit → PR → review → evidence",
            steps=steps,
            estimated_cost=3.0,
            estimated_latency_ms=10000.0,
            confidence=0.8,
            source="default",
        )

    def _predefined_candidates(self, intent: str) -> list[WorkflowCandidate]:
        """Original predefined candidates for non-ETASS intents."""
        base_steps = [
            {"name": "resolve_entity", "capability": "resolve_entity"},
            {"name": "retrieve", "capability": "retrieve"},
            {"name": "format", "capability": "format"},
        ]
        candidates = [
            WorkflowCandidate(
                name="simple_pipeline",
                description="Basic retrieve and format",
                steps=base_steps,
                estimated_cost=1.0,
                estimated_latency_ms=50.0,
                confidence=0.5,
                source="llm",
            )
        ]
        if intent in ["batch_record", "plant_topology", "worker", "maintenance"]:
            candidates.append(
                WorkflowCandidate(
                    name="entity_enriched",
                    description="Entity resolution with hierarchy",
                    steps=[
                        {"name": "resolve_entity", "capability": "resolve_entity"},
                        {"name": "resolve_hierarchy", "capability": "resolve_entity"},
                        {"name": "retrieve", "capability": "retrieve"},
                        {"name": "format", "capability": "format"},
                    ],
                    estimated_cost=1.5,
                    estimated_latency_ms=75.0,
                    confidence=0.6,
                    source="llm",
                )
            )
        if intent in ["production_kpi", "simulation", "decision_intelligence"]:
            candidates.append(
                WorkflowCandidate(
                    name="analytical",
                    description="Retrieve with analysis",
                    steps=[
                        {"name": "resolve_entity", "capability": "resolve_entity"},
                        {"name": "retrieve", "capability": "retrieve"},
                        {"name": "analyze", "capability": "retrieve"},
                        {"name": "format", "capability": "format"},
                    ],
                    estimated_cost=2.0,
                    estimated_latency_ms=100.0,
                    confidence=0.4,
                    source="llm",
                )
            )
        if intent in ["knowledge_base", "sop_compliance", "change_control"]:
            candidates.append(
                WorkflowCandidate(
                    name="knowledge_enriched",
                    description="Knowledge-augmented retrieval",
                    steps=[
                        {"name": "resolve_entity", "capability": "resolve_entity"},
                        {"name": "search_knowledge", "capability": "retrieve"},
                        {"name": "retrieve", "capability": "retrieve"},
                        {"name": "format", "capability": "format"},
                    ],
                    estimated_cost=1.8,
                    estimated_latency_ms=80.0,
                    confidence=0.55,
                    source="llm",
                )
            )
        return candidates

    def candidate_to_workload(self, candidate: WorkflowCandidate) -> Workload:
        """Convert a workflow candidate to an executable workload.

        Steps with an 'agent' key become agent steps (Broca discovery).
        Steps with a 'capability' key become capability steps (Cerebellum registry).
        """
        steps = []
        for step in candidate.steps:
            if "agent" in step:
                steps.append(
                    WorkloadStep(
                        capability_name=step["agent"],
                        metadata={**step, "step_type": "agent"},
                    )
                )
            else:
                steps.append(
                    WorkloadStep(
                        capability_name=step.get("capability", "retrieve"),
                        metadata=step,
                    )
                )

        return Workload(
            steps=steps,
            estimated_cost=candidate.estimated_cost,
            estimated_latency=candidate.estimated_latency_ms,
            metadata={
                "candidate_id": candidate.candidate_id,
                "name": candidate.name,
                "source": candidate.source,
            },
        )

    def get_candidates(self) -> list[WorkflowCandidate]:
        return list(self._candidates)

    def summary(self) -> dict:
        return {
            "total_candidates": len(self._candidates),
            "llm_calls": self._llm_calls,
            "total_tokens": self._total_tokens,
        }
