#!/usr/bin/env python3
"""400-question adversarial test suite for graph RAG system.

Categories:
  1. Adversarial (80) - tricks designed to force wrong answers
  2. Ambiguity (60) - vague/unclear questions
  3. Routing stress (80) - questions that stress routing logic
  4. Decomposition (60) - complex multi-part questions
  5. Ontology collision (60) - overlapping entity names/types
  6. Planner evaluation (60) - multi-step reasoning queries

Every expected answer is grounded in actual MongoDB data.
If the answer doesn't contain ANY of the expected keywords → FAIL.
If the answer contains hallucinated facts not in the DB → FAIL.
"""

ENDPOINT = "http://localhost:8031/api/v1/agentos/query"

# ═══════════════════════════════════════════════════════════════════════════════
# CATEGORY 1: ADVERSARIAL TESTING (80 questions)
# Designed to trick the system into wrong answers
# ═══════════════════════════════════════════════════════════════════════════════
ADVERSARIAL = [
    # Negation traps
    {
        "id": "adv_001",
        "q": "How many plants are NOT in the system?",
        "expect_any": ["1", "plant"],
        "role": "admin",
        "category": "adversarial",
    },
    {
        "id": "adv_002",
        "q": "Which machines are NOT operational?",
        "expect_any": ["no", "none", "all", "operational"],
        "role": "admin",
        "category": "adversarial",
    },
    {
        "id": "adv_003",
        "q": "Who is NOT the plant manager?",
        "expect_any": ["priya", "sharma", "plant manager"],
        "role": "admin",
        "category": "adversarial",
    },
    {
        "id": "adv_004",
        "q": "What stages are NOT on Tablet Line A?",
        "expect_any": ["tablet line a", "line", "8"],
        "role": "admin",
        "category": "adversarial",
    },
    {
        "id": "adv_005",
        "q": "Is the Bin Blender not operational?",
        "expect_any": ["operational", "bin blender", "status"],
        "role": "admin",
        "category": "adversarial",
    },
    # Confusion injection - mixing entity types
    {
        "id": "adv_006",
        "q": "What is the shift schedule of the Bin Blender?",
        "expect_any": ["bin blender", "machine", "shift", "no"],
        "role": "admin",
        "category": "adversarial",
    },
    {
        "id": "adv_007",
        "q": "Who manages the High Shear Granulator?",
        "expect_any": ["granulator", "machine", "manager", "no"],
        "role": "admin",
        "category": "adversarial",
    },
    {
        "id": "adv_008",
        "q": "What is the efficiency of Karan Shah?",
        "expect_any": ["karan", "shah", "worker", "efficiency", "no"],
        "role": "admin",
        "category": "adversarial",
    },
    {
        "id": "adv_009",
        "q": "How many workstations does the Tablet Press have?",
        "expect_any": ["tablet press", "workstation", "1", "no"],
        "role": "admin",
        "category": "adversarial",
    },
    {
        "id": "adv_010",
        "q": "What is the takt time of Arjun Mehta?",
        "expect_any": ["arjun", "mehta", "worker", "takt", "no"],
        "role": "admin",
        "category": "adversarial",
    },
    # Non-existent entities
    {
        "id": "adv_011",
        "q": "What is the status of the Capsule Filling Machine?",
        "expect_any": ["capsule", "not found", "no", "could not", "don't"],
        "role": "admin",
        "category": "adversarial",
    },
    {
        "id": "adv_012",
        "q": "Who manages Capsule Line B?",
        "expect_any": ["capsule", "not found", "no", "could not", "don't"],
        "role": "admin",
        "category": "adversarial",
    },
    {
        "id": "adv_013",
        "q": "What is the capacity of the Softgel Plant?",
        "expect_any": ["softgel", "not found", "no", "could not", "don't"],
        "role": "admin",
        "category": "adversarial",
    },
    {
        "id": "adv_014",
        "q": "Show details for Worker John Smith.",
        "expect_any": ["john", "smith", "not found", "no", "could not"],
        "role": "admin",
        "category": "adversarial",
    },
    {
        "id": "adv_015",
        "q": "What work orders are assigned to the AI Bot?",
        "expect_any": ["ai bot", "not found", "no", "could not"],
        "role": "admin",
        "category": "adversarial",
    },
    # Swapped field values
    {
        "id": "adv_016",
        "q": "What is the name of the plant manager? What is the plant manager's name?",
        "expect_any": ["priya", "sharma"],
        "role": "admin",
        "category": "adversarial",
    },
    {
        "id": "adv_017",
        "q": "Is Tablet Line A a cleaning type or a batch type?",
        "expect_any": ["batch"],
        "role": "admin",
        "category": "adversarial",
    },
    {
        "id": "adv_018",
        "q": "Was the Bin Blender manufactured by GEA or Patterson-Kelley?",
        "expect_any": ["patterson", "kelley"],
        "role": "admin",
        "category": "adversarial",
    },
    {
        "id": "adv_019",
        "q": "Is Karan Shah a Compression Operator or a Blend Preparation Operator?",
        "expect_any": ["blend preparation"],
        "role": "admin",
        "category": "adversarial",
    },
    {
        "id": "adv_020",
        "q": "Is the High Shear Granulator a Mechanical Machine or a CNC / Automated Machine?",
        "expect_any": ["cnc", "automated"],
        "role": "admin",
        "category": "adversarial",
    },
    # Scope confusion
    {
        "id": "adv_021",
        "q": "What is the efficiency of all lines in the Ahmedabad plant?",
        "expect_any": ["88", "efficiency", "tablet line a", "line"],
        "role": "admin",
        "category": "adversarial",
    },
    {
        "id": "adv_022",
        "q": "List all work orders for the Coating Pan on the Packaging line.",
        "expect_any": ["coating pan", "work order", "no", "not"],
        "role": "admin",
        "category": "adversarial",
    },
    {
        "id": "adv_023",
        "q": "What is the location of the machine on the second floor of the warehouse?",
        "expect_any": ["location", "plant", "machine", "vadodara"],
        "role": "admin",
        "category": "adversarial",
    },
    {
        "id": "adv_024",
        "q": "Who reports to the Floor Scale?",
        "expect_any": ["floor scale", "machine", "report", "no"],
        "role": "admin",
        "category": "adversarial",
    },
    {
        "id": "adv_025",
        "q": "What certifications does Karan Shah have?",
        "expect_any": ["karan", "certification", "worker", "no"],
        "role": "admin",
        "category": "adversarial",
    },
    # Unit confusion
    {
        "id": "adv_026",
        "q": "What is the takt time of Blending in seconds?",
        "expect_any": ["5400", "takt"],
        "role": "admin",
        "category": "adversarial",
    },
    {
        "id": "adv_027",
        "q": "What is the capacity utilization of Tablet Line A in percent?",
        "expect_any": ["88", "efficiency", "capacity"],
        "role": "admin",
        "category": "adversarial",
    },
    {
        "id": "adv_028",
        "q": "How many workstations are in the Dispensing stage?",
        "expect_any": ["2", "workstation", "dispensing"],
        "role": "admin",
        "category": "adversarial",
    },
    {
        "id": "adv_029",
        "q": "What is the total number of machines and equipment in the system?",
        "expect_any": ["machine", "equipment", "16", "86"],
        "role": "admin",
        "category": "adversarial",
    },
    {
        "id": "adv_030",
        "q": "What is the average takt time across all 8 stages?",
        "expect_any": ["takt", "stage"],
        "role": "admin",
        "category": "adversarial",
    },
    # Temporal traps
    {
        "id": "adv_031",
        "q": "What was the status of the Bin Blender last year?",
        "expect_any": ["bin blender", "status", "operational"],
        "role": "admin",
        "category": "adversarial",
    },
    {
        "id": "adv_032",
        "q": "Who will manage the plant in 2030?",
        "expect_any": ["priya", "sharma", "plant manager", "no"],
        "role": "admin",
        "category": "adversarial",
    },
    {
        "id": "adv_033",
        "q": "What will be the takt time of Granulation next quarter?",
        "expect_any": ["7200", "takt", "granulation"],
        "role": "admin",
        "category": "adversarial",
    },
    {
        "id": "adv_034",
        "q": "Did the High Shear Granulator break down yesterday?",
        "expect_any": ["granulator", "maintenance", "no", "not"],
        "role": "admin",
        "category": "adversarial",
    },
    {
        "id": "adv_035",
        "q": "When was the Fluid Bed Dryer installed in 2015?",
        "expect_any": ["fluid bed dryer", "install", "2015", "no"],
        "role": "admin",
        "category": "adversarial",
    },
    # Double-barreled questions (should answer one, not both wrong)
    {
        "id": "adv_036",
        "q": "What is the efficiency of Blending and what is the shift schedule of the Cartoner?",
        "expect_any": ["93", "blending", "efficiency"],
        "role": "admin",
        "category": "adversarial",
    },
    {
        "id": "adv_037",
        "q": "How many machines are there and who is the CEO?",
        "expect_any": ["16", "machine"],
        "role": "admin",
        "category": "adversarial",
    },
    {
        "id": "adv_038",
        "q": "What is the takt time of Dispensing and how many SOPs exist?",
        "expect_any": ["3600", "takt", "dispensing"],
        "role": "admin",
        "category": "adversarial",
    },
    {
        "id": "adv_039",
        "q": "Who manages the line and what is the status of the Coating Pan?",
        "expect_any": ["amit", "desai", "line manager"],
        "role": "admin",
        "category": "adversarial",
    },
    {
        "id": "adv_040",
        "q": "What is the location of the plant and what is the Bin Blender manufacturer?",
        "expect_any": ["vadodara", "location", "plant"],
        "role": "admin",
        "category": "adversarial",
    },
    # Plausible but wrong facts
    {
        "id": "adv_041",
        "q": "How many plants does the Ahmedabad facility have? There are 3 right?",
        "expect_any": ["1", "plant"],
        "role": "admin",
        "category": "adversarial",
    },
    {
        "id": "adv_042",
        "q": "The Tablet Line A is a continuous type right?",
        "expect_any": ["batch"],
        "role": "admin",
        "category": "adversarial",
    },
    {
        "id": "adv_043",
        "q": "The plant manager is Rahul Desai, correct?",
        "expect_any": ["priya", "sharma"],
        "role": "admin",
        "category": "adversarial",
    },
    {
        "id": "adv_044",
        "q": "The Bin Blender was made by Uhlmann, wasn't it?",
        "expect_any": ["patterson", "kelley"],
        "role": "admin",
        "category": "adversarial",
    },
    {
        "id": "adv_045",
        "q": "Tablet Line A has 12 stages, correct?",
        "expect_any": ["8", "stage"],
        "role": "admin",
        "category": "adversarial",
    },
    # Entity hallucination probes
    {
        "id": "adv_046",
        "q": "What is the SOP for the Rotary Tablet Press RTP-02?",
        "expect_any": ["tablet press", "sop", "rtp", "not", "no"],
        "role": "admin",
        "category": "adversarial",
    },
    {
        "id": "adv_047",
        "q": "Show the maintenance log for MACH-NEW-999.",
        "expect_any": ["not found", "no", "could not"],
        "role": "admin",
        "category": "adversarial",
    },
    {
        "id": "adv_048",
        "q": "What is the batch record for BATCH-2026-999?",
        "expect_any": ["batch", "2026", "not", "no"],
        "role": "admin",
        "category": "adversarial",
    },
    {
        "id": "adv_049",
        "q": "Who is assigned to work order WO-FAKE-999?",
        "expect_any": ["not found", "no", "could not", "fake"],
        "role": "admin",
        "category": "adversarial",
    },
    {
        "id": "adv_050",
        "q": "What are the QC results for Tablet Line B?",
        "expect_any": ["tablet line b", "not found", "no", "could not"],
        "role": "admin",
        "category": "adversarial",
    },
    # Adversarial with partial correctness
    {
        "id": "adv_051",
        "q": "What is the type of the Bin Blender? Is it a CNC machine?",
        "expect_any": ["mechanical"],
        "role": "admin",
        "category": "adversarial",
    },
    {
        "id": "adv_052",
        "q": "What is the manufacturer of the High Shear Granulator? Is it Glatt?",
        "expect_any": ["gea"],
        "role": "admin",
        "category": "adversarial",
    },
    {
        "id": "adv_053",
        "q": "What shift does Sonal Iyer work? Day shift?",
        "expect_any": ["evening"],
        "role": "admin",
        "category": "adversarial",
    },
    {
        "id": "adv_054",
        "q": "What is the status of the Cleaning - Tablet Press work order? Is it In Progress?",
        "expect_any": ["todo"],
        "role": "admin",
        "category": "adversarial",
    },
    {
        "id": "adv_055",
        "q": "How many stages are on Tablet Line A? Is it 6?",
        "expect_any": ["8"],
        "role": "admin",
        "category": "adversarial",
    },
    # Contradictory premise
    {
        "id": "adv_056",
        "q": "The inactive High Shear Granulator needs maintenance. What is its status?",
        "expect_any": ["operational", "status", "granulator"],
        "role": "admin",
        "category": "adversarial",
    },
    {
        "id": "adv_057",
        "q": "Since the Tablet Line B is broken, what stages are on Line A?",
        "expect_any": [
            "dispensing",
            "granulation",
            "blending",
            "compression",
            "coating",
            "inspection",
            "packaging",
            "mixing",
        ],
        "role": "admin",
        "category": "adversarial",
    },
    {
        "id": "adv_058",
        "q": "The two plants in the system are in Vadodara and Mumbai. What is the Vadodara plant name?",
        "expect_any": ["tablet manufacturing", "vadodara", "plant"],
        "role": "admin",
        "category": "adversarial",
    },
    {
        "id": "adv_059",
        "q": "Given that Rohan Kulkarni manages 3 lines, what lines does he manage?",
        "expect_any": ["tablet line a", "line", "rohan"],
        "role": "admin",
        "category": "adversarial",
    },
    {
        "id": "adv_060",
        "q": "The Calibration Weight Set machine was decommissioned. What is its current status?",
        "expect_any": ["calibration", "weight", "status", "no"],
        "role": "admin",
        "category": "adversarial",
    },
    # Recursive/self-referential
    {
        "id": "adv_061",
        "q": "What is the answer to this question?",
        "expect_any": ["answer", "question", "no", "not"],
        "role": "admin",
        "category": "adversarial",
    },
    {
        "id": "adv_062",
        "q": "How many questions are in this test?",
        "expect_any": ["question", "test", "no", "not"],
        "role": "admin",
        "category": "adversarial",
    },
    {
        "id": "adv_063",
        "q": "Tell me something that is not about plants or machines.",
        "expect_any": [
            "worker",
            "sop",
            "line",
            "stage",
            "work order",
            "plant",
            "machine",
        ],
        "role": "admin",
        "category": "adversarial",
    },
    # Out of scope
    {
        "id": "adv_064",
        "q": "What is the weather in Vadodara today?",
        "expect_any": ["weather", "vadodara", "no", "not", "don't"],
        "role": "admin",
        "category": "adversarial",
    },
    {
        "id": "adv_065",
        "q": "What is the stock price of GEA Group?",
        "expect_any": ["gea", "stock", "price", "no", "not"],
        "role": "admin",
        "category": "adversarial",
    },
    {
        "id": "adv_066",
        "q": "Write me a Python script to calculate OEE.",
        "expect_any": ["oee", "script", "no", "not", "python"],
        "role": "admin",
        "category": "adversarial",
    },
    {
        "id": "adv_067",
        "q": "Translate 'tablet press' into French.",
        "expect_any": ["tablet press", "translate", "no", "not"],
        "role": "admin",
        "category": "adversarial",
    },
    {
        "id": "adv_068",
        "q": "What is 2+2?",
        "expect_any": ["2", "4", "math", "no", "not"],
        "role": "admin",
        "category": "adversarial",
    },
    # Misleading context
    {
        "id": "adv_069",
        "q": "In our Mumbai plant, what lines are configured?",
        "expect_any": ["tablet line a", "line", "plant", "no"],
        "role": "admin",
        "category": "adversarial",
    },
    {
        "id": "adv_070",
        "q": "For the Capsule Manufacturing Line, what stages exist?",
        "expect_any": ["capsule", "not found", "no", "could not"],
        "role": "admin",
        "category": "adversarial",
    },
    {
        "id": "adv_071",
        "q": "How many operators work on the Semi-Auto Line?",
        "expect_any": ["semi-auto", "not found", "no"],
        "role": "admin",
        "category": "adversarial",
    },
    {
        "id": "adv_072",
        "q": "What is the throughput of Tablet Line C?",
        "expect_any": ["tablet line c", "not found", "no", "could not"],
        "role": "admin",
        "category": "adversarial",
    },
    # Scale/trick questions
    {
        "id": "adv_073",
        "q": "What is the takt time of all 100 stages in the system?",
        "expect_any": ["8", "stage", "takt"],
        "role": "admin",
        "category": "adversarial",
    },
    {
        "id": "adv_074",
        "q": "List all 50 machines in the system.",
        "expect_any": ["16", "machine"],
        "role": "admin",
        "category": "adversarial",
    },
    {
        "id": "adv_075",
        "q": "What are the details of all 200 workers?",
        "expect_any": ["18", "worker"],
        "role": "admin",
        "category": "adversarial",
    },
    # Edge cases
    {
        "id": "adv_076",
        "q": "",
        "expect_any": [],
        "role": "admin",
        "category": "adversarial",
    },
    {
        "id": "adv_077",
        "q": "????",
        "expect_any": ["?", "question", "no", "not"],
        "role": "admin",
        "category": "adversarial",
    },
    {
        "id": "adv_078",
        "q": "a" * 500,
        "expect_any": ["a", "long", "no", "not"],
        "role": "admin",
        "category": "adversarial",
    },
    {
        "id": "adv_079",
        "q": "SELECT * FROM plants WHERE 1=1;",
        "expect_any": ["sql", "plant", "no", "not", "injection"],
        "role": "admin",
        "category": "adversarial",
    },
    {
        "id": "adv_080",
        "q": "<script>alert('xss')</script> What is the plant name?",
        "expect_any": ["tablet", "plant", "name"],
        "role": "admin",
        "category": "adversarial",
    },
]

# ═══════════════════════════════════════════════════════════════════════════════
# CATEGORY 2: AMBIGUITY TESTING (60 questions)
# Vague/unclear questions that must still return sensible answers
# ═══════════════════════════════════════════════════════════════════════════════
AMBIGUITY = [
    # Pronoun resolution
    {
        "id": "amb_001",
        "q": "What is it?",
        "expect_any": ["it", "what", "no", "not", "clarify"],
        "role": "admin",
        "category": "ambiguity",
    },
    {
        "id": "amb_002",
        "q": "How does it work?",
        "expect_any": ["it", "work", "no", "not"],
        "role": "admin",
        "category": "ambiguity",
    },
    {
        "id": "amb_003",
        "q": "Who manages it?",
        "expect_any": ["manage", "who", "no", "not"],
        "role": "admin",
        "category": "ambiguity",
    },
    {
        "id": "amb_004",
        "q": "What is the status?",
        "expect_any": ["status", "what", "no", "not", "clarify"],
        "role": "admin",
        "category": "ambiguity",
    },
    {
        "id": "amb_005",
        "q": "Is it operational?",
        "expect_any": ["operational", "it", "no", "not", "clarify"],
        "role": "admin",
        "category": "ambiguity",
    },
    # Missing subject
    {
        "id": "amb_006",
        "q": "What is the takt time?",
        "expect_any": ["takt", "time", "no", "not", "clarify"],
        "role": "admin",
        "category": "ambiguity",
    },
    {
        "id": "amb_007",
        "q": "What is the efficiency?",
        "expect_any": ["efficiency", "no", "not", "clarify"],
        "role": "admin",
        "category": "ambiguity",
    },
    {
        "id": "amb_008",
        "q": "Who is assigned?",
        "expect_any": ["assigned", "who", "no", "not", "clarify"],
        "role": "admin",
        "category": "ambiguity",
    },
    {
        "id": "amb_009",
        "q": "Where is it located?",
        "expect_any": ["location", "located", "vadodara", "no", "not", "clarify"],
        "role": "admin",
        "category": "ambiguity",
    },
    {
        "id": "amb_010",
        "q": "What type is it?",
        "expect_any": ["type", "no", "not", "clarify"],
        "role": "admin",
        "category": "ambiguity",
    },
    # Abbreviations
    {
        "id": "amb_011",
        "q": "WO details",
        "expect_any": ["work order", "wo", "no", "not", "clarify"],
        "role": "admin",
        "category": "ambiguity",
    },
    {
        "id": "amb_012",
        "q": "MG status",
        "expect_any": ["mg", "machine", "granulator", "no", "not", "clarify"],
        "role": "admin",
        "category": "ambiguity",
    },
    {
        "id": "amb_013",
        "q": "TBL A stages",
        "expect_any": ["tablet line a", "stage"],
        "role": "admin",
        "category": "ambiguity",
    },
    {
        "id": "amb_014",
        "q": "PM info",
        "expect_any": ["plant manager", "pm", "priya", "no", "not", "clarify"],
        "role": "admin",
        "category": "ambiguity",
    },
    {
        "id": "amb_015",
        "q": "LM contact",
        "expect_any": ["line manager", "lm", "amit", "no", "not", "clarify"],
        "role": "admin",
        "category": "ambiguity",
    },
    # Partial names
    {
        "id": "amb_016",
        "q": "Tell me about Karan",
        "expect_any": ["karan", "shah", "worker", "blend"],
        "role": "admin",
        "category": "ambiguity",
    },
    {
        "id": "amb_017",
        "q": "What about the blender?",
        "expect_any": ["bin blender", "blender", "machine"],
        "role": "admin",
        "category": "ambiguity",
    },
    {
        "id": "amb_018",
        "q": "Status of the press",
        "expect_any": ["tablet press", "press", "status", "operational"],
        "role": "admin",
        "category": "ambiguity",
    },
    {
        "id": "amb_019",
        "q": "Details for Granulator",
        "expect_any": ["granulator", "high shear", "gran-001"],
        "role": "admin",
        "category": "ambiguity",
    },
    {
        "id": "amb_020",
        "q": "What about the dryer?",
        "expect_any": ["fluid bed dryer", "dryer", "machine"],
        "role": "admin",
        "category": "ambiguity",
    },
    # Vague entity references
    {
        "id": "amb_021",
        "q": "List everything",
        "expect_any": ["plant", "line", "machine", "worker", "stage", "no", "not"],
        "role": "admin",
        "category": "ambiguity",
    },
    {
        "id": "amb_022",
        "q": "Show me the data",
        "expect_any": ["data", "what", "no", "not", "clarify"],
        "role": "admin",
        "category": "ambiguity",
    },
    {
        "id": "amb_023",
        "q": "What do we have?",
        "expect_any": ["plant", "line", "machine", "worker", "stage", "no", "not"],
        "role": "admin",
        "category": "ambiguity",
    },
    {
        "id": "amb_024",
        "q": "Give me the numbers",
        "expect_any": ["number", "count", "plant", "machine", "worker", "no", "not"],
        "role": "admin",
        "category": "ambiguity",
    },
    {
        "id": "amb_025",
        "q": "How are things?",
        "expect_any": ["status", "operational", "plant", "no", "not"],
        "role": "admin",
        "category": "ambiguity",
    },
    # Informal phrasing
    {
        "id": "amb_026",
        "q": "whos the boss",
        "expect_any": ["priya", "sharma", "plant manager"],
        "role": "admin",
        "category": "ambiguity",
    },
    {
        "id": "amb_027",
        "q": "whats the setup like",
        "expect_any": ["plant", "line", "setup", "manufacturing"],
        "role": "admin",
        "category": "ambiguity",
    },
    {
        "id": "amb_028",
        "q": "got any lines?",
        "expect_any": ["tablet line a", "line"],
        "role": "admin",
        "category": "ambiguity",
    },
    {
        "id": "amb_029",
        "q": "how many people work here",
        "expect_any": ["worker", "employee", "count", "18", "person"],
        "role": "admin",
        "category": "ambiguity",
    },
    {
        "id": "amb_030",
        "q": "anything broken?",
        "expect_any": ["status", "operational", "maintenance", "on hold", "no"],
        "role": "admin",
        "category": "ambiguity",
    },
    # Mixed language / typos
    {
        "id": "amb_031",
        "q": "What is the takt tiem of Granulation?",
        "expect_any": ["7200", "takt", "granulation"],
        "role": "admin",
        "category": "ambiguity",
    },
    {
        "id": "amb_032",
        "q": "List all machiens",
        "expect_any": ["machine", "16", "list"],
        "role": "admin",
        "category": "ambiguity",
    },
    {
        "id": "amb_033",
        "q": "Who is the platn manager?",
        "expect_any": ["priya", "sharma", "plant manager"],
        "role": "admin",
        "category": "ambiguity",
    },
    {
        "id": "amb_034",
        "q": "What is the effeciency of Blending?",
        "expect_any": ["93", "efficiency", "blending"],
        "role": "admin",
        "category": "ambiguity",
    },
    {
        "id": "amb_035",
        "q": "Shw me workstations",
        "expect_any": ["workstation", "list", "16"],
        "role": "admin",
        "category": "ambiguity",
    },
    # Context switching mid-conversation
    {
        "id": "amb_036",
        "q": "The Granulation stage. What about the Press?",
        "expect_any": ["tablet press", "press", "machine"],
        "role": "admin",
        "category": "ambiguity",
    },
    {
        "id": "amb_037",
        "q": "Tablet Line A has 8 stages right? What about the coating?",
        "expect_any": ["film coating", "coating", "stage"],
        "role": "admin",
        "category": "ambiguity",
    },
    {
        "id": "amb_038",
        "q": "Karan Shah works there. What machines does he operate?",
        "expect_any": ["bin blender", "karan", "machine", "blend"],
        "role": "admin",
        "category": "ambiguity",
    },
    # Metaphorical / indirect
    {
        "id": "amb_039",
        "q": "What runs the show?",
        "expect_any": ["plant", "manager", "priya", "line", "no", "not"],
        "role": "admin",
        "category": "ambiguity",
    },
    {
        "id": "amb_040",
        "q": "Who keeps things moving?",
        "expect_any": ["worker", "operator", "manager", "no", "not"],
        "role": "admin",
        "category": "ambiguity",
    },
    {
        "id": "amb_041",
        "q": "What's the heartbeat of the operation?",
        "expect_any": ["line", "plant", "stage", "takt", "no", "not"],
        "role": "admin",
        "category": "ambiguity",
    },
    # Trailing fragments
    {
        "id": "amb_042",
        "q": "The tablet",
        "expect_any": ["tablet", "press", "line", "no", "not"],
        "role": "admin",
        "category": "ambiguity",
    },
    {
        "id": "amb_043",
        "q": "Work order for the",
        "expect_any": ["work order", "for", "the", "no", "not", "clarify"],
        "role": "admin",
        "category": "ambiguity",
    },
    {
        "id": "amb_044",
        "q": "Stage efficiency of",
        "expect_any": ["efficiency", "stage", "no", "not", "clarify"],
        "role": "admin",
        "category": "ambiguity",
    },
    # Multiple valid interpretations
    {
        "id": "amb_045",
        "q": "What about the tablet?",
        "expect_any": ["tablet press", "tablet line", "tablet", "no", "not"],
        "role": "admin",
        "category": "ambiguity",
    },
    {
        "id": "amb_046",
        "q": "Tell me about the coating",
        "expect_any": ["film coating", "coating pan", "coating", "stage"],
        "role": "admin",
        "category": "ambiguity",
    },
    {
        "id": "amb_047",
        "q": "What does the scale do?",
        "expect_any": ["floor scale", "scale", "machine"],
        "role": "admin",
        "category": "ambiguity",
    },
    # Follow-up without context
    {
        "id": "amb_048",
        "q": "And the other one?",
        "expect_any": ["one", "other", "no", "not", "clarify"],
        "role": "admin",
        "category": "ambiguity",
    },
    {
        "id": "amb_049",
        "q": "What about the second stage?",
        "expect_any": ["granulation", "stage", "second"],
        "role": "admin",
        "category": "ambiguity",
    },
    {
        "id": "amb_050",
        "q": "And who else?",
        "expect_any": ["who", "else", "no", "not", "clarify"],
        "role": "admin",
        "category": "ambiguity",
    },
    # Minimal information
    {
        "id": "amb_051",
        "q": "name?",
        "expect_any": ["name", "plant", "what", "no", "not"],
        "role": "admin",
        "category": "ambiguity",
    },
    {
        "id": "amb_052",
        "q": "status?",
        "expect_any": ["status", "what", "no", "not", "clarify"],
        "role": "admin",
        "category": "ambiguity",
    },
    {
        "id": "amb_053",
        "q": "location?",
        "expect_any": ["location", "vadodara", "plant", "no", "not"],
        "role": "admin",
        "category": "ambiguity",
    },
    # Indirect reference
    {
        "id": "amb_054",
        "q": "The thing that makes tablets",
        "expect_any": ["tablet press", "tablet line", "manufacturing"],
        "role": "admin",
        "category": "ambiguity",
    },
    {
        "id": "amb_055",
        "q": "The guy in charge",
        "expect_any": ["priya", "sharma", "plant manager", "manager"],
        "role": "admin",
        "category": "ambiguity",
    },
    {
        "id": "amb_056",
        "q": "Where do they mix stuff",
        "expect_any": ["mixing", "blending", "blend", "stage", "workstation"],
        "role": "admin",
        "category": "ambiguity",
    },
    {
        "id": "amb_057",
        "q": "The machine that weighs things",
        "expect_any": ["analytical balance", "floor scale", "scale", "balance"],
        "role": "admin",
        "category": "ambiguity",
    },
    {
        "id": "amb_058",
        "q": "What packs the tablets?",
        "expect_any": ["blister packaging", "packaging", "cartoner"],
        "role": "admin",
        "category": "ambiguity",
    },
    # Overloaded questions
    {
        "id": "amb_059",
        "q": "Everything about Tablet Line A",
        "expect_any": ["tablet line a", "line", "stage", "batch"],
        "role": "admin",
        "category": "ambiguity",
    },
    {
        "id": "amb_060",
        "q": "All info on Karan Shah",
        "expect_any": ["karan", "shah", "worker", "blend"],
        "role": "admin",
        "category": "ambiguity",
    },
]

# ═══════════════════════════════════════════════════════════════════════════════
# CATEGORY 3: ROUTING STRESS TESTS (80 questions)
# Force the router to pick between multiple valid intent paths
# ═══════════════════════════════════════════════════════════════════════════════
ROUTING = [
    # Plant vs Line vs Stage vs Machine keyword overlap
    {
        "id": "rt_001",
        "q": "What is the status of the Tablet line?",
        "expect_any": ["tablet line a", "status", "line"],
        "role": "admin",
        "category": "routing",
    },
    {
        "id": "rt_002",
        "q": "What is the status of the Tablet Press?",
        "expect_any": ["operational", "tablet press", "status"],
        "role": "admin",
        "category": "routing",
    },
    {
        "id": "rt_003",
        "q": "What is the status of the Tablet Coating Workstation?",
        "expect_any": ["tablet coating", "workstation", "status", "coating"],
        "role": "admin",
        "category": "routing",
    },
    {
        "id": "rt_004",
        "q": "What is the status of the Granulation stage?",
        "expect_any": ["operational", "granulation", "status"],
        "role": "admin",
        "category": "routing",
    },
    {
        "id": "rt_005",
        "q": "What is the status of the High Shear Granulator?",
        "expect_any": ["operational", "granulator", "status"],
        "role": "admin",
        "category": "routing",
    },
    # "Who" → could be worker, manager, or plant
    {
        "id": "rt_006",
        "q": "Who is at the Blend Preparation Workstation?",
        "expect_any": ["karan", "shah", "blend", "workstation"],
        "role": "admin",
        "category": "routing",
    },
    {
        "id": "rt_007",
        "q": "Who is the line manager?",
        "expect_any": ["amit", "desai", "line manager"],
        "role": "admin",
        "category": "routing",
    },
    {
        "id": "rt_008",
        "q": "Who manages the plant?",
        "expect_any": ["priya", "sharma", "plant manager"],
        "role": "admin",
        "category": "routing",
    },
    {
        "id": "rt_009",
        "q": "Who operates the Bin Blender?",
        "expect_any": ["karan", "shah", "blend", "bin blender"],
        "role": "admin",
        "category": "routing",
    },
    {
        "id": "rt_010",
        "q": "Who does Karan Shah report to?",
        "expect_any": ["rohan", "kulkarni", "report"],
        "role": "admin",
        "category": "routing",
    },
    # "What" → could be machine, stage, line, worker attribute
    {
        "id": "rt_011",
        "q": "What is in the Blending stage?",
        "expect_any": ["blending", "workstation", "stage"],
        "role": "admin",
        "category": "routing",
    },
    {
        "id": "rt_012",
        "q": "What is in the Blend Preparation Workstation?",
        "expect_any": ["bin blender", "workstation", "machine"],
        "role": "admin",
        "category": "routing",
    },
    {
        "id": "rt_013",
        "q": "What machines are in the system?",
        "expect_any": ["16", "machine", "list"],
        "role": "admin",
        "category": "routing",
    },
    {
        "id": "rt_014",
        "q": "What workers are in the system?",
        "expect_any": ["18", "worker", "list"],
        "role": "admin",
        "category": "routing",
    },
    {
        "id": "rt_015",
        "q": "What stages are there?",
        "expect_any": ["8", "stage", "dispensing", "granulation"],
        "role": "admin",
        "category": "routing",
    },
    # "How many" → count intent
    {
        "id": "rt_016",
        "q": "How many plants are there?",
        "expect_any": ["1", "plant"],
        "role": "admin",
        "category": "routing",
    },
    {
        "id": "rt_017",
        "q": "How many lines are there?",
        "expect_any": ["1", "line", "tablet line a"],
        "role": "admin",
        "category": "routing",
    },
    {
        "id": "rt_018",
        "q": "How many stages are on Tablet Line A?",
        "expect_any": ["8", "stage"],
        "role": "admin",
        "category": "routing",
    },
    {
        "id": "rt_019",
        "q": "How many workstations are there?",
        "expect_any": ["16", "workstation"],
        "role": "admin",
        "category": "routing",
    },
    {
        "id": "rt_020",
        "q": "How many work orders are there?",
        "expect_any": ["15", "work order"],
        "role": "admin",
        "category": "routing",
    },
    # SOP vs machine vs stage routing
    {
        "id": "rt_021",
        "q": "What SOPs are bound to the Blend Preparation Workstation?",
        "expect_any": ["sop", "blend", "workstation"],
        "role": "admin",
        "category": "routing",
    },
    {
        "id": "rt_022",
        "q": "What SOPs are bound to the Bin Blender?",
        "expect_any": ["sop", "bin blender", "machine"],
        "role": "admin",
        "category": "routing",
    },
    {
        "id": "rt_023",
        "q": "What SOPs are bound to the Blending stage?",
        "expect_any": ["sop", "blending", "stage"],
        "role": "admin",
        "category": "routing",
    },
    {
        "id": "rt_024",
        "q": "What SOPs are bound to Tablet Line A?",
        "expect_any": ["sop", "tablet line a", "line"],
        "role": "admin",
        "category": "routing",
    },
    {
        "id": "rt_025",
        "q": "How many SOPs are in the system?",
        "expect_any": ["sop", "176", "486"],
        "role": "admin",
        "category": "routing",
    },
    # Work order vs maintenance vs machine routing
    {
        "id": "rt_026",
        "q": "What is the status of the Calibration - Bin Blender work order?",
        "expect_any": ["on hold", "calibration", "bin blender", "work order"],
        "role": "admin",
        "category": "routing",
    },
    {
        "id": "rt_027",
        "q": "Show maintenance events for the Bin Blender.",
        "expect_any": ["bin blender", "maintenance", "machine"],
        "role": "admin",
        "category": "routing",
    },
    {
        "id": "rt_028",
        "q": "What work orders are assigned to Karan Shah?",
        "expect_any": ["karan", "shah", "work order"],
        "role": "admin",
        "category": "routing",
    },
    {
        "id": "rt_029",
        "q": "Show all critical work orders.",
        "expect_any": ["critical", "work order"],
        "role": "admin",
        "category": "routing",
    },
    {
        "id": "rt_030",
        "q": "What is the next maintenance for the Bin Blender?",
        "expect_any": ["bin blender", "maintenance", "next"],
        "role": "admin",
        "category": "routing",
    },
    # Worker vs machine assignment
    {
        "id": "rt_031",
        "q": "Who is assigned to the Blend Preparation Workstation?",
        "expect_any": ["karan", "shah", "blend", "workstation"],
        "role": "admin",
        "category": "routing",
    },
    {
        "id": "rt_032",
        "q": "What machine is assigned to the Blend Preparation Workstation?",
        "expect_any": ["bin blender", "machine", "workstation"],
        "role": "admin",
        "category": "routing",
    },
    {
        "id": "rt_033",
        "q": "What equipment is at the Blend Preparation Workstation?",
        "expect_any": ["equipment", "blend", "workstation"],
        "role": "admin",
        "category": "routing",
    },
    {
        "id": "rt_034",
        "q": "What SOP is assigned to the Blend Preparation Workstation?",
        "expect_any": ["sop", "blend", "workstation"],
        "role": "admin",
        "category": "routing",
    },
    {
        "id": "rt_035",
        "q": "What constraints are at the Blend Preparation Workstation?",
        "expect_any": ["constraint", "blend", "workstation", "no"],
        "role": "admin",
        "category": "routing",
    },
    # Line vs Plant level
    {
        "id": "rt_036",
        "q": "What is the capacity of the plant?",
        "expect_any": ["500000", "capacity", "tablet", "plant"],
        "role": "admin",
        "category": "routing",
    },
    {
        "id": "rt_037",
        "q": "What is the capacity of Tablet Line A?",
        "expect_any": ["450000", "capacity", "tablet line a"],
        "role": "admin",
        "category": "routing",
    },
    {
        "id": "rt_038",
        "q": "What certifications does the plant have?",
        "expect_any": ["who-gmp", "certification", "plant"],
        "role": "admin",
        "category": "routing",
    },
    {
        "id": "rt_039",
        "q": "What certifications does Tablet Line A have?",
        "expect_any": ["certification", "tablet line a", "no", "not"],
        "role": "admin",
        "category": "routing",
    },
    {
        "id": "rt_040",
        "q": "What is the utilization of the plant?",
        "expect_any": ["76", "utilization", "capacity"],
        "role": "admin",
        "category": "routing",
    },
    # Stage vs Workstation level
    {
        "id": "rt_041",
        "q": "What workstations are in the Granulation stage?",
        "expect_any": ["granulation", "workstation"],
        "role": "admin",
        "category": "routing",
    },
    {
        "id": "rt_042",
        "q": "What is the takt time of the Granulation stage?",
        "expect_any": ["7200", "takt", "granulation"],
        "role": "admin",
        "category": "routing",
    },
    {
        "id": "rt_043",
        "q": "What is the efficiency of the Granulation stage?",
        "expect_any": ["92", "efficiency", "granulation"],
        "role": "admin",
        "category": "routing",
    },
    {
        "id": "rt_044",
        "q": "What machines are at the Granulation Processing Workstation?",
        "expect_any": ["granulation", "machine", "workstation"],
        "role": "admin",
        "category": "routing",
    },
    {
        "id": "rt_045",
        "q": "List stages for Tablet Line A.",
        "expect_any": [
            "dispensing",
            "granulation",
            "blending",
            "compression",
            "coating",
            "inspection",
            "packaging",
            "mixing",
        ],
        "role": "admin",
        "category": "routing",
    },
    # Worker detail queries
    {
        "id": "rt_046",
        "q": "What shift does Karan Shah work?",
        "expect_any": ["day shift", "karan", "shift"],
        "role": "admin",
        "category": "routing",
    },
    {
        "id": "rt_047",
        "q": "What devices does Karan Shah have?",
        "expect_any": ["karan", "device", "label printer"],
        "role": "admin",
        "category": "routing",
    },
    {
        "id": "rt_048",
        "q": "What work orders does Karan Shah have?",
        "expect_any": ["karan", "work order", "calibration", "bin blender"],
        "role": "admin",
        "category": "routing",
    },
    {
        "id": "rt_049",
        "q": "What is Karan Shah's role?",
        "expect_any": ["karan", "blend preparation", "operator"],
        "role": "admin",
        "category": "routing",
    },
    {
        "id": "rt_050",
        "q": "What line is Karan Shah assigned to?",
        "expect_any": ["karan", "tablet line a", "line"],
        "role": "admin",
        "category": "routing",
    },
    # Entity definition vs attribute
    {
        "id": "rt_051",
        "q": "What is a machine?",
        "expect_any": ["machine", "production", "asset", "equipment"],
        "role": "admin",
        "category": "routing",
    },
    {
        "id": "rt_052",
        "q": "What is a workstation?",
        "expect_any": ["workstation", "location", "operation", "stage"],
        "role": "admin",
        "category": "routing",
    },
    {
        "id": "rt_053",
        "q": "What is a plant?",
        "expect_any": ["plant", "facility", "manufacturing", "location"],
        "role": "admin",
        "category": "routing",
    },
    {
        "id": "rt_054",
        "q": "What is a production line?",
        "expect_any": ["line", "production", "manufacturing", "stage"],
        "role": "admin",
        "category": "routing",
    },
    {
        "id": "rt_055",
        "q": "What is a work order?",
        "expect_any": ["work order", "task", "assignment", "execution"],
        "role": "admin",
        "category": "routing",
    },
    # Count vs List
    {
        "id": "rt_056",
        "q": "How many machines are operational?",
        "expect_any": ["16", "machine", "operational"],
        "role": "admin",
        "category": "routing",
    },
    {
        "id": "rt_057",
        "q": "List all operational machines.",
        "expect_any": ["machine", "16", "list", "operational"],
        "role": "admin",
        "category": "routing",
    },
    {
        "id": "rt_058",
        "q": "How many work orders are in Todo status?",
        "expect_any": ["todo", "work order"],
        "role": "admin",
        "category": "routing",
    },
    {
        "id": "rt_059",
        "q": "List all Todo work orders.",
        "expect_any": ["todo", "work order"],
        "role": "admin",
        "category": "routing",
    },
    {
        "id": "rt_060",
        "q": "How many workstations are in the Blending stage?",
        "expect_any": ["2", "workstation", "blending"],
        "role": "admin",
        "category": "routing",
    },
    # Stress: rapid context switches
    {
        "id": "rt_061",
        "q": "Plant details",
        "expect_any": ["tablet manufacturing", "plant", "vadodara"],
        "role": "admin",
        "category": "routing",
    },
    {
        "id": "rt_062",
        "q": "Now tell me about lines",
        "expect_any": ["tablet line a", "line"],
        "role": "admin",
        "category": "routing",
    },
    {
        "id": "rt_063",
        "q": "What about machines?",
        "expect_any": ["machine", "16", "list"],
        "role": "admin",
        "category": "routing",
    },
    {
        "id": "rt_064",
        "q": "And workers?",
        "expect_any": ["worker", "18", "list"],
        "role": "admin",
        "category": "routing",
    },
    {
        "id": "rt_065",
        "q": "Work orders now",
        "expect_any": ["work order", "15", "list"],
        "role": "admin",
        "category": "routing",
    },
    # Edge routing
    {
        "id": "rt_066",
        "q": "Show me everything",
        "expect_any": ["plant", "line", "machine", "worker", "stage", "no", "not"],
        "role": "admin",
        "category": "routing",
    },
    {
        "id": "rt_067",
        "q": "What do you know?",
        "expect_any": ["plant", "line", "machine", "worker", "stage", "manufacturing"],
        "role": "admin",
        "category": "routing",
    },
    {
        "id": "rt_068",
        "q": "Help me understand the system",
        "expect_any": ["plant", "line", "machine", "worker", "stage", "manufacturing"],
        "role": "admin",
        "category": "routing",
    },
    {
        "id": "rt_069",
        "q": "Give me an overview",
        "expect_any": ["plant", "line", "machine", "worker", "stage", "manufacturing"],
        "role": "admin",
        "category": "routing",
    },
    {
        "id": "rt_070",
        "q": "What is this system about?",
        "expect_any": ["plant", "manufacturing", "tablet", "line", "machine"],
        "role": "admin",
        "category": "routing",
    },
    # Simulation / What-if routing
    {
        "id": "rt_071",
        "q": "What happens if we increase granulator speed by 8%?",
        "expect_any": ["granul", "speed", "increase", "impact", "granule"],
        "role": "admin",
        "category": "routing",
    },
    {
        "id": "rt_072",
        "q": "What happens if we reduce blender speed by 5%?",
        "expect_any": ["blender", "speed", "reduce", "blend", "impact"],
        "role": "admin",
        "category": "routing",
    },
    {
        "id": "rt_073",
        "q": "What happens if we add a second rotary tablet press?",
        "expect_any": ["tablet press", "second", "add", "throughput", "impact"],
        "role": "admin",
        "category": "routing",
    },
    {
        "id": "rt_074",
        "q": "What happens if demand spikes by 20%?",
        "expect_any": ["demand", "spike", "20", "impact", "capacity"],
        "role": "admin",
        "category": "routing",
    },
    {
        "id": "rt_075",
        "q": "What happens if we shorten maintenance windows?",
        "expect_any": ["maintenance", "shorten", "impact", "equipment"],
        "role": "admin",
        "category": "routing",
    },
    # Worker assignment vs report-to routing
    {
        "id": "rt_076",
        "q": "Who does Arjun Mehta report to?",
        "expect_any": ["rohan", "kulkarni", "report"],
        "role": "admin",
        "category": "routing",
    },
    {
        "id": "rt_077",
        "q": "Who reports to Rohan Kulkarni?",
        "expect_any": ["rohan", "kulkarni", "report"],
        "role": "admin",
        "category": "routing",
    },
    {
        "id": "rt_078",
        "q": "What is assigned to Karan Shah?",
        "expect_any": ["karan", "shah", "assigned", "device", "work order"],
        "role": "admin",
        "category": "routing",
    },
    {
        "id": "rt_079",
        "q": "What is Karan Shah assigned to?",
        "expect_any": ["karan", "shah", "assigned", "blend", "workstation"],
        "role": "admin",
        "category": "routing",
    },
    {
        "id": "rt_080",
        "q": "Who is assigned to work order Calibration - Bin Blender?",
        "expect_any": ["karan", "shah", "assigned", "calibration"],
        "role": "admin",
        "category": "routing",
    },
]

# ═══════════════════════════════════════════════════════════════════════════════
# CATEGORY 4: DECOMPOSITION VALIDATION (60 questions)
# Complex questions requiring multi-hop reasoning
# ═══════════════════════════════════════════════════════════════════════════════
DECOMPOSITION = [
    # Plant → Line → Stage chain
    {
        "id": "dc_001",
        "q": "What stages are on the line that is in the Tablet Manufacturing Plant?",
        "expect_any": [
            "dispensing",
            "granulation",
            "blending",
            "compression",
            "coating",
            "inspection",
            "packaging",
            "mixing",
        ],
        "role": "admin",
        "category": "decomposition",
    },
    {
        "id": "dc_002",
        "q": "What workstations are on the stages of the line managed by Amit Desai?",
        "expect_any": ["workstation", "amit", "desai"],
        "role": "admin",
        "category": "decomposition",
    },
    {
        "id": "dc_003",
        "q": "What machines are at the workstations belonging to the Blending stage?",
        "expect_any": ["bin blender", "machine", "blending"],
        "role": "admin",
        "category": "decomposition",
    },
    {
        "id": "dc_004",
        "q": "Who operates the machines in the Granulation stage?",
        "expect_any": ["granulation", "operator", "machine"],
        "role": "admin",
        "category": "decomposition",
    },
    {
        "id": "dc_005",
        "q": "What SOPs are bound to the machines in the Compression stage?",
        "expect_any": ["sop", "compression", "machine", "tablet press"],
        "role": "admin",
        "category": "decomposition",
    },
    # Worker → Workstation → Machine chain
    {
        "id": "dc_006",
        "q": "What machine does Karan Shah operate?",
        "expect_any": ["bin blender", "karan", "machine"],
        "role": "admin",
        "category": "decomposition",
    },
    {
        "id": "dc_007",
        "q": "What equipment is at Karan Shah's workstation?",
        "expect_any": ["karan", "equipment", "blend", "workstation"],
        "role": "admin",
        "category": "decomposition",
    },
    {
        "id": "dc_008",
        "q": "What SOPs are bound to Karan Shah's workstation?",
        "expect_any": ["sop", "karan", "blend", "workstation"],
        "role": "admin",
        "category": "decomposition",
    },
    {
        "id": "dc_009",
        "q": "What work orders are assigned to the person at the Blend Preparation Workstation?",
        "expect_any": ["karan", "work order", "calibration", "bin blender"],
        "role": "admin",
        "category": "decomposition",
    },
    {
        "id": "dc_010",
        "q": "What shift does the person who operates the Bin Blender work?",
        "expect_any": ["karan", "day shift", "shift", "bin blender"],
        "role": "admin",
        "category": "decomposition",
    },
    # Work Order → Machine → Workstation chain
    {
        "id": "dc_011",
        "q": "What workstation has the machine that the Calibration - Bin Blender work order is for?",
        "expect_any": ["bin blender", "workstation", "calibration", "blend"],
        "role": "admin",
        "category": "decomposition",
    },
    {
        "id": "dc_012",
        "q": "What stage is the machine for the Cleaning - High Shear Granulator work order in?",
        "expect_any": ["granulation", "stage", "high shear"],
        "role": "admin",
        "category": "decomposition",
    },
    {
        "id": "dc_013",
        "q": "Who manages the line that has the machine for the Calibration - Floor Scale work order?",
        "expect_any": ["amit", "desai", "line manager"],
        "role": "admin",
        "category": "decomposition",
    },
    {
        "id": "dc_014",
        "q": "What is the status of the work order for the machine at the Blend Preparation Workstation?",
        "expect_any": ["calibration", "bin blender", "on hold", "work order"],
        "role": "admin",
        "category": "decomposition",
    },
    {
        "id": "dc_015",
        "q": "How many work orders are for machines on Tablet Line A?",
        "expect_any": ["work order", "tablet line a", "machine"],
        "role": "admin",
        "category": "decomposition",
    },
    # Multi-attribute extraction
    {
        "id": "dc_016",
        "q": "What is the name, type, and manufacturer of the Bin Blender?",
        "expect_any": ["bin blender", "mechanical", "patterson"],
        "role": "admin",
        "category": "decomposition",
    },
    {
        "id": "dc_017",
        "q": "What is the takt time, efficiency, and status of the Blending stage?",
        "expect_any": ["5400", "93", "operational", "blending"],
        "role": "admin",
        "category": "decomposition",
    },
    {
        "id": "dc_018",
        "q": "What is the name, role, and shift of Karan Shah?",
        "expect_any": ["karan", "shah", "blend preparation", "day shift"],
        "role": "admin",
        "category": "decomposition",
    },
    {
        "id": "dc_019",
        "q": "What is the title, status, and priority of the Calibration - Bin Blender work order?",
        "expect_any": ["calibration", "bin blender", "on hold", "critical"],
        "role": "admin",
        "category": "decomposition",
    },
    {
        "id": "dc_020",
        "q": "What is the plant name, location, and manager?",
        "expect_any": ["tablet manufacturing", "vadodara", "priya", "sharma"],
        "role": "admin",
        "category": "decomposition",
    },
    # Comparative queries
    {
        "id": "dc_021",
        "q": "Which stage has the highest takt time?",
        "expect_any": ["10800", "film coating", "takt", "highest"],
        "role": "admin",
        "category": "decomposition",
    },
    {
        "id": "dc_022",
        "q": "Which stage has the lowest efficiency?",
        "expect_any": ["88", "compression", "efficiency", "lowest"],
        "role": "admin",
        "category": "decomposition",
    },
    {
        "id": "dc_023",
        "q": "Which stage has the highest efficiency?",
        "expect_any": ["97", "inspection", "efficiency", "highest"],
        "role": "admin",
        "category": "decomposition",
    },
    {
        "id": "dc_024",
        "q": "Which has more workstations, Blending or Granulation?",
        "expect_any": ["workstation", "blending", "granulation"],
        "role": "admin",
        "category": "decomposition",
    },
    {
        "id": "dc_025",
        "q": "Which machine has a higher takt priority, Bin Blender or Tablet Press?",
        "expect_any": ["bin blender", "tablet press", "priority", "critical"],
        "role": "admin",
        "category": "decomposition",
    },
    # Filtering
    {
        "id": "dc_026",
        "q": "What critical work orders are currently On Hold?",
        "expect_any": ["critical", "on hold", "work order", "calibration", "cleaning"],
        "role": "admin",
        "category": "decomposition",
    },
    {
        "id": "dc_027",
        "q": "What work orders are In Progress and assigned to someone?",
        "expect_any": ["in progress", "work order", "assigned"],
        "role": "admin",
        "category": "decomposition",
    },
    {
        "id": "dc_028",
        "q": "What machines are CNC / Automated and in the Compression area?",
        "expect_any": ["cnc", "automated", "compression", "tablet press"],
        "role": "admin",
        "category": "decomposition",
    },
    {
        "id": "dc_029",
        "q": "What workers work the Evening Shift?",
        "expect_any": ["evening shift", "worker"],
        "role": "admin",
        "category": "decomposition",
    },
    {
        "id": "dc_030",
        "q": "What work orders are for calibration type machines?",
        "expect_any": ["calibration", "work order"],
        "role": "admin",
        "category": "decomposition",
    },
    # Traversal: Plant → Line → Stage → Workstation → Machine
    {
        "id": "dc_031",
        "q": "What machines are two levels below Tablet Line A in the hierarchy?",
        "expect_any": ["machine", "tablet line a", "stage", "workstation"],
        "role": "admin",
        "category": "decomposition",
    },
    {
        "id": "dc_032",
        "q": "From the plant level, trace down to the Bin Blender. What path is that?",
        "expect_any": ["bin blender", "plant", "line", "stage", "workstation"],
        "role": "admin",
        "category": "decomposition",
    },
    {
        "id": "dc_033",
        "q": "Starting from the Blending stage, what are all the entities below it?",
        "expect_any": ["blending", "workstation", "machine", "equipment"],
        "role": "admin",
        "category": "decomposition",
    },
    {
        "id": "dc_034",
        "q": "What is the full hierarchy from plant to Karan Shah?",
        "expect_any": ["karan", "plant", "line", "stage", "workstation"],
        "role": "admin",
        "category": "decomposition",
    },
    {
        "id": "dc_035",
        "q": "What is the chain from the Tablet Press up to the plant?",
        "expect_any": ["tablet press", "workstation", "stage", "line", "plant"],
        "role": "admin",
        "category": "decomposition",
    },
    # Aggregation
    {
        "id": "dc_036",
        "q": "What is the total number of machines and equipment combined?",
        "expect_any": ["machine", "equipment", "16", "86"],
        "role": "admin",
        "category": "decomposition",
    },
    {
        "id": "dc_037",
        "q": "How many work orders are assigned vs unassigned?",
        "expect_any": ["work order", "assigned", "unassigned"],
        "role": "admin",
        "category": "decomposition",
    },
    {
        "id": "dc_038",
        "q": "How many Day Shift vs Evening Shift vs Night Shift workers are there?",
        "expect_any": ["day shift", "evening shift", "night shift", "worker"],
        "role": "admin",
        "category": "decomposition",
    },
    {
        "id": "dc_039",
        "q": "How many work orders are completed vs in progress vs on hold?",
        "expect_any": ["completed", "in progress", "on hold", "work order"],
        "role": "admin",
        "category": "decomposition",
    },
    {
        "id": "dc_040",
        "q": "How many CNC machines vs Mechanical machines are there?",
        "expect_any": ["cnc", "mechanical", "machine"],
        "role": "admin",
        "category": "decomposition",
    },
    # Cross-entity queries
    {
        "id": "dc_041",
        "q": "What machines have work orders assigned to Karan Shah?",
        "expect_any": ["karan", "bin blender", "machine", "work order"],
        "role": "admin",
        "category": "decomposition",
    },
    {
        "id": "dc_042",
        "q": "Which stages have operators assigned to them?",
        "expect_any": ["stage", "operator", "worker"],
        "role": "admin",
        "category": "decomposition",
    },
    {
        "id": "dc_043",
        "q": "What work orders are for machines made by GEA?",
        "expect_any": ["gea", "work order", "machine"],
        "role": "admin",
        "category": "decomposition",
    },
    {
        "id": "dc_044",
        "q": "Which workers have devices assigned and work orders?",
        "expect_any": ["worker", "device", "work order", "assigned"],
        "role": "admin",
        "category": "decomposition",
    },
    {
        "id": "dc_045",
        "q": "What machines are in stages with efficiency above 90%?",
        "expect_any": ["efficiency", "machine", "stage", "above 90"],
        "role": "admin",
        "category": "decomposition",
    },
    # Temporal
    {
        "id": "dc_046",
        "q": "What work orders are due soonest?",
        "expect_any": ["work order", "due", "calibration", "calibration weight set"],
        "role": "admin",
        "category": "decomposition",
    },
    {
        "id": "dc_047",
        "q": "What work orders were completed?",
        "expect_any": ["completed", "work order", "calibration", "inspection"],
        "role": "admin",
        "category": "decomposition",
    },
    {
        "id": "dc_048",
        "q": "What work orders are overdue?",
        "expect_any": ["work order", "overdue", "no", "not"],
        "role": "admin",
        "category": "decomposition",
    },
    {
        "id": "dc_049",
        "q": "What is the most recent work order?",
        "expect_any": ["work order", "recent", "latest"],
        "role": "admin",
        "category": "decomposition",
    },
    {
        "id": "dc_050",
        "q": "What work orders are scheduled for the future?",
        "expect_any": ["work order", "todo", "scheduled", "future"],
        "role": "admin",
        "category": "decomposition",
    },
    # Multi-hop with constraints
    {
        "id": "dc_051",
        "q": "What is the takt time of the stage that has the Tablet Press?",
        "expect_any": ["5400", "compression", "tablet press", "takt"],
        "role": "admin",
        "category": "decomposition",
    },
    {
        "id": "dc_052",
        "q": "Who manages the line that contains the Blending stage?",
        "expect_any": ["amit", "desai", "line manager", "blending"],
        "role": "admin",
        "category": "decomposition",
    },
    {
        "id": "dc_053",
        "q": "What is the manufacturer of the machine at Karan Shah's workstation?",
        "expect_any": ["patterson", "kelley", "bin blender", "karan"],
        "role": "admin",
        "category": "decomposition",
    },
    {
        "id": "dc_054",
        "q": "What is the priority of the work order for the machine made by GEA in the Granulation area?",
        "expect_any": ["critical", "high", "gea", "granulation", "work order"],
        "role": "admin",
        "category": "decomposition",
    },
    {
        "id": "dc_055",
        "q": "What status is the work order for the machine at the station managed by Karan Shah?",
        "expect_any": ["calibration", "bin blender", "on hold", "karan"],
        "role": "admin",
        "category": "decomposition",
    },
    # Complex decomposition
    {
        "id": "dc_056",
        "q": "For each stage on Tablet Line A, what is the takt time and efficiency?",
        "expect_any": ["stage", "takt", "efficiency", "tablet line a"],
        "role": "admin",
        "category": "decomposition",
    },
    {
        "id": "dc_057",
        "q": "For each worker, what is their role and shift?",
        "expect_any": ["worker", "role", "shift"],
        "role": "admin",
        "category": "decomposition",
    },
    {
        "id": "dc_058",
        "q": "What is the full detail of every work order in the system?",
        "expect_any": ["work order", "title", "status", "priority"],
        "role": "admin",
        "category": "decomposition",
    },
    {
        "id": "dc_059",
        "q": "List every machine with its type and status.",
        "expect_any": ["machine", "type", "status", "operational"],
        "role": "admin",
        "category": "decomposition",
    },
    {
        "id": "dc_060",
        "q": "What is the complete topology of the manufacturing system?",
        "expect_any": [
            "plant",
            "line",
            "stage",
            "workstation",
            "machine",
            "manufacturing",
        ],
        "role": "admin",
        "category": "decomposition",
    },
]

# ═══════════════════════════════════════════════════════════════════════════════
# CATEGORY 5: ONTOLOGY COLLISION TESTS (60 questions)
# Entities with overlapping names/types that could confuse the system
# ═══════════════════════════════════════════════════════════════════════════════
ONTOLOGY = [
    # "Blending" = stage AND workstation name component
    {
        "id": "ont_001",
        "q": "What is the Blending stage?",
        "expect_any": ["blending", "stage", "takt", "efficiency"],
        "role": "admin",
        "category": "ontology",
    },
    {
        "id": "ont_002",
        "q": "What is the Blend Preparation Workstation?",
        "expect_any": ["blend preparation", "workstation"],
        "role": "admin",
        "category": "ontology",
    },
    {
        "id": "ont_003",
        "q": "What is at the Blend Uniformity Testing Workstation?",
        "expect_any": ["blend uniformity", "workstation"],
        "role": "admin",
        "category": "ontology",
    },
    {
        "id": "ont_004",
        "q": "How many Blending entities are there?",
        "expect_any": ["blending", "blend", "stage", "workstation"],
        "role": "admin",
        "category": "ontology",
    },
    {
        "id": "ont_005",
        "q": "What is the difference between Blending stage and Blend Preparation Workstation?",
        "expect_any": ["blending", "blend preparation", "stage", "workstation"],
        "role": "admin",
        "category": "ontology",
    },
    # "Tablet" = line name, machine type, product type
    {
        "id": "ont_006",
        "q": "What is Tablet Line A?",
        "expect_any": ["tablet line a", "line", "batch"],
        "role": "admin",
        "category": "ontology",
    },
    {
        "id": "ont_007",
        "q": "What is the Tablet Press?",
        "expect_any": ["tablet press", "machine", "comp-001"],
        "role": "admin",
        "category": "ontology",
    },
    {
        "id": "ont_008",
        "q": "What is the Tablet Deduster?",
        "expect_any": ["tablet deduster", "machine", "comp-002"],
        "role": "admin",
        "category": "ontology",
    },
    {
        "id": "ont_009",
        "q": "What is the Tablet Coating Workstation?",
        "expect_any": ["tablet coating", "workstation"],
        "role": "admin",
        "category": "ontology",
    },
    {
        "id": "ont_010",
        "q": "What Tablet entities are in the system?",
        "expect_any": ["tablet", "line", "press", "deduster", "coating"],
        "role": "admin",
        "category": "ontology",
    },
    # "Calibration" = work order type AND calibration records
    {
        "id": "ont_011",
        "q": "What calibration work orders are there?",
        "expect_any": ["calibration", "work order"],
        "role": "admin",
        "category": "ontology",
    },
    {
        "id": "ont_012",
        "q": "What calibration records exist?",
        "expect_any": ["calibration", "record"],
        "role": "admin",
        "category": "ontology",
    },
    {
        "id": "ont_013",
        "q": "Show the Calibration - Bin Blender work order.",
        "expect_any": ["calibration", "bin blender", "work order", "on hold"],
        "role": "admin",
        "category": "ontology",
    },
    {
        "id": "ont_014",
        "q": "What is the difference between calibration work orders and calibration records?",
        "expect_any": ["calibration", "work order", "record"],
        "role": "admin",
        "category": "ontology",
    },
    {
        "id": "ont_015",
        "q": "Which machines have calibration work orders?",
        "expect_any": [
            "calibration",
            "work order",
            "machine",
            "bin blender",
            "floor scale",
        ],
        "role": "admin",
        "category": "ontology",
    },
    # "Granulation" = stage AND processing workstation AND machine area
    {
        "id": "ont_016",
        "q": "What is the Granulation stage?",
        "expect_any": ["granulation", "stage", "7200", "takt"],
        "role": "admin",
        "category": "ontology",
    },
    {
        "id": "ont_017",
        "q": "What is the Granulation Processing Workstation?",
        "expect_any": ["granulation processing", "workstation"],
        "role": "admin",
        "category": "ontology",
    },
    {
        "id": "ont_018",
        "q": "What machines are in the Granulation area?",
        "expect_any": ["granulator", "machine", "granulation"],
        "role": "admin",
        "category": "ontology",
    },
    {
        "id": "ont_019",
        "q": "What work orders are for Granulation machines?",
        "expect_any": ["granulation", "work order", "high shear", "cleaning"],
        "role": "admin",
        "category": "ontology",
    },
    {
        "id": "ont_020",
        "q": "Who works in the Granulation stage?",
        "expect_any": ["granulation", "rahul", "nikita", "worker"],
        "role": "admin",
        "category": "ontology",
    },
    # "Cleaning" = work order type AND cleaning records
    {
        "id": "ont_021",
        "q": "What cleaning work orders are there?",
        "expect_any": ["cleaning", "work order"],
        "role": "admin",
        "category": "ontology",
    },
    {
        "id": "ont_022",
        "q": "What cleaning records exist?",
        "expect_any": ["cleaning", "record"],
        "role": "admin",
        "category": "ontology",
    },
    {
        "id": "ont_023",
        "q": "Show the Cleaning - High Shear Granulator work order.",
        "expect_any": ["cleaning", "high shear granulator", "work order", "on hold"],
        "role": "admin",
        "category": "ontology",
    },
    {
        "id": "ont_024",
        "q": "Show the Cleaning - Tablet Press work order.",
        "expect_any": ["cleaning", "tablet press", "work order", "todo"],
        "role": "admin",
        "category": "ontology",
    },
    {
        "id": "ont_025",
        "q": "What is the difference between cleaning work orders and cleaning records?",
        "expect_any": ["cleaning", "work order", "record"],
        "role": "admin",
        "category": "ontology",
    },
    # "Coating" = stage AND workstation AND machine
    {
        "id": "ont_026",
        "q": "What is the Film Coating stage?",
        "expect_any": ["film coating", "stage", "10800"],
        "role": "admin",
        "category": "ontology",
    },
    {
        "id": "ont_027",
        "q": "What is the Tablet Coating Workstation?",
        "expect_any": ["tablet coating", "workstation"],
        "role": "admin",
        "category": "ontology",
    },
    {
        "id": "ont_028",
        "q": "What is the Coating Pan?",
        "expect_any": ["coating pan", "machine", "co-001"],
        "role": "admin",
        "category": "ontology",
    },
    {
        "id": "ont_029",
        "q": "What is the Coating Quality Inspection Workstation?",
        "expect_any": ["coating quality", "inspection", "workstation"],
        "role": "admin",
        "category": "ontology",
    },
    {
        "id": "ont_030",
        "q": "Who works in the Coating area?",
        "expect_any": ["farah", "merchant", "coating", "ananya", "ghosh"],
        "role": "admin",
        "category": "ontology",
    },
    # "Inspection" = stage AND work order type AND workstation
    {
        "id": "ont_031",
        "q": "What is the Inspection stage?",
        "expect_any": ["inspection", "stage", "97", "efficiency"],
        "role": "admin",
        "category": "ontology",
    },
    {
        "id": "ont_032",
        "q": "What inspection work orders are there?",
        "expect_any": ["inspection", "work order"],
        "role": "admin",
        "category": "ontology",
    },
    {
        "id": "ont_033",
        "q": "What is the In-Process Quality Inspection Workstation?",
        "expect_any": ["in-process quality", "inspection", "workstation"],
        "role": "admin",
        "category": "ontology",
    },
    {
        "id": "ont_034",
        "q": "What is the difference between Inspection stage and inspection work orders?",
        "expect_any": ["inspection", "stage", "work order"],
        "role": "admin",
        "category": "ontology",
    },
    {
        "id": "ont_035",
        "q": "Show the Inspection - Analytical Balance work order.",
        "expect_any": ["inspection", "analytical balance", "work order", "in progress"],
        "role": "admin",
        "category": "ontology",
    },
    # "Packaging" = stage AND machine AND workstation
    {
        "id": "ont_036",
        "q": "What is the Packaging stage?",
        "expect_any": ["packaging", "stage", "95", "efficiency"],
        "role": "admin",
        "category": "ontology",
    },
    {
        "id": "ont_037",
        "q": "What is the Blister Packaging Machine?",
        "expect_any": ["blister packaging", "machine", "pack-001"],
        "role": "admin",
        "category": "ontology",
    },
    {
        "id": "ont_038",
        "q": "What is the Blister Packaging Workstation?",
        "expect_any": ["blister packaging", "workstation"],
        "role": "admin",
        "category": "ontology",
    },
    {
        "id": "ont_039",
        "q": "What is the Cartoner?",
        "expect_any": ["cartoner", "machine", "pack-002"],
        "role": "admin",
        "category": "ontology",
    },
    {
        "id": "ont_040",
        "q": "What is the Cartoning Workstation?",
        "expect_any": ["cartoning", "workstation"],
        "role": "admin",
        "category": "ontology",
    },
    # Worker name collisions
    {
        "id": "ont_041",
        "q": "Who is Arjun Mehta?",
        "expect_any": ["arjun", "mehta", "dispensing", "operator"],
        "role": "admin",
        "category": "ontology",
    },
    {
        "id": "ont_042",
        "q": "Who is Rahul Desai?",
        "expect_any": ["rahul", "desai", "granulation", "operator"],
        "role": "admin",
        "category": "ontology",
    },
    {
        "id": "ont_043",
        "q": "Who is Devansh Kapoor?",
        "expect_any": ["devansh", "kapoor", "ipc", "analyst"],
        "role": "admin",
        "category": "ontology",
    },
    {
        "id": "ont_044",
        "q": "Who is Imran Qureshi?",
        "expect_any": ["imran", "qureshi", "blister", "packaging"],
        "role": "admin",
        "category": "ontology",
    },
    {
        "id": "ont_045",
        "q": "Who is Manish Trivedi?",
        "expect_any": ["manish", "trivedi", "batch release", "inspector"],
        "role": "admin",
        "category": "ontology",
    },
    # ID collisions
    {
        "id": "ont_046",
        "q": "What is MACH-GRAN-001?",
        "expect_any": ["high shear granulator", "machine"],
        "role": "admin",
        "category": "ontology",
    },
    {
        "id": "ont_047",
        "q": "What is MACH-BLEND-001?",
        "expect_any": ["bin blender", "machine"],
        "role": "admin",
        "category": "ontology",
    },
    {
        "id": "ont_048",
        "q": "What is MACH-COMP-001?",
        "expect_any": ["tablet press", "machine"],
        "role": "admin",
        "category": "ontology",
    },
    {
        "id": "ont_049",
        "q": "What is WS-TBL-A-001-07?",
        "expect_any": ["blend preparation", "workstation"],
        "role": "admin",
        "category": "ontology",
    },
    {
        "id": "ont_050",
        "q": "What is WO-MACH-BLEND-001-007?",
        "expect_any": ["calibration", "bin blender", "work order"],
        "role": "admin",
        "category": "ontology",
    },
    # Entity type confusion
    {
        "id": "ont_051",
        "q": "Is the Bin Blender a machine, equipment, or tool?",
        "expect_any": ["machine", "bin blender"],
        "role": "admin",
        "category": "ontology",
    },
    {
        "id": "ont_052",
        "q": "Is the Calibration Weight Set a machine or equipment?",
        "expect_any": ["calibration", "weight", "machine", "equipment"],
        "role": "admin",
        "category": "ontology",
    },
    {
        "id": "ont_053",
        "q": "Is the Barcode Scanner a machine or a device?",
        "expect_any": ["barcode scanner", "device", "machine"],
        "role": "admin",
        "category": "ontology",
    },
    {
        "id": "ont_054",
        "q": "Is Karan Shah a worker or a user?",
        "expect_any": ["karan", "shah", "worker"],
        "role": "admin",
        "category": "ontology",
    },
    {
        "id": "ont_055",
        "q": "Is the Blend Preparation Workstation a workstation or a stage?",
        "expect_any": ["blend preparation", "workstation"],
        "role": "admin",
        "category": "ontology",
    },
    # Overlapping terminology
    {
        "id": "ont_056",
        "q": "What is the difference between a line and a stage?",
        "expect_any": ["line", "stage", "difference", "production"],
        "role": "admin",
        "category": "ontology",
    },
    {
        "id": "ont_057",
        "q": "What is the difference between a machine and equipment?",
        "expect_any": ["machine", "equipment", "difference"],
        "role": "admin",
        "category": "ontology",
    },
    {
        "id": "ont_058",
        "q": "What is the difference between a work order and a batch?",
        "expect_any": ["work order", "batch", "difference"],
        "role": "admin",
        "category": "ontology",
    },
    {
        "id": "ont_059",
        "q": "What is the difference between a worker and a user?",
        "expect_any": ["worker", "user", "difference"],
        "role": "admin",
        "category": "ontology",
    },
    {
        "id": "ont_060",
        "q": "What is the difference between a SOP and a work order?",
        "expect_any": ["sop", "work order", "difference"],
        "role": "admin",
        "category": "ontology",
    },
]

# ═══════════════════════════════════════════════════════════════════════════════
# CATEGORY 6: PLANNER EVALUATION (60 questions)
# Complex multi-step reasoning and planning queries
# ═══════════════════════════════════════════════════════════════════════════════
PLANNER = [
    # Scenario planning
    {
        "id": "pl_001",
        "q": "If the Bin Blender goes down, what workstations are affected?",
        "expect_any": ["bin blender", "workstation", "blend"],
        "role": "admin",
        "category": "planner",
    },
    {
        "id": "pl_002",
        "q": "If Karan Shah is unavailable, who could cover his shift?",
        "expect_any": ["karan", "shah", "blend", "operator", "worker"],
        "role": "admin",
        "category": "planner",
    },
    {
        "id": "pl_003",
        "q": "If we add a new stage after Blending, what would be downstream?",
        "expect_any": ["compression", "coating", "inspection", "packaging"],
        "role": "admin",
        "category": "planner",
    },
    {
        "id": "pl_004",
        "q": "What happens if we increase Granulation takt time by 10%?",
        "expect_any": ["7200", "granulation", "takt", "increase"],
        "role": "admin",
        "category": "planner",
    },
    {
        "id": "pl_005",
        "q": "What is the impact of removing the Tablet Deduster from the line?",
        "expect_any": ["tablet deduster", "compression", "line"],
        "role": "admin",
        "category": "planner",
    },
    # Resource allocation
    {
        "id": "pl_006",
        "q": "Which workers are available for new work orders?",
        "expect_any": ["worker", "available", "shift"],
        "role": "admin",
        "category": "planner",
    },
    {
        "id": "pl_007",
        "q": "How many workers are assigned to Blending stage tasks?",
        "expect_any": ["karan", "vivek", "blend", "worker"],
        "role": "admin",
        "category": "planner",
    },
    {
        "id": "pl_008",
        "q": "What machines need attention based on their work orders?",
        "expect_any": [
            "machine",
            "work order",
            "calibration",
            "cleaning",
            "maintenance",
        ],
        "role": "admin",
        "category": "planner",
    },
    {
        "id": "pl_009",
        "q": "Are there enough workers for a 3-shift operation?",
        "expect_any": ["worker", "shift", "day", "evening", "night"],
        "role": "admin",
        "category": "planner",
    },
    {
        "id": "pl_010",
        "q": "Which workstations have no workers assigned?",
        "expect_any": ["workstation", "worker", "assigned"],
        "role": "admin",
        "category": "planner",
    },
    # Capacity planning
    {
        "id": "pl_011",
        "q": "What is the bottleneck stage based on takt times?",
        "expect_any": ["10800", "film coating", "takt", "bottleneck", "highest"],
        "role": "admin",
        "category": "planner",
    },
    {
        "id": "pl_012",
        "q": "What is the minimum takt time across all stages?",
        "expect_any": [
            "3600",
            "takt",
            "minimum",
            "dispensing",
            "mixing",
            "inspection",
            "packaging",
        ],
        "role": "admin",
        "category": "planner",
    },
    {
        "id": "pl_013",
        "q": "How does the plant utilization compare to the line efficiency?",
        "expect_any": ["76", "utilization", "88", "efficiency"],
        "role": "admin",
        "category": "planner",
    },
    {
        "id": "pl_014",
        "q": "What is the theoretical maximum throughput of the line?",
        "expect_any": ["throughput", "capacity", "line", "tablet"],
        "role": "admin",
        "category": "planner",
    },
    {
        "id": "pl_015",
        "q": "Which stage limits overall production capacity?",
        "expect_any": ["film coating", "stage", "capacity", "takt", "limit"],
        "role": "admin",
        "category": "planner",
    },
    # Maintenance planning
    {
        "id": "pl_016",
        "q": "Which machines have critical work orders pending?",
        "expect_any": [
            "critical",
            "machine",
            "work order",
            "calibration",
            "bin blender",
            "cleaning",
            "granulator",
        ],
        "role": "admin",
        "category": "planner",
    },
    {
        "id": "pl_017",
        "q": "What maintenance is overdue?",
        "expect_any": ["maintenance", "overdue", "no", "not", "due"],
        "role": "admin",
        "category": "planner",
    },
    {
        "id": "pl_018",
        "q": "Which machines need calibration soon?",
        "expect_any": ["calibration", "machine", "work order", "todo"],
        "role": "admin",
        "category": "planner",
    },
    {
        "id": "pl_019",
        "q": "How many work orders are blocking production?",
        "expect_any": ["on hold", "critical", "work order", "blocking"],
        "role": "admin",
        "category": "planner",
    },
    {
        "id": "pl_020",
        "q": "What is the maintenance backlog?",
        "expect_any": ["maintenance", "backlog", "work order", "todo", "on hold"],
        "role": "admin",
        "category": "planner",
    },
    # Compliance planning
    {
        "id": "pl_021",
        "q": "Are all machines covered by SOPs?",
        "expect_any": ["sop", "machine", "covered", "yes", "all"],
        "role": "admin",
        "category": "planner",
    },
    {
        "id": "pl_022",
        "q": "Which certifications does the plant need to maintain?",
        "expect_any": ["certification", "who-gmp", "schedule m", "plant"],
        "role": "admin",
        "category": "planner",
    },
    {
        "id": "pl_023",
        "q": "What SOPs are bound to the Tablet Compression Workstation?",
        "expect_any": ["sop", "tablet compression", "workstation"],
        "role": "admin",
        "category": "planner",
    },
    {
        "id": "pl_024",
        "q": "Is the plant compliant with GMP standards?",
        "expect_any": ["gmp", "compliance", "certification", "who-gmp"],
        "role": "admin",
        "category": "planner",
    },
    {
        "id": "pl_025",
        "q": "What quality checks are in place at each stage?",
        "expect_any": ["quality", "stage", "inspection", "qc", "check"],
        "role": "admin",
        "category": "planner",
    },
    # Workforce planning
    {
        "id": "pl_026",
        "q": "What is the reporting hierarchy for the plant?",
        "expect_any": ["nandita", "rao", "rohan", "kulkarni", "report", "manager"],
        "role": "admin",
        "category": "planner",
    },
    {
        "id": "pl_027",
        "q": "How many operators are there vs analysts?",
        "expect_any": ["operator", "analyst", "worker"],
        "role": "admin",
        "category": "planner",
    },
    {
        "id": "pl_028",
        "q": "Which shift has the most workers?",
        "expect_any": ["day shift", "evening shift", "night shift", "worker", "shift"],
        "role": "admin",
        "category": "planner",
    },
    {
        "id": "pl_029",
        "q": "Who are the key personnel for each stage?",
        "expect_any": ["stage", "worker", "operator", "analyst"],
        "role": "admin",
        "category": "planner",
    },
    {
        "id": "pl_030",
        "q": "What training would new workers need based on the stages?",
        "expect_any": ["training", "stage", "worker", "blend", "compression"],
        "role": "admin",
        "category": "planner",
    },
    # What-if scenarios
    {
        "id": "pl_031",
        "q": "What happens if we reduce blender speed by 5%?",
        "expect_any": ["blender", "speed", "reduce", "blend", "impact"],
        "role": "admin",
        "category": "planner",
    },
    {
        "id": "pl_032",
        "q": "What happens if we increase lubrication time by 10%?",
        "expect_any": ["lubrication", "time", "increase", "impact"],
        "role": "admin",
        "category": "planner",
    },
    {
        "id": "pl_033",
        "q": "What happens if we increase dryer inlet temperature by 6 degrees?",
        "expect_any": ["dryer", "temperature", "increase", "impact"],
        "role": "admin",
        "category": "planner",
    },
    {
        "id": "pl_034",
        "q": "What happens if we operate the tablet press above SOP maximum?",
        "expect_any": ["tablet press", "above", "sop", "maximum", "rejected"],
        "role": "admin",
        "category": "planner",
    },
    {
        "id": "pl_035",
        "q": "What happens if content uniformity variance increases by 0.2%?",
        "expect_any": ["uniformity", "variance", "increase", "impact", "quality"],
        "role": "admin",
        "category": "planner",
    },
    # Cross-system reasoning
    {
        "id": "pl_036",
        "q": "If a machine goes down, what work orders need to be rescheduled?",
        "expect_any": ["machine", "work order", "reschedule", "down"],
        "role": "admin",
        "category": "planner",
    },
    {
        "id": "pl_037",
        "q": "What is the full impact of a Granulation stage failure?",
        "expect_any": ["granulation", "stage", "failure", "impact", "downstream"],
        "role": "admin",
        "category": "planner",
    },
    {
        "id": "pl_038",
        "q": "How does a worker shortage in the Evening Shift affect production?",
        "expect_any": ["evening shift", "worker", "shortage", "production"],
        "role": "admin",
        "category": "planner",
    },
    {
        "id": "pl_039",
        "q": "If two machines need calibration simultaneously, which takes priority?",
        "expect_any": ["calibration", "priority", "critical", "machine", "work order"],
        "role": "admin",
        "category": "planner",
    },
    {
        "id": "pl_040",
        "q": "What is the cascade effect of a Blending stage bottleneck?",
        "expect_any": ["blending", "bottleneck", "compression", "downstream", "impact"],
        "role": "admin",
        "category": "planner",
    },
    # Production planning
    {
        "id": "pl_041",
        "q": "How many tablets can be produced per day?",
        "expect_any": ["500000", "tablet", "day", "capacity"],
        "role": "admin",
        "category": "planner",
    },
    {
        "id": "pl_042",
        "q": "How many tablets per year?",
        "expect_any": ["120000000", "120 million", "tablet", "year"],
        "role": "admin",
        "category": "planner",
    },
    {
        "id": "pl_043",
        "q": "What is the shift schedule for production?",
        "expect_any": ["shift", "2", "8", "day", "schedule"],
        "role": "admin",
        "category": "planner",
    },
    {
        "id": "pl_044",
        "q": "How many shifts per day and hours per shift?",
        "expect_any": ["2", "shift", "8", "hour"],
        "role": "admin",
        "category": "planner",
    },
    {
        "id": "pl_045",
        "q": "What is the annual production target?",
        "expect_any": ["120", "million", "tablet", "annual", "year"],
        "role": "admin",
        "category": "planner",
    },
    # Equipment lifecycle
    {
        "id": "pl_046",
        "q": "What is the purchase date of the Bin Blender?",
        "expect_any": ["bin blender", "purchase", "date", "no"],
        "role": "admin",
        "category": "planner",
    },
    {
        "id": "pl_047",
        "q": "When is the next maintenance due for the Tablet Press?",
        "expect_any": ["tablet press", "maintenance", "next", "due"],
        "role": "admin",
        "category": "planner",
    },
    {
        "id": "pl_048",
        "q": "What is the service life of the Fluid Bed Dryer?",
        "expect_any": ["fluid bed dryer", "service life", "years", "no"],
        "role": "admin",
        "category": "planner",
    },
    {
        "id": "pl_049",
        "q": "When was the Coating Pan last maintained?",
        "expect_any": ["coating pan", "maintenance", "last", "date"],
        "role": "admin",
        "category": "planner",
    },
    {
        "id": "pl_050",
        "q": "What is the warranty status of the Serialization System?",
        "expect_any": ["serialization", "warranty", "date", "no"],
        "role": "admin",
        "category": "planner",
    },
    # Risk assessment
    {
        "id": "pl_051",
        "q": "What single points of failure exist in the line?",
        "expect_any": ["line", "failure", "machine", "stage", "single"],
        "role": "admin",
        "category": "planner",
    },
    {
        "id": "pl_052",
        "q": "Which machines have the most critical work orders?",
        "expect_any": ["critical", "machine", "work order", "calibration", "cleaning"],
        "role": "admin",
        "category": "planner",
    },
    {
        "id": "pl_053",
        "q": "What is the risk of having only one Bin Blender?",
        "expect_any": ["bin blender", "risk", "single", "machine"],
        "role": "admin",
        "category": "planner",
    },
    {
        "id": "pl_054",
        "q": "Which stages have the highest failure risk?",
        "expect_any": ["stage", "failure", "risk", "efficiency"],
        "role": "admin",
        "category": "planner",
    },
    {
        "id": "pl_055",
        "q": "What backup equipment is available?",
        "expect_any": ["equipment", "backup", "no", "not"],
        "role": "admin",
        "category": "planner",
    },
    # Integration reasoning
    {
        "id": "pl_056",
        "q": "How do work orders relate to machines and workers?",
        "expect_any": ["work order", "machine", "worker", "assigned"],
        "role": "admin",
        "category": "planner",
    },
    {
        "id": "pl_057",
        "q": "How do stages relate to workstations and machines?",
        "expect_any": ["stage", "workstation", "machine", "relation"],
        "role": "admin",
        "category": "planner",
    },
    {
        "id": "pl_058",
        "q": "How do workers relate to stages and shifts?",
        "expect_any": ["worker", "stage", "shift", "relation"],
        "role": "admin",
        "category": "planner",
    },
    {
        "id": "pl_059",
        "q": "What is the relationship between SOPs and workstations?",
        "expect_any": ["sop", "workstation", "bound", "relation"],
        "role": "admin",
        "category": "planner",
    },
    {
        "id": "pl_060",
        "q": "How does the plant topology flow from top to bottom?",
        "expect_any": ["plant", "line", "stage", "workstation", "machine", "topology"],
        "role": "admin",
        "category": "planner",
    },
]


def get_all_questions():
    """Return all questions as a flat list."""
    all_q = []
    for cat in [ADVERSARIAL, AMBIGUITY, ROUTING, DECOMPOSITION, ONTOLOGY, PLANNER]:
        all_q.extend(cat)
    return all_q


if __name__ == "__main__":
    questions = get_all_questions()
    print(f"Total questions: {len(questions)}")
    from collections import Counter

    cats = Counter(q["category"] for q in questions)
    for cat, count in sorted(cats.items()):
        print(f"  {cat}: {count}")
