"""Intent examples: approval_query (part 1/2)."""

from __future__ import annotations

EXAMPLES: dict[str, list[str]] = {
    "approval_query": [
        "List all approvals",
        "Approvals dashboard",
        "What approvals are in Finance?",
        "Open approval APR-0040",
        "List approval requests",
        "What is the status of Batch Release?",
        "View APR-0084",
        "What approvals are in Warehouse & Logistics?",
        "Show approvals with status Rejected",
        "Who approved Equipment Qualification?",
        "What needs to be approved?",
        "How many approvals are waiting?",
        "Show me approval APR-0074",
        "Tell me about APR-0098",
        "Open approval APR-0026",
        "List approvals for Regulatory Affairs",
        "What is the approval status for APR-0058?",
        "Approval summary",
        "Open approval APR-0083",
        "What is the approval status for APR-0030?",
        "What is the status of Deviation Closure?",
        "Show me open approvals",
        "Status of approval APR-0098",
        "Show me what needs approval",
        "List approved items",
        "Approval APR-0038 details",
        "Show all pending approvals",
        "What approvals need my attention?",
        "What is the status of Equipment Qualification?",
        "Show rejected approvals",
        "Show pending approvals for Batch Release",
        "List approvals for Finance",
        "Show me approval APR-0094",
        "Show me approval APR-0043",
        "Approval history for Equipment Qualification",
        "What is the status of CAPA Approval?",
        "Tell me about APR-0051",
        "Open approval APR-0045",
        "Who approved Change Control Review?",
        "Pending approval list",
        "Status of approval APR-0049",
        "Status of approval APR-0061",
        "Show pending approvals in EHS",
        "What is the approval status for APR-0053?",
        "Status of approval APR-0028",
        "Open approval APR-0015",
        "Show approvals with status Pending",
        "Approval APR-0053 details",
        "Tell me about APR-0010",
        "All approval requests",
        "View APR-0097",
        "View APR-0003",
        "Show pending approvals in Supply Chain",
        "What is the approval status for APR-0086?",
        "What is waiting for approval?",
        "Who approved CAPA Approval?",
        "Show me approval APR-0070",
        "Show me approval APR-0100",
        "What is the approval status for APR-0077?",
        "Recent approvals",
        "Show pending approvals in Regulatory Affairs",
        "View APR-0052",
        "Show me approval APR-0062",
        "Tell me about APR-0017",
        "Show pending approvals in Quality Control",
        "Open approval APR-0039",
        "What is the status of Process Change?",
        "View APR-0099",
        "Tell me about APR-0080",
        "What approvals are in Supply Chain?",
        "Status of approval APR-0070",
        "Status of approval APR-0075",
        "Tell me about APR-0056",
        "Approval history for SOP Approval",
        "List rejected approvals",
        "Show pending approvals for CAPA Approval",
        "What is the approval status for APR-0075?",
        "Tell me about APR-0088",
        "List approved approvals",
        "What approvals are in EHS?",
        "Approval queue",
        "What is the approval status for APR-0011?",
        "List approvals for Operations",
        "Approval history for Change Control Review",
        "List approvals for Supply Chain",
        "What approvals are in Regulatory Affairs?",
        "View APR-0059",
        "What approvals are in Operations?",
        "Approval APR-0029 details",
        "View APR-0049",
        "What approvals are approved?",
        "Show approvals with status Approved",
        "List pending approvals",
        "Approval requests from Engineering",
        "Approval requests from Human Resources",
        "Show pending approvals for Equipment Qualification",
        "Who approved Process Change?",
        "Approval requests from Quality Assurance",
        "View APR-0057",
        "View APR-0012",
        "List approvals for Quality Control",
        "Status of approval APR-0076",
        "Open approval APR-0037",
        "What is the approval status for APR-0023?",
        "Show me approval APR-0020",
        "What approvals are pending?",
        "Approval requests from EHS",
        "Show approval history",
        "List approvals for Quality Assurance",
        "View APR-0053",
        "Tell me about APR-0034",
        "Approval APR-0001 details",
        "What is the approval status for APR-0049?",
        "Show pending approvals in Engineering",
        "What is the approval status for APR-0099?",
        "Approval history for Process Change",
        "Show pending approvals for SOP Approval",
        "Show pending approvals for Deviation Closure",
        "Show pending approvals in Human Resources",
        "What approvals are in Quality Assurance?",
        "Approval requests from Operations",
        "Approval history for Deviation Closure",
        "Approval APR-0041 details",
        "Tell me about APR-0047",
        "Show pending approvals in Quality Assurance",
        "What is the approval status for APR-0021?",
        "Who approved Deviation Closure?",
        "What approvals are rejected?",
        "Who approved Batch Release?",
        "List approvals for Engineering",
        "Who approved SOP Approval?",
        "Approval APR-0011 details",
        "What approvals are in Human Resources?",
        "Open approval APR-0067",
        "Approval requests from Quality Control",
        "What is the approval status for APR-0065?",
        "What is the approval status for APR-0085?",
        "View APR-0008",
        "View APR-0015",
        "Status of approval APR-0014",
        "Approval APR-0078 details",
        "Open approval APR-0049",
        "Status of approval APR-0020",
        "What is the approval status for APR-0095?",
        "Tell me about APR-0039",
        "What is the approval status for APR-0081?",
        "Status of approval APR-0087",
        "Show pending approvals in Operations",
        "What is the approval status for APR-0007?",
        "Status of approval APR-0064",
        "Tell me about APR-0026",
        "Approval history for Batch Release",
        "Show me approval APR-0092",
        "Approval APR-0034 details",
        "Status of approval APR-0022",
        "Status of approval APR-0069",
        "What approvals are in Engineering?",
        "Tell me about APR-0085",
        "Approval APR-0033 details",
        "Status of approval APR-0017",
        "Approval requests from Finance",
        "View APR-0094",
        "Tell me about APR-0099",
        "Approval requests from Warehouse & Logistics",
        "View APR-0056",
        "Open approval APR-0008",
        "Approval APR-0059 details",
        "Open approval APR-0036",
        "Tell me about APR-0042",
        "Open approval APR-0073",
        "Tell me about APR-0062",
        "List approvals for EHS",
        "Show me approval APR-0065",
        "Show me approval APR-0061",
        "Approval APR-0060 details",
        "Open approval APR-0097",
        "Tell me about APR-0084",
        "Approval history for CAPA Approval",
        "Show pending approvals in Finance",
        "View APR-0042",
        "Open approval APR-0081",
        "List approvals for Warehouse & Logistics",
        "Open approval APR-0018",
        "What is the approval status for APR-0042?",
        "What is the approval status for APR-0093?",
        "Status of approval APR-0046",
        "View APR-0028",
        "View APR-0085",
        "Approval APR-0025 details",
        "View APR-0036",
        "What is the approval status for APR-0013?",
        "Show me approval APR-0059",
        "View APR-0077",
        "Approval requests from Supply Chain",
        "Open approval APR-0028",
        "Tell me about APR-0033",
        "Tell me about APR-0073",
        "View APR-0090",
        "Show pending approvals in Warehouse & Logistics",
        "Open approval APR-0099",
        "Approval APR-0069 details",
        "View APR-0009",
        "Show me approval APR-0081",
        "View APR-0095",
        "Approval APR-0065 details",
        "View APR-0068",
        "Tell me about APR-0057",
        "Tell me about APR-0031",
        "Show me approval APR-0036",
        "Tell me about APR-0046",
        "Approval APR-0006 details",
        "Open approval APR-0004",
        "Show me approval APR-0023",
        "Tell me about APR-0024",
        "What is the approval status for APR-0039?",
        "Show pending approvals for Process Change",
        "Status of approval APR-0039",
        "Approval APR-0054 details",
        "View APR-0096",
        "Tell me about APR-0059",
        "Show me approval APR-0013",
        "Show pending approvals for Change Control Review",
        "Tell me about APR-0038",
        "Approval requests from Regulatory Affairs",
        "Open approval APR-0031",
        "What is the status of Change Control Review?",
        "Status of approval APR-0047",
        "Tell me about APR-0079",
        "What is the approval status for APR-0009?",
        "View APR-0034",
        "Approval APR-0026 details",
        "What is the status of SOP Approval?",
        "What is the approval status for APR-0041?",
        "Tell me about APR-0069",
        "View APR-0045",
        "Tell me about APR-0013",
        "Approval APR-0057 details",
        "View APR-0058",
        "Show me approval APR-0042",
        "Status of approval APR-0094",
        "Tell me about APR-0082",
        "View APR-0087",
        "Show me approval APR-0095",
        "Open approval APR-0064",
        "What is the approval status for APR-0063?",
        "View APR-0061",
        "Status of approval APR-0013",
        "What approvals are in Quality Control?",
        "Open approval APR-0085",
        "Approval APR-0016 details",
        "Show me approval APR-0083",
        "Approval APR-0075 details",
        "Show me approval APR-0082",
        "Tell me about APR-0076",
        "Open approval APR-0070",
        "Show me approval APR-0025",
        "Approval APR-0097 details",
        "Status of approval APR-0091",
        "Approval APR-0096 details",
        "Open approval APR-0054",
        "Tell me about APR-0001",
        "Tell me about APR-0053",
        "What is the approval status for APR-0094?",
        "View APR-0093",
        "Show me approval APR-0096",
        "Status of approval APR-0009",
        "View APR-0071",
        "Show me approval APR-0006",
        "Approval APR-0089 details",
        "Tell me about APR-0052",
        "Show me approval APR-0041",
        "View APR-0013",
        "Open approval APR-0009",
        "Open approval APR-0074",
        "Status of approval APR-0034",
        "Tell me about APR-0036",
        "Tell me about APR-0070",
        "What is the approval status for APR-0100?",
        "Approval APR-0090 details",
        "What is the approval status for APR-0090?",
        "Open approval APR-0046",
        "Approval APR-0074 details",
        "Show me approval APR-0079",
        "Approval APR-0003 details",
        "View APR-0050",
        "What is the approval status for APR-0003?",
        "What is the approval status for APR-0073?",
        "Status of approval APR-0027",
        "Open approval APR-0017",
        "Status of approval APR-0011",
        "What is the approval status for APR-0050?",
        "Status of approval APR-0010",
        "Status of approval APR-0025",
        "Open approval APR-0091",
        "What is the approval status for APR-0084?",
        "List approvals for Human Resources",
        "Open approval APR-0077",
        "What is the approval status for APR-0046?",
        "View APR-0018",
        "Status of approval APR-0048",
        "Approval APR-0093 details",
        "What is the approval status for APR-0088?",
        "Show me approval APR-0066",
        "Show me approval APR-0052",
        "View APR-0062",
        "Status of approval APR-0003",
        "Show me approval APR-0097",
        "What is the approval status for APR-0059?",
        "What is the approval status for APR-0045?",
        "View APR-0076",
        "Approval APR-0050 details",
        "View APR-0039",
        "Approval APR-0019 details",
        "Show me approval APR-0029",
        "Status of approval APR-0089",
        "Open approval APR-0014",
        "Tell me about APR-0045",
        "Open approval APR-0002",
        "Tell me about APR-0094",
        "Status of approval APR-0040",
        "Status of approval APR-0072",
        "Tell me about APR-0044",
        "Status of approval APR-0056",
        "Status of approval APR-0099",
        "What is the approval status for APR-0078?",
        "Status of approval APR-0042",
        "View APR-0023",
        "Show me approval APR-0072",
        "Open approval APR-0013",
        "Tell me about APR-0095",
        "View APR-0048",
        "Status of approval APR-0004",
        "What is the approval status for APR-0043?",
        "Approval APR-0018 details",
        "Approval APR-0045 details",
        "Approval APR-0070 details",
        "Status of approval APR-0012",
        "Status of approval APR-0037",
        "Status of approval APR-0057",
        "Open approval APR-0093",
        "Tell me about APR-0020",
        "What is the approval status for APR-0087?",
        "View APR-0100",
        "What is the approval status for APR-0002?",
        "Tell me about APR-0005",
        "Show me approval APR-0040",
        "Status of approval APR-0024",
        "Status of approval APR-0088",
        "Tell me about APR-0048",
        "Show me approval APR-0045",
        "Show me approval APR-0073",
        "What is the approval status for APR-0082?",
        "Open approval APR-0075",
        "Show me approval APR-0067",
        "Show me approval APR-0021",
        "Open approval APR-0023",
    ],
}
