"""Intent examples: batch_record (part 6/7)."""

from __future__ import annotations

EXAMPLES: dict[str, list[str]] = {
    "batch_record": [
        "What is the yield for batch BATCH-107?",
        "BER BER--B7E91E10 status",
        "What is the status of BER BER--543A6B39?",
        "Batch BATCH-101 details",
        "What is the status of batch BATCH-140?",
        "What is the status of batch BATCH-098?",
        "Deviations for batch BATCH-018",
        "Deviations for batch BATCH-038",
        "View batch BATCH-187",
        "Display batch record BATCH-165",
        "Show batch execution record BER--4D0846AC",
        "Show me the batch record for BATCH-110",
        "How is batch BATCH-165 doing?",
        "Quality metrics for batch BATCH-033",
        "Status of production batch BATCH-040",
        "Quality metrics for batch BATCH-188",
        "Show yield for BATCH-070",
        "How is batch BATCH-186 doing?",
        "Display batch record BATCH-018",
        "Deviations for batch BATCH-056",
        "How is batch BATCH-037 doing?",
        "View batch BATCH-079",
        "Tell me about batch BATCH-044",
        "Show me the batch record for BATCH-005",
        "What is the yield for batch BATCH-196?",
        "Display batch record BATCH-037",
        "Show yield for BATCH-120",
        "Tell me about batch BATCH-145",
        "What is the status of batch BATCH-047?",
        "Deviations for batch BATCH-117",
        "Deviations for batch BATCH-033",
        "Fetch batch details for BATCH-173",
        "Display batch record BATCH-022",
        "Display batch record BATCH-031",
        "Get batch record for BATCH-146",
        "Display batch record BATCH-062",
        "Status of production batch BATCH-104",
        "What is the status of BER BER--704D1C97?",
        "Show batch execution record BER--710307CC",
        "Show batch execution record BER--CB57ED02",
        "What happened to batch BATCH-182?",
        "What happened to batch BATCH-089?",
        "Give me info on batch BATCH-088",
        "Show yield for BATCH-049",
        "What is the status of BER BER-900F4A83?",
        "Batch BATCH-145 quality data",
        "Show me the batch record for BATCH-043",
        "Batch BATCH-010 quality data",
        "View batch BATCH-037",
        "Fetch batch details for BATCH-069",
        "Quality metrics for batch BATCH-080",
        "Show yield for BATCH-071",
        "Get batch record for BATCH-028",
        "What is the status of BER BER-5B293B91?",
        "Show yield for BATCH-058",
        "How is batch BATCH-126 doing?",
        "Execution record BER--6DE912AF",
        "Quality metrics for batch BATCH-178",
        "Batch BATCH-151 summary",
        "Batch BATCH-101 quality data",
        "Batch BATCH-017 quality data",
        "Display batch record BATCH-190",
        "Show me the batch record for BATCH-115",
        "BER BER--FBB40518 status",
        "Tell me about batch BATCH-107",
        "Fetch batch details for BATCH-087",
        "BER BER--6AFAC919 status",
        "Open batch BATCH-022",
        "Batch BATCH-087 details",
        "Batch BATCH-139 details",
        "What happened to batch BATCH-054?",
        "Batch BATCH-102 details",
        "Show batch execution record BER--804F7CA8",
        "How is batch BATCH-199 doing?",
        "Get batch record for BATCH-093",
        "Get batch record for BATCH-144",
        "View batch BATCH-147",
        "What happened to batch BATCH-117?",
        "What happened to batch BATCH-135?",
        "Tell me about batch BATCH-014",
        "Batch BATCH-022 summary",
        "BER BER--AE3C9DC3 status",
        "Show yield for BATCH-156",
        "Open batch BATCH-136",
        "What is the yield for batch BATCH-007?",
        "Get batch record for BATCH-157",
        "Show yield for BATCH-184",
        "Display batch record BATCH-060",
        "Get batch record for BATCH-035",
        "Batch BATCH-065 summary",
        "What is the yield for batch BATCH-153?",
        "How is batch BATCH-022 doing?",
        "Give me info on batch BATCH-023",
        "What is the status of BER BER--7D539067?",
        "Show me the batch record for BATCH-076",
        "Quality metrics for batch BATCH-119",
        "Execution record BER--7D43413E",
        "Quality metrics for batch BATCH-099",
        "Batch BATCH-051 quality data",
        "What is the yield for batch BATCH-131?",
        "Show me the batch record for BATCH-167",
        "Give me info on batch BATCH-183",
        "Fetch batch details for BATCH-109",
        "Fetch batch details for BATCH-176",
        "Get batch record for BATCH-011",
        "Batch BATCH-127 details",
        "Show me the batch record for BATCH-058",
        "Open batch BATCH-180",
        "Fetch batch details for BATCH-038",
        "Deviations for batch BATCH-089",
        "Batch BATCH-092 quality data",
        "What is the status of BER BER--9605D93B?",
        "Batch BATCH-055 summary",
        "Open batch BATCH-196",
        "Fetch batch details for BATCH-184",
        "Show me the batch record for BATCH-170",
        "Show batch BATCH-085",
        "Fetch batch details for BATCH-065",
        "What is the yield for batch BATCH-193?",
        "Quality metrics for batch BATCH-012",
        "Show batch BATCH-004",
        "Get batch record for BATCH-177",
        "Show batch execution record BER--BCDB47E8",
        "What is the status of batch BATCH-054?",
        "Batch BATCH-069 quality data",
        "View batch BATCH-196",
        "Batch BATCH-188 details",
        "Quality metrics for batch BATCH-184",
        "What happened to batch BATCH-023?",
        "What is the status of batch BATCH-070?",
        "Get batch record for BATCH-132",
        "Deviations for batch BATCH-071",
        "Fetch batch details for BATCH-156",
        "Give me info on batch BATCH-059",
        "Show me the batch record for BATCH-098",
        "BER BER--E2A75EC8 status",
        "How is batch BATCH-168 doing?",
        "Show batch BATCH-132",
        "View batch BATCH-121",
        "Quality metrics for batch BATCH-007",
        "Get batch record for BATCH-126",
        "Fetch batch details for BATCH-188",
        "Batch BATCH-116 details",
        "BER BER--CC87C715 status",
        "Fetch batch details for BATCH-136",
        "Open batch BATCH-129",
        "Give me info on batch BATCH-104",
        "Fetch batch details for BATCH-135",
        "Execution record BER-AF735A33",
        "Quality metrics for batch BATCH-054",
        "Open batch BATCH-118",
        "Show batch BATCH-194",
        "Show yield for BATCH-174",
        "What is the status of batch BATCH-167?",
        "Show batch execution record BER--86A9CFC3",
        "BER BER--92E8A3BA status",
        "Tell me about batch BATCH-130",
        "Batch BATCH-066 summary",
        "What is the yield for batch BATCH-155?",
        "Batch BATCH-100 summary",
        "Execution record BER--47133F71",
        "Fetch batch details for BATCH-096",
        "What is the status of batch BATCH-155?",
        "How is batch BATCH-151 doing?",
        "Quality metrics for batch BATCH-009",
        "Get batch record for BATCH-021",
        "What is the yield for batch BATCH-085?",
        "BER BER-AF735A33 status",
        "Give me info on batch BATCH-187",
        "Show batch BATCH-042",
        "Show batch BATCH-046",
        "What is the yield for batch BATCH-019?",
        "What is the status of BER BER--928111F0?",
        "Deviations for batch BATCH-170",
        "What is the status of BER BER--F4D71333?",
        "How is batch BATCH-125 doing?",
        "Tell me about batch BATCH-088",
        "Batch BATCH-023 quality data",
        "Batch BATCH-122 quality data",
        "Deviations for batch BATCH-158",
        "View batch BATCH-090",
        "Deviations for batch BATCH-039",
        "Status of production batch BATCH-180",
        "What is the status of BER BER--F81835A3?",
        "BER BER-B4705A0F status",
        "Fetch batch details for BATCH-085",
        "Batch BATCH-131 details",
        "Tell me about batch BATCH-191",
        "What is the status of batch BATCH-117?",
        "Execution record BER--1B40FE38",
        "Display batch record BATCH-197",
        "Display batch record BATCH-069",
        "What is the status of batch BATCH-074?",
        "Display batch record BATCH-189",
        "Status of production batch BATCH-007",
        "What is the yield for batch BATCH-066?",
        "Deviations for batch BATCH-084",
        "Execution record BER--543A6B39",
        "Execution record BER--B5CF9B89",
        "Show batch BATCH-167",
        "Tell me about batch BATCH-062",
        "Display batch record BATCH-057",
        "Show yield for BATCH-055",
        "Execution record BER--5222804E",
        "Show me the batch record for BATCH-188",
        "Show yield for BATCH-074",
        "Show batch execution record BER--C7474D36",
        "How is batch BATCH-104 doing?",
        "View batch BATCH-162",
        "How is batch BATCH-137 doing?",
        "Open batch BATCH-055",
        "Display batch record BATCH-104",
        "View batch BATCH-083",
        "Status of production batch BATCH-185",
        "What happened to batch BATCH-041?",
        "Execution record BER--928111F0",
        "Show batch BATCH-079",
        "View batch BATCH-138",
        "Status of production batch BATCH-117",
        "Deviations for batch BATCH-034",
        "View batch BATCH-042",
        "Display batch record BATCH-050",
        "Show batch BATCH-191",
        "What is the status of BER BER--FDE1870B?",
        "What is the yield for batch BATCH-194?",
        "Display batch record BATCH-043",
        "How is batch BATCH-064 doing?",
        "What is the yield for batch BATCH-143?",
        "What is the status of batch BATCH-063?",
        "Display batch record BATCH-003",
        "Deviations for batch BATCH-154",
        "Batch BATCH-183 summary",
        "Display batch record BATCH-198",
        "Fetch batch details for BATCH-163",
        "What is the status of batch BATCH-178?",
        "Deviations for batch BATCH-035",
        "Show me the batch record for BATCH-013",
        "Show batch BATCH-050",
        "Show yield for BATCH-111",
        "BER BER--0F7E722D status",
        "How is batch BATCH-110 doing?",
        "Deviations for batch BATCH-097",
        "What is the status of BER BER--12DC03A0?",
        "Batch BATCH-199 quality data",
        "Open batch BATCH-095",
        "BER BER--CC43C94C status",
        "Batch BATCH-129 quality data",
        "What is the status of batch BATCH-011?",
        "Show batch execution record BER--FC77B470",
        "Execution record BER-3E9C8187",
        "Tell me about batch BATCH-150",
        "Show batch execution record BER--9D757166",
        "Batch BATCH-200 quality data",
        "Tell me about batch BATCH-019",
        "View batch BATCH-111",
        "Open batch BATCH-093",
        "Status of production batch BATCH-116",
        "What happened to batch BATCH-195?",
        "Open batch BATCH-133",
        "Fetch batch details for BATCH-107",
        "Show yield for BATCH-172",
        "Display batch record BATCH-095",
        "Batch BATCH-066 details",
        "Status of production batch BATCH-087",
        "Fetch batch details for BATCH-059",
        "Batch BATCH-126 summary",
        "Open batch BATCH-182",
        "Deviations for batch BATCH-161",
        "Get batch record for BATCH-060",
        "Batch BATCH-018 details",
        "What is the status of BER BER--CDFFBCA2?",
        "Execution record BER--E2A75EC8",
        "Open batch BATCH-178",
        "Show yield for BATCH-140",
        "Display batch record BATCH-021",
        "What is the status of BER BER--BCC654F9?",
        "Show batch execution record BER--5222804E",
        "Display batch record BATCH-131",
        "Execution record BER--3A88D9AF",
        "Execution record BER--DEC61AD3",
        "Batch BATCH-091 summary",
        "BER BER--3A88D9AF status",
        "Batch BATCH-054 summary",
        "What happened to batch BATCH-033?",
        "Deviations for batch BATCH-011",
        "Open batch BATCH-039",
        "View batch BATCH-065",
        "Get batch record for BATCH-027",
        "What is the status of batch BATCH-035?",
        "Status of production batch BATCH-085",
        "What is the yield for batch BATCH-199?",
        "Fetch batch details for BATCH-066",
        "Give me info on batch BATCH-094",
        "Fetch batch details for BATCH-061",
        "Fetch batch details for BATCH-017",
        "Tell me about batch BATCH-086",
        "View batch BATCH-186",
        "Show me the batch record for BATCH-007",
        "BER BER--009D541A status",
        "Show batch BATCH-196",
        "Give me info on batch BATCH-096",
        "Fetch batch details for BATCH-185",
        "Open batch BATCH-044",
        "What is the yield for batch BATCH-093?",
        "Show batch BATCH-200",
        "Show batch execution record BER--569B9422",
        "Quality metrics for batch BATCH-190",
        "What is the status of batch BATCH-187?",
        "Give me info on batch BATCH-074",
        "Show yield for BATCH-147",
        "BER BER--804F7CA8 status",
        "View batch BATCH-158",
        "Show me the batch record for BATCH-158",
        "Batch BATCH-148 quality data",
        "What is the status of batch BATCH-153?",
        "Give me info on batch BATCH-087",
        "Show me the batch record for BATCH-182",
        "Tell me about batch BATCH-197",
        "Batch BATCH-183 details",
        "Batch BATCH-093 details",
        "What happened to batch BATCH-105?",
        "Batch BATCH-149 details",
        "Fetch batch details for BATCH-110",
        "Batch BATCH-002 details",
        "Open batch BATCH-080",
        "Tell me about batch BATCH-140",
        "BER BER-BD364549 status",
        "Batch BATCH-043 summary",
        "Show me the batch record for BATCH-095",
        "How is batch BATCH-146 doing?",
        "What is the status of BER BER--6CE61952?",
        "Show batch execution record BER--E060AEC8",
        "Batch BATCH-149 summary",
        "Give me info on batch BATCH-012",
        "Quality metrics for batch BATCH-062",
        "Show batch BATCH-083",
        "Batch BATCH-022 details",
        "Get batch record for BATCH-172",
        "What is the yield for batch BATCH-192?",
        "Show yield for BATCH-187",
        "Fetch batch details for BATCH-160",
        "Give me info on batch BATCH-146",
        "Display batch record BATCH-048",
        "Show batch BATCH-108",
        "What happened to batch BATCH-018?",
        "What is the status of batch BATCH-176?",
        "Display batch record BATCH-132",
        "BER BER--7B315106 status",
        "Batch BATCH-108 quality data",
        "Batch BATCH-016 details",
        "Execution record BER--1454F070",
        "Batch BATCH-069 summary",
        "BER BER--1B40FE38 status",
        "Give me info on batch BATCH-091",
        "Show batch execution record BER--F0693564",
        "How is batch BATCH-076 doing?",
        "How is batch BATCH-190 doing?",
        "Display batch record BATCH-023",
        "What is the status of BER BER--EA1C0105?",
        "Quality metrics for batch BATCH-048",
        "BER BER--8B5EE8FD status",
        "Fetch batch details for BATCH-082",
        "Batch BATCH-040 quality data",
        "Status of production batch BATCH-125",
        "Execution record BER--DB91A76B",
        "Get batch record for BATCH-197",
        "How is batch BATCH-049 doing?",
        "Deviations for batch BATCH-115",
        "What happened to batch BATCH-174?",
        "What happened to batch BATCH-020?",
        "What is the yield for batch BATCH-004?",
        "Batch BATCH-116 quality data",
        "What is the status of BER BER-1A1B5A36?",
        "Get batch record for BATCH-077",
        "Fetch batch details for BATCH-051",
        "BER BER--0C9334F6 status",
        "How is batch BATCH-066 doing?",
        "Execution record BER-314E5802",
        "Batch BATCH-015 details",
        "Open batch BATCH-072",
        "Deviations for batch BATCH-128",
        "Display batch record BATCH-099",
        "Display batch record BATCH-026",
        "What happened to batch BATCH-072?",
        "Fetch batch details for BATCH-025",
        "What happened to batch BATCH-155?",
        "What is the yield for batch BATCH-065?",
        "Batch BATCH-119 quality data",
        "Give me info on batch BATCH-037",
        "Open batch BATCH-120",
        "View batch BATCH-008",
        "Batch BATCH-044 summary",
        "Batch BATCH-074 summary",
        "What is the status of BER BER--5DB5DDEA?",
        "View batch BATCH-118",
        "Get batch record for BATCH-159",
        "Execution record BER--8D87D8FF",
        "Show batch execution record BER--449EF621",
        "BER BER--E2D35188 status",
        "What is the status of batch BATCH-134?",
        "Fetch batch details for BATCH-055",
        "View batch BATCH-029",
        "Batch BATCH-186 quality data",
        "View batch BATCH-098",
        "What happened to batch BATCH-001?",
        "Show yield for BATCH-195",
        "What is the status of batch BATCH-135?",
        "Deviations for batch BATCH-151",
        "Tell me about batch BATCH-198",
        "Status of production batch BATCH-122",
        "What is the status of BER BER--FC981C1C?",
        "What happened to batch BATCH-042?",
        "BER BER-AFA53C7A status",
        "Execution record BER--CDFFBCA2",
        "Execution record BER--C7BEE953",
        "Deviations for batch BATCH-178",
        "Fetch batch details for BATCH-151",
        "Status of production batch BATCH-164",
        "What is the status of BER BER--ABD040A0?",
        "Open batch BATCH-174",
        "Tell me about batch BATCH-134",
        "Give me info on batch BATCH-058",
        "Give me info on batch BATCH-127",
        "Batch BATCH-138 summary",
        "Fetch batch details for BATCH-047",
        "Show me the batch record for BATCH-071",
        "What is the yield for batch BATCH-021?",
        "Show yield for BATCH-066",
        "Display batch record BATCH-066",
        "Quality metrics for batch BATCH-179",
        "Tell me about batch BATCH-135",
        "What is the status of batch BATCH-177?",
        "Batch BATCH-097 quality data",
        "Show batch BATCH-148",
        "Execution record BER--14FB7C4E",
        "Tell me about batch BATCH-069",
        "Show me the batch record for BATCH-090",
        "Give me info on batch BATCH-014",
        "Quality metrics for batch BATCH-075",
        "Show yield for BATCH-096",
        "Get batch record for BATCH-023",
        "Batch BATCH-169 summary",
        "Tell me about batch BATCH-169",
        "Batch BATCH-001 details",
        "View batch BATCH-185",
        "Quality metrics for batch BATCH-177",
        "How is batch BATCH-195 doing?",
        "Display batch record BATCH-146",
        "Quality metrics for batch BATCH-110",
        "View batch BATCH-013",
        "Get batch record for BATCH-184",
        "What happened to batch BATCH-148?",
        "What is the status of batch BATCH-157?",
        "Batch BATCH-194 quality data",
        "Quality metrics for batch BATCH-172",
        "Batch BATCH-018 summary",
        "What is the status of BER BER-E3B78D7A?",
        "What happened to batch BATCH-071?",
        "What happened to batch BATCH-036?",
        "Show me the batch record for BATCH-010",
        "View batch BATCH-064",
        "Deviations for batch BATCH-132",
        "Show yield for BATCH-089",
        "Batch BATCH-041 summary",
        "How is batch BATCH-003 doing?",
        "Batch BATCH-130 details",
        "What happened to batch BATCH-091?",
        "Get batch record for BATCH-168",
        "Show me the batch record for BATCH-153",
        "Fetch batch details for BATCH-179",
        "Show me the batch record for BATCH-169",
        "Give me info on batch BATCH-071",
        "Fetch batch details for BATCH-169",
        "View batch BATCH-200",
        "What is the status of BER BER--F7166F9F?",
        "What is the yield for batch BATCH-117?",
        "Show batch BATCH-016",
        "View batch BATCH-177",
        "Get batch record for BATCH-085",
        "Batch BATCH-079 quality data",
        "Execution record BER--04F787DF",
        "Batch BATCH-030 summary",
        "Show batch BATCH-026",
        "Show batch BATCH-141",
    ],
}
