"""Intent examples: batch_record (part 2/7)."""

from __future__ import annotations

EXAMPLES: dict[str, list[str]] = {
    "batch_record": [
        "What is the status of BER BER--7E7F46C6?",
        "Open batch BATCH-115",
        "Status of production batch BATCH-160",
        "Open batch BATCH-169",
        "Give me info on batch BATCH-001",
        "Batch BATCH-195 quality data",
        "Quality metrics for batch BATCH-066",
        "Give me info on batch BATCH-063",
        "Deviations for batch BATCH-094",
        "What is the status of BER BER-7755A8F1?",
        "BER BER--770B452F status",
        "Get batch record for BATCH-149",
        "Give me info on batch BATCH-115",
        "Deviations for batch BATCH-022",
        "What is the status of BER BER--B7B46DA1?",
        "How is batch BATCH-080 doing?",
        "Batch BATCH-046 quality data",
        "Execution record BER--9EB710B7",
        "Batch BATCH-104 details",
        "View batch BATCH-043",
        "What happened to batch BATCH-038?",
        "List batches with status Rejected",
        "Quality metrics for batch BATCH-176",
        "Get batch record for BATCH-186",
        "Show batch BATCH-165",
        "Quality metrics for batch BATCH-055",
        "Batch BATCH-179 summary",
        "Execution record BER--4E45475E",
        "Display batch record BATCH-011",
        "Tell me about batch BATCH-171",
        "What is the status of batch BATCH-123?",
        "Batch BATCH-114 details",
        "Display batch record BATCH-156",
        "Get batch record for BATCH-189",
        "Give me info on batch BATCH-095",
        "Status of production batch BATCH-131",
        "Show batches in Dispensing status",
        "What is the status of BER BER--1C8F5C98?",
        "Show batch execution record BER-F3E117EE",
        "What is the yield for batch BATCH-113?",
        "BER BER--772FDFC2 status",
        "Show me the batch record for BATCH-177",
        "Execution record BER--2F0540F8",
        "How is batch BATCH-200 doing?",
        "How is batch BATCH-129 doing?",
        "Deviations for batch BATCH-193",
        "Status of production batch BATCH-062",
        "What batches are cancelled?",
        "Deviations for batch BATCH-156",
        "Show batch BATCH-008",
        "Open batch BATCH-139",
        "What is the yield for batch BATCH-118?",
        "What happened to batch BATCH-046?",
        "Show me the batch record for BATCH-109",
        "Get batch record for BATCH-001",
        "Quality metrics for batch BATCH-137",
        "What is the yield for batch BATCH-165?",
        "Status of production batch BATCH-121",
        "What is the status of batch BATCH-022?",
        "Display batch record BATCH-006",
        "Execution record BER-3A335864",
        "Batch BATCH-021 summary",
        "Fetch batch details for BATCH-077",
        "Deviations for batch BATCH-185",
        "What is the yield for batch BATCH-070?",
        "View batch BATCH-007",
        "BER BER--6CE61952 status",
        "Quality metrics for batch BATCH-002",
        "Find all in progress batches",
        "Fetch batch details for BATCH-046",
        "BER BER--EEA53DA3 status",
        "Batch BATCH-038 details",
        "What is the yield for batch BATCH-054?",
        "Display batch record BATCH-036",
        "Give me info on batch BATCH-157",
        "Open batch BATCH-052",
        "Display batch record BATCH-088",
        "What is the yield for batch BATCH-106?",
        "Quality metrics for batch BATCH-165",
        "What is the status of BER BER--A887CEBE?",
        "Execution record BER--F7166F9F",
        "Deviations for batch BATCH-050",
        "Fetch batch details for BATCH-187",
        "Quality metrics for batch BATCH-126",
        "What is the status of BER BER--6180633F?",
        "What is the yield for batch BATCH-169?",
        "What is the status of BER BER--C8D81DAD?",
        "Open batch BATCH-032",
        "Status of production batch BATCH-027",
        "Batch BATCH-077 summary",
        "Display batch record BATCH-086",
        "Show yield for BATCH-130",
        "BER BER--7F4A75AF status",
        "How is batch BATCH-196 doing?",
        "View batch BATCH-127",
        "View batch BATCH-032",
        "Batch BATCH-114 summary",
        "Give me info on batch BATCH-190",
        "How is batch BATCH-068 doing?",
        "Give me info on batch BATCH-160",
        "What is the status of batch BATCH-018?",
        "Tell me about batch BATCH-156",
        "Open batch BATCH-090",
        "What happened to batch BATCH-058?",
        "Execution record BER--FC77B470",
        "Execution record BER--92E8A3BA",
        "Tell me about batch BATCH-077",
        "View batch BATCH-190",
        "Show batch execution record BER--300DC74F",
        "Quality metrics for batch BATCH-161",
        "Show batch BATCH-149",
        "Get batch record for BATCH-111",
        "BER BER-900F4A83 status",
        "What is the yield for batch BATCH-136?",
        "Find all on hold batches",
        "Batch BATCH-107 summary",
        "Quality metrics for batch BATCH-011",
        "View batch BATCH-002",
        "How is batch BATCH-118 doing?",
        "Get batch record for BATCH-152",
        "What is the status of batch BATCH-164?",
        "Batch BATCH-082 quality data",
        "Show batch execution record BER-AFA53C7A",
        "Show yield for BATCH-110",
        "BER BER--FDE1870B status",
        "Get batch record for BATCH-129",
        "What is the status of BER BER--DEC61AD3?",
        "Show yield for BATCH-191",
        "Quality metrics for batch BATCH-053",
        "What happened to batch BATCH-016?",
        "Show me the batch record for BATCH-165",
        "Show batch BATCH-001",
        "What is the yield for batch BATCH-158?",
        "Tell me about batch BATCH-116",
        "Show batches in In Progress status",
        "Show batch BATCH-164",
        "How is batch BATCH-184 doing?",
        "Give me info on batch BATCH-022",
        "Batch BATCH-139 summary",
        "Show yield for BATCH-163",
        "What is the status of batch BATCH-043?",
        "Batch BATCH-131 summary",
        "Show me the batch record for BATCH-197",
        "How is batch BATCH-150 doing?",
        "Open batch BATCH-045",
        "View batch BATCH-143",
        "Show me the batch record for BATCH-062",
        "BER BER-F3E117EE status",
        "Deviations for batch BATCH-189",
        "View batch BATCH-021",
        "Show me the batch record for BATCH-020",
        "Show batches in Rejected status",
        "What is the status of BER BER--BCDB47E8?",
        "Give me info on batch BATCH-147",
        "Status of production batch BATCH-177",
        "What is the status of BER BER--0C9334F6?",
        "Batch BATCH-150 quality data",
        "Batch BATCH-039 quality data",
        "Batch BATCH-159 quality data",
        "Batch BATCH-100 details",
        "Batch BATCH-082 details",
        "Give me info on batch BATCH-197",
        "Open batch BATCH-027",
        "Show me the batch record for BATCH-025",
        "What happened to batch BATCH-197?",
        "How is batch BATCH-156 doing?",
        "BER BER--51D67B67 status",
        "Show batch execution record BER-D893B10A",
        "What is the status of BER BER-29121EC6?",
        "Quality metrics for batch BATCH-193",
        "What is the status of batch BATCH-082?",
        "How is batch BATCH-025 doing?",
        "View batch BATCH-184",
        "BER BER--8CE73799 status",
        "Execution record BER--449EF621",
        "Display batch record BATCH-084",
        "Batch BATCH-169 details",
        "Status of production batch BATCH-187",
        "Show yield for BATCH-108",
        "Open batch BATCH-113",
        "Batch BATCH-133 quality data",
        "Tell me about batch BATCH-160",
        "What happened to batch BATCH-153?",
        "Deviations for batch BATCH-010",
        "Execution record BER--768A0997",
        "What is the status of BER BER--C7BEE953?",
        "Display batch record BATCH-176",
        "How is batch BATCH-142 doing?",
        "What is the yield for batch BATCH-176?",
        "Status of production batch BATCH-170",
        "View batch BATCH-080",
        "Execution record BER-5D728E09",
        "Batch BATCH-088 summary",
        "BER BER--6DE912AF status",
        "What is the yield for batch BATCH-121?",
        "What happened to batch BATCH-111?",
        "What is the yield for batch BATCH-161?",
        "What is the status of BER BER-F280724C?",
        "Show batch BATCH-029",
        "What happened to batch BATCH-013?",
        "BER BER--E060AEC8 status",
        "Deviations for batch BATCH-152",
        "How is batch BATCH-177 doing?",
        "Batch BATCH-198 summary",
        "Tell me about batch BATCH-172",
        "What is the status of batch BATCH-100?",
        "Open batch BATCH-171",
        "View batch BATCH-142",
        "Show batch BATCH-070",
        "What is the yield for batch BATCH-149?",
        "Batch BATCH-014 details",
        "Open batch BATCH-011",
        "Show yield for BATCH-175",
        "What happened to batch BATCH-168?",
        "What is the yield for batch BATCH-175?",
        "Tell me about batch BATCH-071",
        "Quality metrics for batch BATCH-102",
        "What is the status of batch BATCH-154?",
        "Status of production batch BATCH-102",
        "Batch BATCH-154 quality data",
        "Give me info on batch BATCH-067",
        "Batch BATCH-037 summary",
        "Show batch BATCH-152",
        "Fetch batch details for BATCH-128",
        "Quality metrics for batch BATCH-026",
        "What is the status of BER BER-3E9C8187?",
        "Fetch batch details for BATCH-154",
        "Batch BATCH-119 details",
        "BER BER--2F388213 status",
        "Show batch BATCH-183",
        "What is the status of batch BATCH-089?",
        "What happened to batch BATCH-100?",
        "What is the status of BER BER--78091C53?",
        "Batch BATCH-033 quality data",
        "What is the yield for batch BATCH-053?",
        "What is the status of batch BATCH-132?",
        "What is the status of BER BER--FF9C312C?",
        "Open batch BATCH-010",
        "Execution record BER--A887CEBE",
        "Deviations for batch BATCH-199",
        "Tell me about batch BATCH-185",
        "Show yield for BATCH-057",
        "Show batch execution record BER-3AB9E94D",
        "Status of production batch BATCH-155",
        "Get batch record for BATCH-091",
        "Batch BATCH-118 details",
        "Open batch BATCH-167",
        "Batch BATCH-047 summary",
        "How is batch BATCH-088 doing?",
        "Deviations for batch BATCH-027",
        "Open batch BATCH-150",
        "View batch BATCH-045",
        "What is the status of BER BER--FA32A729?",
        "Show batch execution record BER--05BAE4AA",
        "What is the status of batch BATCH-036?",
        "Status of production batch BATCH-181",
        "Batch BATCH-067 quality data",
        "Fetch batch details for BATCH-189",
        "Status of production batch BATCH-173",
        "Execution record BER--A44C4A35",
        "What happened to batch BATCH-173?",
        "View batch BATCH-084",
        "Show me the batch record for BATCH-044",
        "Tell me about batch BATCH-079",
        "Display batch record BATCH-113",
        "Show yield for BATCH-200",
        "How is batch BATCH-171 doing?",
        "Batch BATCH-087 summary",
        "Show batch BATCH-147",
        "Batch BATCH-006 summary",
        "Display batch record BATCH-115",
        "Batch BATCH-189 quality data",
        "Status of production batch BATCH-070",
        "Tell me about batch BATCH-112",
        "List batches with status Released",
        "Execution record BER--5E837CB4",
        "Get batch record for BATCH-038",
        "Tell me about batch BATCH-154",
        "Execution record BER-900F4A83",
        "Tell me about batch BATCH-100",
        "What is the status of BER BER--47133F71?",
        "Show batch BATCH-012",
        "What is the yield for batch BATCH-166?",
        "Fetch batch details for BATCH-183",
        "Show yield for BATCH-014",
        "What is the status of BER BER--57F24E65?",
        "Fetch batch details for BATCH-007",
        "What is the yield for batch BATCH-002?",
        "What is the status of batch BATCH-110?",
        "Batch BATCH-102 summary",
        "Fetch batch details for BATCH-141",
        "BER BER--1C8F5C98 status",
        "What is the yield for batch BATCH-075?",
        "Batch BATCH-191 summary",
        "Batch BATCH-060 details",
        "Show batch BATCH-099",
        "Show batch BATCH-145",
        "Quality metrics for batch BATCH-096",
        "What is the status of BER BER--89159AB3?",
        "Quality metrics for batch BATCH-105",
        "Show batch execution record BER--272D05CB",
        "Show batch execution record BER--7005E1C3",
        "What is the status of BER BER--66BA5357?",
        "Deviations for batch BATCH-198",
        "Display batch record BATCH-119",
        "Batch BATCH-030 details",
        "Batch BATCH-023 details",
        "Display batch record BATCH-191",
        "Open batch BATCH-012",
        "BER BER--FC77B470 status",
        "Batch BATCH-079 summary",
        "Tell me about batch BATCH-095",
        "Display batch record BATCH-105",
        "BER BER--D9646D23 status",
        "Show me the batch record for BATCH-111",
        "Deviations for batch BATCH-037",
        "Give me info on batch BATCH-027",
        "Show batches in Cancelled status",
        "What is the status of batch BATCH-158?",
        "Show yield for BATCH-006",
        "Give me info on batch BATCH-114",
        "Fetch batch details for BATCH-172",
        "Give me info on batch BATCH-036",
        "What is the yield for batch BATCH-127?",
        "Fetch batch details for BATCH-057",
        "Batch BATCH-181 summary",
        "BER BER--608D8584 status",
        "What happened to batch BATCH-029?",
        "Batch BATCH-032 details",
        "Quality metrics for batch BATCH-159",
        "Display batch record BATCH-135",
        "Status of production batch BATCH-149",
        "Display batch record BATCH-116",
        "Batch BATCH-059 quality data",
        "Fetch batch details for BATCH-132",
        "Give me info on batch BATCH-188",
        "Show batch execution record BER--DEC61AD3",
        "Display batch record BATCH-186",
        "Tell me about batch BATCH-152",
        "BER BER--33C1297F status",
        "Display batch record BATCH-143",
        "Show batch BATCH-084",
        "Tell me about batch BATCH-068",
        "What happened to batch BATCH-044?",
        "What happened to batch BATCH-007?",
        "Batch BATCH-164 quality data",
        "Show me the batch record for BATCH-024",
        "Deviations for batch BATCH-138",
        "Deviations for batch BATCH-136",
        "Execution record BER--89159AB3",
        "What is the yield for batch BATCH-177?",
        "Show batch BATCH-061",
        "Batch BATCH-026 details",
        "Give me info on batch BATCH-111",
        "BER BER--A887CEBE status",
        "Tell me about batch BATCH-143",
        "Show batch BATCH-120",
        "What is the status of batch BATCH-057?",
        "Show me the batch record for BATCH-102",
        "Show yield for BATCH-001",
        "Show batch BATCH-073",
        "Status of production batch BATCH-047",
        "What is the yield for batch BATCH-119?",
        "How is batch BATCH-086 doing?",
        "Display batch record BATCH-053",
        "What happened to batch BATCH-127?",
        "Quality metrics for batch BATCH-170",
        "Give me info on batch BATCH-068",
        "Batch BATCH-162 details",
        "BER BER--3174F14D status",
        "Tell me about batch BATCH-115",
        "What happened to batch BATCH-178?",
        "View batch BATCH-093",
        "Display batch record BATCH-194",
        "Display batch record BATCH-150",
        "Quality metrics for batch BATCH-155",
        "What is the yield for batch BATCH-095?",
        "Deviations for batch BATCH-181",
        "Status of production batch BATCH-189",
        "Quality metrics for batch BATCH-200",
        "Display batch record BATCH-046",
        "Tell me about batch BATCH-050",
        "Show me the batch record for BATCH-147",
        "Fetch batch details for BATCH-161",
        "Deviations for batch BATCH-101",
        "View batch BATCH-170",
        "Tell me about batch BATCH-038",
        "How is batch BATCH-052 doing?",
        "BER BER--06CEA50A status",
        "Open batch BATCH-085",
        "Show yield for BATCH-023",
        "View batch BATCH-130",
        "View batch BATCH-096",
        "Open batch BATCH-029",
        "What is the yield for batch BATCH-133?",
        "Open batch BATCH-177",
        "What is the status of BER BER-67573D58?",
        "Show yield for BATCH-088",
        "Show me the batch record for BATCH-116",
        "Tell me about batch BATCH-153",
        "Batch BATCH-014 quality data",
        "Show batch BATCH-086",
        "Quality metrics for batch BATCH-142",
        "Status of production batch BATCH-023",
        "Give me info on batch BATCH-153",
        "Fetch batch details for BATCH-162",
        "Open batch BATCH-051",
        "Show me the batch record for BATCH-084",
        "Quality metrics for batch BATCH-027",
        "Get batch record for BATCH-020",
        "What happened to batch BATCH-008?",
        "Batch BATCH-168 quality data",
        "Quality metrics for batch BATCH-063",
        "Tell me about batch BATCH-008",
        "Status of production batch BATCH-025",
        "What is the yield for batch BATCH-170?",
        "Tell me about batch BATCH-035",
        "What happened to batch BATCH-149?",
        "Show batch execution record BER--FF9C312C",
        "Display batch record BATCH-185",
        "Fetch batch details for BATCH-004",
        "Status of production batch BATCH-024",
        "Execution record BER-E3246AC9",
        "Tell me about batch BATCH-052",
        "How is batch BATCH-040 doing?",
        "Show batches in Under QA Review status",
        "Deviations for batch BATCH-127",
        "Show batch BATCH-177",
        "Display batch record BATCH-172",
        "Show batch execution record BER--1B40FE38",
        "Show batch BATCH-054",
        "Batch BATCH-051 summary",
        "Batch BATCH-120 summary",
        "How is batch BATCH-041 doing?",
        "What is the status of batch BATCH-044?",
        "What is the status of BER BER--F4197023?",
        "Show batch BATCH-089",
        "BER BER--BCC654F9 status",
        "Show batch execution record BER--EE600F23",
        "Batch BATCH-034 quality data",
        "Deviations for batch BATCH-135",
        "How is batch BATCH-133 doing?",
        "Deviations for batch BATCH-144",
        "Batch BATCH-080 quality data",
        "What happened to batch BATCH-161?",
        "Execution record BER--6C9AD244",
        "What is the status of batch BATCH-004?",
        "Show yield for BATCH-068",
        "What is the status of batch BATCH-021?",
        "Get batch record for BATCH-136",
        "Give me info on batch BATCH-166",
        "Deviations for batch BATCH-021",
        "What is the yield for batch BATCH-039?",
        "Get batch record for BATCH-164",
        "Tell me about batch BATCH-174",
        "Batch BATCH-188 quality data",
        "Open batch BATCH-079",
        "What is the status of batch BATCH-116?",
        "Show yield for BATCH-152",
        "Status of production batch BATCH-147",
        "Show me the batch record for BATCH-103",
        "Batch BATCH-121 quality data",
        "BER BER--604C2A3D status",
        "What is the status of BER BER--E2D35188?",
        "Show batch BATCH-037",
        "Get batch record for BATCH-071",
        "Give me info on batch BATCH-198",
        "Deviations for batch BATCH-167",
        "Tell me about batch BATCH-002",
        "Show me the batch record for BATCH-082",
        "Show me the batch record for BATCH-161",
        "Status of production batch BATCH-078",
        "Tell me about batch BATCH-131",
        "Show me the batch record for BATCH-079",
        "What batches are completed?",
        "What happened to batch BATCH-017?",
        "What happened to batch BATCH-156?",
        "What is the status of batch BATCH-093?",
        "What is the yield for batch BATCH-051?",
        "Display batch record BATCH-055",
        "Display batch record BATCH-168",
        "View batch BATCH-107",
        "Display batch record BATCH-047",
        "Show batch execution record BER--14FB7C4E",
    ],
}
