"""Intent examples: batch_record (part 1/7)."""

from __future__ import annotations

EXAMPLES: dict[str, list[str]] = {
    "batch_record": [
        "Deviations for batch BATCH-072",
        "Show batch execution record BER--0A2EE388",
        "Show me all production batches",
        "Show me the batch record for BATCH-128",
        "Tell me about batch BATCH-030",
        "List all batches in the system",
        "Show released batches this month",
        "What batches are currently running?",
        "Display batch record BATCH-068",
        "Batches in production right now",
        "Status of production batch BATCH-073",
        "Show batches for line LINE-TAB-001",
        "What batches are on line LINE-CAP-001?",
        "Display batch record BATCH-067",
        "List approved batches",
        "Show all Cetirizine 10mg Tablets batches",
        "Show batches for line LINE-CAP-001",
        "Show batch statistics",
        "Show batches in Released status",
        "Status of production batch BATCH-031",
        "List recent batches",
        "Total number of batches",
        "Give me a batch summary",
        "Batches completed this week",
        "Batches producing Atorvastatin 10mg Tablets",
        "Execution record BER--6180633F",
        "Open batch BATCH-140",
        "Execution record BER--D9646D23",
        "What happened to batch BATCH-063?",
        "Find all in production batches",
        "Deviations for batch BATCH-043",
        "Execution record BER--B6A8BD84",
        "What batches are there for Cetirizine 10mg Tablets?",
        "View batch BATCH-030",
        "Deviations for batch BATCH-111",
        "What is the yield for batch BATCH-032?",
        "What is the status of batch BATCH-091?",
        "Fetch batch details for BATCH-011",
        "Which batches contain Paracetamol 500mg Tablets?",
        "What batches are on hold?",
        "Batch BATCH-174 quality data",
        "Which batches contain Amoxicillin 250mg Capsules?",
        "Batches awaiting release",
        "What batches are on line LINE-TAB-001?",
        "How many batches are there?",
        "How is batch BATCH-164 doing?",
        "How many production batches do we have?",
        "What batches have been approved?",
        "Batches on production line LINE-TAB-001",
        "List all batches for Metformin 500mg Tablets",
        "How is batch BATCH-083 doing?",
        "What batches are there for Paracetamol 500mg Tablets?",
        "Show yield for BATCH-009",
        "What is the batch count?",
        "Batch overview",
        "Show batch BATCH-151",
        "Batches producing Amoxicillin 250mg Capsules",
        "Show me the batch record for BATCH-118",
        "What is the status of batch BATCH-001?",
        "List all released batches",
        "How is batch BATCH-194 doing?",
        "Show me the batch record for BATCH-036",
        "What happened to batch BATCH-022?",
        "Give me info on batch BATCH-019",
        "Batch BATCH-164 details",
        "Show batches from last month",
        "BER BER--9D757166 status",
        "Batch BATCH-168 summary",
        "Show batch BATCH-195",
        "What happened to batch BATCH-075?",
        "Open batch BATCH-149",
        "Show in-progress batches",
        "Find all planned batches",
        "Give me info on batch BATCH-138",
        "Active production batches",
        "Which batches contain Atorvastatin 10mg Tablets?",
        "List batches that are suspended",
        "What batches are there for Atorvastatin 10mg Tablets?",
        "Show batch execution record BER--C5864960",
        "Batch BATCH-158 details",
        "Quality metrics for batch BATCH-181",
        "Batch BATCH-157 quality data",
        "BER BER--A7B8D1C6 status",
        "What batches are dispensing?",
        "What is the status of batch BATCH-147?",
        "Batch BATCH-057 quality data",
        "What batches are created?",
        "What happened to batch BATCH-051?",
        "Show yield for BATCH-125",
        "Deviations for batch BATCH-024",
        "What batches were started today?",
        "Count total batches",
        "What is the status of BER BER--29CF6B4A?",
        "Show yield for BATCH-161",
        "What happened to batch BATCH-096?",
        "What is the yield for batch BATCH-142?",
        "What is the yield for batch BATCH-035?",
        "Find batches for product Amoxicillin 250mg Capsules",
        "What is the status of batch BATCH-133?",
        "Show all Atorvastatin 10mg Tablets batches",
        "View batch BATCH-197",
        "Batches producing Cetirizine 10mg Tablets",
        "Quality metrics for batch BATCH-148",
        "What is the yield for batch BATCH-164?",
        "View batch BATCH-137",
        "Show batch execution record BER--6AFAC919",
        "Tell me about batch BATCH-102",
        "What happened to batch BATCH-160?",
        "Show yield for BATCH-141",
        "Which batches contain Metformin 500mg Tablets?",
        "What is the status of BER BER--2F388213?",
        "Batch BATCH-129 summary",
        "View batch BATCH-124",
        "Show batch BATCH-182",
        "Find batches for product Cetirizine 10mg Tablets",
        "Show held batches",
        "List all batches for Paracetamol 500mg Tablets",
        "Get batch record for BATCH-004",
        "Show batch execution record BER--3F7A438B",
        "What is the status of BER BER--CB57ED02?",
        "Batch BATCH-102 quality data",
        "Batch BATCH-106 summary",
        "Open batch BATCH-116",
        "List all batches for Amoxicillin 250mg Capsules",
        "List batches with status Planned",
        "Show batch BATCH-112",
        "Status of production batch BATCH-001",
        "Tell me about batch BATCH-144",
        "Get batch record for BATCH-112",
        "Show batch execution record BER--D16498DD",
        "Get batch record for BATCH-150",
        "Show batch execution record BER--13283CE3",
        "Deviations for batch BATCH-103",
        "Tell me about batch BATCH-195",
        "Execution record BER--CFF34E79",
        "Show all Metformin 500mg Tablets batches",
        "Recent batch activity",
        "Show batches created this week",
        "List all batches for Atorvastatin 10mg Tablets",
        "What is the status of BER BER--04F787DF?",
        "Show all Paracetamol 500mg Tablets batches",
        "List batches with status Dispensing",
        "Display batch record BATCH-195",
        "Show batch execution record BER--7D539067",
        "Batch BATCH-017 summary",
        "What is the status of batch BATCH-105?",
        "Batch BATCH-163 summary",
        "Tell me about batch BATCH-118",
        "View batch BATCH-005",
        "What is the status of BER BER--14FB7C4E?",
        "Execution record BER--B7B46DA1",
        "Status of production batch BATCH-186",
        "Give me info on batch BATCH-097",
        "Open batch BATCH-066",
        "Execution record BER--06CEA50A",
        "Display batch record BATCH-096",
        "Tell me about batch BATCH-072",
        "Batch BATCH-097 details",
        "Batch BATCH-178 quality data",
        "Find all dispensing batches",
        "Tell me about batch BATCH-151",
        "Show me the batch record for BATCH-191",
        "Display batch record BATCH-009",
        "BER BER-0B19CB30 status",
        "List batches with status Created",
        "Give me info on batch BATCH-174",
        "Find all under qa review batches",
        "Open batch BATCH-189",
        "Show batch execution record BER--4BC133F6",
        "List batches with status In Progress",
        "Show all Amoxicillin 250mg Capsules batches",
        "What batches are there for Amoxicillin 250mg Capsules?",
        "Give me info on batch BATCH-189",
        "Batches on production line LINE-CAP-001",
        "Quality metrics for batch BATCH-069",
        "Show batch execution record BER--A464BB15",
        "Batch BATCH-111 quality data",
        "What happened to batch BATCH-085?",
        "Show batch BATCH-052",
        "What is the status of BER BER-F3E117EE?",
        "Show batch BATCH-137",
        "Give me info on batch BATCH-200",
        "View batch BATCH-004",
        "Batch BATCH-012 quality data",
        "Batch BATCH-143 details",
        "Status of production batch BATCH-129",
        "Show yield for BATCH-022",
        "What batches are approved?",
        "What happened to batch BATCH-108?",
        "What batches are under qa review?",
        "Find all approved batches",
        "Display batch record BATCH-127",
        "Give me info on batch BATCH-143",
        "Show batch execution record BER--772FDFC2",
        "Batch BATCH-095 summary",
        "Show batches in Created status",
        "Open batch BATCH-086",
        "Give me info on batch BATCH-078",
        "Execution record BER--9C669C9D",
        "What is the status of BER BER-AFA53C7A?",
        "List all batches for Cetirizine 10mg Tablets",
        "Show batch execution record BER--8B5EE8FD",
        "Batches producing Paracetamol 500mg Tablets",
        "Fetch batch details for BATCH-088",
        "Fetch batch details for BATCH-093",
        "How is batch BATCH-090 doing?",
        "BER BER--C5864960 status",
        "Show me the batch record for BATCH-184",
        "List batches with status Completed",
        "What batches are there for Metformin 500mg Tablets?",
        "Tell me about batch BATCH-006",
        "What is the yield for batch BATCH-186?",
        "Show batches in Completed status",
        "Show batches in In Production status",
        "Quality metrics for batch BATCH-169",
        "Open batch BATCH-021",
        "Tell me about batch BATCH-022",
        "Tell me about batch BATCH-128",
        "What is the yield for batch BATCH-124?",
        "Batch BATCH-072 summary",
        "Deviations for batch BATCH-073",
        "Execution record BER-3AB9E94D",
        "Batch BATCH-152 summary",
        "What is the status of BER BER--3174F14D?",
        "Open batch BATCH-094",
        "Show me the batch record for BATCH-022",
        "Give me info on batch BATCH-077",
        "Give me info on batch BATCH-090",
        "Display batch record BATCH-090",
        "Display batch record BATCH-126",
        "Find all created batches",
        "Deviations for batch BATCH-026",
        "Quality metrics for batch BATCH-145",
        "Batch BATCH-051 details",
        "What is the status of batch BATCH-013?",
        "Batch BATCH-190 summary",
        "Which batches contain Cetirizine 10mg Tablets?",
        "Fetch batch details for BATCH-178",
        "Batch BATCH-160 summary",
        "Get batch record for BATCH-022",
        "Tell me about batch BATCH-003",
        "Show yield for BATCH-194",
        "Deviations for batch BATCH-110",
        "Tell me about batch BATCH-177",
        "Show yield for BATCH-159",
        "BER BER--C7BEE953 status",
        "Display batch record BATCH-166",
        "Quality metrics for batch BATCH-052",
        "Batch BATCH-167 details",
        "Open batch BATCH-101",
        "Tell me about batch BATCH-056",
        "What happened to batch BATCH-030?",
        "Deviations for batch BATCH-063",
        "Quality metrics for batch BATCH-072",
        "Find all cancelled batches",
        "Display batch record BATCH-136",
        "Execution record BER--FBB40518",
        "Display batch record BATCH-103",
        "Get batch record for BATCH-130",
        "Tell me about batch BATCH-017",
        "Show yield for BATCH-085",
        "BER BER-6D61D8D5 status",
        "Display batch record BATCH-033",
        "Get batch record for BATCH-048",
        "Batch BATCH-141 quality data",
        "Show batch execution record BER--F70E78AA",
        "Display batch record BATCH-065",
        "BER BER-B35DC807 status",
        "Show me the batch record for BATCH-108",
        "Show batch BATCH-186",
        "Show me the batch record for BATCH-195",
        "Quality metrics for batch BATCH-038",
        "Show yield for BATCH-015",
        "Status of production batch BATCH-193",
        "Status of production batch BATCH-163",
        "Give me info on batch BATCH-186",
        "Show me the batch record for BATCH-183",
        "What is the yield for batch BATCH-055?",
        "What happened to batch BATCH-139?",
        "What is the status of BER BER--FBB40518?",
        "What is the status of BER BER-D893B10A?",
        "Batch BATCH-138 quality data",
        "What batches are released?",
        "Batch BATCH-024 details",
        "Tell me about batch BATCH-046",
        "View batch BATCH-061",
        "What is the status of batch BATCH-051?",
        "Show batches in On Hold status",
        "What is the status of batch BATCH-148?",
        "What batches are planned?",
        "Quality metrics for batch BATCH-030",
        "What is the status of batch BATCH-088?",
        "Open batch BATCH-031",
        "Tell me about batch BATCH-084",
        "Execution record BER--86A9CFC3",
        "Status of production batch BATCH-050",
        "Execution record BER--F81835A3",
        "Get batch record for BATCH-158",
        "Fetch batch details for BATCH-116",
        "How is batch BATCH-007 doing?",
        "Give me info on batch BATCH-060",
        "Batch BATCH-165 details",
        "How is batch BATCH-114 doing?",
        "View batch BATCH-003",
        "Find batches for product Paracetamol 500mg Tablets",
        "Show yield for BATCH-149",
        "Batch BATCH-035 details",
        "Show me the batch record for BATCH-041",
        "Tell me about batch BATCH-076",
        "Open batch BATCH-020",
        "Execution record BER--15458759",
        "Tell me about batch BATCH-037",
        "Give me info on batch BATCH-118",
        "Status of production batch BATCH-096",
        "Batch BATCH-077 quality data",
        "Fetch batch details for BATCH-086",
        "Show yield for BATCH-046",
        "Batch BATCH-003 details",
        "Deviations for batch BATCH-139",
        "What is the status of batch BATCH-118?",
        "Give me info on batch BATCH-085",
        "View batch BATCH-108",
        "Give me info on batch BATCH-086",
        "Show me the batch record for BATCH-101",
        "Deviations for batch BATCH-165",
        "Open batch BATCH-024",
        "What is the yield for batch BATCH-171?",
        "Status of production batch BATCH-191",
        "Find all completed batches",
        "Batch BATCH-028 quality data",
        "Status of production batch BATCH-049",
        "Show batch execution record BER--9C669C9D",
        "Batches producing Metformin 500mg Tablets",
        "Deviations for batch BATCH-113",
        "Batch BATCH-078 quality data",
        "What is the yield for batch BATCH-029?",
        "What batches are rejected?",
        "Batch BATCH-029 summary",
        "BER BER--12DC03A0 status",
        "Show batches in Planned status",
        "Status of production batch BATCH-115",
        "BER BER--272D05CB status",
        "What is the status of BER BER--2A9601E0?",
        "BER BER--80B6E7C1 status",
        "Fetch batch details for BATCH-170",
        "What happened to batch BATCH-169?",
        "Show batch execution record BER--CC87C715",
        "Tell me about batch BATCH-029",
        "What is the status of BER BER-8E4C419B?",
        "Show batch BATCH-163",
        "Find all released batches",
        "Give me info on batch BATCH-099",
        "Show me the batch record for BATCH-015",
        "Show batch BATCH-075",
        "Tell me about batch BATCH-047",
        "Quality metrics for batch BATCH-065",
        "Show batch BATCH-078",
        "Show me the batch record for BATCH-143",
        "Show batch BATCH-154",
        "Tell me about batch BATCH-083",
        "Show batch execution record BER-900F4A83",
        "Execution record BER--7005E1C3",
        "Open batch BATCH-155",
        "Show batch BATCH-088",
        "Show me the batch record for BATCH-174",
        "Show me the batch record for BATCH-192",
        "How is batch BATCH-056 doing?",
        "Batch BATCH-191 quality data",
        "Batch BATCH-169 quality data",
        "What happened to batch BATCH-166?",
        "What is the status of batch BATCH-031?",
        "Execution record BER-B4705A0F",
        "Tell me about batch BATCH-147",
        "Show batch execution record BER--DB91A76B",
        "What is the yield for batch BATCH-190?",
        "Status of production batch BATCH-080",
        "Show batch execution record BER--EFFD385B",
        "Open batch BATCH-179",
        "Batch BATCH-048 quality data",
        "Find batches for product Metformin 500mg Tablets",
        "What is the status of BER BER--B5CF9B89?",
        "What is the status of batch BATCH-145?",
        "How is batch BATCH-027 doing?",
        "Show batch BATCH-011",
        "Batch BATCH-182 quality data",
        "BER BER-5D728E09 status",
        "Batch BATCH-057 details",
        "Show batch execution record BER--92E8A3BA",
        "Show me the batch record for BATCH-114",
        "Give me info on batch BATCH-055",
        "Batch BATCH-161 quality data",
        "Give me info on batch BATCH-076",
        "Give me info on batch BATCH-038",
        "Batch BATCH-022 quality data",
        "Show batch BATCH-035",
        "Quality metrics for batch BATCH-049",
        "What is the status of batch BATCH-113?",
        "What happened to batch BATCH-043?",
        "Show me the batch record for BATCH-011",
        "Deviations for batch BATCH-090",
        "Show yield for BATCH-101",
        "Batch BATCH-187 summary",
        "Give me info on batch BATCH-105",
        "Show yield for BATCH-025",
        "Fetch batch details for BATCH-114",
        "Show batch BATCH-020",
        "Open batch BATCH-186",
        "Show me the batch record for BATCH-080",
        "Batch BATCH-078 summary",
        "BER BER-3E9C8187 status",
        "Batch BATCH-097 summary",
        "Display batch record BATCH-129",
        "List batches with status Cancelled",
        "Show yield for BATCH-099",
        "What is the yield for batch BATCH-146?",
        "Quality metrics for batch BATCH-003",
        "Tell me about batch BATCH-180",
        "Status of production batch BATCH-138",
        "Status of production batch BATCH-057",
        "Give me info on batch BATCH-065",
        "Deviations for batch BATCH-168",
        "Give me info on batch BATCH-004",
        "Show batch BATCH-135",
        "Show yield for BATCH-062",
        "Deviations for batch BATCH-123",
        "Show me the batch record for BATCH-146",
        "BER BER--7BCBE4FE status",
        "Open batch BATCH-145",
        "Execution record BER--9605D93B",
        "Batch BATCH-195 summary",
        "Quality metrics for batch BATCH-008",
        "View batch BATCH-135",
        "Find all rejected batches",
        "What is the status of batch BATCH-023?",
        "BER BER--15458759 status",
        "What is the yield for batch BATCH-168?",
        "Tell me about batch BATCH-176",
        "BER BER--5CCADE57 status",
        "Tell me about batch BATCH-193",
        "Show me the batch record for BATCH-157",
        "Execution record BER--846D4BB4",
        "Find batches for product Atorvastatin 10mg Tablets",
        "Get batch record for BATCH-122",
        "Execution record BER--8B5EE8FD",
        "View batch BATCH-120",
        "What is the status of BER BER--608D8584?",
        "Show batch BATCH-060",
        "Deviations for batch BATCH-058",
        "Batch BATCH-155 summary",
        "Open batch BATCH-083",
        "What is the status of BER BER--A8713022?",
        "Quality metrics for batch BATCH-076",
        "View batch BATCH-049",
        "What is the yield for batch BATCH-011?",
        "What is the status of BER BER--FC77B470?",
        "Display batch record BATCH-063",
        "Batch BATCH-112 summary",
        "What is the status of batch BATCH-097?",
        "Fetch batch details for BATCH-125",
        "Show me the batch record for BATCH-014",
        "Batch BATCH-078 details",
        "What happened to batch BATCH-196?",
        "Batch BATCH-185 quality data",
        "Batch BATCH-027 details",
        "List batches with status On Hold",
        "Fetch batch details for BATCH-091",
        "Deviations for batch BATCH-146",
        "Show yield for BATCH-117",
        "Show batches in Approved status",
        "Execution record BER-F304869A",
        "Give me info on batch BATCH-040",
        "What is the status of BER BER--6AFAC919?",
        "Batch BATCH-178 details",
        "Get batch record for BATCH-121",
        "BER BER--F81835A3 status",
        "Execution record BER--E060AEC8",
        "Show batch execution record BER--E2D35188",
        "Show batch BATCH-133",
        "What batches are in progress?",
        "What is the status of batch BATCH-192?",
        "Show yield for BATCH-048",
        "Deviations for batch BATCH-192",
        "View batch BATCH-006",
        "Show batch execution record BER-67573D58",
    ],
}
