"""Intent examples: batch_record (part 5/7)."""

from __future__ import annotations

EXAMPLES: dict[str, list[str]] = {
    "batch_record": [
        "Show batch execution record BER--CDFFBCA2",
        "Show batch BATCH-128",
        "Get batch record for BATCH-051",
        "How is batch BATCH-124 doing?",
        "Batch BATCH-024 quality data",
        "View batch BATCH-110",
        "What is the yield for batch BATCH-083?",
        "How is batch BATCH-062 doing?",
        "Get batch record for BATCH-059",
        "What is the status of BER BER--8B2328B5?",
        "Status of production batch BATCH-130",
        "Show batch BATCH-049",
        "Tell me about batch BATCH-091",
        "Fetch batch details for BATCH-043",
        "Execution record BER--6AFAC919",
        "Get batch record for BATCH-133",
        "Show yield for BATCH-077",
        "Give me info on batch BATCH-168",
        "Execution record BER-B35DC807",
        "Show me the batch record for BATCH-089",
        "Tell me about batch BATCH-110",
        "Open batch BATCH-127",
        "Show batch execution record BER--768A0997",
        "BER BER--BEA5733C status",
        "Show batch execution record BER--9605D93B",
        "Display batch record BATCH-114",
        "Open batch BATCH-033",
        "Batch BATCH-107 quality data",
        "Batch BATCH-073 quality data",
        "Show me the batch record for BATCH-040",
        "Batch BATCH-019 summary",
        "Deviations for batch BATCH-130",
        "Get batch record for BATCH-080",
        "What is the yield for batch BATCH-096?",
        "Deviations for batch BATCH-042",
        "Show me the batch record for BATCH-057",
        "Batch BATCH-170 details",
        "Show batch execution record BER--009D541A",
        "Display batch record BATCH-158",
        "Deviations for batch BATCH-009",
        "Quality metrics for batch BATCH-158",
        "View batch BATCH-157",
        "Fetch batch details for BATCH-068",
        "What is the yield for batch BATCH-015?",
        "Show me the batch record for BATCH-049",
        "Execution record BER-2F97B465",
        "What is the status of BER BER--EEA53DA3?",
        "What is the status of BER BER-170ECA79?",
        "Open batch BATCH-106",
        "Batch BATCH-103 summary",
        "Execution record BER-8E4C419B",
        "What is the status of BER BER-79B0326D?",
        "What happened to batch BATCH-005?",
        "How is batch BATCH-153 doing?",
        "Deviations for batch BATCH-188",
        "Display batch record BATCH-192",
        "Show yield for BATCH-150",
        "Show yield for BATCH-118",
        "Show me the batch record for BATCH-002",
        "Status of production batch BATCH-006",
        "What is the status of batch BATCH-030?",
        "What is the status of batch BATCH-186?",
        "View batch BATCH-119",
        "Display batch record BATCH-133",
        "Show yield for BATCH-030",
        "Display batch record BATCH-162",
        "Display batch record BATCH-138",
        "How is batch BATCH-029 doing?",
        "Show batch BATCH-081",
        "Get batch record for BATCH-095",
        "Status of production batch BATCH-159",
        "Show yield for BATCH-054",
        "Deviations for batch BATCH-014",
        "Open batch BATCH-092",
        "What happened to batch BATCH-128?",
        "Display batch record BATCH-108",
        "Fetch batch details for BATCH-099",
        "Get batch record for BATCH-143",
        "Open batch BATCH-042",
        "Fetch batch details for BATCH-131",
        "Batch BATCH-123 details",
        "Get batch record for BATCH-170",
        "Show batch BATCH-101",
        "BER BER--A9795C0E status",
        "Status of production batch BATCH-045",
        "Show batch BATCH-180",
        "How is batch BATCH-081 doing?",
        "What is the status of BER BER--0F7E722D?",
        "Batch BATCH-096 details",
        "View batch BATCH-191",
        "View batch BATCH-172",
        "Batch BATCH-140 details",
        "BER BER--DEC61AD3 status",
        "Tell me about batch BATCH-179",
        "View batch BATCH-082",
        "Tell me about batch BATCH-065",
        "What is the status of BER BER--5E837CB4?",
        "Quality metrics for batch BATCH-092",
        "Status of production batch BATCH-086",
        "Tell me about batch BATCH-097",
        "Fetch batch details for BATCH-196",
        "How is batch BATCH-155 doing?",
        "Batch BATCH-106 details",
        "Tell me about batch BATCH-090",
        "Show batch BATCH-065",
        "Execution record BER-E3B78D7A",
        "Fetch batch details for BATCH-190",
        "What is the yield for batch BATCH-160?",
        "Quality metrics for batch BATCH-017",
        "Show batch execution record BER-3A335864",
        "Display batch record BATCH-142",
        "Open batch BATCH-048",
        "View batch BATCH-113",
        "What is the status of batch BATCH-149?",
        "Batch BATCH-042 details",
        "Show batch execution record BER--8FD9113C",
        "Display batch record BATCH-175",
        "What happened to batch BATCH-099?",
        "Open batch BATCH-058",
        "Batch BATCH-121 summary",
        "Deviations for batch BATCH-121",
        "Batch BATCH-005 summary",
        "Execution record BER--2F388213",
        "Show batch execution record BER--0F7E722D",
        "Execution record BER--EEA53DA3",
        "Status of production batch BATCH-198",
        "Execution record BER--78D84DAD",
        "How is batch BATCH-097 doing?",
        "Batch BATCH-192 quality data",
        "Fetch batch details for BATCH-012",
        "What is the yield for batch BATCH-111?",
        "What is the status of batch BATCH-103?",
        "Status of production batch BATCH-179",
        "Execution record BER-79B0326D",
        "Status of production batch BATCH-108",
        "Tell me about batch BATCH-075",
        "Batch BATCH-090 summary",
        "Show yield for BATCH-185",
        "Show me the batch record for BATCH-178",
        "Give me info on batch BATCH-009",
        "What is the status of batch BATCH-048?",
        "Show batch BATCH-121",
        "Show batch BATCH-097",
        "What happened to batch BATCH-112?",
        "Batch BATCH-130 quality data",
        "Show me the batch record for BATCH-122",
        "What is the status of batch BATCH-084?",
        "What happened to batch BATCH-035?",
        "Show me the batch record for BATCH-003",
        "Batch BATCH-099 quality data",
        "Batch BATCH-174 summary",
        "What is the status of batch BATCH-144?",
        "View batch BATCH-009",
        "View batch BATCH-053",
        "Display batch record BATCH-187",
        "Fetch batch details for BATCH-123",
        "What happened to batch BATCH-144?",
        "What happened to batch BATCH-159?",
        "Get batch record for BATCH-106",
        "Status of production batch BATCH-166",
        "Status of production batch BATCH-101",
        "Tell me about batch BATCH-199",
        "BER BER--8D87D8FF status",
        "What is the status of batch BATCH-190?",
        "What is the yield for batch BATCH-046?",
        "Show me the batch record for BATCH-064",
        "Show yield for BATCH-094",
        "What is the yield for batch BATCH-100?",
        "Give me info on batch BATCH-029",
        "Batch BATCH-049 details",
        "What is the status of BER BER--28D14605?",
        "Show batch execution record BER--04F787DF",
        "What is the status of batch BATCH-130?",
        "Fetch batch details for BATCH-024",
        "Quality metrics for batch BATCH-094",
        "Execution record BER--A8713022",
        "What is the status of batch BATCH-007?",
        "View batch BATCH-069",
        "What is the yield for batch BATCH-159?",
        "What is the status of batch BATCH-029?",
        "Get batch record for BATCH-163",
        "Display batch record BATCH-110",
        "Quality metrics for batch BATCH-171",
        "Show yield for BATCH-145",
        "Get batch record for BATCH-058",
        "Give me info on batch BATCH-033",
        "What is the yield for batch BATCH-141?",
        "What is the status of batch BATCH-181?",
        "View batch BATCH-072",
        "View batch BATCH-155",
        "How is batch BATCH-038 doing?",
        "Show yield for BATCH-010",
        "What is the status of batch BATCH-189?",
        "What is the status of batch BATCH-069?",
        "Show yield for BATCH-179",
        "View batch BATCH-014",
        "Fetch batch details for BATCH-045",
        "Batch BATCH-185 details",
        "What is the yield for batch BATCH-150?",
        "What happened to batch BATCH-121?",
        "BER BER-170ECA79 status",
        "View batch BATCH-018",
        "View batch BATCH-089",
        "Fetch batch details for BATCH-021",
        "What is the yield for batch BATCH-073?",
        "Fetch batch details for BATCH-142",
        "How is batch BATCH-108 doing?",
        "Show batch execution record BER--04319A40",
        "Batch BATCH-142 details",
        "Tell me about batch BATCH-122",
        "Show yield for BATCH-160",
        "Execution record BER--13283CE3",
        "Status of production batch BATCH-146",
        "What is the yield for batch BATCH-057?",
        "Quality metrics for batch BATCH-056",
        "View batch BATCH-066",
        "Show me the batch record for BATCH-171",
        "Fetch batch details for BATCH-113",
        "Execution record BER--7E444145",
        "Show batch execution record BER--FDE1870B",
        "Batch BATCH-154 details",
        "Status of production batch BATCH-137",
        "Fetch batch details for BATCH-036",
        "Batch BATCH-055 details",
        "How is batch BATCH-035 doing?",
        "Open batch BATCH-161",
        "BER BER--10C81775 status",
        "Quality metrics for batch BATCH-125",
        "What is the status of BER BER-AF735A33?",
        "Deviations for batch BATCH-140",
        "How is batch BATCH-145 doing?",
        "Batch BATCH-145 details",
        "Batch BATCH-056 summary",
        "Show batch BATCH-014",
        "Open batch BATCH-108",
        "What is the status of batch BATCH-081?",
        "View batch BATCH-019",
        "Deviations for batch BATCH-095",
        "What is the status of batch BATCH-085?",
        "View batch BATCH-038",
        "Get batch record for BATCH-199",
        "Open batch BATCH-006",
        "Batch BATCH-100 quality data",
        "Give me info on batch BATCH-041",
        "BER BER--A464BB15 status",
        "Show me the batch record for BATCH-078",
        "Show batch execution record BER-8E4C419B",
        "Batch BATCH-128 summary",
        "Status of production batch BATCH-075",
        "Show batch execution record BER--7BCBE4FE",
        "What is the yield for batch BATCH-105?",
        "Give me info on batch BATCH-043",
        "Quality metrics for batch BATCH-016",
        "Open batch BATCH-151",
        "How is batch BATCH-161 doing?",
        "Show yield for BATCH-186",
        "Batch BATCH-081 details",
        "Deviations for batch BATCH-174",
        "Show yield for BATCH-078",
        "How is batch BATCH-089 doing?",
        "What is the yield for batch BATCH-071?",
        "What is the status of BER BER--8CE73799?",
        "Show yield for BATCH-084",
        "Show batch execution record BER--7E444145",
        "Batch BATCH-109 summary",
        "Give me info on batch BATCH-161",
        "Batch BATCH-116 summary",
        "View batch BATCH-106",
        "Show me the batch record for BATCH-053",
        "What is the yield for batch BATCH-104?",
        "Show me the batch record for BATCH-027",
        "How is batch BATCH-096 doing?",
        "Quality metrics for batch BATCH-001",
        "Tell me about batch BATCH-096",
        "Show me the batch record for BATCH-149",
        "Show batch BATCH-146",
        "Show me the batch record for BATCH-173",
        "How is batch BATCH-187 doing?",
        "Batch BATCH-067 summary",
        "View batch BATCH-151",
        "What is the status of batch BATCH-064?",
        "Show batch execution record BER--6DE912AF",
        "What is the yield for batch BATCH-088?",
        "Display batch record BATCH-059",
        "BER BER--1454F070 status",
        "What happened to batch BATCH-124?",
        "Show me the batch record for BATCH-075",
        "Give me info on batch BATCH-061",
        "Get batch record for BATCH-117",
        "Batch BATCH-083 summary",
        "Open batch BATCH-099",
        "Display batch record BATCH-101",
        "What is the status of BER BER--8CB20167?",
        "What is the status of BER BER--D9646D23?",
        "Open batch BATCH-104",
        "View batch BATCH-050",
        "What happened to batch BATCH-185?",
        "View batch BATCH-077",
        "Batch BATCH-023 summary",
        "Batch BATCH-034 details",
        "Open batch BATCH-061",
        "Execution record BER-0B19CB30",
        "Give me info on batch BATCH-179",
        "Batch BATCH-162 quality data",
        "Show yield for BATCH-041",
        "Batch BATCH-029 details",
        "How is batch BATCH-135 doing?",
        "View batch BATCH-115",
        "What is the status of BER BER--272D05CB?",
        "Give me info on batch BATCH-142",
        "Show batch execution record BER-9B56D46F",
        "View batch BATCH-193",
        "Get batch record for BATCH-125",
        "What is the status of BER BER-E3246AC9?",
        "What is the yield for batch BATCH-126?",
        "Get batch record for BATCH-032",
        "Fetch batch details for BATCH-062",
        "What is the status of batch BATCH-099?",
        "What is the status of BER BER--A464BB15?",
        "Show batch BATCH-090",
        "Batch BATCH-035 quality data",
        "What is the status of BER BER-F109D264?",
        "Open batch BATCH-026",
        "How is batch BATCH-085 doing?",
        "What happened to batch BATCH-084?",
        "What is the yield for batch BATCH-028?",
        "Get batch record for BATCH-134",
        "Batch BATCH-061 quality data",
        "Get batch record for BATCH-181",
        "Give me info on batch BATCH-194",
        "How is batch BATCH-179 doing?",
        "What is the status of BER BER--06CEA50A?",
        "View batch BATCH-122",
        "View batch BATCH-102",
        "Status of production batch BATCH-153",
        "Execution record BER--772FDFC2",
        "Give me info on batch BATCH-199",
        "Get batch record for BATCH-109",
        "Batch BATCH-138 details",
        "Show batch execution record BER--6C9AD244",
        "What is the status of BER BER--E2A75EC8?",
        "What is the status of batch BATCH-066?",
        "Open batch BATCH-009",
        "Execution record BER--17D37A69",
        "Show batch BATCH-161",
        "Display batch record BATCH-007",
        "Show yield for BATCH-018",
        "Give me info on batch BATCH-070",
        "Deviations for batch BATCH-148",
        "Tell me about batch BATCH-137",
        "BER BER--86A9CFC3 status",
        "What happened to batch BATCH-133?",
        "Show batch execution record BER-5B293B91",
        "Tell me about batch BATCH-053",
        "Give me info on batch BATCH-108",
        "Deviations for batch BATCH-032",
        "Get batch record for BATCH-167",
        "How is batch BATCH-127 doing?",
        "Batch BATCH-106 quality data",
        "Give me info on batch BATCH-176",
        "Tell me about batch BATCH-129",
        "Batch BATCH-142 quality data",
        "What is the status of BER BER--569B9422?",
        "What happened to batch BATCH-162?",
        "Execution record BER--804F7CA8",
        "What happened to batch BATCH-076?",
        "BER BER--04F787DF status",
        "What is the yield for batch BATCH-047?",
        "Show batch BATCH-047",
        "Quality metrics for batch BATCH-081",
        "Execution record BER--8CE73799",
        "How is batch BATCH-034 doing?",
        "Quality metrics for batch BATCH-122",
        "Status of production batch BATCH-111",
        "What is the status of batch BATCH-182?",
        "What happened to batch BATCH-067?",
        "Open batch BATCH-076",
        "Batch BATCH-028 details",
        "Batch BATCH-112 quality data",
        "BER BER--2A9601E0 status",
        "Batch BATCH-137 quality data",
        "Get batch record for BATCH-154",
        "What happened to batch BATCH-119?",
        "What is the yield for batch BATCH-152?",
        "Open batch BATCH-123",
        "Give me info on batch BATCH-057",
        "Open batch BATCH-016",
        "Get batch record for BATCH-044",
        "Tell me about batch BATCH-070",
        "What is the status of batch BATCH-183?",
        "How is batch BATCH-046 doing?",
        "Fetch batch details for BATCH-117",
        "Batch BATCH-167 summary",
        "BER BER--9F46A182 status",
        "BER BER--5E837CB4 status",
        "Batch BATCH-158 quality data",
        "Fetch batch details for BATCH-100",
        "What is the yield for batch BATCH-027?",
        "Show batch execution record BER--A7B8D1C6",
        "Fetch batch details for BATCH-078",
        "Execution record BER-F280724C",
        "Get batch record for BATCH-135",
        "Execution record BER-170ECA79",
        "Show batch BATCH-069",
        "What happened to batch BATCH-120?",
        "Tell me about batch BATCH-186",
        "Quality metrics for batch BATCH-029",
        "Show batch BATCH-044",
        "Tell me about batch BATCH-005",
        "BER BER--4E45475E status",
        "Show me the batch record for BATCH-050",
        "Show batch execution record BER-F280724C",
        "BER BER--1FF9DD82 status",
        "Batch BATCH-071 summary",
        "Batch BATCH-058 summary",
        "Status of production batch BATCH-071",
        "Get batch record for BATCH-094",
        "Fetch batch details for BATCH-005",
        "Tell me about batch BATCH-141",
        "What is the status of BER BER--804F7CA8?",
        "Batch BATCH-004 quality data",
        "Batch BATCH-015 quality data",
        "Get batch record for BATCH-118",
        "What is the yield for batch BATCH-112?",
        "Batch BATCH-001 summary",
        "What is the status of BER BER--78D84DAD?",
        "Give me info on batch BATCH-011",
        "Show batch BATCH-103",
        "What is the status of batch BATCH-169?",
        "Open batch BATCH-157",
        "Batch BATCH-136 summary",
        "Status of production batch BATCH-036",
        "Batch BATCH-024 summary",
        "Quality metrics for batch BATCH-034",
        "Batch BATCH-194 details",
        "Show batch BATCH-058",
        "Show me the batch record for BATCH-150",
        "What is the status of batch BATCH-125?",
        "Show batch BATCH-187",
        "Display batch record BATCH-155",
        "Show batch execution record BER--7F4A75AF",
        "Status of production batch BATCH-068",
        "Show batch BATCH-140",
        "Batch BATCH-171 quality data",
        "Execution record BER--9EC49100",
        "Display batch record BATCH-020",
        "Fetch batch details for BATCH-191",
        "Show yield for BATCH-012",
        "Batch BATCH-070 summary",
        "How is batch BATCH-101 doing?",
        "Show batch BATCH-064",
        "What is the status of batch BATCH-049?",
        "What is the status of BER BER--7B315106?",
        "What happened to batch BATCH-165?",
        "Status of production batch BATCH-074",
        "Display batch record BATCH-098",
        "Give me info on batch BATCH-021",
        "Open batch BATCH-191",
        "BER BER--6180633F status",
        "Display batch record BATCH-072",
        "What is the yield for batch BATCH-173?",
        "Show me the batch record for BATCH-056",
        "BER BER--928111F0 status",
        "Batch BATCH-120 quality data",
        "How is batch BATCH-070 doing?",
        "What is the status of BER BER-3A335864?",
        "BER BER--78D84DAD status",
        "How is batch BATCH-169 doing?",
        "What is the status of batch BATCH-120?",
        "What is the status of batch BATCH-019?",
        "Deviations for batch BATCH-020",
        "Execution record BER--569B9422",
        "Batch BATCH-045 details",
        "Display batch record BATCH-014",
        "Status of production batch BATCH-196",
        "Open batch BATCH-126",
        "Get batch record for BATCH-179",
        "BER BER-3AB9E94D status",
        "Open batch BATCH-019",
        "Fetch batch details for BATCH-101",
        "Get batch record for BATCH-151",
        "Show yield for BATCH-182",
        "Tell me about batch BATCH-109",
        "Display batch record BATCH-017",
    ],
}
