"""Intent examples: batch_record (part 7/7)."""

from __future__ import annotations

EXAMPLES: dict[str, list[str]] = {
    "batch_record": [
        "Execution record BER--41B1B475",
        "How is batch BATCH-115 doing?",
        "Batch BATCH-038 summary",
        "What is the status of BER BER--7D43413E?",
        "Batch BATCH-052 summary",
        "Open batch BATCH-199",
        "Execution record BER-AFA53C7A",
        "Batch BATCH-184 quality data",
        "Batch BATCH-045 summary",
        "Status of production batch BATCH-028",
        "Batch BATCH-043 quality data",
        "Display batch record BATCH-152",
        "Fetch batch details for BATCH-145",
        "Batch BATCH-060 quality data",
        "Batch BATCH-065 details",
        "Get batch record for BATCH-166",
        "Get batch record for BATCH-200",
        "Give me info on batch BATCH-121",
        "Tell me about batch BATCH-058",
        "Batch BATCH-027 summary",
        "Open batch BATCH-017",
        "Get batch record for BATCH-088",
        "Get batch record for BATCH-017",
        "Display batch record BATCH-029",
        "Show me the batch record for BATCH-028",
        "What happened to batch BATCH-140?",
        "What is the status of batch BATCH-037?",
        "How is batch BATCH-057 doing?",
        "Status of production batch BATCH-119",
        "Give me info on batch BATCH-155",
        "Display batch record BATCH-001",
        "Batch BATCH-171 details",
        "What is the yield for batch BATCH-010?",
        "View batch BATCH-044",
        "How is batch BATCH-143 doing?",
        "What happened to batch BATCH-064?",
        "What is the status of BER BER--42AF6F4B?",
        "Execution record BER-67573D58",
        "Open batch BATCH-162",
        "Get batch record for BATCH-067",
        "What is the status of BER BER--7F4A75AF?",
        "Get batch record for BATCH-013",
        "Show yield for BATCH-124",
        "What is the yield for batch BATCH-026?",
        "Status of production batch BATCH-172",
        "What is the status of batch BATCH-058?",
        "Get batch record for BATCH-008",
        "Show batch BATCH-116",
        "How is batch BATCH-033 doing?",
        "What is the yield for batch BATCH-060?",
        "Batch BATCH-034 summary",
        "Show batch BATCH-087",
        "How is batch BATCH-092 doing?",
        "Execution record BER--28D14605",
        "BER BER--7D43413E status",
        "Show yield for BATCH-143",
        "Quality metrics for batch BATCH-127",
        "Show batch execution record BER--B6A8BD84",
        "Display batch record BATCH-125",
        "Tell me about batch BATCH-020",
        "BER BER--897EE0EC status",
        "Show batch BATCH-106",
        "Fetch batch details for BATCH-027",
        "What is the yield for batch BATCH-050?",
        "Batch BATCH-151 quality data",
        "Execution record BER--2A9601E0",
        "Give me info on batch BATCH-122",
        "What is the status of BER BER--11D7B0D4?",
        "Show batch execution record BER--A44C4A35",
        "Execution record BER--0A2EE388",
        "Batch BATCH-007 summary",
        "What is the yield for batch BATCH-020?",
        "What happened to batch BATCH-012?",
        "Execution record BER--51D67B67",
        "Display batch record BATCH-123",
        "Batch BATCH-084 quality data",
        "Show me the batch record for BATCH-054",
        "What is the yield for batch BATCH-008?",
        "How is batch BATCH-162 doing?",
        "What is the yield for batch BATCH-097?",
        "Deviations for batch BATCH-093",
        "What is the status of BER BER--1FF9DD82?",
        "BER BER--C7474D36 status",
        "Deviations for batch BATCH-029",
        "Batch BATCH-180 quality data",
        "Status of production batch BATCH-060",
        "What happened to batch BATCH-060?",
        "Batch BATCH-089 quality data",
        "How is batch BATCH-132 doing?",
        "Batch BATCH-180 summary",
        "Show yield for BATCH-162",
        "Show batch BATCH-173",
        "How is batch BATCH-123 doing?",
        "How is batch BATCH-012 doing?",
        "Show batch execution record BER-F304869A",
        "Get batch record for BATCH-045",
        "What happened to batch BATCH-172?",
        "Give me info on batch BATCH-182",
        "Show batch execution record BER--0A5DA1E7",
        "Show yield for BATCH-104",
        "Show yield for BATCH-171",
        "Batch BATCH-074 quality data",
        "Quality metrics for batch BATCH-088",
        "What is the status of batch BATCH-102?",
        "What is the yield for batch BATCH-134?",
        "Batch BATCH-064 details",
        "Show yield for BATCH-073",
        "Quality metrics for batch BATCH-168",
        "Get batch record for BATCH-024",
        "What is the yield for batch BATCH-103?",
        "What happened to batch BATCH-187?",
        "Show batch BATCH-018",
        "Show batch BATCH-021",
        "Tell me about batch BATCH-055",
        "Show me the batch record for BATCH-009",
        "Show yield for BATCH-017",
        "What is the yield for batch BATCH-009?",
        "Batch BATCH-016 quality data",
        "View batch BATCH-022",
        "Give me info on batch BATCH-151",
        "Display batch record BATCH-171",
        "View batch BATCH-136",
        "Show yield for BATCH-158",
        "Batch BATCH-010 summary",
        "Batch BATCH-115 quality data",
        "Open batch BATCH-053",
        "Batch BATCH-126 details",
        "BER BER--B7B46DA1 status",
        "Show me the batch record for BATCH-063",
        "Display batch record BATCH-164",
        "Batch BATCH-032 summary",
        "Batch BATCH-071 details",
        "Deviations for batch BATCH-048",
        "Tell me about batch BATCH-081",
        "Show batch execution record BER--C3E318E1",
        "Give me info on batch BATCH-173",
        "Batch BATCH-046 details",
        "Deviations for batch BATCH-041",
        "Show batch BATCH-199",
        "Show batch BATCH-162",
        "What is the status of batch BATCH-156?",
        "View batch BATCH-150",
        "What is the status of batch BATCH-060?",
        "BER BER--BE85AE70 status",
        "Open batch BATCH-165",
        "How is batch BATCH-004 doing?",
        "Give me info on batch BATCH-139",
        "What is the status of BER BER--16F6187F?",
        "What is the status of BER BER--8B5EE8FD?",
        "Fetch batch details for BATCH-031",
        "Status of production batch BATCH-162",
        "Show yield for BATCH-021",
        "Show yield for BATCH-047",
        "What is the status of BER BER-B35DC807?",
        "Show batch execution record BER-F109D264",
        "Show me the batch record for BATCH-017",
        "Show yield for BATCH-115",
        "What is the status of batch BATCH-180?",
        "Quality metrics for batch BATCH-149",
        "Show yield for BATCH-183",
        "Show yield for BATCH-045",
        "What is the status of BER BER--E14789A4?",
        "Fetch batch details for BATCH-095",
        "Give me info on batch BATCH-020",
        "What is the status of BER BER--B7E91E10?",
        "Show batch execution record BER-3E9C8187",
        "Batch BATCH-039 details",
        "Fetch batch details for BATCH-072",
        "Get batch record for BATCH-064",
        "Batch BATCH-113 summary",
        "Batch BATCH-196 summary",
        "Get batch record for BATCH-007",
        "What happened to batch BATCH-132?",
        "How is batch BATCH-141 doing?",
        "Show batch execution record BER--BE85AE70",
        "How is batch BATCH-193 doing?",
        "Show yield for BATCH-134",
        "What is the status of batch BATCH-106?",
        "View batch BATCH-017",
        "Status of production batch BATCH-008",
        "Status of production batch BATCH-168",
        "What is the yield for batch BATCH-043?",
        "Open batch BATCH-060",
        "Deviations for batch BATCH-116",
        "Batch BATCH-098 summary",
        "BER BER--BCDB47E8 status",
        "Show batch BATCH-127",
        "What is the status of BER BER--A7B8D1C6?",
        "Show batch BATCH-104",
        "Open batch BATCH-082",
        "Give me info on batch BATCH-054",
        "Batch BATCH-117 details",
        "BER BER--704D1C97 status",
        "Quality metrics for batch BATCH-020",
        "Batch BATCH-036 details",
        "Quality metrics for batch BATCH-082",
        "Tell me about batch BATCH-018",
        "Deviations for batch BATCH-091",
        "Batch BATCH-017 details",
        "Batch BATCH-135 summary",
        "Fetch batch details for BATCH-175",
        "View batch BATCH-134",
        "Get batch record for BATCH-006",
        "Show batch execution record BER--4A62D117",
        "Open batch BATCH-065",
        "Display batch record BATCH-170",
        "Batch BATCH-090 quality data",
        "Quality metrics for batch BATCH-151",
        "Execution record BER-D893B10A",
        "Show me the batch record for BATCH-131",
        "Batch BATCH-064 summary",
        "Show batch BATCH-169",
        "Get batch record for BATCH-034",
        "How is batch BATCH-178 doing?",
        "View batch BATCH-074",
        "Display batch record BATCH-184",
        "What is the status of BER BER--4BC133F6?",
        "What happened to batch BATCH-069?",
        "BER BER--29CF6B4A status",
        "Give me info on batch BATCH-083",
        "Batch BATCH-163 quality data",
        "BER BER--2F0540F8 status",
        "BER BER--CFF34E79 status",
        "Quality metrics for batch BATCH-041",
        "Quality metrics for batch BATCH-153",
        "Batch BATCH-113 details",
        "Give me info on batch BATCH-152",
        "Show batch BATCH-179",
        "Get batch record for BATCH-026",
        "Show me the batch record for BATCH-008",
        "Show yield for BATCH-093",
        "Quality metrics for batch BATCH-123",
        "Status of production batch BATCH-022",
        "Show me the batch record for BATCH-052",
        "View batch BATCH-173",
        "Open batch BATCH-062",
        "What is the yield for batch BATCH-184?",
        "Quality metrics for batch BATCH-131",
        "Batch BATCH-193 details",
        "How is batch BATCH-103 doing?",
        "Status of production batch BATCH-094",
        "Execution record BER--EA1C0105",
        "Deviations for batch BATCH-017",
        "How is batch BATCH-198 doing?",
        "Execution record BER--D16498DD",
        "Get batch record for BATCH-015",
        "What is the status of BER BER--F70E78AA?",
        "Get batch record for BATCH-041",
        "What is the yield for batch BATCH-195?",
        "Show batch execution record BER--9B07FA21",
        "How is batch BATCH-166 doing?",
        "Display batch record BATCH-149",
        "What is the yield for batch BATCH-040?",
        "What is the status of BER BER--BEA5733C?",
        "Show yield for BATCH-138",
        "Get batch record for BATCH-140",
        "Display batch record BATCH-079",
        "Fetch batch details for BATCH-039",
        "What is the status of batch BATCH-078?",
        "Display batch record BATCH-193",
        "Quality metrics for batch BATCH-040",
        "Display batch record BATCH-121",
        "Get batch record for BATCH-104",
        "What is the status of batch BATCH-108?",
        "How is batch BATCH-173 doing?",
        "Execution record BER--704D1C97",
        "Give me info on batch BATCH-193",
        "Execution record BER--1C8F5C98",
        "BER BER--7005E1C3 status",
        "What happened to batch BATCH-073?",
        "What is the yield for batch BATCH-129?",
        "Quality metrics for batch BATCH-139",
        "Show me the batch record for BATCH-042",
        "Tell me about batch BATCH-060",
        "Show yield for BATCH-197",
        "Execution record BER-9B56D46F",
        "Show batch execution record BER--D9646D23",
        "Batch BATCH-002 summary",
        "BER BER--CB57ED02 status",
        "What is the status of batch BATCH-150?",
        "Fetch batch details for BATCH-092",
        "Deviations for batch BATCH-118",
        "Quality metrics for batch BATCH-107",
        "What is the status of BER BER--5CCADE57?",
        "Batch BATCH-161 details",
        "Tell me about batch BATCH-183",
        "Fetch batch details for BATCH-049",
        "How is batch BATCH-181 doing?",
        "Quality metrics for batch BATCH-067",
        "Batch BATCH-044 details",
        "Deviations for batch BATCH-164",
        "Show yield for BATCH-072",
        "Open batch BATCH-147",
        "Get batch record for BATCH-131",
        "BER BER--04319A40 status",
        "Batch BATCH-021 quality data",
        "How is batch BATCH-050 doing?",
        "View batch BATCH-159",
        "BER BER--EE600F23 status",
        "Deviations for batch BATCH-100",
        "Show me the batch record for BATCH-032",
        "Quality metrics for batch BATCH-120",
        "Show batch BATCH-153",
        "Give me info on batch BATCH-056",
        "Batch BATCH-151 details",
        "Batch BATCH-137 details",
        "Show batch execution record BER--8E057539",
        "Open batch BATCH-014",
        "Show me the batch record for BATCH-006",
        "Open batch BATCH-103",
        "View batch BATCH-189",
        "Display batch record BATCH-151",
        "Show yield for BATCH-024",
        "Batch BATCH-152 details",
        "Get batch record for BATCH-070",
        "View batch BATCH-087",
        "Show yield for BATCH-155",
        "What is the status of batch BATCH-119?",
        "What is the yield for batch BATCH-163?",
        "Batch BATCH-128 details",
        "Show yield for BATCH-123",
        "View batch BATCH-123",
        "Batch BATCH-047 quality data",
        "Tell me about batch BATCH-142",
        "Deviations for batch BATCH-086",
        "Display batch record BATCH-019",
        "Tell me about batch BATCH-001",
        "Quality metrics for batch BATCH-185",
        "What is the yield for batch BATCH-145?",
        "Show me the batch record for BATCH-068",
        "View batch BATCH-192",
        "Quality metrics for batch BATCH-083",
        "What is the status of batch BATCH-171?",
        "Quality metrics for batch BATCH-078",
        "What is the status of BER BER--8FD9113C?",
        "What happened to batch BATCH-056?",
        "Batch BATCH-134 summary",
        "Show me the batch record for BATCH-172",
        "Show yield for BATCH-091",
        "View batch BATCH-128",
        "Fetch batch details for BATCH-023",
        "View batch BATCH-011",
        "BER BER--E14789A4 status",
        "What happened to batch BATCH-192?",
        "Quality metrics for batch BATCH-051",
        "What is the yield for batch BATCH-098?",
        "Display batch record BATCH-200",
        "Tell me about batch BATCH-040",
        "What is the yield for batch BATCH-189?",
        "Batch BATCH-198 quality data",
        "How is batch BATCH-119 doing?",
        "Tell me about batch BATCH-036",
        "What is the status of batch BATCH-200?",
        "Deviations for batch BATCH-025",
        "Show me the batch record for BATCH-094",
        "How is batch BATCH-136 doing?",
        "How is batch BATCH-121 doing?",
        "What happened to batch BATCH-092?",
        "Get batch record for BATCH-065",
        "Get batch record for BATCH-090",
        "Show yield for BATCH-136",
        "Quality metrics for batch BATCH-166",
        "Batch BATCH-075 details",
        "Batch BATCH-011 quality data",
        "Show batch BATCH-051",
        "Batch BATCH-165 quality data",
        "What is the status of batch BATCH-131?",
        "View batch BATCH-182",
        "Show batch execution record BER--704D1C97",
        "Show me the batch record for BATCH-145",
        "Tell me about batch BATCH-170",
        "BER BER-E3246AC9 status",
        "Batch BATCH-187 quality data",
        "Give me info on batch BATCH-010",
        "Fetch batch details for BATCH-073",
        "Open batch BATCH-070",
        "Display batch record BATCH-122",
        "Show yield for BATCH-083",
        "Quality metrics for batch BATCH-035",
        "What is the status of batch BATCH-142?",
        "Batch BATCH-083 details",
        "Execution record BER--4A62D117",
        "Get batch record for BATCH-108",
        "Deviations for batch BATCH-133",
        "Deviations for batch BATCH-173",
        "Quality metrics for batch BATCH-157",
        "What is the status of BER BER--33C1297F?",
        "Batch BATCH-200 details",
        "View batch BATCH-095",
        "Batch BATCH-128 quality data",
        "Batch BATCH-173 summary",
        "Execution record BER--78091C53",
        "Fetch batch details for BATCH-180",
        "What happened to batch BATCH-183?",
        "Give me info on batch BATCH-069",
        "Batch BATCH-064 quality data",
        "Fetch batch details for BATCH-166",
        "Give me info on batch BATCH-064",
        "Execution record BER--A464BB15",
        "Status of production batch BATCH-021",
        "Status of production batch BATCH-128",
        "BER BER--B5CF9B89 status",
        "Give me info on batch BATCH-081",
        "Batch BATCH-053 quality data",
        "What happened to batch BATCH-087?",
        "Show batch execution record BER--AE3C9DC3",
        "Show me the batch record for BATCH-127",
        "How is batch BATCH-082 doing?",
        "Batch BATCH-123 summary",
        "Show batch BATCH-176",
        "Show me the batch record for BATCH-148",
        "What is the yield for batch BATCH-062?",
        "Show yield for BATCH-153",
        "Batch BATCH-020 details",
        "Show batch BATCH-030",
        "What is the status of batch BATCH-107?",
        "BER BER--4339276D status",
        "Open batch BATCH-035",
        "Show yield for BATCH-112",
        "Display batch record BATCH-038",
        "Batch BATCH-184 summary",
        "Open batch BATCH-077",
        "What is the yield for batch BATCH-172?",
        "Show batch execution record BER--EEA53DA3",
        "Open batch BATCH-146",
        "Quality metrics for batch BATCH-091",
        "Open batch BATCH-158",
        "Get batch record for BATCH-068",
        "Batch BATCH-080 details",
        "Batch BATCH-030 quality data",
        "What happened to batch BATCH-048?",
        "Status of production batch BATCH-089",
        "What is the status of batch BATCH-179?",
        "Show me the batch record for BATCH-175",
        "Open batch BATCH-096",
        "Show me the batch record for BATCH-151",
        "Show me the batch record for BATCH-023",
        "What is the status of BER BER--7E444145?",
        "Show batch execution record BER--EA1C0105",
        "Quality metrics for batch BATCH-133",
        "Batch BATCH-058 quality data",
        "Fetch batch details for BATCH-111",
        "Tell me about batch BATCH-054",
        "Show me the batch record for BATCH-132",
        "What is the yield for batch BATCH-135?",
        "Quality metrics for batch BATCH-087",
        "Deviations for batch BATCH-169",
        "What is the status of batch BATCH-094?",
        "What happened to batch BATCH-131?",
        "Status of production batch BATCH-134",
        "Fetch batch details for BATCH-053",
        "Status of production batch BATCH-169",
        "Show batch execution record BER--2F388213",
        "Show yield for BATCH-033",
        "Show me the batch record for BATCH-018",
        "View batch BATCH-020",
        "Status of production batch BATCH-032",
        "BER BER--6C9AD244 status",
        "How is batch BATCH-036 doing?",
        "Show yield for BATCH-105",
        "Display batch record BATCH-085",
        "Deviations for batch BATCH-195",
        "Get batch record for BATCH-043",
        "What is the status of batch BATCH-161?",
        "Give me info on batch BATCH-119",
        "Display batch record BATCH-028",
        "Tell me about batch BATCH-157",
        "Batch BATCH-070 details",
        "Quality metrics for batch BATCH-039",
        "Show yield for BATCH-180",
        "Fetch batch details for BATCH-030",
        "What is the status of batch BATCH-165?",
        "What is the status of batch BATCH-059?",
        "Tell me about batch BATCH-048",
        "Open batch BATCH-138",
        "Display batch record BATCH-027",
        "Quality metrics for batch BATCH-118",
        "What is the status of batch BATCH-141?",
        "Status of production batch BATCH-039",
        "What is the status of BER BER-0B19CB30?",
        "Open batch BATCH-192",
    ],
}
