"""Intent examples: batch_record (part 4/7)."""

from __future__ import annotations

EXAMPLES: dict[str, list[str]] = {
    "batch_record": [
        "Deviations for batch BATCH-078",
        "Batch BATCH-191 details",
        "Tell me about batch BATCH-111",
        "What happened to batch BATCH-146?",
        "What happened to batch BATCH-113?",
        "Batch BATCH-171 summary",
        "View batch BATCH-104",
        "Batch BATCH-184 details",
        "Quality metrics for batch BATCH-074",
        "What is the status of batch BATCH-101?",
        "Quality metrics for batch BATCH-098",
        "Execution record BER--BE85AE70",
        "Tell me about batch BATCH-161",
        "Tell me about batch BATCH-099",
        "Execution record BER--009D541A",
        "What happened to batch BATCH-094?",
        "What is the status of BER BER--3AFF2B51?",
        "Show me the batch record for BATCH-196",
        "Quality metrics for batch BATCH-186",
        "Quality metrics for batch BATCH-037",
        "What is the status of BER BER--C763176D?",
        "What happened to batch BATCH-104?",
        "What is the yield for batch BATCH-025?",
        "Quality metrics for batch BATCH-071",
        "How is batch BATCH-017 doing?",
        "Quality metrics for batch BATCH-163",
        "Show yield for BATCH-032",
        "What is the status of BER BER--51356C61?",
        "Show me the batch record for BATCH-160",
        "Give me info on batch BATCH-107",
        "Execution record BER-6D61D8D5",
        "BER BER-E3B78D7A status",
        "Open batch BATCH-063",
        "How is batch BATCH-180 doing?",
        "Open batch BATCH-041",
        "Give me info on batch BATCH-117",
        "Show batch BATCH-062",
        "Give me info on batch BATCH-136",
        "BER BER--05BAE4AA status",
        "BER BER--F70E78AA status",
        "View batch BATCH-168",
        "Tell me about batch BATCH-139",
        "Get batch record for BATCH-082",
        "Open batch BATCH-119",
        "Show yield for BATCH-056",
        "Fetch batch details for BATCH-112",
        "Batch BATCH-020 quality data",
        "BER BER-F109D264 status",
        "Status of production batch BATCH-002",
        "Execution record BER--CC43C94C",
        "Display batch record BATCH-035",
        "Quality metrics for batch BATCH-146",
        "Status of production batch BATCH-176",
        "Status of production batch BATCH-064",
        "What is the status of BER BER--CFF34E79?",
        "Batch BATCH-032 quality data",
        "Batch BATCH-129 details",
        "Deviations for batch BATCH-112",
        "What happened to batch BATCH-126?",
        "Status of production batch BATCH-010",
        "Show batch execution record BER--41B1B475",
        "Tell me about batch BATCH-136",
        "BER BER--78091C53 status",
        "What is the yield for batch BATCH-115?",
        "Execution record BER--12DC03A0",
        "Show batch BATCH-009",
        "Show yield for BATCH-061",
        "Batch BATCH-013 details",
        "View batch BATCH-183",
        "What is the status of batch BATCH-195?",
        "Batch BATCH-117 quality data",
        "Batch BATCH-121 details",
        "What is the status of batch BATCH-065?",
        "Batch BATCH-124 summary",
        "Open batch BATCH-183",
        "Execution record BER--22F5F0A9",
        "Get batch record for BATCH-169",
        "Batch BATCH-042 quality data",
        "Batch BATCH-108 details",
        "Batch BATCH-086 details",
        "Get batch record for BATCH-162",
        "BER BER--768A0997 status",
        "Display batch record BATCH-089",
        "Get batch record for BATCH-055",
        "Execution record BER--EFFD385B",
        "Quality metrics for batch BATCH-044",
        "What is the yield for batch BATCH-128?",
        "Quality metrics for batch BATCH-021",
        "Batch BATCH-122 details",
        "Give me info on batch BATCH-125",
        "Tell me about batch BATCH-012",
        "Fetch batch details for BATCH-102",
        "How is batch BATCH-107 doing?",
        "Status of production batch BATCH-026",
        "Quality metrics for batch BATCH-196",
        "Get batch record for BATCH-110",
        "Show batch BATCH-168",
        "What is the yield for batch BATCH-006?",
        "Status of production batch BATCH-175",
        "Show batch execution record BER-0B19CB30",
        "Show me the batch record for BATCH-073",
        "Display batch record BATCH-139",
        "How is batch BATCH-122 doing?",
        "View batch BATCH-174",
        "What is the status of BER BER--80B6E7C1?",
        "How is batch BATCH-013 doing?",
        "What happened to batch BATCH-062?",
        "Show yield for BATCH-040",
        "What is the status of batch BATCH-172?",
        "BER BER--C763176D status",
        "Status of production batch BATCH-167",
        "Display batch record BATCH-148",
        "Deviations for batch BATCH-122",
        "Give me info on batch BATCH-116",
        "Fetch batch details for BATCH-197",
        "Show me the batch record for BATCH-179",
        "Open batch BATCH-004",
        "Open batch BATCH-054",
        "Batch BATCH-021 details",
        "View batch BATCH-100",
        "What happened to batch BATCH-200?",
        "Batch BATCH-178 summary",
        "What is the yield for batch BATCH-200?",
        "How is batch BATCH-026 doing?",
        "Show yield for BATCH-135",
        "Deviations for batch BATCH-001",
        "What happened to batch BATCH-068?",
        "Show yield for BATCH-016",
        "Get batch record for BATCH-097",
        "Open batch BATCH-175",
        "Show batch BATCH-158",
        "Tell me about batch BATCH-123",
        "What happened to batch BATCH-059?",
        "Fetch batch details for BATCH-167",
        "Deviations for batch BATCH-109",
        "Deviations for batch BATCH-046",
        "Show batch BATCH-117",
        "Get batch record for BATCH-165",
        "Open batch BATCH-168",
        "Batch BATCH-033 details",
        "Get batch record for BATCH-009",
        "Execution record BER-5B293B91",
        "Show batch BATCH-129",
        "Quality metrics for batch BATCH-006",
        "Status of production batch BATCH-037",
        "Fetch batch details for BATCH-050",
        "BER BER-D893B10A status",
        "Get batch record for BATCH-078",
        "How is batch BATCH-079 doing?",
        "What is the yield for batch BATCH-080?",
        "Display batch record BATCH-008",
        "What is the yield for batch BATCH-012?",
        "Get batch record for BATCH-063",
        "Status of production batch BATCH-112",
        "Tell me about batch BATCH-089",
        "Status of production batch BATCH-016",
        "Show batch execution record BER--A8713022",
        "What is the status of batch BATCH-124?",
        "Open batch BATCH-023",
        "Execution record BER-7755A8F1",
        "Batch BATCH-091 details",
        "Fetch batch details for BATCH-058",
        "View batch BATCH-114",
        "Fetch batch details for BATCH-155",
        "What is the status of BER BER--7005E1C3?",
        "Display batch record BATCH-041",
        "What happened to batch BATCH-057?",
        "Get batch record for BATCH-120",
        "Status of production batch BATCH-046",
        "What is the status of batch BATCH-050?",
        "Execution record BER--4D0846AC",
        "Show yield for BATCH-167",
        "What is the status of BER BER--3A88D9AF?",
        "BER BER--0A5DA1E7 status",
        "Execution record BER--5CCADE57",
        "Tell me about batch BATCH-034",
        "Open batch BATCH-122",
        "Batch BATCH-041 quality data",
        "How is batch BATCH-144 doing?",
        "Batch BATCH-179 details",
        "Batch BATCH-005 details",
        "Show batch BATCH-102",
        "Get batch record for BATCH-072",
        "Deviations for batch BATCH-019",
        "Fetch batch details for BATCH-016",
        "What is the status of BER BER--7604E670?",
        "Deviations for batch BATCH-006",
        "BER BER--47133F71 status",
        "Open batch BATCH-107",
        "Show batch execution record BER-6D61D8D5",
        "Open batch BATCH-046",
        "Show yield for BATCH-189",
        "What is the yield for batch BATCH-188?",
        "Open batch BATCH-184",
        "Get batch record for BATCH-062",
        "Give me info on batch BATCH-024",
        "Show batch execution record BER--8B2328B5",
        "How is batch BATCH-020 doing?",
        "What is the status of BER BER--05BAE4AA?",
        "Status of production batch BATCH-141",
        "Display batch record BATCH-080",
        "What is the yield for batch BATCH-132?",
        "Show me the batch record for BATCH-099",
        "Display batch record BATCH-188",
        "Quality metrics for batch BATCH-085",
        "What is the status of batch BATCH-003?",
        "Show batch execution record BER-5D728E09",
        "BER BER--7604E670 status",
        "Deviations for batch BATCH-134",
        "Get batch record for BATCH-056",
        "What is the status of batch BATCH-151?",
        "What is the status of batch BATCH-015?",
        "Execution record BER--770B452F",
        "Show batch execution record BER--16F6187F",
        "Fetch batch details for BATCH-064",
        "How is batch BATCH-048 doing?",
        "Show me the batch record for BATCH-100",
        "Display batch record BATCH-091",
        "Show me the batch record for BATCH-097",
        "Batch BATCH-186 summary",
        "Open batch BATCH-097",
        "Give me info on batch BATCH-018",
        "Get batch record for BATCH-047",
        "Tell me about batch BATCH-175",
        "Show me the batch record for BATCH-126",
        "What is the status of batch BATCH-025?",
        "Give me info on batch BATCH-025",
        "What is the status of batch BATCH-137?",
        "Open batch BATCH-069",
        "Get batch record for BATCH-087",
        "What is the yield for batch BATCH-030?",
        "Tell me about batch BATCH-104",
        "Quality metrics for batch BATCH-128",
        "How is batch BATCH-053 doing?",
        "Open batch BATCH-005",
        "Batch BATCH-098 quality data",
        "Deviations for batch BATCH-085",
        "What happened to batch BATCH-191?",
        "BER BER--543A6B39 status",
        "What happened to batch BATCH-150?",
        "BER BER--9605D93B status",
        "Batch BATCH-083 quality data",
        "Deviations for batch BATCH-096",
        "Show me the batch record for BATCH-163",
        "Tell me about batch BATCH-126",
        "What is the status of batch BATCH-046?",
        "What happened to batch BATCH-179?",
        "Show batch BATCH-122",
        "Batch BATCH-054 details",
        "Fetch batch details for BATCH-060",
        "BER BER--8B2328B5 status",
        "What is the yield for batch BATCH-082?",
        "Batch BATCH-052 details",
        "What is the status of BER BER--F0693564?",
        "Quality metrics for batch BATCH-189",
        "Show batch BATCH-190",
        "Fetch batch details for BATCH-192",
        "View batch BATCH-125",
        "Show batch BATCH-138",
        "View batch BATCH-036",
        "Tell me about batch BATCH-132",
        "Show yield for BATCH-095",
        "Show me the batch record for BATCH-045",
        "Quality metrics for batch BATCH-014",
        "What is the yield for batch BATCH-078?",
        "Show batch BATCH-002",
        "View batch BATCH-180",
        "Batch BATCH-124 quality data",
        "Fetch batch details for BATCH-019",
        "Batch BATCH-109 quality data",
        "BER BER-67573D58 status",
        "Show batch BATCH-142",
        "Show me the batch record for BATCH-061",
        "Status of production batch BATCH-084",
        "BER BER--9C669C9D status",
        "Give me info on batch BATCH-164",
        "What is the status of batch BATCH-127?",
        "Tell me about batch BATCH-094",
        "What is the yield for batch BATCH-084?",
        "What is the yield for batch BATCH-044?",
        "Deviations for batch BATCH-015",
        "What is the status of batch BATCH-068?",
        "What is the status of batch BATCH-152?",
        "Show batch BATCH-063",
        "What is the status of batch BATCH-188?",
        "Fetch batch details for BATCH-124",
        "Batch BATCH-016 summary",
        "Batch BATCH-177 summary",
        "How is batch BATCH-094 doing?",
        "Batch BATCH-088 details",
        "Show yield for BATCH-142",
        "Give me info on batch BATCH-154",
        "Batch BATCH-147 quality data",
        "Batch BATCH-019 details",
        "Show me the batch record for BATCH-016",
        "Batch BATCH-175 details",
        "Batch BATCH-196 details",
        "What is the status of batch BATCH-005?",
        "Give me info on batch BATCH-049",
        "Quality metrics for batch BATCH-031",
        "Display batch record BATCH-124",
        "View batch BATCH-070",
        "Deviations for batch BATCH-106",
        "How is batch BATCH-006 doing?",
        "Show batch execution record BER--3AFF2B51",
        "Deviations for batch BATCH-172",
        "What batches are in production?",
        "Deviations for batch BATCH-002",
        "View batch BATCH-016",
        "Deviations for batch BATCH-145",
        "What happened to batch BATCH-167?",
        "Batch BATCH-080 summary",
        "What happened to batch BATCH-157?",
        "View batch BATCH-046",
        "Display batch record BATCH-106",
        "Deviations for batch BATCH-180",
        "Quality metrics for batch BATCH-140",
        "Show me the batch record for BATCH-119",
        "Execution record BER--7F4A75AF",
        "What is the status of batch BATCH-053?",
        "Open batch BATCH-074",
        "Tell me about batch BATCH-009",
        "Show batch execution record BER-BD364549",
        "What is the yield for batch BATCH-013?",
        "Open batch BATCH-110",
        "Batch BATCH-007 quality data",
        "Deviations for batch BATCH-031",
        "Show batch execution record BER--A9A27280",
        "Batch BATCH-186 details",
        "Show me the batch record for BATCH-048",
        "What is the status of BER BER--5222804E?",
        "Display batch record BATCH-145",
        "Show me the batch record for BATCH-083",
        "Batch BATCH-183 quality data",
        "Show batch execution record BER--E2A75EC8",
        "What is the status of BER BER-B4705A0F?",
        "Show me the batch record for BATCH-096",
        "Execution record BER--897EE0EC",
        "Status of production batch BATCH-118",
        "How is batch BATCH-030 doing?",
        "Show batch execution record BER--CFF34E79",
        "Batch BATCH-176 details",
        "BER BER-1A1B5A36 status",
        "Display batch record BATCH-177",
        "What happened to batch BATCH-164?",
        "Show yield for BATCH-043",
        "BER BER--4D0846AC status",
        "What is the status of BER BER--6C9AD244?",
        "Deviations for batch BATCH-179",
        "Give me info on batch BATCH-051",
        "BER BER--7E7F46C6 status",
        "View batch BATCH-056",
        "What is the status of batch BATCH-112?",
        "Batch BATCH-156 quality data",
        "Show batch execution record BER--51356C61",
        "Deviations for batch BATCH-079",
        "Batch BATCH-019 quality data",
        "What is the status of batch BATCH-193?",
        "Fetch batch details for BATCH-033",
        "What is the yield for batch BATCH-031?",
        "BER BER--41B1B475 status",
        "Status of production batch BATCH-135",
        "View batch BATCH-023",
        "What happened to batch BATCH-083?",
        "Batch BATCH-049 quality data",
        "Tell me about batch BATCH-061",
        "Show batch execution record BER--F81835A3",
        "Tell me about batch BATCH-093",
        "View batch BATCH-160",
        "Show batch execution record BER--1454F070",
        "Display batch record BATCH-094",
        "Display batch record BATCH-012",
        "Show me the batch record for BATCH-107",
        "What is the yield for batch BATCH-005?",
        "Tell me about batch BATCH-200",
        "BER BER--A44C4A35 status",
        "Display batch record BATCH-087",
        "How is batch BATCH-065 doing?",
        "What is the yield for batch BATCH-061?",
        "Fetch batch details for BATCH-138",
        "Show batch execution record BER--8CB20167",
        "BER BER--FC981C1C status",
        "Execution record BER--51356C61",
        "Deviations for batch BATCH-088",
        "Status of production batch BATCH-017",
        "Display batch record BATCH-117",
        "Show me the batch record for BATCH-168",
        "View batch BATCH-073",
        "Show batch execution record BER--17D37A69",
        "Batch BATCH-135 details",
        "Show batch BATCH-193",
        "Show batch execution record BER--B7B46DA1",
        "Show yield for BATCH-013",
        "Batch BATCH-150 details",
        "Display batch record BATCH-040",
        "Status of production batch BATCH-056",
        "What happened to batch BATCH-180?",
        "View batch BATCH-088",
        "Status of production batch BATCH-035",
        "Execution record BER--80B6E7C1",
        "What is the status of batch BATCH-028?",
        "Status of production batch BATCH-051",
        "Status of production batch BATCH-148",
        "Show batch execution record BER--8CE73799",
        "Quality metrics for batch BATCH-079",
        "Give me info on batch BATCH-079",
        "What is the status of batch BATCH-061?",
        "Batch BATCH-104 summary",
        "Batch BATCH-103 details",
        "Execution record BER--8B2328B5",
        "Display batch record BATCH-058",
        "Batch BATCH-084 details",
        "Batch BATCH-086 quality data",
        "What is the status of batch BATCH-166?",
        "What is the status of batch BATCH-076?",
        "Get batch record for BATCH-033",
        "Batch BATCH-149 quality data",
        "Give me info on batch BATCH-072",
        "Show me the batch record for BATCH-086",
        "Get batch record for BATCH-161",
        "Give me info on batch BATCH-120",
        "Show batch execution record BER-B35DC807",
        "What is the status of BER BER--9B07FA21?",
        "Display batch record BATCH-147",
        "Tell me about batch BATCH-133",
        "What is the yield for batch BATCH-076?",
        "Show batch execution record BER--9EB710B7",
        "Show batch BATCH-006",
        "Open batch BATCH-142",
        "Batch BATCH-033 summary",
        "Deviations for batch BATCH-068",
        "Show batch execution record BER--15458759",
        "Open batch BATCH-144",
        "What happened to batch BATCH-142?",
        "View batch BATCH-086",
        "Show batch BATCH-003",
        "Show batch BATCH-074",
        "Get batch record for BATCH-029",
        "Deviations for batch BATCH-183",
        "What is the yield for batch BATCH-157?",
        "What happened to batch BATCH-176?",
        "Show me the batch record for BATCH-141",
        "Open batch BATCH-185",
        "Deviations for batch BATCH-047",
        "Show me the batch record for BATCH-199",
        "Batch BATCH-035 summary",
        "Batch BATCH-141 summary",
        "What happened to batch BATCH-009?",
        "What is the yield for batch BATCH-090?",
        "How is batch BATCH-100 doing?",
        "Batch BATCH-050 details",
        "Display batch record BATCH-061",
        "Show batch execution record BER--4339276D",
        "What is the yield for batch BATCH-114?",
        "Quality metrics for batch BATCH-152",
        "Show yield for BATCH-028",
        "What is the status of batch BATCH-083?",
        "Execution record BER--B7E91E10",
        "Fetch batch details for BATCH-120",
        "View batch BATCH-031",
        "Show batch BATCH-017",
        "Execution record BER--6CE61952",
        "Quality metrics for batch BATCH-113",
        "Show batch BATCH-071",
        "BER BER--846D4BB4 status",
        "How is batch BATCH-176 doing?",
        "Quality metrics for batch BATCH-160",
        "Deviations for batch BATCH-137",
        "BER BER--B6A8BD84 status",
        "Fetch batch details for BATCH-108",
        "Get batch record for BATCH-083",
        "Give me info on batch BATCH-126",
        "What is the status of BER BER--B6A8BD84?",
        "How is batch BATCH-197 doing?",
        "Tell me about batch BATCH-064",
        "Show me the batch record for BATCH-019",
        "Deviations for batch BATCH-082",
        "How is batch BATCH-002 doing?",
        "Execution record BER--FDE1870B",
        "How is batch BATCH-069 doing?",
        "View batch BATCH-059",
        "Batch BATCH-031 summary",
        "Batch BATCH-037 quality data",
        "Batch BATCH-120 details",
    ],
}
