"""Intent examples: batch_record (part 3/7)."""

from __future__ import annotations

EXAMPLES: dict[str, list[str]] = {
    "batch_record": [
        "Show batch BATCH-124",
        "Batch BATCH-157 summary",
        "Execution record BER--BEA5733C",
        "Fetch batch details for BATCH-129",
        "Show batch execution record BER--8D87D8FF",
        "What is the status of batch BATCH-170?",
        "Tell me about batch BATCH-105",
        "Open batch BATCH-159",
        "Show me the batch record for BATCH-162",
        "Show me the batch record for BATCH-021",
        "What happened to batch BATCH-123?",
        "Fetch batch details for BATCH-075",
        "Open batch BATCH-059",
        "Execution record BER--7B315106",
        "Show me the batch record for BATCH-144",
        "Batch BATCH-093 quality data",
        "What is the status of batch BATCH-006?",
        "Quality metrics for batch BATCH-195",
        "Deviations for batch BATCH-102",
        "Batch BATCH-189 summary",
        "Display batch record BATCH-137",
        "Show yield for BATCH-076",
        "Show batch BATCH-028",
        "Show batch BATCH-192",
        "Quality metrics for batch BATCH-013",
        "Quality metrics for batch BATCH-130",
        "View batch BATCH-041",
        "Batch BATCH-094 details",
        "What is the status of batch BATCH-159?",
        "Tell me about batch BATCH-021",
        "What is the yield for batch BATCH-156?",
        "What is the status of BER BER--1B40FE38?",
        "How is batch BATCH-192 doing?",
        "What is the status of batch BATCH-038?",
        "Deviations for batch BATCH-004",
        "What is the status of BER BER--4D0846AC?",
        "Fetch batch details for BATCH-001",
        "View batch BATCH-117",
        "What is the yield for batch BATCH-045?",
        "Execution record BER--04319A40",
        "Show batch execution record BER--3A88D9AF",
        "Get batch record for BATCH-113",
        "Deviations for batch BATCH-069",
        "Show batch execution record BER--5CCADE57",
        "Show yield for BATCH-004",
        "Get batch record for BATCH-005",
        "Show me the batch record for BATCH-112",
        "Batch BATCH-014 summary",
        "What is the yield for batch BATCH-180?",
        "How is batch BATCH-078 doing?",
        "What happened to batch BATCH-138?",
        "Show yield for BATCH-090",
        "Batch BATCH-185 summary",
        "What is the status of batch BATCH-009?",
        "Fetch batch details for BATCH-070",
        "View batch BATCH-035",
        "Status of production batch BATCH-069",
        "Show batch BATCH-007",
        "BER BER--7E444145 status",
        "Display batch record BATCH-182",
        "Batch BATCH-190 details",
        "Show batch BATCH-098",
        "Execution record BER--AE3C9DC3",
        "Batch BATCH-068 summary",
        "What happened to batch BATCH-011?",
        "Deviations for batch BATCH-129",
        "Batch BATCH-050 quality data",
        "Batch BATCH-028 summary",
        "Fetch batch details for BATCH-152",
        "Get batch record for BATCH-137",
        "View batch BATCH-175",
        "What happened to batch BATCH-006?",
        "How is batch BATCH-106 doing?",
        "View batch BATCH-034",
        "Give me info on batch BATCH-112",
        "Show me the batch record for BATCH-186",
        "What is the status of batch BATCH-121?",
        "How is batch BATCH-045 doing?",
        "Show me the batch record for BATCH-046",
        "Execution record BER--C5864960",
        "Show batch execution record BER--22F5F0A9",
        "Deviations for batch BATCH-051",
        "Batch BATCH-143 quality data",
        "BER BER-314E5802 status",
        "Quality metrics for batch BATCH-086",
        "Show me the batch record for BATCH-029",
        "View batch BATCH-039",
        "Deviations for batch BATCH-182",
        "Deviations for batch BATCH-200",
        "What is the yield for batch BATCH-116?",
        "Deviations for batch BATCH-153",
        "BER BER--5DB5DDEA status",
        "Status of production batch BATCH-011",
        "Fetch batch details for BATCH-071",
        "List batches with status Under QA Review",
        "Give me info on batch BATCH-163",
        "Show batch execution record BER--2A9601E0",
        "Status of production batch BATCH-055",
        "Give me info on batch BATCH-124",
        "Batch BATCH-156 summary",
        "Display batch record BATCH-051",
        "Show batch BATCH-031",
        "Show batch BATCH-094",
        "What happened to batch BATCH-145?",
        "Status of production batch BATCH-197",
        "Execution record BER--5DB5DDEA",
        "Give me info on batch BATCH-045",
        "Get batch record for BATCH-073",
        "Get batch record for BATCH-180",
        "Show batch BATCH-036",
        "Show me the batch record for BATCH-198",
        "Batch BATCH-096 summary",
        "Give me info on batch BATCH-195",
        "Show yield for BATCH-067",
        "Open batch BATCH-172",
        "What happened to batch BATCH-122?",
        "Tell me about batch BATCH-041",
        "Display batch record BATCH-160",
        "Display batch record BATCH-052",
        "Batch BATCH-142 summary",
        "Batch BATCH-072 details",
        "Batch BATCH-001 quality data",
        "Fetch batch details for BATCH-130",
        "Batch BATCH-199 summary",
        "Batch BATCH-133 details",
        "What happened to batch BATCH-188?",
        "Display batch record BATCH-016",
        "Show me the batch record for BATCH-065",
        "Give me info on batch BATCH-030",
        "View batch BATCH-060",
        "Give me info on batch BATCH-003",
        "What happened to batch BATCH-024?",
        "Show batch BATCH-118",
        "What happened to batch BATCH-082?",
        "Show batch BATCH-170",
        "Batch BATCH-196 quality data",
        "Tell me about batch BATCH-113",
        "Show me the batch record for BATCH-069",
        "Display batch record BATCH-180",
        "What is the status of BER BER-3AB9E94D?",
        "Tell me about batch BATCH-015",
        "Execution record BER--4BC133F6",
        "Batch BATCH-177 details",
        "Batch BATCH-075 summary",
        "Show batch execution record BER--12DC03A0",
        "Show batch BATCH-136",
        "BER BER--0A2EE388 status",
        "Fetch batch details for BATCH-121",
        "What happened to batch BATCH-077?",
        "What is the yield for batch BATCH-041?",
        "Batch BATCH-167 quality data",
        "Open batch BATCH-114",
        "Display batch record BATCH-056",
        "Batch BATCH-095 quality data",
        "View batch BATCH-153",
        "What is the status of BER BER--8E057539?",
        "How is batch BATCH-182 doing?",
        "Batch BATCH-057 summary",
        "Open batch BATCH-166",
        "What happened to batch BATCH-061?",
        "What is the status of batch BATCH-079?",
        "Batch BATCH-168 details",
        "What happened to batch BATCH-098?",
        "How is batch BATCH-140 doing?",
        "Deviations for batch BATCH-005",
        "Status of production batch BATCH-066",
        "Show yield for BATCH-005",
        "View batch BATCH-055",
        "Display batch record BATCH-045",
        "Show batch BATCH-115",
        "How is batch BATCH-189 doing?",
        "Show batch BATCH-123",
        "Get batch record for BATCH-183",
        "Batch BATCH-162 summary",
        "Batch BATCH-061 summary",
        "Get batch record for BATCH-196",
        "Get batch record for BATCH-010",
        "What is the yield for batch BATCH-003?",
        "Fetch batch details for BATCH-122",
        "Batch BATCH-062 details",
        "Status of production batch BATCH-136",
        "Show me the batch record for BATCH-187",
        "View batch BATCH-126",
        "Show batch execution record BER--89159AB3",
        "Batch BATCH-012 details",
        "Deviations for batch BATCH-157",
        "Quality metrics for batch BATCH-058",
        "Execution record BER--8E057539",
        "Execution record BER--9B07FA21",
        "Show yield for BATCH-020",
        "Batch BATCH-027 quality data",
        "Get batch record for BATCH-096",
        "What happened to batch BATCH-129?",
        "Status of production batch BATCH-012",
        "Get batch record for BATCH-019",
        "Show batch execution record BER-E3246AC9",
        "Show batch execution record BER--608D8584",
        "Status of production batch BATCH-133",
        "What is the status of batch BATCH-184?",
        "BER BER--14FB7C4E status",
        "Batch BATCH-066 quality data",
        "Show yield for BATCH-039",
        "What is the status of batch BATCH-122?",
        "Show me the batch record for BATCH-026",
        "Show yield for BATCH-063",
        "What is the yield for batch BATCH-033?",
        "Batch BATCH-013 summary",
        "Give me info on batch BATCH-130",
        "How is batch BATCH-095 doing?",
        "Give me info on batch BATCH-106",
        "Get batch record for BATCH-039",
        "View batch BATCH-109",
        "Show yield for BATCH-019",
        "Deviations for batch BATCH-060",
        "Tell me about batch BATCH-063",
        "What is the status of BER BER--768A0997?",
        "Tell me about batch BATCH-023",
        "Show me the batch record for BATCH-034",
        "How is batch BATCH-016 doing?",
        "Open batch BATCH-007",
        "Batch BATCH-054 quality data",
        "Execution record BER--0F7E722D",
        "Batch BATCH-132 details",
        "Fetch batch details for BATCH-174",
        "List batches with status In Production",
        "Execution record BER--BCC654F9",
        "How is batch BATCH-032 doing?",
        "Show batch BATCH-093",
        "What is the status of batch BATCH-095?",
        "Get batch record for BATCH-195",
        "View batch BATCH-028",
        "Show me the batch record for BATCH-142",
        "How is batch BATCH-087 doing?",
        "Fetch batch details for BATCH-002",
        "Show batch BATCH-095",
        "Get batch record for BATCH-031",
        "Fetch batch details for BATCH-022",
        "Fetch batch details for BATCH-182",
        "Show batch execution record BER--7604E670",
        "Get batch record for BATCH-061",
        "What is the yield for batch BATCH-077?",
        "Get batch record for BATCH-037",
        "Show me the batch record for BATCH-106",
        "What happened to batch BATCH-088?",
        "Show me the batch record for BATCH-105",
        "Quality metrics for batch BATCH-198",
        "Status of production batch BATCH-014",
        "Show batch BATCH-032",
        "Batch BATCH-025 details",
        "What is the status of batch BATCH-191?",
        "Status of production batch BATCH-038",
        "Fetch batch details for BATCH-026",
        "Show batch execution record BER--928111F0",
        "Display batch record BATCH-179",
        "Give me info on batch BATCH-141",
        "Display batch record BATCH-077",
        "Batch BATCH-133 summary",
        "Batch BATCH-159 summary",
        "What is the status of batch BATCH-198?",
        "Tell me about batch BATCH-190",
        "Fetch batch details for BATCH-028",
        "Execution record BER-29121EC6",
        "Deviations for batch BATCH-114",
        "How is batch BATCH-130 doing?",
        "Get batch record for BATCH-099",
        "BER BER--9EC49100 status",
        "Get batch record for BATCH-069",
        "Show yield for BATCH-166",
        "Batch BATCH-135 quality data",
        "What is the yield for batch BATCH-001?",
        "What is the status of BER BER--86A9CFC3?",
        "Give me info on batch BATCH-066",
        "Batch BATCH-125 quality data",
        "View batch BATCH-148",
        "What happened to batch BATCH-004?",
        "Quality metrics for batch BATCH-182",
        "Deviations for batch BATCH-007",
        "Get batch record for BATCH-076",
        "Show batch BATCH-013",
        "Show me the batch record for BATCH-129",
        "Display batch record BATCH-154",
        "Status of production batch BATCH-097",
        "What happened to batch BATCH-125?",
        "Batch BATCH-118 quality data",
        "What is the status of batch BATCH-071?",
        "Give me info on batch BATCH-171",
        "View batch BATCH-112",
        "What is the status of BER BER--300DC74F?",
        "Give me info on batch BATCH-075",
        "Show batch execution record BER--2F0540F8",
        "How is batch BATCH-185 doing?",
        "What is the status of batch BATCH-168?",
        "Status of production batch BATCH-158",
        "What is the status of BER BER--3F7A438B?",
        "Execution record BER--1FF9DD82",
        "Batch BATCH-144 summary",
        "How is batch BATCH-072 doing?",
        "Give me info on batch BATCH-149",
        "BER BER--DB91A76B status",
        "Give me info on batch BATCH-144",
        "What is the yield for batch BATCH-024?",
        "Execution record BER-F3E117EE",
        "Deviations for batch BATCH-162",
        "Batch BATCH-113 quality data",
        "Display batch record BATCH-083",
        "Batch BATCH-015 summary",
        "Quality metrics for batch BATCH-061",
        "Status of production batch BATCH-020",
        "Quality metrics for batch BATCH-111",
        "Show batch execution record BER--E14789A4",
        "Batch BATCH-011 summary",
        "Show batch execution record BER--28D14605",
        "Batch BATCH-197 summary",
        "What happened to batch BATCH-154?",
        "Status of production batch BATCH-072",
        "Show batch execution record BER--C7BEE953",
        "Show me the batch record for BATCH-055",
        "Execution record BER--CC87C715",
        "Show batch BATCH-134",
        "Show batch BATCH-096",
        "View batch BATCH-033",
        "Status of production batch BATCH-092",
        "What happened to batch BATCH-079?",
        "Show batch BATCH-156",
        "What is the status of batch BATCH-126?",
        "What is the status of BER BER--9F46A182?",
        "Fetch batch details for BATCH-008",
        "Deviations for batch BATCH-175",
        "Batch BATCH-073 summary",
        "How is batch BATCH-109 doing?",
        "Show yield for BATCH-173",
        "How is batch BATCH-148 doing?",
        "Status of production batch BATCH-043",
        "Give me info on batch BATCH-110",
        "Fetch batch details for BATCH-171",
        "Get batch record for BATCH-084",
        "Show me the batch record for BATCH-037",
        "Execution record BER--F70E78AA",
        "Open batch BATCH-154",
        "Fetch batch details for BATCH-009",
        "What happened to batch BATCH-158?",
        "BER BER--28D14605 status",
        "Status of production batch BATCH-067",
        "BER BER--CDFFBCA2 status",
        "What is the status of batch BATCH-111?",
        "BER BER--ABD040A0 status",
        "Give me info on batch BATCH-017",
        "Batch BATCH-146 quality data",
        "Show batch BATCH-166",
        "What happened to batch BATCH-147?",
        "Give me info on batch BATCH-082",
        "Show batch BATCH-130",
        "Batch BATCH-067 details",
        "Get batch record for BATCH-116",
        "Display batch record BATCH-097",
        "Get batch record for BATCH-012",
        "Show batch execution record BER--51D67B67",
        "What is the status of BER BER-F304869A?",
        "Tell me about batch BATCH-028",
        "Show me the batch record for BATCH-121",
        "What is the status of BER BER--17D37A69?",
        "Batch BATCH-095 details",
        "Show batch BATCH-022",
        "What is the yield for batch BATCH-182?",
        "BER BER-79B0326D status",
        "Batch BATCH-007 details",
        "What is the status of BER BER-BD364549?",
        "Status of production batch BATCH-120",
        "Open batch BATCH-131",
        "What is the status of BER BER--9EB710B7?",
        "BER BER--FF9C312C status",
        "Give me info on batch BATCH-084",
        "What happened to batch BATCH-190?",
        "Display batch record BATCH-167",
        "Show yield for BATCH-026",
        "BER BER--66BA5357 status",
        "View batch BATCH-027",
        "Batch BATCH-158 summary",
        "Quality metrics for batch BATCH-010",
        "What happened to batch BATCH-116?",
        "Quality metrics for batch BATCH-112",
        "Tell me about batch BATCH-158",
        "Get batch record for BATCH-194",
        "Quality metrics for batch BATCH-064",
        "View batch BATCH-141",
        "What happened to batch BATCH-130?",
        "Deviations for batch BATCH-187",
        "Batch BATCH-055 quality data",
        "Show yield for BATCH-157",
        "Show batch execution record BER--10C81775",
        "Batch BATCH-008 quality data",
        "Open batch BATCH-037",
        "What is the yield for batch BATCH-110?",
        "Get batch record for BATCH-188",
        "Show batch BATCH-109",
        "Batch BATCH-148 summary",
        "List batches with status Approved",
        "Show batch BATCH-072",
        "Give me info on batch BATCH-129",
        "How is batch BATCH-170 doing?",
        "View batch BATCH-057",
        "Fetch batch details for BATCH-056",
        "How is batch BATCH-008 doing?",
        "What happened to batch BATCH-002?",
        "How is batch BATCH-131 doing?",
        "Fetch batch details for BATCH-106",
        "Show batch execution record BER--0C9334F6",
        "What is the yield for batch BATCH-086?",
        "Quality metrics for batch BATCH-089",
        "Execution record BER--E2D35188",
        "Batch BATCH-081 quality data",
        "Open batch BATCH-173",
        "Deviations for batch BATCH-120",
        "Show me the batch record for BATCH-067",
        "Show batch execution record BER--FA32A729",
        "What is the yield for batch BATCH-123?",
        "Status of production batch BATCH-157",
        "Give me info on batch BATCH-133",
        "Batch BATCH-190 quality data",
        "Deviations for batch BATCH-177",
        "Fetch batch details for BATCH-195",
        "Open batch BATCH-078",
        "Deviations for batch BATCH-155",
        "Quality metrics for batch BATCH-043",
        "Show yield for BATCH-132",
        "Batch BATCH-009 details",
        "What is the yield for batch BATCH-198?",
        "Tell me about batch BATCH-121",
        "Open batch BATCH-152",
        "Fetch batch details for BATCH-194",
        "Deviations for batch BATCH-087",
        "What is the status of BER BER--C5864960?",
        "What is the status of BER BER--0A5DA1E7?",
        "Status of production batch BATCH-145",
        "Quality metrics for batch BATCH-199",
        "Batch BATCH-193 quality data",
        "What is the status of BER BER--C7474D36?",
        "View batch BATCH-092",
        "What is the status of batch BATCH-002?",
        "Display batch record BATCH-181",
        "What happened to batch BATCH-028?",
        "BER BER--57F24E65 status",
        "Deviations for batch BATCH-131",
        "Show batch BATCH-114",
        "Show me the batch record for BATCH-194",
        "Execution record BER--9D757166",
        "Open batch BATCH-176",
        "Quality metrics for batch BATCH-197",
        "Batch BATCH-037 details",
        "Show yield for BATCH-075",
        "How is batch BATCH-154 doing?",
        "Batch BATCH-026 quality data",
        "View batch BATCH-146",
        "Batch BATCH-143 summary",
        "Get batch record for BATCH-066",
        "What is the status of BER BER--897EE0EC?",
        "Execution record BER--A7B8D1C6",
        "How is batch BATCH-163 doing?",
        "Open batch BATCH-193",
        "What happened to batch BATCH-086?",
        "Show me the batch record for BATCH-190",
        "What is the status of batch BATCH-073?",
        "Show yield for BATCH-092",
        "Batch BATCH-025 summary",
        "What is the status of BER BER--4339276D?",
        "What happened to batch BATCH-184?",
        "Give me info on batch BATCH-089",
        "Show batch BATCH-027",
        "Status of production batch BATCH-029",
        "What happened to batch BATCH-114?",
        "Display batch record BATCH-082",
        "Batch BATCH-074 details",
        "What is the yield for batch BATCH-069?",
        "Batch BATCH-164 summary",
        "What is the status of batch BATCH-039?",
        "Open batch BATCH-160",
        "Tell me about batch BATCH-004",
        "Fetch batch details for BATCH-042",
        "What happened to batch BATCH-026?",
        "Tell me about batch BATCH-194",
        "Fetch batch details for BATCH-063",
        "Show yield for BATCH-139",
        "Deviations for batch BATCH-124",
        "Give me info on batch BATCH-159",
    ],
}
