"""Small standalone intents grouped together (each individually tiny)."""

from __future__ import annotations

EXAMPLES: dict[str, list[str]] = {
    "asset_management": [
        "show me the machines",
        "what equipment do we have",
        "list all machines",
        "machine details",
    ],
    "audit_log": [
        "Show change history",
        "System access audit",
        "Compliance audit log",
        "Electronic signature log",
        "List recent audit events",
        "What was modified?",
        "Show me recent changes",
        "What changes were made today?",
        "Show audit trail",
        "Compliance dashboard",
        "System activity report",
        "Regulatory compliance events",
        "Data integrity audit",
        "Change audit trail",
        "Audit records for today",
        "Recent system changes",
        "List all compliance events",
        "GxP audit records",
        "Show part 11 audit events",
        "Audit summary",
        "Part 11 compliance report",
        "Show me the audit log for today",
        "Who accessed what?",
        "User activity log",
        "What compliance events happened this week?",
    ],
    "count": [
        "how many",
        "count the",
        "what is the total",
        "number of",
    ],
    "decision_intelligence": [
        "Alert summary",
        "Decision support overview",
        "Help me decide which batch to prioritize",
        "Situational awareness report",
        "Show me decision support data",
        "Critical path analysis",
        "Priority recommendations",
        "What is most urgent?",
        "What needs immediate attention?",
        "Executive summary",
        "Decision matrix",
        "What are the critical issues?",
        "Give me a decision summary",
        "Help me prioritize my work",
        "What requires my decision?",
        "What are the key decisions to make?",
        "What action should I take?",
        "What should I focus on today?",
        "Help me analyze the situation",
        "Recommended actions",
    ],
    "drug_research": [
        "Research progress for Cetirizine 10mg Tablets",
        "Research progress for Paracetamol 500mg Tablets",
        "What drugs are we researching?",
        "List active drug research projects",
        "What is the research status for Atorvastatin 10mg Tablets?",
        "What are the active research projects?",
        "Stability study results",
        "Formulation development status",
        "What is the research status for Cetirizine 10mg Tablets?",
        "Show formulation studies",
        "Tell me about drug research findings",
        "Bioequivalence data",
        "Clinical trial progress",
        "Development status of Cetirizine 10mg Tablets",
        "API research data",
        "Show formulation data for Amoxicillin 250mg Capsules",
        "Show formulation data for Atorvastatin 10mg Tablets",
        "Show formulation data for Paracetamol 500mg Tablets",
        "Show formulation data for Metformin 500mg Tablets",
        "Research progress for Amoxicillin 250mg Capsules",
        "What drug formulations are in research?",
        "Research and development overview",
        "Drug development pipeline",
        "Development status of Metformin 500mg Tablets",
        "Tell me about our research pipeline",
        "Research progress for Metformin 500mg Tablets",
        "Show formulation data for Cetirizine 10mg Tablets",
        "Excipient studies",
        "What is the research status for Amoxicillin 250mg Capsules?",
        "Development status of Amoxicillin 250mg Capsules",
        "Development status of Atorvastatin 10mg Tablets",
        "Show me R&D data",
        "Development status of Paracetamol 500mg Tablets",
        "Research progress for Atorvastatin 10mg Tablets",
        "What is the research status for Paracetamol 500mg Tablets?",
        "What is the research status for Metformin 500mg Tablets?",
    ],
    "knowledge_base": [
        "search for information",
        "find documentation",
        "knowledge search",
        "what do you know about",
    ],
    "line": [
        "show me the production lines",
        "what lines exist",
        "list all lines",
        "production line details",
    ],
    "plant_topology": [
        "show me the plant structure",
        "what plants do we have",
        "list all plants",
        "plant hierarchy",
    ],
    "production_kpi": [
        "Show downtime report for this week",
        "What are the quality metrics?",
        "Show production metrics",
        "Show production performance",
        "Show production KPIs for Finance",
        "What is the first pass yield?",
        "Process capability indices",
        "Show yield trend",
        "Show cycle time data",
        "Manufacturing KPIs",
        "Production targets vs actual",
        "What are the KPIs for Quality Control?",
        "Performance rate summary",
        "Engineering performance metrics",
        "What is the MTBF for our machines?",
        "Show me the KPIs for this shift",
        "Overall plant performance",
        "Quality rate for this week",
        "Show OEE breakdown",
        "What is the OEE for production line 1?",
        "What is the scrap rate?",
        "Production efficiency report",
        "Production efficiency in Warehouse & Logistics",
        "List all deviations this month",
        "What is the overall equipment effectiveness?",
        "Show me manufacturing metrics",
        "Downtime analysis",
        "What is the batch rejection rate?",
        "Machine availability report",
        "Batch success rate",
        "Show production yield for today",
        "Production output summary",
        "What is the throughput?",
        "Show equipment effectiveness",
    ],
    "simulation": [
        "simulate this scenario",
        "what if we change",
        "predict the outcome",
        "impact analysis",
    ],
    "sittingface_pipeline": [
        "run the sitting face pipeline",
        "execute the somatic pipeline",
        "compile somatic charts and generate code",
        "run sittingface loop until no diff",
        "sittingface pipeline execute",
        "generate code from charts and diff",
        "run the full pipeline loop",
        "soma pipeline execute",
    ],
    "stage": [
        "show me the stages",
        "what stages are there",
        "list all stages",
        "process stages",
    ],
    "web_search": [
        "search the web",
        "find online information",
        "web search for",
        "look up online",
    ],
    "workstation": [
        "show me workstations",
        "what workstations exist",
        "list all workstations",
        "workstation details",
    ],
}
