"""Intent examples: sop_compliance."""

from __future__ import annotations

EXAMPLES: dict[str, list[str]] = {
    "sop_compliance": [
        "View SOP SOP-TAB-INSP-001",
        "Show Sifting - Vibro Sifter Station SOP",
        "Show me SOP SOP-TAB-COMP-001",
        "Show Quality Assurance SOPs",
        "Recent SOP changes",
        "SOP library overview",
        "List SOPs that need review",
        "List SOPs for Warehouse & Logistics",
        "SOP SOP-CAP-SIFT-003 details",
        "SOP review schedule",
        "What SOPs do we have?",
        "Show me all standard operating procedures",
        "Open SOP SOP-TAB-SZ-001",
        "Show recent SOP updates",
        "Show me SOP SOP-CAP-DRY-001",
        "Show Regulatory Affairs SOPs",
        "Tell me about Sifting - Sifter Station procedure",
        "All standard operating procedures",
        "View SOP SOP-CAP-DRY-002",
        "List SOPs for Supply Chain",
        "Tell me about Inspection - Metal Detector procedure",
        "Tell me about Polishing - Capsule Polisher procedure",
        "Show me SOP SOP-CAP-BLD-003",
        "Open SOP SOP-TAB-INSP-001",
        "Show SOP compliance status",
        "SOP SOP-CAP-FILL-003 details",
        "View SOP SOP-TAB-SIFT-003",
        "Who approved SOP SOP-TAB-DISP-002?",
        "SOP SOP-TAB-BLD-002 details",
        "List SOPs for Regulatory Affairs",
        "What SOPs are in Quality Assurance?",
        "List SOPs for Operations",
        "Show Human Resources SOPs",
        "Is SOP SOP-TAB-SZ-002 current?",
        "Show me SOP SOP-TAB-DISP-002",
        "List SOPs for Engineering",
        "Open SOP SOP-CAP-GRAN-001",
        "What SOPs are expiring?",
        "What SOPs are in Finance?",
        "SOP summary",
        "Display SOP SOP-CAP-DRY-002",
        "SOP SOP-TAB-PKG-004 details",
        "Display SOP SOP-CAP-BLD-002",
        "SOP SOP-CAP-GRAN-002 details",
        "Show me SOP SOP-TAB-DISP-001",
        "What SOPs are in Regulatory Affairs?",
        "Who approved SOP SOP-CAP-BLD-003?",
        "Open SOP SOP-CAP-BLD-002",
        "What is the SOP for Sizing - Sieve Station?",
        "What is the SOP for Dispensing - Weighing Booth?",
        "Show Finance SOPs",
        "Open SOP SOP-CAP-POL-002",
        "List all SOPs",
        "SOP SOP-CAP-GRAN-001 details",
        "Open SOP SOP-TAB-PKG-001",
        "Tell me about Drying - FBD Unloading procedure",
        "Open SOP SOP-CAP-SZ-001",
        "What is the SOP for Drying - FBD Unloading?",
        "Display SOP SOP-TAB-DISP-003",
        "What is the SOP for Blending - Blender Station?",
        "Tell me about Dispensing - Weighing Booth procedure",
        "Show Dispensing - Sampling Booth SOP",
        "Show me SOP SOP-TAB-GRAN-002",
        "Show Drying - FBD Loading SOP",
        "Open SOP SOP-TAB-DRY-001",
        "Is SOP SOP-TAB-PKG-001 current?",
        "Is SOP SOP-TAB-PKG-002 current?",
        "SOP SOP-TAB-GRAN-001 details",
        "List SOPs for Finance",
        "Show Dispensing - Weighing Booth SOP",
        "Show Operations SOPs",
        "Display SOP SOP-CAP-SIFT-003",
        "Show Packaging - Blister/Strip SOP",
        "List SOPs for Quality Control",
        "Who approved SOP SOP-CAP-SZ-001?",
        "Who approved SOP SOP-TAB-COMP-001?",
        "Who approved SOP SOP-TAB-SIFT-001?",
        "List SOPs for EHS",
        "Tell me about Sizing - Co-Mill (post-dry) procedure",
        "Show Dispensing - Material Staging SOP",
        "Show me SOP SOP-TAB-COAT-002",
        "Open SOP SOP-TAB-COMP-002",
        "Who approved SOP SOP-TAB-GRAN-002?",
        "Tell me about Inspection - Visual Inspection procedure",
        "View SOP SOP-CAP-SZ-002",
        "Is SOP SOP-TAB-SIFT-001 current?",
        "Show me SOP SOP-CAP-GRAN-002",
        "Is SOP SOP-TAB-SZ-001 current?",
        "SOP SOP-TAB-DISP-002 details",
        "View SOP SOP-CAP-BLD-003",
        "Show Engineering SOPs",
        "Tell me about Drying - FBD Loading procedure",
        "Who approved SOP SOP-CAP-SIFT-003?",
        "Who approved SOP SOP-TAB-PKG-003?",
        "Show me SOP SOP-TAB-PKG-001",
        "What is the SOP for Inspection - Visual Inspection?",
        "Open SOP SOP-TAB-PKG-004",
        "What is the SOP for Sifting - Vibro Sifter Station?",
        "Show Supply Chain SOPs",
        "View SOP SOP-TAB-PKG-003",
        "Open SOP SOP-CAP-GRAN-002",
        "Show me SOP SOP-TAB-BLD-003",
        "Is SOP SOP-TAB-PKG-004 current?",
        "Show Warehouse & Logistics SOPs",
        "Show Quality Control SOPs",
        "What SOPs are in Human Resources?",
        "What SOPs are in Operations?",
        "What SOPs are in EHS?",
        "Open SOP SOP-CAP-DRY-002",
        "SOP SOP-CAP-POL-001 details",
        "Show Blending - Blender Station SOP",
        "Show me SOP SOP-CAP-DRY-002",
        "Show me SOP SOP-TAB-BLD-001",
        "Show me SOP SOP-TAB-SIFT-003",
        "SOP SOP-TAB-INSP-001 details",
        "Show Blending - Blender Loading SOP",
        "View SOP SOP-TAB-DRY-002",
        "List SOPs for Quality Assurance",
        "Tell me about Blending - Blender Loading procedure",
        "SOP SOP-TAB-BLD-001 details",
        "List SOPs for Human Resources",
        "Display SOP SOP-TAB-INSP-001",
        "View SOP SOP-CAP-BLD-001",
        "What is the SOP for Packaging - Cartoning?",
        "Tell me about Sifting - Vibro Sifter Station procedure",
        "SOP SOP-TAB-COAT-003 details",
        "Display SOP SOP-TAB-PKG-002",
        "Who approved SOP SOP-TAB-PKG-004?",
        "Display SOP SOP-TAB-SIFT-001",
        "Open SOP SOP-TAB-GRAN-002",
        "What is the SOP for Sifting - Sifter Station?",
        "Open SOP SOP-CAP-FILL-003",
        "Show me SOP SOP-CAP-INSP-001",
        "SOP SOP-TAB-DISP-003 details",
        "Open SOP SOP-CAP-DISP-001",
        "Show me SOP SOP-CAP-SZ-001",
        "What SOPs are in Warehouse & Logistics?",
        "Is SOP SOP-CAP-DRY-002 current?",
        "Tell me about Compression - Tablet Press procedure",
        "Tell me about Packaging - Labelling procedure",
        "SOP SOP-CAP-SZ-001 details",
        "Is SOP SOP-TAB-SIFT-002 current?",
        "SOP SOP-TAB-DRY-002 details",
        "Open SOP SOP-CAP-SIFT-001",
        "Who approved SOP SOP-TAB-SZ-001?",
        "Who approved SOP SOP-CAP-DISP-002?",
        "View SOP SOP-TAB-SZ-002",
        "Show Sifting - Co-Mill Station SOP",
        "Display SOP SOP-TAB-BLD-002",
        "Is SOP SOP-CAP-BLD-001 current?",
        "Open SOP SOP-TAB-BLD-001",
        "Open SOP SOP-TAB-COMP-003",
        "Who approved SOP SOP-TAB-INSP-003?",
        "Tell me about Compression - Deduster procedure",
        "Show EHS SOPs",
        "View SOP SOP-TAB-COAT-003",
        "Is SOP SOP-CAP-INSP-002 current?",
        "Display SOP SOP-CAP-POL-002",
        "Tell me about Sifting - Co-Mill Station procedure",
        "What is the SOP for Inspection - Metal Detector?",
        "View SOP SOP-CAP-SZ-001",
        "Is SOP SOP-CAP-FILL-001 current?",
        "Show me SOP SOP-TAB-COAT-003",
        "Show me SOP SOP-TAB-SIFT-002",
        "Is SOP SOP-CAP-SZ-002 current?",
        "SOP SOP-TAB-COMP-001 details",
        "SOP SOP-CAP-INSP-001 details",
        "Tell me about Inspection - Polishing procedure",
        "Is SOP SOP-TAB-SIFT-003 current?",
        "What is the SOP for Capsule Filling - In-Process QC?",
        "Who approved SOP SOP-CAP-BLD-001?",
        "What is the SOP for Packaging - Blister/Strip?",
        "Display SOP SOP-TAB-DRY-002",
        "Show me SOP SOP-TAB-COAT-001",
        "Show Inspection - Metal Detector SOP",
        "What SOPs are in Engineering?",
        "Show me SOP SOP-TAB-BLD-002",
        "Who approved SOP SOP-CAP-POL-002?",
        "Who approved SOP SOP-CAP-DRY-001?",
        "Show me SOP SOP-CAP-INSP-002",
        "Tell me about Packaging - Bottle Filling procedure",
        "Who approved SOP SOP-TAB-DRY-001?",
        "Show Granulation - RMG Station SOP",
        "View SOP SOP-CAP-INSP-002",
        "What is the SOP for Dispensing - Sampling Booth?",
        "SOP SOP-TAB-COMP-003 details",
        "View SOP SOP-CAP-GRAN-002",
        "Who approved SOP SOP-TAB-SZ-002?",
        "Is SOP SOP-TAB-DISP-001 current?",
        "What is the SOP for Granulation - RMG Station?",
        "What is the SOP for Dispensing - Material Staging?",
        "SOP SOP-TAB-COMP-002 details",
        "Who approved SOP SOP-CAP-FILL-002?",
        "Show Capsule Filling - In-Process QC SOP",
        "Display SOP SOP-CAP-BLD-003",
        "Display SOP SOP-TAB-SIFT-002",
        "What is the SOP for Blending - Lubrication?",
        "Show Coating - Coating Pan SOP",
        "Show Inspection - Visual Inspection SOP",
        "SOP SOP-CAP-DRY-001 details",
        "Who approved SOP SOP-CAP-POL-001?",
        "Show me SOP SOP-CAP-SIFT-001",
        "Open SOP SOP-CAP-SIFT-003",
        "Display SOP SOP-TAB-PKG-001",
        "Tell me about Dispensing - Material Staging procedure",
        "Display SOP SOP-TAB-COAT-001",
        "Open SOP SOP-TAB-DRY-002",
        "Is SOP SOP-CAP-FILL-002 current?",
        "SOP SOP-CAP-DISP-002 details",
        "What is the SOP for Granulation - Binder Prep?",
        "Open SOP SOP-TAB-BLD-003",
        "Tell me about Dispensing - Sampling Booth procedure",
        "SOP SOP-TAB-SZ-002 details",
        "Who approved SOP SOP-TAB-COAT-001?",
        "SOP SOP-TAB-INSP-003 details",
        "Who approved SOP SOP-TAB-PKG-001?",
        "Open SOP SOP-CAP-SZ-002",
        "SOP SOP-CAP-FILL-002 details",
        "Display SOP SOP-TAB-DISP-002",
        "Who approved SOP SOP-TAB-COAT-003?",
        "Is SOP SOP-TAB-COAT-003 current?",
        "View SOP SOP-CAP-DISP-002",
        "Tell me about Capsule Filling - In-Process QC procedure",
        "What is the SOP for Packaging - Bottle Filling?",
        "Display SOP SOP-CAP-SZ-002",
        "Show Compression - Deduster SOP",
        "Tell me about Blending - Blender Station procedure",
        "Open SOP SOP-TAB-INSP-002",
        "View SOP SOP-TAB-GRAN-002",
        "Show Drying - FBD Unloading SOP",
        "View SOP SOP-TAB-PKG-004",
        "Show Granulation - Binder Prep SOP",
        "SOP SOP-TAB-DRY-001 details",
        "Open SOP SOP-CAP-INSP-001",
        "Who approved SOP SOP-TAB-DISP-003?",
        "Display SOP SOP-TAB-BLD-003",
        "What SOPs are in Supply Chain?",
        "Display SOP SOP-CAP-DRY-001",
        "SOP SOP-TAB-PKG-001 details",
        "Show me SOP SOP-CAP-GRAN-001",
        "View SOP SOP-CAP-FILL-001",
        "Show me SOP SOP-TAB-COMP-002",
        "Show me SOP SOP-TAB-PKG-004",
        "Display SOP SOP-CAP-INSP-002",
        "SOP SOP-TAB-DISP-001 details",
        "View SOP SOP-CAP-INSP-001",
        "Open SOP SOP-TAB-DISP-003",
        "Is SOP SOP-TAB-BLD-002 current?",
        "Tell me about Capsule Filling - Main Station procedure",
        "Who approved SOP SOP-TAB-BLD-001?",
        "Is SOP SOP-CAP-DRY-001 current?",
        "SOP SOP-CAP-BLD-001 details",
        "View SOP SOP-TAB-DISP-002",
        "Show Blending - Lubrication SOP",
        "What SOPs are in Quality Control?",
        "What is the SOP for Sizing - Co-Mill (post-dry)?",
        "SOP SOP-TAB-GRAN-002 details",
        "SOP SOP-TAB-COAT-001 details",
        "SOP SOP-TAB-PKG-002 details",
        "Display SOP SOP-CAP-INSP-001",
        "Display SOP SOP-TAB-INSP-003",
        "Is SOP SOP-CAP-POL-002 current?",
        "Display SOP SOP-CAP-GRAN-001",
        "Show Compression - In-Process QC SOP",
        "Open SOP SOP-TAB-COAT-003",
        "Open SOP SOP-CAP-BLD-003",
        "Tell me about Capsule Filling - Empty Capsule Feed procedure",
        "Who approved SOP SOP-CAP-SIFT-002?",
        "Show Sifting - Sifter Station SOP",
        "Show Capsule Filling - Empty Capsule Feed SOP",
        "View SOP SOP-CAP-POL-002",
        "Is SOP SOP-CAP-GRAN-002 current?",
        "Show me SOP SOP-TAB-DRY-002",
        "Display SOP SOP-CAP-SZ-001",
        "Display SOP SOP-CAP-FILL-001",
        "View SOP SOP-TAB-GRAN-001",
        "Who approved SOP SOP-CAP-INSP-002?",
        "What is the SOP for Sifting - Co-Mill Station?",
        "Is SOP SOP-CAP-INSP-001 current?",
        "Is SOP SOP-TAB-COMP-002 current?",
        "Is SOP SOP-TAB-DRY-001 current?",
        "Tell me about Packaging - Cartoning procedure",
        "Who approved SOP SOP-CAP-BLD-002?",
        "View SOP SOP-TAB-INSP-003",
        "Display SOP SOP-TAB-GRAN-001",
        "SOP SOP-CAP-SIFT-001 details",
        "Show me SOP SOP-TAB-INSP-003",
        "Tell me about Sizing - Sieve Station procedure",
        "Who approved SOP SOP-TAB-DRY-002?",
        "What is the SOP for Inspection - Polishing?",
        "Is SOP SOP-CAP-BLD-003 current?",
        "Show me SOP SOP-TAB-DISP-003",
        "Is SOP SOP-TAB-DRY-002 current?",
        "Display SOP SOP-TAB-DISP-001",
        "Show me SOP SOP-CAP-BLD-001",
        "SOP SOP-TAB-COAT-002 details",
        "View SOP SOP-TAB-PKG-001",
        "SOP SOP-CAP-SIFT-002 details",
        "View SOP SOP-CAP-POL-001",
        "Who approved SOP SOP-CAP-FILL-003?",
        "Who approved SOP SOP-CAP-FILL-001?",
        "Display SOP SOP-CAP-FILL-002",
        "SOP SOP-CAP-FILL-001 details",
        "View SOP SOP-TAB-INSP-002",
        "Display SOP SOP-CAP-DISP-002",
        "What is the SOP for Polishing - Capsule Polisher?",
        "Display SOP SOP-TAB-SIFT-003",
        "Is SOP SOP-CAP-DISP-003 current?",
        "Display SOP SOP-TAB-COMP-003",
        "View SOP SOP-TAB-DRY-001",
        "Open SOP SOP-CAP-DISP-003",
        "Show me SOP SOP-TAB-SZ-001",
        "Is SOP SOP-TAB-COAT-002 current?",
        "Tell me about Blending - Lubrication procedure",
        "Show Compression - Tablet Press SOP",
        "Who approved SOP SOP-CAP-DISP-003?",
        "Who approved SOP SOP-CAP-SIFT-001?",
        "SOP SOP-CAP-DRY-002 details",
        "Display SOP SOP-TAB-COAT-002",
        "What is the SOP for Dedusting - Deduster Station?",
        "Show me SOP SOP-CAP-BLD-002",
        "Show me SOP SOP-CAP-FILL-001",
        "Open SOP SOP-TAB-INSP-003",
        "View SOP SOP-TAB-COMP-003",
        "Show Coating - Air Handling SOP",
        "Open SOP SOP-CAP-SIFT-002",
        "Open SOP SOP-TAB-SIFT-003",
        "Is SOP SOP-CAP-POL-001 current?",
        "View SOP SOP-CAP-DISP-001",
        "Who approved SOP SOP-TAB-PKG-002?",
        "View SOP SOP-CAP-SIFT-003",
        "What is the SOP for Capsule Filling - Main Station?",
        "Who approved SOP SOP-TAB-INSP-002?",
        "Is SOP SOP-TAB-PKG-003 current?",
        "Show Sizing - Sieve Station SOP",
        "Open SOP SOP-TAB-DISP-001",
        "Open SOP SOP-TAB-SIFT-001",
        "View SOP SOP-TAB-DISP-001",
        "Open SOP SOP-CAP-POL-001",
        "Display SOP SOP-CAP-SIFT-001",
        "Is SOP SOP-CAP-SIFT-001 current?",
        "SOP SOP-CAP-DISP-003 details",
        "Display SOP SOP-TAB-BLD-001",
        "Who approved SOP SOP-TAB-COAT-002?",
        "Show me SOP SOP-CAP-DISP-001",
        "SOP SOP-TAB-PKG-003 details",
        "View SOP SOP-TAB-SIFT-002",
        "Tell me about Compression - In-Process QC procedure",
        "What is the SOP for Compression - Deduster?",
        "Tell me about Granulation - RMG Station procedure",
        "SOP SOP-TAB-SIFT-001 details",
        "Display SOP SOP-CAP-DISP-001",
        "Show me SOP SOP-TAB-INSP-001",
        "Tell me about Dedusting - Deduster Station procedure",
        "Show Packaging - Cartoning SOP",
        "Is SOP SOP-TAB-GRAN-002 current?",
        "Is SOP SOP-CAP-SIFT-002 current?",
        "Is SOP SOP-CAP-GRAN-001 current?",
        "SOP SOP-TAB-BLD-003 details",
        "Is SOP SOP-CAP-DISP-002 current?",
        "Open SOP SOP-CAP-DISP-002",
        "Open SOP SOP-TAB-PKG-002",
        "Show me SOP SOP-TAB-DRY-001",
        "Who approved SOP SOP-TAB-DISP-001?",
        "View SOP SOP-TAB-SIFT-001",
        "Tell me about Granulation - Binder Prep procedure",
        "Who approved SOP SOP-CAP-SZ-002?",
        "What is the SOP for Compression - Tablet Press?",
        "Show Inspection - Polishing SOP",
        "Show me SOP SOP-CAP-FILL-003",
        "Is SOP SOP-TAB-BLD-001 current?",
        "View SOP SOP-TAB-COAT-001",
        "Is SOP SOP-TAB-INSP-003 current?",
        "What is the SOP for Compression - In-Process QC?",
        "Show me SOP SOP-CAP-SIFT-002",
        "Is SOP SOP-CAP-BLD-002 current?",
        "View SOP SOP-TAB-SZ-001",
        "Open SOP SOP-CAP-FILL-001",
        "SOP SOP-CAP-BLD-002 details",
        "Show me SOP SOP-CAP-FILL-002",
        "View SOP SOP-TAB-DISP-003",
        "What is the SOP for Coating - Air Handling?",
        "Show Sizing - Co-Mill (post-dry) SOP",
        "Show me SOP SOP-CAP-POL-002",
        "View SOP SOP-TAB-COAT-002",
        "Show me SOP SOP-TAB-GRAN-001",
        "Who approved SOP SOP-CAP-GRAN-001?",
        "Open SOP SOP-CAP-DRY-001",
        "View SOP SOP-CAP-GRAN-001",
        "Show Dedusting - Deduster Station SOP",
        "Display SOP SOP-CAP-POL-001",
        "Show me SOP SOP-TAB-COMP-003",
        "Open SOP SOP-CAP-INSP-002",
        "Display SOP SOP-CAP-DISP-003",
        "Display SOP SOP-TAB-PKG-003",
        "SOP SOP-CAP-DISP-001 details",
        "Is SOP SOP-TAB-DISP-003 current?",
        "View SOP SOP-TAB-BLD-002",
        "Is SOP SOP-TAB-COMP-001 current?",
        "Show Packaging - Labelling SOP",
        "Is SOP SOP-TAB-INSP-002 current?",
        "Is SOP SOP-CAP-DISP-001 current?",
        "Show me SOP SOP-CAP-POL-001",
        "What is the SOP for Drying - FBD Loading?",
        "Open SOP SOP-CAP-BLD-001",
        "Who approved SOP SOP-CAP-DISP-001?",
        "Display SOP SOP-TAB-DRY-001",
        "SOP SOP-TAB-SIFT-002 details",
        "What is the SOP for Coating - Coating Pan?",
        "Who approved SOP SOP-TAB-SIFT-003?",
        "Who approved SOP SOP-CAP-INSP-001?",
        "Is SOP SOP-TAB-GRAN-001 current?",
        "Open SOP SOP-TAB-PKG-003",
        "What is the SOP for Packaging - Labelling?",
        "Display SOP SOP-TAB-SZ-002",
        "View SOP SOP-TAB-COMP-002",
        "Show Polishing - Capsule Polisher SOP",
        "Who approved SOP SOP-TAB-SIFT-002?",
        "View SOP SOP-TAB-BLD-003",
        "SOP SOP-CAP-POL-002 details",
        "Show me SOP SOP-TAB-SZ-002",
        "Display SOP SOP-CAP-BLD-001",
        "Who approved SOP SOP-TAB-BLD-002?",
        "What is the SOP for Blending - Blender Loading?",
        "Who approved SOP SOP-TAB-INSP-001?",
        "View SOP SOP-CAP-DRY-001",
        "Is SOP SOP-TAB-DISP-002 current?",
        "Open SOP SOP-CAP-FILL-002",
        "Who approved SOP SOP-TAB-COMP-003?",
        "Is SOP SOP-TAB-INSP-001 current?",
        "Who approved SOP SOP-TAB-BLD-003?",
        "Show me SOP SOP-TAB-SIFT-001",
        "View SOP SOP-CAP-SIFT-002",
        "Tell me about Coating - Coating Pan procedure",
        "Open SOP SOP-TAB-GRAN-001",
        "View SOP SOP-CAP-FILL-003",
        "Display SOP SOP-TAB-PKG-004",
        "View SOP SOP-CAP-DISP-003",
        "SOP SOP-CAP-SZ-002 details",
        "Display SOP SOP-TAB-GRAN-002",
        "What is the SOP for Capsule Filling - Empty Capsule Feed?",
        "Open SOP SOP-TAB-DISP-002",
        "Open SOP SOP-TAB-COAT-001",
        "Display SOP SOP-TAB-COAT-003",
        "Display SOP SOP-TAB-SZ-001",
        "Open SOP SOP-TAB-BLD-002",
        "Display SOP SOP-TAB-INSP-002",
        "Show me SOP SOP-CAP-DISP-002",
        "Show me SOP SOP-TAB-PKG-002",
        "Show me SOP SOP-CAP-SZ-002",
        "Who approved SOP SOP-CAP-DRY-002?",
        "View SOP SOP-TAB-PKG-002",
        "Show Packaging - Bottle Filling SOP",
        "View SOP SOP-TAB-BLD-001",
        "Is SOP SOP-CAP-SIFT-003 current?",
        "Who approved SOP SOP-CAP-GRAN-002?",
        "View SOP SOP-CAP-SIFT-001",
        "Tell me about Coating - Solution Prep procedure",
        "Is SOP SOP-CAP-SZ-001 current?",
        "Show me SOP SOP-CAP-DISP-003",
        "SOP SOP-CAP-INSP-002 details",
        "Show Coating - Solution Prep SOP",
        "Show me SOP SOP-TAB-PKG-003",
        "Show Capsule Filling - Main Station SOP",
        "Open SOP SOP-TAB-SZ-002",
        "SOP SOP-TAB-INSP-002 details",
        "Tell me about Coating - Air Handling procedure",
        "Open SOP SOP-TAB-SIFT-002",
        "Show me SOP SOP-CAP-SIFT-003",
        "SOP SOP-TAB-SZ-001 details",
        "Display SOP SOP-TAB-COMP-001",
        "SOP SOP-CAP-BLD-003 details",
        "Who approved SOP SOP-TAB-GRAN-001?",
        "Display SOP SOP-CAP-FILL-003",
        "Display SOP SOP-CAP-GRAN-002",
        "Is SOP SOP-CAP-FILL-003 current?",
        "Open SOP SOP-TAB-COMP-001",
        "What is the SOP for Coating - Solution Prep?",
        "View SOP SOP-CAP-FILL-002",
        "Who approved SOP SOP-TAB-COMP-002?",
        "View SOP SOP-CAP-BLD-002",
        "SOP SOP-TAB-SIFT-003 details",
        "Is SOP SOP-TAB-COMP-003 current?",
        "Is SOP SOP-TAB-BLD-003 current?",
        "Display SOP SOP-TAB-COMP-002",
        "Tell me about Packaging - Blister/Strip procedure",
        "Is SOP SOP-TAB-COAT-001 current?",
        "Open SOP SOP-TAB-COAT-002",
    ],
}
