"""Intent examples: warehouse_shipping, work_order_create."""

from __future__ import annotations

EXAMPLES: dict[str, list[str]] = {
    "warehouse_shipping": [
        "Show warehouse status",
        "Warehouse stock levels",
        "Inventory for Paracetamol 500mg Tablets",
        "Shipping queue",
        "List all shipments",
        "What is in the warehouse?",
        "Logistics overview",
        "What is the shipping status for batch BATCH-003?",
        "What is the shipping status for batch BATCH-187?",
        "Pending deliveries",
        "Inbound receipt log",
        "Shipment tracking dashboard",
        "Stock status for Cetirizine 10mg Tablets",
        "Outbound shipment list",
        "Stock status for Metformin 500mg Tablets",
        "What is the shipping status for batch BATCH-141?",
        "What is the shipping status for batch BATCH-071?",
        "Warehouse inventory report",
        "Show dispatch schedule",
        "What is the shipping status for batch BATCH-160?",
        "What is the status of outbound freight?",
        "What is the shipping status for batch BATCH-038?",
        "What shipments are pending?",
        "Inventory for Metformin 500mg Tablets",
        "What is the shipping status for batch BATCH-124?",
        "Dispatch summary",
        "Show warehouse inventory for Paracetamol 500mg Tablets",
        "Show me shipment tracking",
        "Show warehouse inventory for Atorvastatin 10mg Tablets",
        "What is the shipping status for batch BATCH-023?",
        "Stock status for Amoxicillin 250mg Capsules",
        "Inventory for Cetirizine 10mg Tablets",
        "Inventory for Amoxicillin 250mg Capsules",
        "What is the shipping status for batch BATCH-076?",
        "What is the shipping status for batch BATCH-022?",
        "List warehouse shipments for today",
        "What is the shipping status for batch BATCH-189?",
        "List pending dispatch orders",
        "Inventory for Atorvastatin 10mg Tablets",
        "What is the shipping status for batch BATCH-183?",
        "What is the shipping status for batch BATCH-099?",
        "What is the shipping status for batch BATCH-053?",
        "Show warehouse inventory for Metformin 500mg Tablets",
        "What is the shipping status for batch BATCH-079?",
        "What is the shipping status for batch BATCH-171?",
        "Freight status report",
        "Show warehouse inventory for Amoxicillin 250mg Capsules",
        "What is the shipping status for batch BATCH-136?",
        "What is the shipping status for batch BATCH-072?",
        "Stock status for Atorvastatin 10mg Tablets",
        "Stock status for Paracetamol 500mg Tablets",
        "What is the shipping status for batch BATCH-005?",
        "What is the shipping status for batch BATCH-118?",
        "Show inbound shipments this week",
        "What is the shipping status for batch BATCH-109?",
        "What is the shipping status for batch BATCH-167?",
        "What is the shipping status for batch BATCH-105?",
        "What is the shipping status for batch BATCH-016?",
        "What is the shipping status for batch BATCH-078?",
        "What is the shipping status for batch BATCH-088?",
        "What is the shipping status for batch BATCH-054?",
        "What is the shipping status for batch BATCH-073?",
        "Show warehouse inventory for Cetirizine 10mg Tablets",
        "What is the shipping status for batch BATCH-113?",
        "What is the shipping status for batch BATCH-011?",
        "What is the shipping status for batch BATCH-106?",
        "What is the shipping status for batch BATCH-018?",
        "What is the shipping status for batch BATCH-185?",
        "What is the shipping status for batch BATCH-020?",
        "What is the shipping status for batch BATCH-139?",
        "What is the shipping status for batch BATCH-096?",
        "What is the shipping status for batch BATCH-176?",
        "What is the shipping status for batch BATCH-036?",
        "What is the shipping status for batch BATCH-145?",
        "What is the shipping status for batch BATCH-123?",
        "What is the shipping status for batch BATCH-059?",
        "What is the shipping status for batch BATCH-063?",
        "What is the shipping status for batch BATCH-149?",
        "What is the shipping status for batch BATCH-090?",
        "What is the shipping status for batch BATCH-060?",
        "What is the shipping status for batch BATCH-132?",
        "What is the shipping status for batch BATCH-086?",
        "What is the shipping status for batch BATCH-042?",
        "What is the shipping status for batch BATCH-190?",
        "What is the shipping status for batch BATCH-193?",
        "What is the shipping status for batch BATCH-028?",
        "What is the shipping status for batch BATCH-154?",
        "What is the shipping status for batch BATCH-166?",
        "What is the shipping status for batch BATCH-097?",
        "What is the shipping status for batch BATCH-182?",
        "What is the shipping status for batch BATCH-178?",
        "What is the shipping status for batch BATCH-155?",
        "What is the shipping status for batch BATCH-019?",
        "What is the shipping status for batch BATCH-133?",
        "What is the shipping status for batch BATCH-101?",
        "What is the shipping status for batch BATCH-100?",
        "What is the shipping status for batch BATCH-116?",
        "What is the shipping status for batch BATCH-135?",
        "What is the shipping status for batch BATCH-091?",
        "What is the shipping status for batch BATCH-107?",
        "What is the shipping status for batch BATCH-085?",
        "What is the shipping status for batch BATCH-188?",
        "What is the shipping status for batch BATCH-040?",
        "What is the shipping status for batch BATCH-035?",
        "What is the shipping status for batch BATCH-131?",
        "What is the shipping status for batch BATCH-051?",
        "What is the shipping status for batch BATCH-093?",
        "What is the shipping status for batch BATCH-115?",
        "What is the shipping status for batch BATCH-092?",
        "What is the shipping status for batch BATCH-058?",
        "What is the shipping status for batch BATCH-197?",
        "What is the shipping status for batch BATCH-146?",
        "What is the shipping status for batch BATCH-021?",
        "What is the shipping status for batch BATCH-164?",
        "What is the shipping status for batch BATCH-069?",
        "What is the shipping status for batch BATCH-029?",
        "What is the shipping status for batch BATCH-052?",
        "What is the shipping status for batch BATCH-117?",
        "What is the shipping status for batch BATCH-061?",
        "What is the shipping status for batch BATCH-012?",
        "What is the shipping status for batch BATCH-032?",
        "What is the shipping status for batch BATCH-055?",
        "What is the shipping status for batch BATCH-026?",
        "What is the shipping status for batch BATCH-152?",
        "What is the shipping status for batch BATCH-043?",
        "What is the shipping status for batch BATCH-002?",
        "What is the shipping status for batch BATCH-084?",
        "What is the shipping status for batch BATCH-108?",
        "What is the shipping status for batch BATCH-103?",
        "What is the shipping status for batch BATCH-175?",
        "What is the shipping status for batch BATCH-089?",
        "What is the shipping status for batch BATCH-157?",
        "What is the shipping status for batch BATCH-156?",
        "What is the shipping status for batch BATCH-173?",
        "What is the shipping status for batch BATCH-151?",
        "What is the shipping status for batch BATCH-129?",
        "What is the shipping status for batch BATCH-122?",
        "What is the shipping status for batch BATCH-044?",
        "What is the shipping status for batch BATCH-057?",
        "What is the shipping status for batch BATCH-162?",
        "What is the shipping status for batch BATCH-186?",
        "What is the shipping status for batch BATCH-070?",
        "What is the shipping status for batch BATCH-140?",
        "What is the shipping status for batch BATCH-200?",
        "What is the shipping status for batch BATCH-137?",
        "What is the shipping status for batch BATCH-014?",
        "What is the shipping status for batch BATCH-074?",
        "What is the shipping status for batch BATCH-030?",
        "What is the shipping status for batch BATCH-039?",
        "What is the shipping status for batch BATCH-102?",
        "What is the shipping status for batch BATCH-094?",
        "What is the shipping status for batch BATCH-172?",
        "What is the shipping status for batch BATCH-179?",
        "What is the shipping status for batch BATCH-033?",
        "What is the shipping status for batch BATCH-082?",
        "What is the shipping status for batch BATCH-025?",
        "What is the shipping status for batch BATCH-128?",
        "What is the shipping status for batch BATCH-144?",
        "What is the shipping status for batch BATCH-031?",
        "What is the shipping status for batch BATCH-121?",
        "What is the shipping status for batch BATCH-126?",
        "What is the shipping status for batch BATCH-138?",
        "What is the shipping status for batch BATCH-027?",
        "What is the shipping status for batch BATCH-009?",
        "What is the shipping status for batch BATCH-191?",
        "What is the shipping status for batch BATCH-081?",
        "What is the shipping status for batch BATCH-034?",
        "What is the shipping status for batch BATCH-046?",
        "What is the shipping status for batch BATCH-147?",
        "What is the shipping status for batch BATCH-165?",
        "What is the shipping status for batch BATCH-195?",
        "What is the shipping status for batch BATCH-163?",
        "What is the shipping status for batch BATCH-001?",
        "What is the shipping status for batch BATCH-114?",
        "What is the shipping status for batch BATCH-010?",
        "What is the shipping status for batch BATCH-098?",
        "What is the shipping status for batch BATCH-007?",
        "What is the shipping status for batch BATCH-153?",
        "What is the shipping status for batch BATCH-125?",
        "What is the shipping status for batch BATCH-130?",
        "What is the shipping status for batch BATCH-170?",
        "What is the shipping status for batch BATCH-008?",
        "What is the shipping status for batch BATCH-110?",
        "What is the shipping status for batch BATCH-198?",
        "What is the shipping status for batch BATCH-158?",
        "What is the shipping status for batch BATCH-065?",
        "What is the shipping status for batch BATCH-006?",
        "What is the shipping status for batch BATCH-067?",
        "What is the shipping status for batch BATCH-037?",
        "What is the shipping status for batch BATCH-095?",
        "What is the shipping status for batch BATCH-064?",
        "What is the shipping status for batch BATCH-150?",
        "What is the shipping status for batch BATCH-127?",
        "What is the shipping status for batch BATCH-024?",
        "What is the shipping status for batch BATCH-196?",
        "What is the shipping status for batch BATCH-050?",
        "What is the shipping status for batch BATCH-056?",
        "What is the shipping status for batch BATCH-068?",
        "What is the shipping status for batch BATCH-134?",
        "What is the shipping status for batch BATCH-062?",
        "What is the shipping status for batch BATCH-177?",
        "What is the shipping status for batch BATCH-047?",
        "What is the shipping status for batch BATCH-120?",
        "What is the shipping status for batch BATCH-080?",
        "What is the shipping status for batch BATCH-168?",
        "What is the shipping status for batch BATCH-015?",
        "What is the shipping status for batch BATCH-194?",
        "What is the shipping status for batch BATCH-159?",
        "What is the shipping status for batch BATCH-077?",
        "What is the shipping status for batch BATCH-184?",
        "What is the shipping status for batch BATCH-041?",
        "What is the shipping status for batch BATCH-143?",
        "What is the shipping status for batch BATCH-174?",
        "What is the shipping status for batch BATCH-111?",
        "What is the shipping status for batch BATCH-119?",
        "What is the shipping status for batch BATCH-148?",
        "What is the shipping status for batch BATCH-004?",
        "What is the shipping status for batch BATCH-013?",
    ],
    "work_order_create": [
        "Submit a new work order request",
        "I need to create a work order",
        "Create a maintenance work order",
        "Create a work order for RPM Controller calibration",
        "Open a installation work order",
        "Create a work order for Rejection Bin calibration",
        "Open work order for Overhead Stirrer maintenance",
        "New work order for equipment",
        "Open a inspection work order",
        "Open a work order for pump inspection",
        "Start a new work order",
        "Create calibration work order",
        "Create a work order for Supply Chain",
        "Create a work order for Operations",
        "Initiate a work order",
        "Create a preventive maintenance work order for Sieve",
        "New work order for Vision Inspection System",
        "Create a work order for Engineering",
        "Open a repair work order",
        "Create a preventive maintenance work order for Discharge Trolley",
        "Create a preventive maintenance work order for Pallet Truck",
        "New work order for RPM Indicator",
        "Create a new work order",
        "Open work order for Leaflet Inserter maintenance",
        "Create a work order for Finger Bag Set calibration",
        "Create a preventive maintenance work order for Spray Gun Assembly",
        "Create a work order for Orientation Sorter calibration",
        "Create a work order for Capsule Counter calibration",
        "Create a work order for Dust Collector calibration",
        "Open a maintenance work order",
        "New work order for Checkweigher",
        "Create a work order for Pallet Truck calibration",
        "Create a work order for Quality Assurance",
        "New work order for Vernier Caliper",
        "Create a preventive maintenance work order for Illuminated Inspection Table",
        "Create a preventive maintenance work order for Metal Detector",
        "Create a work order for Hot Water Generator calibration",
        "Create a work order for Self-Adhesive Labeller calibration",
        "Open a calibration work order",
        "Open work order for Lubricant Dispenser maintenance",
        "Create a work order for Floor Scale calibration",
        "Create a work order for Warehouse & Logistics",
        "Open a other work order",
        "Raise a work order",
        "Create a work order for Regulatory Affairs",
        "Open work order for Metal Detector maintenance",
        "New work order for Analytical Balance",
        "Open work order for Desiccant Inserter maintenance",
        "Create a work order for Product Container calibration",
        "New work order for RH Sensor",
        "New work order for Inlet Temp Sensor",
        "Create a preventive maintenance work order for Inspection Conveyor",
        "Open work order for Rejection Bin maintenance",
        "Create a preventive maintenance work order for Finger Bag Set",
        "Create a preventive maintenance work order for Dust Collector",
        "Open work order for Chopper Motor maintenance",
        "Create a preventive maintenance work order for SS Bin",
        "Create a preventive maintenance work order for Product Container",
        "New work order for Exhaust Temp Sensor",
        "Create a work order for Capsule Polishing Machine calibration",
        "Create a preventive maintenance work order for Tablet Deduster",
        "Create a preventive maintenance work order for Tablet Counter",
        "Create a preventive maintenance work order for Capsule Deduster",
        "New work order for Hardness Tester",
        "Open work order for Peristaltic Pump maintenance",
        "Create a work order for Tablet Deduster calibration",
        "Create a work order for Chopper Motor calibration",
        "Create a work order for Illuminated Inspection Table calibration",
        "Create a work order for Peristaltic Pump calibration",
        "Open work order for Cap Sealer maintenance",
        "Create a work order for Overhead Stirrer calibration",
        "Create a work order for Exhaust Blower calibration",
        "Create a work order for Sampling Spatula calibration",
        "New work order for Pan RPM Sensor",
        "Create a work order for Quality Control",
        "Create a work order for Dosing Disc Set calibration",
        "Create a work order for Finance",
        "Create a preventive maintenance work order for Desiccant Inserter",
        "Create a work order for Metal Detector calibration",
        "Create a preventive maintenance work order for Capsule Rectifier",
        "Create a work order for Human Resources",
        "Open work order for Sampling Spatula maintenance",
        "Open work order for RPM Controller maintenance",
        "Create a preventive maintenance work order for Overhead Stirrer",
        "Open work order for Exhaust Blower maintenance",
        "Create a preventive maintenance work order for Hot Water Generator",
        "Create a work order for Cartoning Machine calibration",
        "New work order for Thermometer",
        "Create a preventive maintenance work order for Capsule Counter",
        "Create a work order for SS Bin calibration",
        "New work order for Pre-compression Sensor",
        "Create a work order for Tamping Pin Set calibration",
        "Open work order for Batch Coding Machine maintenance",
        "Open work order for Finger Bag Set maintenance",
        "New work order for Leak Tester",
        "New work order for Capsule Rejection Sensor",
        "Create a work order for EHS",
        "Open work order for Tablet Deduster maintenance",
        "Create a preventive maintenance work order for AHU",
        "Create a preventive maintenance work order for Batch Coding Machine",
        "New work order for Compression Force Sensor",
        "Create a preventive maintenance work order for Exhaust Blower",
        "Open work order for Dust Collector maintenance",
        "Create a work order for Dust Extractor calibration",
        "New work order for Disintegration Tester",
        "Create a work order for Force Feeder calibration",
        "Create a work order for Material Transfer Trolley calibration",
        "Open work order for Pallet Truck maintenance",
        "Open work order for Capsule Counter maintenance",
        "Open work order for Discharge Trolley maintenance",
        "Create a work order for AHU calibration",
        "Open work order for Impeller Motor maintenance",
        "Open work order for Blister Packing Machine maintenance",
        "Open work order for SS Bin maintenance",
        "Create a preventive maintenance work order for Dust Extractor",
        "Create a preventive maintenance work order for Peristaltic Pump",
        "Create a preventive maintenance work order for Foil Unwinder",
        "New work order for Viscometer",
        "Open work order for Self-Adhesive Labeller maintenance",
        "Create a preventive maintenance work order for Rejection Bin",
        "New work order for Moisture Analyzer",
        "Open work order for Sieve maintenance",
        "New work order for Timer",
        "Open work order for Dust Extractor maintenance",
        "Create a work order for Sieve calibration",
        "Create a work order for Cap Sealer calibration",
        "Open work order for Tablet Polisher maintenance",
        "Open work order for Bottle Filler maintenance",
        "New work order for Fill Weight Sensor",
        "Open work order for AHU maintenance",
        "Create a work order for Batch Coding Machine calibration",
        "Create a preventive maintenance work order for Sampling Spatula",
        "Create a preventive maintenance work order for Blister Packing Machine",
        "Open work order for Dosing Disc Set maintenance",
        "Open work order for Illuminated Inspection Table maintenance",
        "Create a work order for Desiccant Inserter calibration",
        "Create a work order for Blister Packing Machine calibration",
        "Create a preventive maintenance work order for Closing Module",
        "Create a work order for Lubricant Dispenser calibration",
        "New work order for Inlet Air Temp Sensor",
        "Open work order for Material Transfer Trolley maintenance",
        "Create a preventive maintenance work order for Chopper Motor",
        "Open work order for Tablet Counter maintenance",
        "Create a work order for Bottle Filler calibration",
        "New work order for LOD Moisture Analyzer",
        "Open work order for Closing Module maintenance",
        "Create a preventive maintenance work order for Floor Scale",
        "Open work order for Foil Unwinder maintenance",
        "Create a work order for Capsule Deduster calibration",
        "New work order for Spray Rate Controller",
        "Create a preventive maintenance work order for Lubricant Dispenser",
        "Create a preventive maintenance work order for Cap Sealer",
        "Create a preventive maintenance work order for RPM Controller",
        "New work order for Load Cell",
        "New work order for Seal Temp Sensor",
        "Create a preventive maintenance work order for Cartoning Machine",
        "Open work order for Tamping Pin Set maintenance",
        "Create a preventive maintenance work order for Capsule Polishing Machine",
        "Open work order for Cartoning Machine maintenance",
        "Create a preventive maintenance work order for Punch & Die Set",
        "Create a work order for Discharge Trolley calibration",
        "Create a work order for Closing Module calibration",
        "Create a preventive maintenance work order for Material Transfer Trolley",
        "Open work order for Floor Scale maintenance",
        "Create a work order for Impeller Motor calibration",
        "Create a preventive maintenance work order for Impeller Motor",
        "Open work order for Capsule Rectifier maintenance",
        "Open work order for Force Feeder maintenance",
        "Create a work order for Punch & Die Set calibration",
        "Open work order for Capsule Polishing Machine maintenance",
        "Create a preventive maintenance work order for Leaflet Inserter",
        "New work order for Friability Tester",
        "Create a preventive maintenance work order for Self-Adhesive Labeller",
        "Open work order for Punch & Die Set maintenance",
        "Create a work order for Inspection Conveyor calibration",
        "Open work order for Bin Lifter maintenance",
        "Create a work order for Tablet Counter calibration",
        "Open work order for Product Container maintenance",
        "Create a work order for Bin Lifter calibration",
        "Open work order for Capsule Deduster maintenance",
        "Create a preventive maintenance work order for Bottle Filler",
        "Open work order for Inspection Conveyor maintenance",
        "Create a preventive maintenance work order for Tamping Pin Set",
        "Open work order for Spray Gun Assembly maintenance",
        "New work order for RPM Counter",
        "Create a preventive maintenance work order for Dosing Disc Set",
        "Create a work order for Leaflet Inserter calibration",
        "Open work order for Hot Water Generator maintenance",
        "New work order for Differential Pressure Gauge",
        "Create a work order for Spray Gun Assembly calibration",
        "Create a work order for Foil Unwinder calibration",
        "Create a work order for Tablet Polisher calibration",
        "Create a work order for Capsule Rectifier calibration",
        "Create a preventive maintenance work order for Bin Lifter",
        "Create a preventive maintenance work order for Tablet Polisher",
        "Open work order for Orientation Sorter maintenance",
        "Create a preventive maintenance work order for Orientation Sorter",
        "Create a preventive maintenance work order for Force Feeder",
    ],
}
