"""Intent examples: work_order_query (part 2/5)."""

from __future__ import annotations

EXAMPLES: dict[str, list[str]] = {
    "work_order_query": [
        "What has Rajesh Nair been assigned?",
        "Get details for CAL-TWR-001",
        "Work orders assigned to Swati Deshmukh",
        "How is work order CAL-FRB-001?",
        "Display CAL-WGT-001",
        "Show me work order WO-00161",
        "Fetch WO-00114",
        "What work orders are for Chopper Motor?",
        "Show Mamta Banerjee's assignments",
        "What is WO-00196?",
        "What is PM-RMG-001?",
        "Fetch WO-00130",
        "Work orders assigned to Rajesh Patel",
        "What is Priya Patel working on?",
        "Work orders assigned to Amit Singh",
        "Show me tasks for Arun Choudhary",
        "Show details for work order CAL-TMP-001",
        "Show Nisha Agarwal's assignments",
        "Show me work order WO-00126",
        "Open EM-WO--020",
        "Show me tasks for Arjun Mehta",
        "Show me tasks for Lata Hegde",
        "Open WO-00135",
        "List tasks for Swati Deshmukh",
        "What has Prasad Gokhale been assigned?",
        "Open PRD-014",
        "Display WO-00132",
        "What work orders are for Sieve?",
        "What is Sanjay Rao working on?",
        "Fetch EM-WO-013",
        "List tasks for Manish Tiwari",
        "Show work orders for Material Transfer Trolley",
        "Maintenance orders for RPM Controller",
        "List tasks for Vikram Desai",
        "Display WO-00147",
        "List tasks for Arun Choudhary",
        "View work order WO-00180",
        "Show details for work order WO-00144",
        "What has Ritu Saxena been assigned?",
        "Fetch CAL-TMP-004",
        "Show me tasks for Sunita Kulkarni",
        "Work orders assigned to Suresh Kumar",
        "Maintenance orders for SS Bin",
        "What is the status of work order WO-00195?",
        "Show work orders for Batch Coding Machine",
        "Status of CAL-DPG-002",
        "Get details for PM-TBP-002",
        "What has Pooja Verma been assigned?",
        "Work order WO-00097 details",
        "Get details for WO-00193",
        "What is PRD-005?",
        "What work orders are for Batch Coding Machine?",
        "Work order WO-00139 details",
        "List tasks for Anjali Reddy",
        "Work order WO-00170 details",
        "What has Tarun Chopra been assigned?",
        "Show work orders for Metal Detector",
        "Work order WO-00093 details",
        "How is work order WO-00157?",
        "Display PRD-004",
        "Work order CAL-VIS-002B details",
        "Work orders assigned to Lata Hegde",
        "Work order CAL-FRB-001 details",
        "Fetch WO-00188",
        "Open CAL-LOD-001",
        "What is the status of work order PRD-009?",
        "Fetch WO-00107",
        "List tasks for Ritu Saxena",
        "Display PM-ACT-001",
        "Show me tasks for Meera Iyer",
        "What is CAL-TMP-001?",
        "What is the status of work order PM-TBP-001?",
        "What is the status of work order WO-00147?",
        "What work orders are for Impeller Motor?",
        "Fetch PRD-004",
        "Tell me about work order WO-00158",
        "Show details for work order WO-00163",
        "Display WO-00123",
        "Show work orders for Finger Bag Set",
        "Get details for CAL-BAL-002",
        "Show me work order WO-00200",
        "Display WO-00157",
        "What is WO-MAINT-2026-0042?",
        "Show Neha Gupta's assignments",
        "How is work order CAL-DPG-001?",
        "Work order WO-00103 details",
        "Work order WO-00190 details",
        "Show details for work order WO-00135",
        "What has Rahul Sharma been assigned?",
        "Show details for work order WO-00145",
        "Show Swati Deshmukh's assignments",
        "List tasks for Lata Hegde",
        "Display PRD-001",
        "Display WO-00195",
        "What has Aarav Mehta been assigned?",
        "Maintenance orders for Exhaust Blower",
        "Fetch EM-WO--019",
        "What is PRD-011?",
        "Get details for PM-AHU-002",
        "Get details for PM-LAF-001",
        "Status of PM-AHU-001",
        "Display WO-00189",
        "Tell me about work order WO-00191",
        "Get details for WO-00200",
        "View work order PM-CTM-001",
        "Open WO-00145",
        "What work orders are for Closing Module?",
        "Maintenance orders for Hot Water Generator",
        "View work order CAL-RH-002",
        "Work order CAL-MMT-001 details",
        "Display WO-00141",
        "Tell me about work order CAL-TWR-001",
        "Tell me about work order PRD-016",
        "View work order WO-00115",
        "Maintenance orders for Rejection Bin",
        "How is work order WO-00154?",
        "Status of WO-00124",
        "Status of EM-WO-008",
        "Display WO-00149",
        "What is the status of work order CAL-VIS-001B?",
        "Show me work order WO-00130",
        "Tell me about work order WO-00121",
        "Show Rohan Bhat's assignments",
        "Maintenance orders for Force Feeder",
        "How is work order WO-00145?",
        "Work orders assigned to Devansh Kapoor",
        "What has Deepa Menon been assigned?",
        "What is CAL-CWG-002?",
        "Show me work order WO-00118",
        "List tasks for Prasad Gokhale",
        "View work order WO-00120",
        "Work orders assigned to Tarun Chopra",
        "View work order WO-00196",
        "What is the status of work order CM-002?",
        "What work orders are assigned to Meera Iyer?",
        "What is the status of work order CAL-CLM-001?",
        "How is work order WO-00097?",
        "Status of WO-00090",
        "What is CAL-MOI-001?",
        "What work orders are assigned to Anjali Reddy?",
        "Show work orders for Leaflet Inserter",
        "Show me work order CAL-LOD-001",
        "Show me work order WO-00178",
        "Show details for work order WO-00133",
        "Status of WO-00143",
        "Open PM-TBP-001",
        "What has Neha Gupta been assigned?",
        "Tell me about work order WO-00113",
        "What is the status of work order WO-00129?",
        "Show me tasks for Suresh Kumar",
        "What has Karthik Subramanian been assigned?",
        "Maintenance orders for Dosing Disc Set",
        "Status of WO-00144",
        "Work orders assigned to Deepa Menon",
        "Open WO-00187",
        "View work order PRD-007",
        "What is the status of work order PRD-005?",
        "Open EM-WO--016",
        "Show me tasks for Rajesh Nair",
        "Maintenance orders for Lubricant Dispenser",
        "How is work order WO-00156?",
        "Status of WO-00130",
        "Show work orders in Finance",
        "How is work order PM-RMG-001?",
        "Work order WO-00089 details",
        "View work order EM-WO-008",
        "Show me work order WO-00109",
        "Status of WO-00186",
        "View work order WO-00090",
        "Maintenance orders for Bottle Filler",
        "Maintenance orders for Floor Scale",
        "Status of PRD-008",
        "Show work orders for Punch & Die Set",
        "Show me work order WO-00186",
        "Tell me about work order EM-WO-002",
        "View work order WO-00189",
        "Status of WO-00148",
        "Work orders assigned to Vivek Malhotra",
        "Status of WO-00170",
        "What is the status of work order PM-FBD-001?",
        "Status of PM-ACT-001",
        "Open WO-00169",
        "Fetch CAL-FRB-001",
        "What is the status of work order PRD-016?",
        "View work order WO-00193",
        "Work order PRD-015 details",
        "Maintenance orders for Bin Lifter",
        "What has Rekha Pillai been assigned?",
        "Work order WO-00141 details",
        "Tell me about work order EM-WO-022",
        "Display CAL-TMP-002",
        "Maintenance orders for Cartoning Machine",
        "What work orders are assigned to Manish Tiwari?",
        "Status of CAL-MMT-001",
        "List tasks for Meera Iyer",
        "Show Sunita Kulkarni's assignments",
        "Show me tasks for Amit Singh",
        "Show repair work orders",
        "Status of CAL-THM-002",
        "Show Priya Patel's assignments",
        "Get details for PRD-010",
        "Open CAL-TWR-001",
        "Open WO-00159",
        "What has Rohit Verma been assigned?",
        "What is Mamta Banerjee working on?",
        "Open WO-00139",
        "Tell me about work order WO-00170",
        "Work order WO-00156 details",
        "Open EM-WO-017",
        "Show me tasks for Karan Shah",
        "Show details for work order WO-00142",
        "Maintenance orders for Capsule Deduster",
        "What work orders are assigned to Karthik Subramanian?",
        "View work order WO-00101",
        "Show details for work order PRD-013",
        "Work orders assigned to Rajesh Nair",
        "Work order WO-00154 details",
        "Show Suresh Kumar's assignments",
        "Work orders assigned to Karthik Subramanian",
        "What work orders are for Dust Extractor?",
        "Status of WO-00142",
        "Show work orders for Tablet Deduster",
        "Fetch WO-00159",
        "How is work order WO-00115?",
        "Display WO-00162",
        "View work order PRD-006",
        "Find work orders for department Warehouse & Logistics",
        "What work orders are for Desiccant Inserter?",
        "Show me work order WO-00176",
        "Status of WO-00195",
        "What is the status of work order WO-00180?",
        "Open WO-00196",
        "What work orders are for Blister Packing Machine?",
        "Show me work order CAL-TAC-001",
        "Status of EM-WO-005",
        "Fetch PRD-001",
        "What is WO-00117?",
        "Show details for work order WO-00138",
        "Show details for work order EM-WO-018",
        "Display EM-WO-017",
        "Work order WO-00189 details",
        "What is WO-00094?",
        "Show work orders for Overhead Stirrer",
        "Status of WO-00106",
        "What work orders are assigned to Shruti Kulkarni?",
        "Tell me about work order WO-00087",
        "List Human Resources work orders",
        "Display WO-00106",
        "Display CAL-MMT-001",
        "Work order PM-FBD-001 details",
        "View work order WO-00126",
        "View work order WO-00154",
        "Show me tasks for Pooja Verma",
        "Work order WO-00092 details",
        "Show me work order EM-WO-008",
        "Maintenance orders for Self-Adhesive Labeller",
        "What work orders are for Metal Detector?",
        "What is EM-WO-017?",
        "What is the status of work order WO-00137?",
        "Maintenance orders for Overhead Stirrer",
        "Get details for PRD-002",
        "Show Nitin Saxena's assignments",
        "Work orders assigned to Rekha Pillai",
        "Show details for work order WO-00091",
        "What is the status of work order WO-00194?",
        "What is WO-00162?",
        "Work orders assigned to Vikram Desai",
        "Open WO-00144",
        "Tell me about work order CAL-VIS-001B",
        "Status of EM-WO--020",
        "Work order CAL-BAL-001 details",
        "Open CAL-TMP-003",
        "What is Manish Tiwari working on?",
        "Tell me about work order WO-00128",
        "Show Shruti Kulkarni's assignments",
        "What is WO-00182?",
        "Fetch CAL-THM-001",
        "How is work order WO-00125?",
        "Fetch WO-00120",
        "Maintenance orders for Product Container",
        "How is work order WO-00160?",
        "What is Sunita Kulkarni working on?",
        "What is WO-00101?",
        "What work orders are for Lubricant Dispenser?",
        "What is the status of work order WO-00091?",
        "Get details for WO-MAINT-2026-0050",
        "Show me work order WO-00174",
        "Show me work order CAL-WGT-001",
        "Work order EM-WO-022 details",
        "Show me work order WO-00136",
        "Tell me about work order WO-00114",
        "What has Priya Sharma been assigned?",
        "Tell me about work order WO-00091",
        "What work orders are for AHU?",
        "Work order WO-00110 details",
        "Fetch PM-TBP-001",
        "Display WO-00167",
        "Show work orders for Capsule Rectifier",
        "What work orders are assigned to Ashwini Kulkarni?",
        "Status of WO-00095",
        "Fetch WO-MAINT-2026-0042",
        "Status of WO-00125",
        "Fetch PRD-008",
        "View work order PM-TBP-001",
        "Display PM-LAF-001",
        "Status of PRD-014",
        "Open WO-00184",
        "Display CAL-DPG-002",
        "Maintenance orders for Cap Sealer",
        "What is WO-00135?",
        "Show Lata Hegde's assignments",
        "Open WO-00195",
        "Display CAL-BAL-001",
        "What is PRD-010?",
        "What is WO-00098?",
        "Fetch WO-00187",
        "What work orders are assigned to Divya Pandey?",
        "Tell me about work order WO-00188",
        "What is WO-00154?",
        "What is CAL-FRB-001?",
        "Show me work order WO-00105",
        "What is Ritu Saxena working on?",
        "How is work order WO-00169?",
        "Status of CAL-LPC-001",
        "What is CAL-DPG-002?",
        "What is the status of work order WO-00181?",
        "What is WO-00130?",
        "What is Nitin Saxena working on?",
        "Show me work order WO-00143",
        "Get details for WO-00180",
        "What is WO-00163?",
        "Status of EM-WO--021",
        "Tell me about work order CAL-MOI-001",
        "List tasks for Rahul Sharma",
        "Show details for work order WO-00182",
        "Tell me about work order WO-00120",
        "Tell me about work order CAL-TMP-004",
        "What has Gaurav Mishra been assigned?",
        "What is Pallavi Joshi working on?",
        "How is work order WO-00123?",
        "Status of WO-00097",
        "What is the status of work order WO-00087?",
        "What work orders belong to Quality Control?",
        "Show me work order WO-00151",
        "Maintenance orders for Capsule Rectifier",
        "Work orders assigned to Aditya Bose",
        "Show me tasks for Manish Tiwari",
        "Open WO-00126",
        "What is Rohit Verma working on?",
        "Open WO-00168",
        "Tell me about work order PM-TBP-002",
        "Show other work orders",
        "Show me work order CAL-WGT-002",
        "Show me work order EM-WO--020",
        "Status of WO-00145",
        "What is Prasad Gokhale working on?",
        "Work order WO-00147 details",
        "Display WO-00143",
        "Open CAL-CWG-002",
        "Show me tasks for Deepa Menon",
        "Get details for WO-00104",
        "What is the status of work order PRD-006?",
        "List tasks for Divya Pandey",
        "Get details for PM-AHU-001",
        "What is Divya Pandey working on?",
        "What is WO-00160?",
        "Show details for work order WO-00200",
        "How is work order WO-00138?",
        "What has Rohan Bhat been assigned?",
        "What work orders are assigned to Rohan Bhat?",
        "Show details for work order CAL-TWR-001",
        "Show Gaurav Mishra's assignments",
        "What work orders are assigned to Sunita Kulkarni?",
        "What work orders are assigned to Pallavi Joshi?",
        "List tasks for Rahul Deshmukh",
        "Status of WO-00174",
        "Work order WO-00191 details",
        "What is Neha Gupta working on?",
        "View work order WO-00109",
        "Fetch WO-00116",
        "How is work order WO-00114?",
        "Work order PRD-004 details",
        "View work order WO-00097",
        "Get details for WO-00097",
        "Show work orders for Force Feeder",
        "Display WO-00103",
        "What is CAL-THM-002?",
        "Show Ashwini Kulkarni's assignments",
        "Show me tasks for Vivek Malhotra",
        "How is work order WO-00184?",
        "Work order EM-WO-013 details",
        "Maintenance orders for Tablet Deduster",
        "Work orders assigned to Arjun Mehta",
        "Tell me about work order WO-00137",
        "Work order WO-00087 details",
        "Open EM-WO-011",
        "View work order WO-00144",
        "Get details for WO-00148",
        "What work orders are assigned to Rahul Sharma?",
        "What is the status of work order WO-00092?",
        "List tasks for Sachin Kulkarni",
        "What work orders are for Capsule Counter?",
        "Tell me about work order PM-LAF-001",
        "What has Manish Tiwari been assigned?",
        "Display WO-00151",
        "Show me work order CAL-RH-002",
        "How is work order EM-WO-007?",
        "Open WO-00130",
        "List tasks for Amit Singh",
        "List Quality Control work orders",
        "Get details for WO-00142",
        "What work orders are for Peristaltic Pump?",
        "Show work orders for Dust Collector",
        "Show me work order WO-00188",
        "Show me work order WO-00124",
        "What is CAL-DPG-001?",
        "What is the status of work order WO-00164?",
        "What is PRD-003?",
        "View work order WO-00129",
        "Get details for WO-00171",
        "Show me work order WO-00144",
        "What is Suresh Kumar working on?",
        "What is the status of work order WO-00134?",
        "Tell me about work order PM-BPM-001",
        "What is the status of work order CAL-TMP-002?",
        "Show Karthik Subramanian's assignments",
        "Open WO-00108",
        "Show me work order WO-00170",
        "Fetch WO-00146",
        "View work order WO-00137",
        "List tasks for Mamta Banerjee",
        "Open CAL-DIS-001",
        "Show Rajesh Patel's assignments",
        "View work order WO-00156",
        "How is work order CAL-TWR-001?",
        "Display WO-00175",
        "Show me work order CAL-BAL-002",
        "Display CAL-LPC-001",
        "Show work orders for Cartoning Machine",
        "Show details for work order WO-00118",
        "Open WO-00173",
        "Tell me about work order PRD-006",
        "Show work orders for Exhaust Blower",
        "Status of WO-00154",
        "Show me work order WO-00149",
        "Show work orders for SS Bin",
        "Display PRD-002",
        "Open WO-00127",
        "Show me tasks for Rahul Sharma",
        "Show me tasks for Rohan Bhat",
        "Fetch WO-00133",
        "Tell me about work order WO-00148",
        "How is work order CAL-DIS-001?",
        "What work orders are for Bin Lifter?",
        "What is the status of work order WO-00094?",
        "List tasks for Sanjay Rao",
        "What is the status of work order WO-00099?",
        "Open WO-00192",
        "Fetch PM-BPM-001",
        "Show work orders for Discharge Trolley",
        "Display PRD-014",
        "List tasks for Shruti Kulkarni",
        "Display PM-TBP-001",
        "Open WO-00098",
        "Maintenance orders for Punch & Die Set",
        "Work orders assigned to Rahul Sharma",
        "Open WO-00158",
        "Get details for CAL-WGT-001",
        "How is work order EM-WO-006?",
        "What has Suresh Kumar been assigned?",
        "Work order PRD-010 details",
        "Show details for work order WO-00158",
        "Work orders assigned to Kavita Joshi",
        "Tell me about work order WO-00126",
        "Display WO-00178",
        "Work order WO-00094 details",
        "What has Vikram Desai been assigned?",
        "Fetch PM-LAF-001",
        "How is work order WO-00196?",
        "Work order WO-00100 details",
        "Open WO-00106",
        "Get details for EM-WO--016",
        "Show details for work order CAL-RH-001",
        "Open PRD-010",
        "What is Devansh Kapoor working on?",
        "Get details for PM-CTM-001",
        "View work order WO-00170",
        "How is work order EM-WO-018?",
        "Open PM-TBP-002",
    ],
}
