"""Intent examples: work_order_query (part 1/5)."""

from __future__ import annotations

EXAMPLES: dict[str, list[str]] = {
    "work_order_query": [
        "List completed work orders",
        "Show Arjun Mehta's assignments",
        "What work orders are overdue?",
        "Show me work order EM-WO--014",
        "What work orders have status Todo?",
        "Show critical work orders",
        "List tasks for Gaurav Mishra",
        "What work orders are assigned to Tarun Chopra?",
        "Filter work orders by type Repair",
        "Find work orders that are in progress",
        "Show work orders in Quality Assurance",
        "What work orders belong to Human Resources?",
        "List high priority work orders",
        "Filter work orders by type Calibration",
        "Show me work order WO-00162",
        "What is WO-00107?",
        "Find work orders that are scheduled",
        "List tasks for Rohit Verma",
        "Tell me about work order WO-00184",
        "Show me work order WO-00171",
        "Show work orders with high priority",
        "List medium priority work orders",
        "Display PM-AHU-002",
        "Open WO-00109",
        "Display WO-00094",
        "Status of CAL-HRD-001",
        "All work orders",
        "Show details for work order WO-00175",
        "Show all todo work orders",
        "Status of CAL-CLM-001",
        "Status of WO-00139",
        "What work orders are assigned to Ritu Saxena?",
        "What low priority work orders exist?",
        "List work orders in Todo state",
        "What has Shruti Kulkarni been assigned?",
        "List all maintenance work orders",
        "What has Amit Singh been assigned?",
        "Display WO-00117",
        "What are the urgent work orders?",
        "Work orders assigned to Priya Patel",
        "Count total work orders",
        "How many work orders do we have?",
        "Show me calibration work orders",
        "Status of WO-00104",
        "What work orders are there?",
        "Show details for work order CAL-MMT-001",
        "Work order summary",
        "List Regulatory Affairs work orders",
        "What is Karthik Subramanian working on?",
        "Show work order list",
        "What has Arun Choudhary been assigned?",
        "What has Sachin Kulkarni been assigned?",
        "Show work orders by priority",
        "Tell me about work order PRD-013",
        "How is work order EM-WO-005?",
        "Show work orders in EHS",
        "Show me work orders that are overdue",
        "Display WO-00153",
        "What other work orders do we have?",
        "List all open work orders",
        "How is work order EM-WO-011?",
        "What is Deepa Menon working on?",
        "What is the status of work order CAL-TMP-003?",
        "What work orders are for Capsule Polishing Machine?",
        "Filter work orders by type Other",
        "Show Pooja Verma's assignments",
        "Show work orders in Supply Chain",
        "What work orders are for Hot Water Generator?",
        "What calibration work orders do we have?",
        "Fetch PM-DCU-001",
        "What work orders have status In Progress?",
        "What is Shruti Kulkarni working on?",
        "List work orders in In Progress state",
        "Find work orders that are completed",
        "List tasks for Pallavi Joshi",
        "What work orders have status Completed?",
        "Show me tasks for Shruti Kulkarni",
        "What work orders belong to Finance?",
        "What is WO-00090?",
        "Maintenance orders for Finger Bag Set",
        "Filter work orders by type Inspection",
        "Work order PM-AHU-002 details",
        "Show calibration work orders",
        "Fetch WO-00167",
        "How is work order WO-00111?",
        "Open PRD-006",
        "Find work orders that are todo",
        "Get details for WO-00194",
        "List work orders in Scheduled state",
        "Status of WO-00138",
        "Find work orders for department Supply Chain",
        "List tasks for Nisha Agarwal",
        "Open CM-002",
        "Maintenance orders for Illuminated Inspection Table",
        "Find work orders for department Regulatory Affairs",
        "Show work orders for Foil Unwinder",
        "Show me tasks for Sachin Kulkarni",
        "What inspection work orders do we have?",
        "What work orders are for Material Transfer Trolley?",
        "What is the status of work order WO-00127?",
        "List all other work orders",
        "What is Pooja Verma working on?",
        "Fetch PM-RMG-001",
        "List tasks for Rohan Bhat",
        "List tasks for Tarun Chopra",
        "List EHS work orders",
        "Show me work order CAL-VIS-002B",
        "What maintenance work orders do we have?",
        "What is WO-00099?",
        "Show me work order WO-00122",
        "What has Divya Pandey been assigned?",
        "Show work orders for Illuminated Inspection Table",
        "Filter work orders by type Installation",
        "Status of CAL-VIS-001B",
        "Work orders assigned to Sunita Kulkarni",
        "What is EM-WO-011?",
        "Filter work orders by type Maintenance",
        "Show Prasad Gokhale's assignments",
        "What has Aditya Bose been assigned?",
        "Get details for PM-DCU-001",
        "List Supply Chain work orders",
        "Fetch CAL-VIS-002B",
        "Maintenance orders for Pallet Truck",
        "What work orders are assigned to Vikram Desai?",
        "Show me work order PM-CTM-001",
        "Display WO-00172",
        "List Operations work orders",
        "List all installation work orders",
        "List tasks for Priya Sharma",
        "Show me all work orders",
        "Show work orders for Rejection Bin",
        "What work orders are assigned to Deepa Menon?",
        "Status of WO-00133",
        "How is work order WO-00112?",
        "Show me tasks for Pallavi Joshi",
        "What is the status of work order CAL-DPG-002?",
        "What work orders are in progress?",
        "List tasks for Neha Gupta",
        "What work orders are assigned to Priya Sharma?",
        "Show Rajesh Nair's assignments",
        "Find work orders for department EHS",
        "Status of PRD-006",
        "View work order WO-00093",
        "What work orders are assigned to Neha Gupta?",
        "View work order WO-MAINT-2026-0050",
        "Work order WO-00148 details",
        "Status of WO-00173",
        "Show work orders in Operations",
        "Show details for work order WO-00189",
        "What work orders are assigned to Rahul Deshmukh?",
        "Show me tasks for Aditya Bose",
        "How is work order WO-00127?",
        "Show work orders for Lubricant Dispenser",
        "List Quality Assurance work orders",
        "Show Vivek Malhotra's assignments",
        "Show work orders for Desiccant Inserter",
        "Open WO-00129",
        "What is CAL-DIS-001?",
        "Show work orders with status In Progress",
        "Work orders assigned to Rohan Bhat",
        "What work orders are assigned to Nitin Saxena?",
        "Display WO-00110",
        "Show me work order WO-00159",
        "Work order CAL-TMP-001 details",
        "Show me work order PM-TBP-001",
        "Show me tasks for Vikram Desai",
        "List tasks for Kavita Joshi",
        "Show me work order WO-00163",
        "Get details for WO-00176",
        "Work orders assigned to Nitin Saxena",
        "What work orders belong to Regulatory Affairs?",
        "List tasks for Aditya Bose",
        "List all repair work orders",
        "Fetch WO-00178",
        "What is the status of work order CAL-MOI-001?",
        "Show work orders for Self-Adhesive Labeller",
        "What work orders are for Dosing Disc Set?",
        "Show work orders with status Scheduled",
        "What is Tarun Chopra working on?",
        "What work orders have status On Hold?",
        "How is work order WO-00200?",
        "Show work orders for Sampling Spatula",
        "What work orders are for Inspection Conveyor?",
        "Open WO-00143",
        "Work order CAL-BAL-002 details",
        "What installation work orders do we have?",
        "View work order WO-00176",
        "Maintenance orders for Dust Collector",
        "Status of WO-00191",
        "What work orders are for Pallet Truck?",
        "What is EM-WO-001?",
        "What is the status of work order WO-00119?",
        "Get details for CAL-LPC-001",
        "Show work orders in Warehouse & Logistics",
        "Show me tasks for Swati Deshmukh",
        "What work orders are for Overhead Stirrer?",
        "What has Nisha Agarwal been assigned?",
        "Get details for PM-ACT-001",
        "Tell me about work order PM-FBD-001",
        "What has Meera Iyer been assigned?",
        "View work order EM-WO--019",
        "List work orders in On Hold state",
        "What repair work orders do we have?",
        "Maintenance orders for Impeller Motor",
        "Show details for work order WO-00174",
        "Fetch CAL-CWG-001",
        "View work order WO-00168",
        "Show me tasks for Ashwini Kulkarni",
        "What work orders are assigned to Lata Hegde?",
        "What is WO-00087?",
        "What work orders are for Spray Gun Assembly?",
        "Show work orders with status Completed",
        "Get details for WO-00138",
        "Status of WO-00192",
        "What is Vivek Malhotra working on?",
        "Show work orders for Cap Sealer",
        "Show Ritu Saxena's assignments",
        "What is Vikram Desai working on?",
        "Get details for WO-00116",
        "List Warehouse & Logistics work orders",
        "Find work orders for department Quality Control",
        "What work orders are assigned to Suresh Kumar?",
        "Work orders assigned to Divya Pandey",
        "What has Lata Hegde been assigned?",
        "What has Rahul Deshmukh been assigned?",
        "What is WO-00105?",
        "Maintenance orders for Orientation Sorter",
        "What has Sanjay Rao been assigned?",
        "List all calibration work orders",
        "What work orders belong to Engineering?",
        "Open WO-00107",
        "View work order WO-00087",
        "View work order EM-WO--020",
        "Show me tasks for Rekha Pillai",
        "Show details for work order PRD-014",
        "Maintenance orders for Peristaltic Pump",
        "Find work orders that are on hold",
        "What has Mamta Banerjee been assigned?",
        "List all inspection work orders",
        "What is WO-MAINT-2026-0050?",
        "Show work orders in Quality Control",
        "What work orders are for Rejection Bin?",
        "What is CAL-RH-002?",
        "Show Devansh Kapoor's assignments",
        "Status of CM-002",
        "Show details for work order WO-00187",
        "Show me tasks for Aarav Mehta",
        "Tell me about work order WO-00185",
        "What is the status of work order CAL-WGT-002?",
        "How is work order WO-00188?",
        "Tell me about work order WO-00183",
        "Tell me about work order WO-00186",
        "Tell me about work order WO-00086",
        "Show work orders with status Todo",
        "List Engineering work orders",
        "How is work order WO-00122?",
        "Status of EM-WO-007",
        "What is Rajesh Nair working on?",
        "Status of WO-00128",
        "Work order WO-00193 details",
        "How is work order EM-WO-013?",
        "Show Anjali Reddy's assignments",
        "Tell me about work order WO-00123",
        "What is Meera Iyer working on?",
        "Show work orders for Peristaltic Pump",
        "Show Rahul Sharma's assignments",
        "Show Pallavi Joshi's assignments",
        "What is WO-00125?",
        "Tell me about work order WO-00144",
        "Maintenance orders for Desiccant Inserter",
        "Tell me about work order WO-00157",
        "View work order WO-00166",
        "What work orders are assigned to Pooja Verma?",
        "Display WO-00193",
        "How is work order CAL-BAL-001?",
        "How is work order EM-WO-008?",
        "Get details for WO-00175",
        "Show me tasks for Anjali Reddy",
        "Tell me about work order WO-00152",
        "What work orders belong to EHS?",
        "What work orders belong to Quality Assurance?",
        "Show work orders in Engineering",
        "How is work order WO-00164?",
        "How is work order PRD-011?",
        "Display PRD-007",
        "Display CAL-TMP-004",
        "Show details for work order PM-FBD-001",
        "Show inspection work orders",
        "Show me work order WO-00183",
        "Fetch WO-00086",
        "List tasks for Nitin Saxena",
        "View work order CAL-MMT-001",
        "How is work order WO-00130?",
        "What is Amit Singh working on?",
        "Work order WO-00118 details",
        "Work order WO-00181 details",
        "Display WO-00163",
        "What is WO-00175?",
        "Show me work order WO-00142",
        "Show me tasks for Nisha Agarwal",
        "Work order WO-00198 details",
        "Display WO-00087",
        "What has Arjun Mehta been assigned?",
        "What work orders are assigned to Rekha Pillai?",
        "What work orders belong to Supply Chain?",
        "Fetch WO-00136",
        "What is PRD-004?",
        "View work order CAL-FRB-001",
        "What is the status of work order WO-00152?",
        "Show me work order EM-WO-013",
        "What is Nisha Agarwal working on?",
        "What is Ashwini Kulkarni working on?",
        "What work orders have status Scheduled?",
        "Status of WO-00163",
        "What has Anjali Reddy been assigned?",
        "Show work orders in Human Resources",
        "Show installation work orders",
        "Tell me about work order WO-00165",
        "Fetch WO-00171",
        "Tell me about work order PM-DCU-001",
        "List tasks for Pooja Verma",
        "What is EM-WO--012?",
        "Show me tasks for Priya Patel",
        "Display WO-00150",
        "Open CAL-THM-002",
        "What is WO-00136?",
        "Find work orders for department Finance",
        "How is work order WO-00185?",
        "Show me tasks for Neha Gupta",
        "Show me tasks for Mamta Banerjee",
        "Show me tasks for Karthik Subramanian",
        "Display EM-WO--019",
        "Display PM-DCU-001",
        "Maintenance orders for Material Transfer Trolley",
        "What work orders are assigned to Amit Singh?",
        "Show details for work order WO-00116",
        "Work orders assigned to Nisha Agarwal",
        "Show work orders for Sieve",
        "What has Priya Patel been assigned?",
        "What work orders are assigned to Priya Patel?",
        "Find work orders for department Quality Assurance",
        "Status of PRD-009",
        "What is the status of work order WO-00168?",
        "Show me work order WO-00194",
        "What work orders are assigned to Rohit Verma?",
        "Maintenance orders for Batch Coding Machine",
        "Show Arun Choudhary's assignments",
        "What is the status of work order WO-00191?",
        "Fetch WO-00117",
        "Display WO-00144",
        "Get details for WO-00127",
        "Open PRD-013",
        "Show me work order PRD-005",
        "Show Karan Shah's assignments",
        "Get details for WO-00092",
        "Tell me about work order WO-00175",
        "What is the status of work order WO-00086?",
        "Open WO-00133",
        "What is WO-00200?",
        "How is work order WO-00161?",
        "How is work order WO-00102?",
        "How is work order EM-WO--004?",
        "Show me work order WO-00145",
        "Status of WO-00172",
        "Tell me about work order WO-00097",
        "Open CAL-RH-001",
        "Open WO-00096",
        "Status of WO-00200",
        "Work orders assigned to Rohit Verma",
        "Show me work order WO-00155",
        "What is the status of work order EM-WO-005?",
        "How is work order EM-WO-002?",
        "What is the status of work order WO-00100?",
        "What work orders are for SS Bin?",
        "View work order WO-00198",
        "Show details for work order EM-WO--012",
        "Fetch WO-00179",
        "Show Vikram Desai's assignments",
        "Fetch CM-001",
        "Show me work order WO-00133",
        "Show details for work order WO-00191",
        "What work orders are assigned to Arun Choudhary?",
        "What work orders are assigned to Arjun Mehta?",
        "Work orders assigned to Neha Gupta",
        "List tasks for Priya Patel",
        "How is work order PRD-003?",
        "How is work order WO-00124?",
        "Show details for work order CAL-DPG-001",
        "Show maintenance work orders",
        "What is the status of work order CAL-TAC-001?",
        "Find work orders for department Human Resources",
        "Display WO-00165",
        "Display WO-00190",
        "Display WO-00125",
        "Work order CAL-WGT-001 details",
        "How is work order EM-WO-001?",
        "Show me work order WO-00120",
        "What is the status of work order WO-00154?",
        "How is work order WO-MAINT-2026-0050?",
        "Open WO-00178",
        "Open WO-00140",
        "How is work order WO-00165?",
        "What work orders are assigned to Kavita Joshi?",
        "What work orders are for Orientation Sorter?",
        "Work order PM-BPM-001 details",
        "View work order WO-00174",
        "Open WO-00110",
        "Show me work order CAL-TMP-004",
        "Show me work order WO-00160",
        "Show me work order PRD-008",
        "Fetch EM-WO--004",
        "Get details for WO-00107",
        "What work orders are for Finger Bag Set?",
        "Display WO-00124",
        "Work order WO-00195 details",
        "Status of PRD-001",
        "How is work order WO-00140?",
        "View work order EM-WO--004",
        "What work orders are for Tablet Counter?",
        "Work order PRD-012 details",
        "Show Amit Singh's assignments",
        "Find work orders for department Operations",
        "Show me work order PM-LAF-001",
        "Work orders assigned to Pooja Verma",
        "What is PRD-014?",
        "Open WO-00163",
        "Show me tasks for Sanjay Rao",
        "What is the status of work order WO-00116?",
        "List tasks for Karan Shah",
        "How is work order WO-00139?",
        "What has Sunita Kulkarni been assigned?",
        "List tasks for Ashwini Kulkarni",
        "How is work order WO-00133?",
        "Show work orders in Regulatory Affairs",
        "What is CM-001?",
        "Fetch WO-00135",
        "View work order WO-MAINT-2026-0042",
        "Work orders assigned to Sanjay Rao",
        "Show me tasks for Priya Sharma",
        "Display PRD-011",
        "Work orders assigned to Sachin Kulkarni",
        "Show work orders for Product Container",
        "What work orders belong to Operations?",
        "What work orders are for Capsule Rectifier?",
        "What work orders are for Punch & Die Set?",
        "List tasks for Sunita Kulkarni",
        "Maintenance orders for Dust Extractor",
        "What work orders belong to Warehouse & Logistics?",
        "View work order PM-BLD-001",
        "Show work orders for Dust Extractor",
        "Show me work order CM-001",
        "What is WO-00173?",
        "Show work orders for Capsule Counter",
        "Maintenance orders for Sieve",
        "How is work order WO-00098?",
        "What is EM-WO-015?",
        "Fetch WO-00162",
        "Display WO-00170",
        "Work orders assigned to Arun Choudhary",
        "List Finance work orders",
        "What is the status of work order EM-WO-006?",
        "Display CAL-DPG-001",
        "Show work orders with status On Hold",
        "What work orders are for Floor Scale?",
        "Work order WO-MAINT-2026-0042 details",
        "Show details for work order PM-CFM-001",
        "Get details for WO-00162",
        "Maintenance orders for Foil Unwinder",
        "Work order WO-00105 details",
        "Status of WO-00089",
        "Show details for work order WO-00173",
        "What is the status of work order CAL-DPG-001?",
        "Find work orders for department Engineering",
        "Show work orders for Pallet Truck",
        "What has Ashwini Kulkarni been assigned?",
        "Status of CAL-TMP-003",
        "Show Divya Pandey's assignments",
        "How is work order WO-00108?",
        "How is work order CAL-RH-001?",
        "View work order EM-WO-003",
        "List work orders in Completed state",
        "What is WO-00192?",
        "Tell me about work order PRD-012",
        "Show work orders for Spray Gun Assembly",
        "Get details for WO-00143",
        "What is Anjali Reddy working on?",
        "Show work orders for Tamping Pin Set",
        "What is WO-00195?",
        "Show Sanjay Rao's assignments",
    ],
}
