"""Intent examples: worker (part 2/2)."""

from __future__ import annotations

EXAMPLES: dict[str, list[str]] = {
    "worker": [
        "Show Rahul Deshmukh profile",
        "Show Nitin Saxena's assignments",
        "Show Rohit Verma's assignments",
        "What work orders are assigned to Anjali Reddy?",
        "Schedule for Karthik Subramanian",
        "Workload for Aditya Bose",
        "Workload for Pooja Verma",
        "Show Sunita Kulkarni profile",
        "Show Neha Gupta profile",
        "What does Vikram Desai do?",
        "What work orders are assigned to Vikram Desai?",
        "Show Rahul Sharma profile",
        "Show Arjun Mehta's assignments",
        "What is Divya Pandey's role?",
        "What work orders are assigned to Priya Sharma?",
        "Schedule for Rajesh Nair",
        "Workload for Rekha Pillai",
        "Show Lata Hegde's assignments",
        "Schedule for Vikram Desai",
        "Workload for Divya Pandey",
        "What is Vikram Desai's role?",
        "Workload for Ashwini Kulkarni",
        "Show me tasks for Ritu Saxena",
        "What work orders are assigned to Karan Shah?",
        "Show all production workers",
        "Tell me about Priya Sharma",
        "Schedule for Sachin Kulkarni",
        "Tell me about Kavita Joshi",
        "Show Amit Singh profile",
        "What is Swati Deshmukh's role?",
        "What work orders are assigned to Karthik Subramanian?",
        "Schedule for Rajesh Patel",
        "Schedule for Devansh Kapoor",
        "Show Amit Singh's assignments",
        "Tell me about Karthik Subramanian",
        "What is Manish Tiwari's role?",
        "Tasks assigned to Ashwini Kulkarni",
        "List all operators in EHS",
        "Tasks assigned to Aarav Mehta",
        "Show Kavita Joshi's assignments",
        "Show all safety officers",
        "What is Nitin Saxena's role?",
        "What work orders are assigned to Prasad Gokhale?",
        "Workload for Priya Sharma",
        "What does Divya Pandey do?",
        "Tell me about Vivek Malhotra",
        "Show Rahul Deshmukh's assignments",
        "Workload for Karan Shah",
        "Show Rekha Pillai's assignments",
        "List plant safety officers",
        "Show me tasks for Ashwini Kulkarni",
        "Workload for Deepa Menon",
        "Tell me about Neha Gupta",
        "Tasks assigned to Rekha Pillai",
        "Workers in Regulatory Affairs",
        "What work orders are assigned to Rahul Sharma?",
        "What does Rajesh Patel do?",
        "Tasks assigned to Pallavi Joshi",
        "Tasks assigned to Nisha Agarwal",
        "What is Rahul Sharma's role?",
        "Tell me about Manish Tiwari",
        "Show Manish Tiwari profile",
        "Who is the manager of EHS?",
        "What does Suresh Kumar do?",
        "Tasks assigned to Suresh Kumar",
        "Show Arun Choudhary's assignments",
        "Schedule for Priya Patel",
        "List granulation operators",
        "Schedule for Arun Choudhary",
        "Tell me about Pooja Verma",
        "Tell me about Deepa Menon",
        "Show me tasks for Kavita Joshi",
        "Tell me about Prasad Gokhale",
        "Schedule for Shruti Kulkarni",
        "Tasks assigned to Meera Iyer",
        "Tell me about Ritu Saxena",
        "Workload for Anjali Reddy",
        "What is Prasad Gokhale's role?",
        "What work orders are assigned to Arjun Mehta?",
        "Show Ritu Saxena's assignments",
        "Show me tasks for Nitin Saxena",
        "Schedule for Rahul Deshmukh",
        "Tasks assigned to Mamta Banerjee",
        "What work orders are assigned to Kavita Joshi?",
        "What does Sachin Kulkarni do?",
        "Tasks assigned to Rohit Verma",
        "Tasks assigned to Devansh Kapoor",
        "Workload for Rahul Sharma",
        "What work orders are assigned to Sachin Kulkarni?",
        "What does Lata Hegde do?",
        "Show EHS team",
        "Workload for Sunita Kulkarni",
        "Staff of Finance",
        "Show Priya Patel's assignments",
        "Show Pallavi Joshi's assignments",
        "Tell me about Sanjay Rao",
        "Show Manish Tiwari's assignments",
        "Workload for Mamta Banerjee",
        "Tell me about Rohit Verma",
        "What work orders are assigned to Suresh Kumar?",
        "Workload for Rajesh Patel",
        "Show Divya Pandey profile",
        "Workload for Nisha Agarwal",
        "Show Pooja Verma profile",
        "Show Devansh Kapoor profile",
        "Schedule for Swati Deshmukh",
        "Schedule for Lata Hegde",
        "Schedule for Prasad Gokhale",
        "Show Sunita Kulkarni's assignments",
        "Workload for Pallavi Joshi",
        "What does Ritu Saxena do?",
        "What does Aarav Mehta do?",
        "Tasks assigned to Anjali Reddy",
        "What does Ashwini Kulkarni do?",
        "Tell me about Meera Iyer",
        "What does Sunita Kulkarni do?",
        "Tasks assigned to Arjun Mehta",
        "Show me tasks for Manish Tiwari",
        "Schedule for Gaurav Mishra",
        "Show Priya Sharma's assignments",
        "Tasks assigned to Rajesh Patel",
        "Show Rohan Bhat profile",
        "What work orders are assigned to Devansh Kapoor?",
        "Show Karthik Subramanian's assignments",
        "What work orders are assigned to Aarav Mehta?",
        "Schedule for Suresh Kumar",
        "Workload for Manish Tiwari",
        "Show me tasks for Devansh Kapoor",
        "What is Meera Iyer's role?",
        "Show Priya Sharma profile",
        "Show Vikram Desai profile",
        "Tell me about Sachin Kulkarni",
        "What work orders are assigned to Rajesh Patel?",
        "Show Karan Shah profile",
        "Workload for Gaurav Mishra",
        "Show Deepa Menon profile",
        "Schedule for Sanjay Rao",
        "Show Prasad Gokhale's assignments",
        "Show Meera Iyer profile",
        "What is Sanjay Rao's role?",
        "Schedule for Aarav Mehta",
        "Tell me about Pallavi Joshi",
        "What does Rajesh Nair do?",
        "Show Sachin Kulkarni's assignments",
        "Schedule for Aditya Bose",
        "Show Kavita Joshi profile",
        "Workload for Arun Choudhary",
        "Show me tasks for Arun Choudhary",
        "What work orders are assigned to Pooja Verma?",
        "Tell me about Shruti Kulkarni",
        "Tasks assigned to Rohan Bhat",
        "Show Lata Hegde profile",
        "Workload for Devansh Kapoor",
        "Schedule for Manish Tiwari",
        "What does Rahul Sharma do?",
        "Schedule for Karan Shah",
        "Show me tasks for Rahul Sharma",
        "Show me tasks for Rahul Deshmukh",
        "What does Arun Choudhary do?",
        "What is Rohan Bhat's role?",
        "Show Pooja Verma's assignments",
        "What does Priya Sharma do?",
        "Tell me about Arjun Mehta",
        "What does Gaurav Mishra do?",
        "What is Sunita Kulkarni's role?",
        "Tell me about Tarun Chopra",
        "What is Ritu Saxena's role?",
        "Show me tasks for Aarav Mehta",
        "Show me tasks for Sanjay Rao",
        "Show me tasks for Priya Sharma",
        "What does Vivek Malhotra do?",
        "Tasks assigned to Vivek Malhotra",
        "What work orders are assigned to Rahul Deshmukh?",
        "Show me tasks for Neha Gupta",
        "Workload for Vivek Malhotra",
        "Show Sanjay Rao profile",
        "Show Karan Shah's assignments",
        "What is Shruti Kulkarni's role?",
        "Tell me about Swati Deshmukh",
        "What does Mamta Banerjee do?",
        "Schedule for Rohan Bhat",
        "Show Rajesh Patel's assignments",
        "Schedule for Vivek Malhotra",
        "What does Rohit Verma do?",
        "Show me tasks for Vivek Malhotra",
        "Workload for Aarav Mehta",
        "What is Sachin Kulkarni's role?",
        "Show Mamta Banerjee's assignments",
        "What does Priya Patel do?",
        "List operators",
        "Workload for Meera Iyer",
        "Tell me about Arun Choudhary",
        "Schedule for Pooja Verma",
        "What work orders are assigned to Gaurav Mishra?",
        "Show Ritu Saxena profile",
        "What work orders are assigned to Meera Iyer?",
        "Show me tasks for Shruti Kulkarni",
        "What work orders are assigned to Lata Hegde?",
        "What work orders are assigned to Vivek Malhotra?",
        "What is Karan Shah's role?",
        "What does Rahul Deshmukh do?",
        "What does Swati Deshmukh do?",
        "Show Divya Pandey's assignments",
        "What is Devansh Kapoor's role?",
        "Show me tasks for Rajesh Nair",
        "What does Sanjay Rao do?",
        "Show Swati Deshmukh's assignments",
        "What does Kavita Joshi do?",
        "Show Nisha Agarwal's assignments",
        "Show me tasks for Gaurav Mishra",
        "Show me tasks for Sunita Kulkarni",
        "What does Shruti Kulkarni do?",
        "Tasks assigned to Ritu Saxena",
        "Schedule for Rohit Verma",
        "Workload for Sanjay Rao",
        "What is Mamta Banerjee's role?",
        "Tasks assigned to Sunita Kulkarni",
        "What work orders are assigned to Ritu Saxena?",
        "Show Rekha Pillai profile",
        "Show Aarav Mehta profile",
        "What work orders are assigned to Nisha Agarwal?",
        "What is Rajesh Nair's role?",
        "Schedule for Rekha Pillai",
        "What is Priya Sharma's role?",
        "Schedule for Mamta Banerjee",
        "Schedule for Deepa Menon",
        "Show me tasks for Pooja Verma",
        "What does Aditya Bose do?",
        "What work orders are assigned to Divya Pandey?",
        "What work orders are assigned to Manish Tiwari?",
        "Show Nitin Saxena profile",
        "Tell me about Rajesh Patel",
        "What is Kavita Joshi's role?",
        "What work orders are assigned to Rohit Verma?",
        "Show Mamta Banerjee profile",
        "What is Tarun Chopra's role?",
        "What work orders are assigned to Deepa Menon?",
        "Show Anjali Reddy profile",
        "Show me tasks for Swati Deshmukh",
        "What does Deepa Menon do?",
        "What work orders are assigned to Aditya Bose?",
        "Tasks assigned to Prasad Gokhale",
        "Workload for Rajesh Nair",
        "Show me tasks for Karan Shah",
        "What is Pallavi Joshi's role?",
        "Show Sanjay Rao's assignments",
        "Show me tasks for Divya Pandey",
        "Workload for Lata Hegde",
        "What does Tarun Chopra do?",
        "What does Prasad Gokhale do?",
        "Show Vivek Malhotra's assignments",
        "Workload for Rahul Deshmukh",
        "Show me tasks for Rohan Bhat",
        "Show Ashwini Kulkarni's assignments",
    ],
}
