"""Intent examples: work_order_query (part 3/5)."""

from __future__ import annotations

EXAMPLES: dict[str, list[str]] = {
    "work_order_query": [
        "How is work order CAL-BAL-002?",
        "List tasks for Vivek Malhotra",
        "Tell me about work order WO-00200",
        "View work order EM-WO-018",
        "Open WO-00141",
        "Show me work order WO-00140",
        "Open EM-WO-001",
        "Display WO-00183",
        "Show details for work order WO-00168",
        "View work order CAL-TAC-001",
        "Show work orders for Bottle Filler",
        "Status of WO-00105",
        "Status of WO-00155",
        "Fetch WO-00103",
        "Work order CAL-CWG-001 details",
        "Open WO-00089",
        "View work order WO-00152",
        "What is the status of work order WO-00192?",
        "Show me work order CAL-LPC-001",
        "Show work orders for Chopper Motor",
        "Fetch WO-00189",
        "Tell me about work order WO-00162",
        "Work orders assigned to Mamta Banerjee",
        "Show details for work order WO-00194",
        "What is WO-00171?",
        "Show me work order EM-WO-007",
        "View work order WO-00148",
        "Get details for WO-00112",
        "Work order WO-00091 details",
        "Tell me about work order PRD-011",
        "What is the status of work order WO-00115?",
        "Open WO-00193",
        "Show details for work order CAL-PRE-001",
        "Open WO-00114",
        "Work orders assigned to Anjali Reddy",
        "What is WO-00115?",
        "Open CAL-DPG-002",
        "Fetch WO-00110",
        "What is the status of work order EM-WO-010?",
        "Fetch WO-00148",
        "Display WO-00200",
        "Show Kavita Joshi's assignments",
        "Show Meera Iyer's assignments",
        "Show me work order WO-00173",
        "Status of WO-00167",
        "What is WO-00152?",
        "Tell me about work order WO-00155",
        "What is the status of work order WO-00153?",
        "Open EM-WO-007",
        "Tell me about work order WO-00117",
        "How is work order WO-00116?",
        "Status of CAL-DIS-001",
        "Display WO-00111",
        "Status of PRD-007",
        "Work order WO-00124 details",
        "What work orders are assigned to Aarav Mehta?",
        "Open WO-00175",
        "Display WO-00137",
        "What work orders are for Illuminated Inspection Table?",
        "Fetch WO-00153",
        "Show me work order PRD-002",
        "Tell me about work order PRD-001",
        "What has Vivek Malhotra been assigned?",
        "What work orders are assigned to Nisha Agarwal?",
        "What is WO-00157?",
        "What work orders are for Cartoning Machine?",
        "Open EM-WO-022",
        "Status of WO-00176",
        "Work order PM-ACT-001 details",
        "Open WO-00105",
        "View work order WO-00191",
        "What is WO-00184?",
        "Display CAL-CWG-002",
        "What is the status of work order WO-00150?",
        "What is PM-ACT-001?",
        "Fetch PRD-015",
        "Tell me about work order WO-00089",
        "Show details for work order WO-00156",
        "Get details for CAL-MMT-001",
        "Tell me about work order PRD-009",
        "Status of WO-00169",
        "How is work order WO-00132?",
        "Fetch WO-00164",
        "Tell me about work order WO-00177",
        "What is the status of work order CAL-HRD-001?",
        "Get details for CAL-TMP-004",
        "Show details for work order WO-00125",
        "Status of WO-00121",
        "View work order WO-00139",
        "What work orders are for Sampling Spatula?",
        "Work order WO-00135 details",
        "Status of WO-00126",
        "Work order WO-00108 details",
        "Get details for EM-WO-013",
        "Work order WO-00109 details",
        "View work order EM-WO-006",
        "Get details for PRD-015",
        "Tell me about work order PM-AHU-001",
        "Fetch EM-WO-010",
        "What work orders are assigned to Prasad Gokhale?",
        "How is work order WO-00107?",
        "Tell me about work order WO-00198",
        "View work order WO-00121",
        "Status of WO-00141",
        "View work order PRD-008",
        "Show details for work order WO-00122",
        "Open PRD-005",
        "Maintenance orders for Blister Packing Machine",
        "What is WO-00140?",
        "Show details for work order WO-00164",
        "Work order WO-00197 details",
        "What is CAL-TMP-003?",
        "View work order WO-00088",
        "Work order WO-00173 details",
        "Status of CAL-MOI-001",
        "What is PRD-016?",
        "What is the status of work order WO-00103?",
        "View work order WO-00122",
        "Show work orders for Floor Scale",
        "Status of EM-WO--016",
        "Get details for WO-00191",
        "Work order WO-00179 details",
        "What is WO-00106?",
        "Show details for work order WO-00196",
        "Work order WO-00121 details",
        "Display CAL-DIS-001",
        "What is the status of work order WO-00159?",
        "What is WO-00113?",
        "Status of EM-WO-017",
        "Open PM-BLD-001",
        "How is work order CAL-TMP-001?",
        "Tell me about work order WO-00131",
        "Show me work order WO-MAINT-2026-0042",
        "Get details for EM-WO-002",
        "Display WO-00128",
        "Show work orders for Closing Module",
        "Open WO-00188",
        "Work order WO-00088 details",
        "Show me tasks for Rahul Deshmukh",
        "Display EM-WO--016",
        "Status of WO-00149",
        "Show work orders for Blister Packing Machine",
        "What is Karan Shah working on?",
        "Fetch WO-00186",
        "Show me tasks for Divya Pandey",
        "Get details for CAL-TAC-001",
        "Get details for WO-00091",
        "What is the status of work order WO-00198?",
        "Status of WO-00112",
        "What is WO-00159?",
        "Show details for work order WO-00176",
        "Open WO-00146",
        "Work orders assigned to Prasad Gokhale",
        "View work order CAL-CLM-001",
        "Show details for work order WO-00105",
        "Status of PM-BLD-001",
        "Get details for WO-00163",
        "Show details for work order WO-00154",
        "Fetch WO-00128",
        "Work order PRD-007 details",
        "What is Swati Deshmukh working on?",
        "What is the status of work order WO-00105?",
        "Work order WO-00164 details",
        "Show me work order EM-WO--004",
        "How is work order PM-AHU-002?",
        "View work order CAL-THM-002",
        "Show me work order WO-00096",
        "Fetch PM-AHU-002",
        "What work orders are for Product Container?",
        "What is the status of work order WO-00108?",
        "How is work order WO-00136?",
        "Tell me about work order CAL-WGT-001",
        "What is Arun Choudhary working on?",
        "Show me work order PRD-004",
        "Fetch EM-WO-015",
        "Work order PM-BLD-001 details",
        "Show me work order WO-00169",
        "View work order WO-00181",
        "View work order WO-00110",
        "Get details for CAL-FRB-001",
        "What is the status of work order EM-WO--009?",
        "Show work orders for Hot Water Generator",
        "Fetch EM-WO-002",
        "Tell me about work order WO-00166",
        "How is work order EM-WO--016?",
        "Fetch WO-00131",
        "Show details for work order PM-ACT-001",
        "Work order WO-00086 details",
        "Work order WO-00127 details",
        "How is work order CAL-TMP-004?",
        "Tell me about work order WO-00172",
        "What work orders are for Foil Unwinder?",
        "Show me work order PRD-015",
        "Display CAL-VIS-001B",
        "Show me work order EM-WO--012",
        "What work orders are assigned to Rajesh Nair?",
        "What is WO-00181?",
        "Status of WO-00157",
        "Fetch WO-00196",
        "Open PRD-015",
        "Display WO-00140",
        "How is work order PM-TBP-002?",
        "How is work order WO-00134?",
        "Work orders assigned to Aarav Mehta",
        "Tell me about work order WO-00149",
        "What work orders are for Leaflet Inserter?",
        "Get details for CAL-RH-002",
        "How is work order WO-00121?",
        "Work order WO-00192 details",
        "Status of PM-LAF-001",
        "What is WO-00109?",
        "Fetch WO-00139",
        "Tell me about work order WO-00139",
        "What work orders are for Bottle Filler?",
        "What work orders are for Discharge Trolley?",
        "Show details for work order PRD-010",
        "What is the status of work order WO-00118?",
        "How is work order WO-00129?",
        "Work order WO-00155 details",
        "Fetch WO-00184",
        "What is the status of work order WO-00162?",
        "What is Aditya Bose working on?",
        "How is work order PRD-001?",
        "Show work orders for Inspection Conveyor",
        "What is the status of work order WO-00179?",
        "What is the status of work order WO-00135?",
        "View work order CM-002",
        "What is Gaurav Mishra working on?",
        "Open PRD-001",
        "Maintenance orders for Metal Detector",
        "Status of EM-WO-002",
        "Work order PM-TBP-001 details",
        "Open WO-00154",
        "What is the status of work order PRD-008?",
        "What is CAL-RH-001?",
        "Show details for work order CAL-RH-002",
        "List tasks for Rajesh Patel",
        "Work order WO-00188 details",
        "List tasks for Rekha Pillai",
        "Get details for EM-WO-015",
        "Show me tasks for Ritu Saxena",
        "What is WO-00179?",
        "List tasks for Aarav Mehta",
        "What is EM-WO--021?",
        "Tell me about work order WO-00109",
        "Get details for WO-00173",
        "Work order CAL-MOI-001 details",
        "Work order WO-00136 details",
        "Maintenance orders for Leaflet Inserter",
        "Work orders assigned to Gaurav Mishra",
        "List tasks for Deepa Menon",
        "Work orders assigned to Ritu Saxena",
        "What is WO-00145?",
        "Tell me about work order WO-00181",
        "Get details for WO-00119",
        "Get details for EM-WO-006",
        "What is WO-00146?",
        "Show details for work order WO-00188",
        "How is work order WO-00192?",
        "Display WO-00129",
        "Fetch WO-00183",
        "Work order CAL-VIS-001B details",
        "What is WO-00131?",
        "Open EM-WO-006",
        "Status of EM-WO--012",
        "What is the status of work order WO-00149?",
        "Display WO-00133",
        "What has Karan Shah been assigned?",
        "Show me work order WO-00107",
        "Display CAL-LOD-001",
        "How is work order CAL-PRE-001?",
        "Status of CAL-VIS-002B",
        "Work orders assigned to Meera Iyer",
        "What is WO-00104?",
        "How is work order WO-00152?",
        "Show me tasks for Prasad Gokhale",
        "Open EM-WO-015",
        "Open WO-MAINT-2026-0050",
        "How is work order CAL-TMP-003?",
        "View work order PM-DCU-001",
        "View work order WO-00124",
        "Show me work order CAL-MOI-001",
        "What is the status of work order WO-00151?",
        "Show details for work order WO-00167",
        "What work orders are assigned to Mamta Banerjee?",
        "Show details for work order WO-00099",
        "View work order WO-00104",
        "Display WO-00159",
        "Display PRD-016",
        "How is work order WO-00092?",
        "Show work orders for Dosing Disc Set",
        "What is the status of work order WO-00112?",
        "Show me work order PRD-013",
        "What is WO-00108?",
        "Fetch WO-00165",
        "Tell me about work order WO-MAINT-2026-0042",
        "What is the status of work order CAL-TWR-001?",
        "What work orders are for Self-Adhesive Labeller?",
        "Show details for work order WO-00090",
        "Get details for WO-00113",
        "Tell me about work order EM-WO-007",
        "Open WO-00162",
        "Show me work order WO-00125",
        "Fetch WO-00119",
        "View work order CM-001",
        "Show me work order EM-WO-002",
        "Status of EM-WO-010",
        "How is work order WO-00180?",
        "Show details for work order WO-00179",
        "Open PM-LAF-001",
        "Status of WO-00177",
        "Show me tasks for Rajesh Patel",
        "View work order WO-00164",
        "Show details for work order WO-00157",
        "Show details for work order CAL-THM-001",
        "Get details for WO-00122",
        "Status of WO-00171",
        "Maintenance orders for Spray Gun Assembly",
        "What is WO-00110?",
        "Open WO-00111",
        "Get details for PM-BPM-001",
        "Maintenance orders for Inspection Conveyor",
        "Show details for work order WO-00155",
        "Open CAL-TMP-002",
        "Tell me about work order EM-WO-008",
        "Show me work order CM-002",
        "How is work order WO-00193?",
        "Show me work order CAL-DIS-001",
        "Status of PRD-012",
        "Show details for work order EM-WO-010",
        "Open PRD-009",
        "Status of PM-AHU-002",
        "Tell me about work order PM-AHU-002",
        "Work order CAL-HRD-001 details",
        "View work order WO-00162",
        "What work orders are for Dust Collector?",
        "What is WO-00137?",
        "Fetch WO-00102",
        "Get details for WO-00149",
        "What is CAL-TMP-004?",
        "View work order WO-00136",
        "Display PRD-008",
        "Fetch EM-WO-022",
        "View work order WO-00149",
        "Tell me about work order EM-WO-011",
        "What is WO-00148?",
        "Show Rekha Pillai's assignments",
        "Fetch WO-00163",
        "Display WO-00121",
        "Display PRD-010",
        "What work orders are assigned to Sanjay Rao?",
        "Display WO-00169",
        "What is the status of work order WO-00141?",
        "Status of CAL-PRE-001",
        "What work orders are assigned to Vivek Malhotra?",
        "Show work orders for RPM Controller",
        "What is WO-00122?",
        "Show details for work order WO-00128",
        "Open WO-00136",
        "Status of CAL-BAL-002",
        "What is WO-00197?",
        "Show me work order WO-00154",
        "Fetch WO-00138",
        "Tell me about work order WO-00146",
        "Tell me about work order CAL-TMP-002",
        "Show details for work order WO-00111",
        "How is work order CAL-LOD-001?",
        "Fetch WO-00192",
        "Show details for work order CAL-DIS-001",
        "Show details for work order WO-00136",
        "What is the status of work order WO-00178?",
        "Work order WO-00149 details",
        "Work orders assigned to Ashwini Kulkarni",
        "Show me work order WO-00110",
        "Display WO-00109",
        "Open WO-00093",
        "List tasks for Devansh Kapoor",
        "Display WO-00119",
        "Fetch CAL-THM-002",
        "What is WO-00128?",
        "Work order WO-00194 details",
        "What is the status of work order EM-WO--014?",
        "Status of EM-WO-018",
        "Display WO-00185",
        "Display WO-00138",
        "Status of WO-00101",
        "Tell me about work order WO-00151",
        "Tell me about work order WO-00195",
        "How is work order WO-00091?",
        "Show Deepa Menon's assignments",
        "Open EM-WO-005",
        "Tell me about work order EM-WO-018",
        "How is work order WO-00147?",
        "Tell me about work order PM-RMG-001",
        "Fetch WO-00175",
        "What is WO-00112?",
        "How is work order WO-00099?",
        "Display CM-001",
        "How is work order EM-WO-003?",
        "What is the status of work order WO-00148?",
        "Work order CM-001 details",
        "Show me work order WO-00189",
        "Display EM-WO-007",
        "Work orders assigned to Rahul Deshmukh",
        "Show work orders for Orientation Sorter",
        "What is the status of work order PRD-003?",
        "What is WO-00170?",
        "Work order WO-00159 details",
        "Show me work order PM-BPM-001",
        "Tell me about work order EM-WO-015",
        "What work orders are for Exhaust Blower?",
        "What is WO-00086?",
        "Show me work order WO-00196",
        "Show me work order CAL-MMT-001",
        "View work order CAL-VIS-001B",
        "Display WO-MAINT-2026-0050",
        "What is the status of work order WO-00182?",
        "Display CAL-BAL-002",
        "Work order WO-00180 details",
        "Work order PRD-016 details",
        "Open EM-WO-018",
        "What is the status of work order CAL-RH-001?",
        "Fetch WO-00111",
        "Tell me about work order PRD-015",
        "Status of WO-00184",
        "Work order WO-00145 details",
        "Fetch EM-WO-001",
        "Work order CAL-CWG-002 details",
        "Get details for CAL-LOD-001",
        "Show me work order PM-CFM-001",
        "Tell me about work order CAL-TMP-003",
        "View work order WO-00107",
        "Show me work order PRD-014",
        "Show me work order EM-WO--009",
        "What is WO-00177?",
        "Show Rohit Verma's assignments",
        "Get details for CAL-THM-001",
        "What work orders are assigned to Rajesh Patel?",
        "Tell me about work order WO-00161",
        "Show details for work order PRD-005",
        "Show details for work order WO-00161",
        "Show details for work order PM-AHU-001",
        "Maintenance orders for Chopper Motor",
        "How is work order WO-00088?",
        "What is the status of work order WO-00117?",
        "What is the status of work order WO-00143?",
        "Status of EM-WO-013",
        "Fetch WO-00129",
        "Show me work order EM-WO-022",
        "Tell me about work order CAL-WGT-002",
        "What is the status of work order WO-00104?",
        "Work order WO-00142 details",
        "Show me work order WO-00166",
        "How is work order WO-00137?",
        "Show me work order WO-00131",
        "Tell me about work order WO-00094",
        "What is CAL-WGT-001?",
        "View work order WO-00100",
        "Get details for PRD-013",
        "Fetch WO-00144",
        "What work orders are assigned to Devansh Kapoor?",
        "Fetch WO-00198",
        "Work order WO-00158 details",
        "Status of WO-00165",
        "Show details for work order EM-WO--009",
        "Fetch CAL-DPG-001",
        "View work order EM-WO-015",
        "What is EM-WO--019?",
        "View work order WO-00117",
        "How is work order CAL-VIS-001B?",
        "Work orders assigned to Shruti Kulkarni",
        "Show me work order CAL-CWG-002",
        "Status of PM-FBD-001",
        "View work order WO-00143",
        "Maintenance orders for Closing Module",
        "What is PM-FBD-001?",
        "Show details for work order CAL-BAL-002",
        "Fetch CAL-BAL-001",
        "Display WO-00166",
        "Show details for work order EM-WO--020",
        "View work order EM-WO-001",
        "What is PRD-015?",
        "Fetch PM-FBD-001",
        "Show details for work order CM-002",
        "Display WO-00102",
        "View work order CAL-LOD-001",
        "Tell me about work order WO-00133",
        "Show details for work order WO-00143",
        "What has Devansh Kapoor been assigned?",
    ],
}
