"""Intent examples: work_order_query (part 4/5)."""

from __future__ import annotations

EXAMPLES: dict[str, list[str]] = {
    "work_order_query": [
        "Open WO-00115",
        "Fetch WO-00191",
        "Display WO-00171",
        "Work order WO-00157 details",
        "Maintenance orders for Sampling Spatula",
        "Get details for CAL-HRD-001",
        "Display WO-00089",
        "Show me work order EM-WO--016",
        "Tell me about work order WO-00192",
        "What is Lata Hegde working on?",
        "Show details for work order WO-00190",
        "What is CM-002?",
        "What work orders are assigned to Karan Shah?",
        "Display CAL-MOI-001",
        "What is EM-WO-010?",
        "How is work order WO-00151?",
        "Show details for work order WO-00119",
        "What is PM-CFM-001?",
        "Maintenance orders for Capsule Counter",
        "What is the status of work order CAL-VIS-001?",
        "What is the status of work order EM-WO--020?",
        "Display CAL-THM-002",
        "Display WO-00145",
        "Open CAL-FRB-001",
        "Tell me about work order CAL-VIS-001",
        "Show me work order WO-00123",
        "What is CAL-VIS-001B?",
        "Show me work order CAL-RH-001",
        "Get details for WO-00129",
        "How is work order WO-00117?",
        "How is work order CAL-WGT-001?",
        "Get details for WO-00195",
        "Show me work order PRD-001",
        "View work order PRD-001",
        "Display WO-00197",
        "Display WO-00184",
        "Status of EM-WO--019",
        "Work order WO-00132 details",
        "Get details for CAL-CLM-001",
        "Show Manish Tiwari's assignments",
        "Display CAL-PRE-001",
        "Display EM-WO-002",
        "What is the status of work order WO-00090?",
        "Work order CAL-DPG-002 details",
        "Fetch WO-00161",
        "Show me work order WO-00132",
        "Get details for WO-00187",
        "Status of WO-00137",
        "Display WO-MAINT-2026-0042",
        "How is work order CAL-TAC-001?",
        "Show work orders for Capsule Deduster",
        "Show me work order WO-00197",
        "Open WO-00086",
        "Tell me about work order CAL-CLM-001",
        "Show Tarun Chopra's assignments",
        "Tell me about work order CAL-PRE-001",
        "Display EM-WO-006",
        "How is work order PM-FBD-001?",
        "Show me work order PM-DCU-001",
        "View work order WO-00102",
        "Open CAL-LPC-001",
        "Show work orders for Impeller Motor",
        "Show work orders for Capsule Polishing Machine",
        "What is the status of work order CAL-THM-001?",
        "How is work order PM-ACT-001?",
        "How is work order WO-00166?",
        "Status of WO-00197",
        "How is work order PM-CFM-001?",
        "View work order WO-00135",
        "Fetch WO-00089",
        "Status of WO-00194",
        "Tell me about work order WO-00122",
        "Open WO-00095",
        "Tell me about work order WO-00104",
        "What is the status of work order WO-00136?",
        "Show details for work order WO-00109",
        "Get details for WO-00087",
        "Open WO-00117",
        "Get details for CAL-THM-002",
        "What work orders are for Tablet Deduster?",
        "What work orders are assigned to Gaurav Mishra?",
        "Status of WO-00182",
        "What is the status of work order PM-DCU-001?",
        "How is work order PM-CTM-001?",
        "Get details for WO-00159",
        "Display WO-00174",
        "Fetch WO-00157",
        "Show details for work order EM-WO-013",
        "Status of WO-00179",
        "Work order CAL-WGT-002 details",
        "What is the status of work order EM-WO-013?",
        "Get details for WO-00134",
        "Show me work order WO-00100",
        "What is WO-00143?",
        "Display WO-00116",
        "Tell me about work order CAL-DPG-001",
        "Show me work order WO-00184",
        "Status of WO-00111",
        "How is work order EM-WO-010?",
        "What is EM-WO-018?",
        "How is work order PRD-007?",
        "Work order WO-00122 details",
        "Tell me about work order EM-WO-013",
        "View work order WO-00141",
        "View work order WO-00157",
        "Show details for work order WO-00171",
        "What is Arjun Mehta working on?",
        "What is Rahul Deshmukh working on?",
        "Tell me about work order CM-001",
        "Show me work order WO-00150",
        "View work order EM-WO--012",
        "Display CAL-VIS-002B",
        "Show me tasks for Nitin Saxena",
        "Open WO-00087",
        "Display PM-AHU-001",
        "What is the status of work order WO-00183?",
        "View work order WO-00140",
        "What is WO-00161?",
        "Work orders assigned to Pallavi Joshi",
        "Show details for work order WO-00139",
        "Display WO-00186",
        "Maintenance orders for Tablet Polisher",
        "What work orders are for Cap Sealer?",
        "What is WO-00189?",
        "Fetch PRD-002",
        "Show me work order PRD-012",
        "Get details for PM-CFM-001",
        "Show work orders for Tablet Polisher",
        "What is the status of work order CAL-VIS-002B?",
        "Tell me about work order WO-00182",
        "What is the status of work order PRD-001?",
        "Work order WO-00115 details",
        "What is EM-WO-003?",
        "Show details for work order PRD-001",
        "Display WO-00093",
        "How is work order WO-00109?",
        "Work order PRD-008 details",
        "View work order EM-WO-011",
        "Show Aditya Bose's assignments",
        "What has Rajesh Patel been assigned?",
        "Fetch PRD-016",
        "Work order WO-00153 details",
        "Show details for work order EM-WO-001",
        "Tell me about work order EM-WO-010",
        "Tell me about work order WO-00153",
        "Work order WO-00096 details",
        "Show me work order WO-00157",
        "Status of CAL-TMP-004",
        "Open CAL-HRD-001",
        "Get details for WO-00172",
        "Get details for WO-00156",
        "Work order WO-00095 details",
        "Work orders assigned to Manish Tiwari",
        "Show me work order CAL-BAL-001",
        "Get details for WO-00124",
        "Show details for work order WO-00170",
        "Open WO-00122",
        "View work order EM-WO-002",
        "Status of PM-TBP-002",
        "Status of EM-WO-006",
        "Work order WO-00112 details",
        "What is PM-CTM-001?",
        "Show details for work order PM-RMG-001",
        "Get details for WO-00105",
        "How is work order PM-LAF-001?",
        "Show details for work order EM-WO-011",
        "Show me tasks for Devansh Kapoor",
        "Open EM-WO--009",
        "How is work order PRD-010?",
        "List tasks for Suresh Kumar",
        "Get details for WO-00094",
        "Status of WO-00153",
        "Work order EM-WO--012 details",
        "Work order WO-00126 details",
        "What is the status of work order CAL-CWG-002?",
        "View work order WO-00184",
        "Work order PRD-009 details",
        "Tell me about work order WO-00105",
        "Work order CAL-CLM-001 details",
        "View work order PRD-009",
        "Fetch PM-TBP-002",
        "Tell me about work order WO-00156",
        "Fetch PRD-003",
        "What work orders are for Capsule Deduster?",
        "Get details for PRD-007",
        "Show details for work order CAL-TMP-004",
        "Show details for work order WO-00160",
        "Display EM-WO-015",
        "View work order WO-00200",
        "What is the status of work order WO-00093?",
        "View work order WO-00125",
        "What is Kavita Joshi working on?",
        "Tell me about work order CAL-DPG-002",
        "Status of WO-00183",
        "What is the status of work order EM-WO-015?",
        "Show me work order WO-00134",
        "Open CAL-MOI-001",
        "Fetch WO-00140",
        "Show details for work order WO-00134",
        "Get details for WO-MAINT-2026-0042",
        "What has Kavita Joshi been assigned?",
        "Show me work order WO-00127",
        "Open WO-00104",
        "Display PM-TBP-002",
        "How is work order WO-00087?",
        "Status of WO-00120",
        "Get details for EM-WO-022",
        "Status of WO-00199",
        "View work order PM-AHU-001",
        "What is PRD-008?",
        "What is the status of work order WO-00088?",
        "Work order CAL-TMP-004 details",
        "What is the status of work order WO-00165?",
        "Work order WO-00116 details",
        "View work order CAL-TMP-003",
        "Status of WO-00100",
        "Tell me about work order CAL-BAL-002",
        "What is PM-LAF-001?",
        "What is the status of work order EM-WO-022?",
        "Display WO-00194",
        "Work order WO-00123 details",
        "Show details for work order EM-WO--019",
        "Display CAL-HRD-001",
        "What is Rahul Sharma working on?",
        "Work orders assigned to Priya Sharma",
        "Show details for work order PM-TBP-002",
        "View work order CAL-DPG-002",
        "Show Sachin Kulkarni's assignments",
        "How is work order EM-WO--009?",
        "Show Rahul Deshmukh's assignments",
        "Status of EM-WO-015",
        "View work order WO-00182",
        "Show me work order PM-TBP-002",
        "Work order WO-00186 details",
        "Fetch WO-00101",
        "How is work order WO-00089?",
        "View work order EM-WO-005",
        "Work order PM-DCU-001 details",
        "What work orders are for RPM Controller?",
        "What is WO-00091?",
        "What is the status of work order CAL-BAL-002?",
        "What is the status of work order WO-00102?",
        "What is WO-00153?",
        "Display WO-00160",
        "Status of WO-00109",
        "Status of WO-00188",
        "Status of WO-00094",
        "What is WO-00188?",
        "Show Aarav Mehta's assignments",
        "Open CAL-TMP-004",
        "Get details for WO-00147",
        "Show details for work order PM-CTM-001",
        "What is the status of work order WO-00188?",
        "View work order WO-00112",
        "Display WO-00148",
        "Show me work order WO-00095",
        "Display WO-00156",
        "What is WO-00172?",
        "Display PM-BPM-001",
        "What is the status of work order PM-CFM-001?",
        "What is the status of work order PRD-011?",
        "Open PRD-012",
        "What is EM-WO-002?",
        "Status of WO-MAINT-2026-0042",
        "Fetch WO-00098",
        "Work order WO-00131 details",
        "Get details for WO-00152",
        "Work order PM-LAF-001 details",
        "View work order WO-00138",
        "Tell me about work order CAL-FRB-001",
        "Display CAL-FRB-001",
        "Show details for work order EM-WO-008",
        "What is the status of work order PM-BPM-001?",
        "What is PM-AHU-001?",
        "Tell me about work order WO-00159",
        "Fetch CAL-CWG-002",
        "Work order WO-00150 details",
        "Fetch PRD-014",
        "Work order CAL-THM-002 details",
        "What is the status of work order EM-WO--021?",
        "Show details for work order EM-WO--014",
        "Get details for WO-00158",
        "Show me work order EM-WO--019",
        "Work order EM-WO-010 details",
        "View work order PM-BPM-001",
        "Work order CAL-THM-001 details",
        "How is work order WO-00186?",
        "Show me work order WO-00190",
        "Work order WO-00134 details",
        "Status of WO-00151",
        "Show details for work order WO-00107",
        "Open WO-00116",
        "How is work order WO-00096?",
        "View work order WO-00185",
        "Show me work order WO-00179",
        "Fetch CAL-VIS-001",
        "Show details for work order WO-00115",
        "Tell me about work order CAL-THM-001",
        "Fetch WO-00093",
        "Status of WO-00181",
        "Fetch CAL-CLM-001",
        "What is WO-00144?",
        "What is WO-00168?",
        "Fetch PM-CFM-001",
        "What is the status of work order WO-00125?",
        "Display WO-00104",
        "Status of EM-WO-011",
        "How is work order WO-00128?",
        "Open WO-00171",
        "Status of CAL-BAL-001",
        "What work orders are assigned to Sachin Kulkarni?",
        "Get details for PRD-011",
        "Work order CM-002 details",
        "Work order WO-00167 details",
        "How is work order CAL-THM-002?",
        "Maintenance orders for Discharge Trolley",
        "What is the status of work order EM-WO--016?",
        "What is the status of work order PM-LAF-001?",
        "What is WO-00119?",
        "Open CAL-TAC-001",
        "What is the status of work order WO-00113?",
        "Status of WO-00189",
        "Show me work order WO-00099",
        "Status of WO-00113",
        "What is the status of work order WO-00122?",
        "Work order PM-CTM-001 details",
        "Fetch WO-00194",
        "Open WO-00097",
        "Get details for WO-00139",
        "Get details for WO-00131",
        "Tell me about work order WO-00179",
        "How is work order WO-00105?",
        "What is the status of work order WO-00172?",
        "Work order WO-00160 details",
        "What is the status of work order WO-00187?",
        "Show details for work order WO-00141",
        "What is the status of work order WO-00196?",
        "Show me work order EM-WO-010",
        "Open WO-00119",
        "Get details for WO-00099",
        "Show details for work order CAL-FRB-001",
        "Fetch WO-00091",
        "Display WO-00168",
        "Tell me about work order PRD-008",
        "How is work order WO-00150?",
        "What is WO-00174?",
        "What is the status of work order EM-WO-008?",
        "What is the status of work order EM-WO-003?",
        "Fetch WO-00106",
        "What is PM-TBP-002?",
        "Fetch CM-002",
        "Work order EM-WO--016 details",
        "Get details for CAL-CWG-001",
        "What is the status of work order WO-00200?",
        "Show details for work order WO-00184",
        "What is the status of work order WO-00131?",
        "Work order EM-WO--020 details",
        "Show details for work order WO-00088",
        "View work order WO-00099",
        "What is Priya Sharma working on?",
        "View work order WO-00161",
        "Get details for PRD-005",
        "Show details for work order PRD-003",
        "What is the status of work order WO-00175?",
        "What is WO-00134?",
        "What is the status of work order WO-00106?",
        "What has Swati Deshmukh been assigned?",
        "How is work order WO-00159?",
        "Show work orders for Bin Lifter",
        "Show me work order EM-WO-006",
        "View work order WO-00130",
        "Get details for WO-00182",
        "View work order WO-00119",
        "Show me work order WO-00116",
        "Work order WO-MAINT-2026-0050 details",
        "Status of WO-00115",
        "Work order WO-00137 details",
        "Get details for WO-00153",
        "Tell me about work order WO-00095",
        "What is the status of work order WO-00199?",
        "What is WO-00092?",
        "How is work order WO-00086?",
        "Fetch EM-WO-011",
        "Fetch WO-00099",
        "View work order WO-00114",
        "Fetch PM-AHU-001",
        "View work order WO-00113",
        "View work order CAL-WGT-002",
        "Status of CAL-TMP-002",
        "View work order PRD-010",
        "Open WO-00172",
        "What is WO-00193?",
        "Show details for work order WO-00192",
        "Fetch WO-00118",
        "Get details for PM-BLD-001",
        "Show details for work order WO-00159",
        "Display WO-00155",
        "Show me work order WO-00148",
        "Fetch WO-00172",
        "Tell me about work order WO-00102",
        "Status of WO-00114",
        "Work order PRD-006 details",
        "Tell me about work order WO-00169",
        "Show details for work order EM-WO-017",
        "Show me work order PRD-003",
        "Get details for EM-WO--021",
        "What is the status of work order WO-00173?",
        "What has Pallavi Joshi been assigned?",
        "Status of WO-00098",
        "Fetch WO-00200",
        "Status of CAL-RH-001",
        "Get details for WO-00181",
        "Fetch CAL-PRE-001",
        "Tell me about work order PM-ACT-001",
        "How is work order PM-BPM-001?",
        "Show me work order WO-00104",
        "What is WO-00191?",
        "View work order EM-WO-022",
        "Show details for work order WO-00100",
        "View work order WO-00095",
        "Get details for PRD-016",
        "What is CAL-VIS-001?",
        "Fetch WO-00149",
        "How is work order EM-WO-015?",
        "Get details for WO-00168",
        "Open WO-00094",
        "Show me work order WO-00146",
        "Show me work order WO-MAINT-2026-0050",
        "Get details for PRD-003",
        "Display WO-00098",
        "Show me work order PRD-016",
        "View work order CAL-CWG-002",
        "Open WO-00177",
        "Work order WO-00128 details",
        "Show me work order WO-00093",
        "How is work order WO-00170?",
        "Show work orders for AHU",
        "Display WO-00115",
        "Fetch WO-00197",
        "Fetch WO-00199",
        "View work order WO-00183",
        "Work order WO-00175 details",
        "Fetch CAL-TMP-003",
        "Show me work order WO-00117",
        "Get details for EM-WO-003",
        "Work order WO-00174 details",
        "Get details for WO-00199",
        "How is work order WO-00101?",
        "View work order CAL-TWR-001",
        "Get details for WO-00120",
        "What is the status of work order WO-00132?",
        "Show details for work order EM-WO-022",
        "Work order EM-WO-006 details",
        "What is WO-00187?",
        "Show details for work order WO-00146",
        "How is work order CAL-HRD-001?",
        "Open PM-DCU-001",
        "Open WO-00166",
        "Fetch WO-00127",
        "What is WO-00126?",
        "How is work order WO-00106?",
        "Get details for PRD-004",
        "What is WO-00194?",
        "Status of PM-DCU-001",
        "View work order PM-CFM-001",
        "Status of WO-00158",
        "What is Rajesh Patel working on?",
        "Open WO-00167",
        "Tell me about work order WO-00115",
        "What is Sachin Kulkarni working on?",
        "Display PRD-012",
        "Fetch WO-00154",
        "What is EM-WO-013?",
        "Get details for EM-WO-011",
        "Status of WO-00096",
        "Show me work order PM-RMG-001",
        "Display WO-00198",
        "What has Nitin Saxena been assigned?",
        "Get details for PRD-012",
        "Display WO-00090",
        "Status of WO-00134",
        "Show details for work order WO-00089",
        "What is WO-00164?",
        "View work order WO-00177",
        "What is the status of work order PM-TBP-002?",
        "Show details for work order WO-00121",
        "Open PRD-007",
        "Show details for work order PRD-004",
        "Get details for PRD-008",
    ],
}
