"""Intent examples: worker (part 1/2)."""

from __future__ import annotations

EXAMPLES: dict[str, list[str]] = {
    "worker": [
        "What work orders are assigned to Nitin Saxena?",
        "Worker directory",
        "Schedule for Tarun Chopra",
        "Who works here?",
        "Tasks assigned to Kavita Joshi",
        "What does Pooja Verma do?",
        "Show me the workers",
        "Show Suresh Kumar profile",
        "What work orders are assigned to Mamta Banerjee?",
        "Staff list",
        "Tasks assigned to Pooja Verma",
        "Tell me about Priya Patel",
        "Show team members",
        "List all operators in Supply Chain",
        "List all operators in Finance",
        "Workload for Amit Singh",
        "Workload for Suresh Kumar",
        "Workload for Vikram Desai",
        "Schedule for Anjali Reddy",
        "Workers in Human Resources",
        "Personnel directory",
        "What does Anjali Reddy do?",
        "Staff of Regulatory Affairs",
        "What is Nisha Agarwal's role?",
        "List all workers",
        "Who is the manager of Warehouse & Logistics?",
        "Tell me about Mamta Banerjee",
        "Schedule for Kavita Joshi",
        "Tasks assigned to Rahul Deshmukh",
        "Show Quality Control team",
        "Tasks assigned to Aditya Bose",
        "Tasks assigned to Gaurav Mishra",
        "Workload for Shruti Kulkarni",
        "Show Human Resources team",
        "Team roster",
        "What is Aarav Mehta's role?",
        "Who is the manager of Quality Control?",
        "Show me tasks for Mamta Banerjee",
        "What work orders are assigned to Rekha Pillai?",
        "Show all operators",
        "Who is the manager of Human Resources?",
        "What work orders are assigned to Shruti Kulkarni?",
        "Show Finance team",
        "Show all plant safety officers",
        "Show all supervisors",
        "Show Priya Patel profile",
        "Tell me about Vikram Desai",
        "Tasks assigned to Tarun Chopra",
        "Workers in Quality Assurance",
        "Tasks assigned to Shruti Kulkarni",
        "Schedule for Divya Pandey",
        "What does Nisha Agarwal do?",
        "Schedule for Meera Iyer",
        "All employees",
        "Who is the manager of Quality Assurance?",
        "Show Arjun Mehta profile",
        "Tell me about Anjali Reddy",
        "Show active workers",
        "What work orders are assigned to Neha Gupta?",
        "Show Prasad Gokhale profile",
        "List all operators in Operations",
        "Staff of Operations",
        "List packaging operators",
        "List all operators in Warehouse & Logistics",
        "Tasks assigned to Priya Sharma",
        "Show me tasks for Suresh Kumar",
        "Workers in Operations",
        "Tell me about Divya Pandey",
        "Show Operations team",
        "Tell me about Gaurav Mishra",
        "Show Rajesh Patel profile",
        "Staff of Quality Assurance",
        "Workload for Tarun Chopra",
        "Tell me about Aditya Bose",
        "Workload for Kavita Joshi",
        "Who is the manager of Operations?",
        "List supervisors",
        "Schedule for Rahul Sharma",
        "What is Arun Choudhary's role?",
        "Show me tasks for Aditya Bose",
        "What does Meera Iyer do?",
        "What is Pooja Verma's role?",
        "Workload for Priya Patel",
        "Who is the manager of Regulatory Affairs?",
        "Workers in Supply Chain",
        "Show Swati Deshmukh profile",
        "Tell me about Rajesh Nair",
        "Workers in Finance",
        "Show me tasks for Sachin Kulkarni",
        "Show Neha Gupta's assignments",
        "What does Karan Shah do?",
        "Show Engineering team",
        "Show Regulatory Affairs team",
        "Who is the manager of Supply Chain?",
        "Show Warehouse & Logistics team",
        "Tell me about Rahul Deshmukh",
        "Show Vivek Malhotra profile",
        "Schedule for Ritu Saxena",
        "Show Gaurav Mishra profile",
        "What is Gaurav Mishra's role?",
        "Show all line managers",
        "Show me tasks for Amit Singh",
        "List all operators in Quality Assurance",
        "Workload for Rohan Bhat",
        "List production workers",
        "What does Devansh Kapoor do?",
        "What is Rajesh Patel's role?",
        "What is Amit Singh's role?",
        "Staff of Quality Control",
        "List line supervisors",
        "Show all senior technicians",
        "Workload for Nitin Saxena",
        "Schedule for Amit Singh",
        "What is Suresh Kumar's role?",
        "Tasks assigned to Divya Pandey",
        "What work orders are assigned to Amit Singh?",
        "What is Rohit Verma's role?",
        "List senior technicians",
        "Workload for Arjun Mehta",
        "Show all line supervisors",
        "Show Rohit Verma profile",
        "What does Rekha Pillai do?",
        "What is Ashwini Kulkarni's role?",
        "Show all packaging operators",
        "What work orders are assigned to Sanjay Rao?",
        "Show Quality Assurance team",
        "Workload for Neha Gupta",
        "What does Pallavi Joshi do?",
        "Show all engineers",
        "List safety officers",
        "Tasks assigned to Karan Shah",
        "Schedule for Nitin Saxena",
        "Schedule for Pallavi Joshi",
        "What is Neha Gupta's role?",
        "Staff of Engineering",
        "Tasks assigned to Neha Gupta",
        "Workload for Swati Deshmukh",
        "What does Neha Gupta do?",
        "Show Suresh Kumar's assignments",
        "Show Rajesh Nair's assignments",
        "Show me tasks for Deepa Menon",
        "Show Rohan Bhat's assignments",
        "Show Supply Chain team",
        "Staff of Warehouse & Logistics",
        "Workload for Rohit Verma",
        "Show Gaurav Mishra's assignments",
        "Tell me about Rekha Pillai",
        "Show Shruti Kulkarni's assignments",
        "Show Devansh Kapoor's assignments",
        "Show all blending operators",
        "Tasks assigned to Sachin Kulkarni",
        "Tasks assigned to Arun Choudhary",
        "What does Karthik Subramanian do?",
        "Workers in EHS",
        "What does Manish Tiwari do?",
        "What is Arjun Mehta's role?",
        "What is Rekha Pillai's role?",
        "Show all qa analysts",
        "Workers in Quality Control",
        "Tell me about Aarav Mehta",
        "Show Aditya Bose profile",
        "What work orders are assigned to Ashwini Kulkarni?",
        "Tasks assigned to Sanjay Rao",
        "Show me tasks for Anjali Reddy",
        "Show Deepa Menon's assignments",
        "Staff of EHS",
        "Tasks assigned to Nitin Saxena",
        "Show me tasks for Tarun Chopra",
        "What work orders are assigned to Arun Choudhary?",
        "Workload for Prasad Gokhale",
        "Tasks assigned to Swati Deshmukh",
        "Schedule for Arjun Mehta",
        "List plant managers",
        "Schedule for Neha Gupta",
        "Show Pallavi Joshi profile",
        "List all operators in Regulatory Affairs",
        "Show Vikram Desai's assignments",
        "What does Amit Singh do?",
        "Show Arun Choudhary profile",
        "Who is the manager of Finance?",
        "Show all plant managers",
        "Tell me about Lata Hegde",
        "Workers in Warehouse & Logistics",
        "Who is the manager of Engineering?",
        "Show me tasks for Priya Patel",
        "Tell me about Rohan Bhat",
        "Show Rahul Sharma's assignments",
        "What work orders are assigned to Rohan Bhat?",
        "Show me tasks for Nisha Agarwal",
        "Tell me about Ashwini Kulkarni",
        "Tell me about Amit Singh",
        "List all operators in Quality Control",
        "What work orders are assigned to Pallavi Joshi?",
        "What does Nitin Saxena do?",
        "Tasks assigned to Manish Tiwari",
        "What is Priya Patel's role?",
        "List line managers",
        "What is Aditya Bose's role?",
        "What work orders are assigned to Sunita Kulkarni?",
        "Tasks assigned to Vikram Desai",
        "Show Rajesh Nair profile",
        "Tell me about Sunita Kulkarni",
        "What does Arjun Mehta do?",
        "Tasks assigned to Rajesh Nair",
        "Show Karthik Subramanian profile",
        "Tell me about Rahul Sharma",
        "List blending operators",
        "Schedule for Sunita Kulkarni",
        "What work orders are assigned to Tarun Chopra?",
        "Tasks assigned to Karthik Subramanian",
        "Show me tasks for Meera Iyer",
        "Staff of Supply Chain",
        "List engineers",
        "Show me tasks for Vikram Desai",
        "Show me tasks for Pallavi Joshi",
        "Tell me about Suresh Kumar",
        "What is Lata Hegde's role?",
        "What is Karthik Subramanian's role?",
        "Tell me about Nisha Agarwal",
        "What is Vivek Malhotra's role?",
        "What work orders are assigned to Priya Patel?",
        "Tasks assigned to Rahul Sharma",
        "Tasks assigned to Priya Patel",
        "List qa analysts",
        "What is Deepa Menon's role?",
        "Schedule for Priya Sharma",
        "Workload for Sachin Kulkarni",
        "What is Rahul Deshmukh's role?",
        "Tasks assigned to Deepa Menon",
        "Show Shruti Kulkarni profile",
        "Show Tarun Chopra profile",
        "What is Anjali Reddy's role?",
        "Tasks assigned to Amit Singh",
        "Show me tasks for Arjun Mehta",
        "Show Meera Iyer's assignments",
        "Show me tasks for Rekha Pillai",
        "Show Ashwini Kulkarni profile",
        "Workers in Engineering",
        "List all operators in Human Resources",
        "What does Rohan Bhat do?",
        "Show me tasks for Rajesh Patel",
        "Workload for Ritu Saxena",
        "Tell me about Devansh Kapoor",
        "Show me tasks for Rohit Verma",
        "Show all granulation operators",
        "Tell me about Nitin Saxena",
        "List all operators in Engineering",
        "Show me tasks for Karthik Subramanian",
        "Staff of Human Resources",
        "Show Aditya Bose's assignments",
        "Tasks assigned to Lata Hegde",
        "Show Anjali Reddy's assignments",
        "Tell me about Karan Shah",
        "Show Tarun Chopra's assignments",
    ],
}
