"""PullRequestAgent — GitHub PR creation, returns typed AgentResult with PR artifact."""

from __future__ import annotations
import logging
import os
import subprocess
from typing import Any
from ._base import BaseETASSAgent

logger = logging.getLogger("broca.agents.pull_request")


class PullRequestAgent(BaseETASSAgent):
    agent_type = "pull_request"
    description = "Creates a GitHub pull request for the ETASS-generated code branch"

    async def handle(self, context: dict[str, Any]):
        return await self._run(context, self._impl)

    async def _impl(self, context: dict):
        try:
            from src.monkey_brain.kernel.execute.runtime.outcome import Artifact
        except ImportError:
            Artifact = None

        token = os.environ.get("GITHUB_TOKEN", "")
        chart = context.get("chart_name", "etass")
        version = context.get("chart_version", "0.1.0")

        if token:
            owner = os.environ.get("GITHUB_OWNER", "")
            repo_name = os.environ.get("GITHUB_REPO", "")
            if owner and repo_name:
                try:
                    return await self._api(token, owner, repo_name, chart, version, Artifact)
                except Exception as e:
                    logger.warning("[pull_request] GitHub API failed: %s — gh CLI", e)

        return await self._gh_cli(chart, version, Artifact)

    async def _api(self, token, owner, repo_name, chart, version, Artifact):
        import httpx

        async with httpx.AsyncClient(timeout=30) as client:
            resp = await client.post(
                f"https://api.github.com/repos/{owner}/{repo_name}/pulls",
                headers={
                    "Authorization": f"token {token}",
                    "Accept": "application/vnd.github.v3+json",
                },
                json={
                    "title": f"[ETASS] {chart} v{version}",
                    "head": f"etass/{chart}/{version}",
                    "base": "main",
                    "body": "Auto-generated by ETASS dynamic pipeline.",
                },
            )
        data = resp.json()
        success = resp.status_code in (200, 201)
        self._reward(success, 0.5)
        pr_url = data.get("html_url", "")
        artifacts = (
            [Artifact(kind="pull_request", name=f"PR #{data.get('number')}", uri=pr_url)] if Artifact and pr_url else []
        )
        return self._result(
            payload={"pr_url": pr_url, "pr_number": data.get("number")},
            artifacts=artifacts,
            observations=[(f"PR created: {pr_url}" if success else f"PR failed: {data.get('message', '')}")],
        )

    async def _gh_cli(self, chart, version, Artifact):
        import asyncio

        try:
            loop = asyncio.get_event_loop()
            r = await loop.run_in_executor(
                None,
                lambda: subprocess.run(
                    [
                        "gh",
                        "pr",
                        "create",
                        "--title",
                        f"[ETASS] {chart} v{version}",
                        "--body",
                        "Auto-generated by ETASS.",
                        "--base",
                        "main",
                    ],
                    capture_output=True,
                    text=True,
                    timeout=30,
                ),
            )
            success = r.returncode == 0
            self._reward(success, 0.5)
            pr_url = r.stdout.strip().split()[-1] if success else ""
            artifacts = (
                [
                    Artifact(
                        kind="pull_request",
                        name=f"[ETASS] {chart} v{version}",
                        uri=pr_url,
                    )
                ]
                if Artifact and pr_url
                else []
            )
            return self._result(
                payload={
                    "status": "created" if success else "failed",
                    "pr_url": pr_url,
                },
                artifacts=artifacts,
                observations=[(r.stdout + r.stderr)[:200]],
            )
        except FileNotFoundError:
            self._reward(False, 0.4)
            return self._result(payload={"status": "skipped"}, observations=["gh CLI not available"])
