"""ReleaseAgent — GitHub Release creation with tagging, pushing, and release notes.

Post-merge, this agent tags the commit, pushes the tag, creates a GitHub
Release via the REST API, and optionally attaches release assets. Returns
typed AgentResult with a release artifact.
"""

from __future__ import annotations

import asyncio
import logging
import os
import re
import subprocess
from datetime import date
from pathlib import Path
from typing import Any

from ._base import BaseETASSAgent

logger = logging.getLogger("broca.agents.release")

_REPO = Path(os.environ.get("MONKEYBRAIN_REPO", str(Path(__file__).parents[4])))


class ReleaseAgent(BaseETASSAgent):
    agent_type = "release"
    description = "Creates a GitHub Release: tags the commit, pushes the tag, and publishes a release with notes"

    async def handle(self, context: dict[str, Any]):
        return await self._run(context, self._impl)

    async def _impl(self, context: dict):
        try:
            from src.monkey_brain.kernel.execute.runtime.outcome import Artifact
        except ImportError:
            Artifact = None

        token = os.environ.get("GITHUB_TOKEN", "")
        owner = os.environ.get("GITHUB_OWNER", "")
        repo_name = os.environ.get("GITHUB_REPO", "")
        version = context.get("chart_version", context.get("version", ""))
        chart = context.get("chart_name", "etass")
        service_slug = context.get("service_slug", chart)
        release_notes = context.get("release_notes", "")
        branch = context.get("branch", "main")

        if not version:
            version = self._read_version_from_pyproject(service_slug)
        if not version:
            version = f"0.1.{_today_patch()}"

        tag = f"v{version}"

        tag_ok = await self._create_tag(tag, branch)
        if not tag_ok:
            self._reward(False, 0.1)
            return self._result(
                payload={"released": False, "error": "failed to create/push tag"},
                observations=["git tag or git push failed"],
            )

        push_ok = await self._push_tag(tag)
        if not push_ok:
            self._reward(False, 0.2)
            return self._result(
                payload={"released": False, "tag": tag, "error": "failed to push tag"},
                observations=[f"tag {tag} created locally but push failed"],
            )

        if token and owner and repo_name:
            return await self._create_github_release(
                token,
                owner,
                repo_name,
                tag,
                version,
                chart,
                release_notes,
                Artifact,
            )

        return await self._create_local_release(
            tag,
            version,
            chart,
            Artifact,
        )

    async def _create_tag(self, tag: str, branch: str) -> bool:
        loop = asyncio.get_event_loop()
        r = await loop.run_in_executor(
            None,
            lambda: subprocess.run(
                ["git", "tag", "-a", tag, "-m", f"Release {tag}"],
                cwd=str(_REPO),
                capture_output=True,
                text=True,
                timeout=15,
            ),
        )
        if r.returncode != 0 and "already exists" not in r.stderr:
            logger.warning("[release] git tag failed: %s", r.stderr)
            return False
        return True

    async def _push_tag(self, tag: str) -> bool:
        loop = asyncio.get_event_loop()
        r = await loop.run_in_executor(
            None,
            lambda: subprocess.run(
                ["git", "push", "origin", tag],
                cwd=str(_REPO),
                capture_output=True,
                text=True,
                timeout=30,
            ),
        )
        if r.returncode != 0:
            logger.warning("[release] git push tag failed: %s", r.stderr)
            return False
        return True

    async def _create_github_release(
        self,
        token: str,
        owner: str,
        repo: str,
        tag: str,
        version: str,
        chart: str,
        release_notes: str,
        Artifact: Any,
    ) -> dict:
        import httpx

        if not release_notes:
            release_notes = f"Automated release of {chart} {tag}\n\nGenerated by the Cognitive OS SDLC pipeline."

        async with httpx.AsyncClient(timeout=30) as client:
            resp = await client.post(
                f"https://api.github.com/repos/{owner}/{repo}/releases",
                headers={
                    "Authorization": f"token {token}",
                    "Accept": "application/vnd.github.v3+json",
                },
                json={
                    "tag_name": tag,
                    "name": f"[ETASS] {chart} {tag}",
                    "body": release_notes,
                    "draft": False,
                    "prerelease": False,
                },
            )

        data = resp.json()
        success = resp.status_code in (200, 201)
        self._reward(success, 0.7)

        release_url = data.get("html_url", "")
        artifacts = (
            [Artifact(kind="release", name=f"Release {tag}", uri=release_url)] if Artifact and release_url else []
        )

        return self._result(
            payload={
                "released": success,
                "tag": tag,
                "release_url": release_url,
                "release_id": data.get("id"),
                "version": version,
            },
            artifacts=artifacts,
            observations=[
                (
                    f"GitHub Release created: {release_url}"
                    if success
                    else f"GitHub Release failed: {data.get('message', '')}"
                )
            ],
        )

    async def _create_local_release(
        self,
        tag: str,
        version: str,
        chart: str,
        Artifact: Any,
    ) -> dict:
        release_dir = _REPO / "releases"
        release_dir.mkdir(exist_ok=True)
        release_file = release_dir / f"{chart}-{tag}.json"

        import json

        release_info = {
            "tag": tag,
            "version": version,
            "chart": chart,
            "created_at": date.today().isoformat(),
            "pipeline": "cognitive_os_sdlc",
        }
        release_file.write_text(json.dumps(release_info, indent=2))

        self._reward(True, 0.5)
        artifacts = [Artifact(kind="release", name=f"Release {tag}", uri=str(release_file))] if Artifact else []

        return self._result(
            payload={
                "released": True,
                "tag": tag,
                "release_file": str(release_file),
                "version": version,
            },
            artifacts=artifacts,
            observations=[f"Local release manifest written: {release_file}"],
        )

    def _read_version_from_pyproject(self, service_slug: str) -> str:
        output_dir = Path(str(_REPO / "generated"))
        pyproject = output_dir / service_slug / "pyproject.toml"
        if pyproject.exists():
            try:
                text = pyproject.read_text()
                m = re.search(r'version\s*=\s*"([^"]+)"', text)
                if m:
                    return m.group(1)
            except Exception:
                pass
        return ""


def _today_patch() -> int:
    return date.today().day
