#!/usr/bin/env python3
"""Seed equipment cleaning records into MongoDB."""

import asyncio
import sys
from datetime import datetime, timezone, timedelta

sys.path.insert(0, "/Users/prashunjaveri/Code/monkeypatched")

from motor.motor_asyncio import AsyncIOMotorClient
from services.common.config import settings

NOW = datetime.now(timezone.utc)

CLEANING_RECORDS = [
    # === TABLET LINE A - DISPENSING ===
    {
        "record_id": "CLR-001",
        "equipment_id": "WS-TAB-01-01",
        "workstation_id": "WS-TAB-01-01",
        "stage_id": "STAGE-01",
        "line_id": "LINE-TAB-001",
        "cleaning_type": "Post-Production",
        "cleaning_method": "Manual",
        "status": "Completed",
        "performed_by": "Dispensing Operator",
        "previous_product": "Tablet BN-2401",
        "current_product": "Tablet BN-2402",
        "water_type": "Purified Water",
        "water_volume_liters": 20.0,
        "verification_method": "Visual Inspection",
        "verification_result": "Pass",
        "residue_limit_ppm": 10.0,
        "residue_found_ppm": 2.1,
        "remarks": "Standard post-production cleaning of sampling booth",
    },
    {
        "record_id": "CLR-002",
        "equipment_id": "WS-TAB-01-02",
        "workstation_id": "WS-TAB-01-02",
        "stage_id": "STAGE-01",
        "line_id": "LINE-TAB-001",
        "cleaning_type": "Post-Production",
        "cleaning_method": "Manual",
        "status": "Completed",
        "performed_by": "Dispensing Operator",
        "previous_product": "Tablet BN-2401",
        "current_product": "Tablet BN-2402",
        "water_type": "Purified Water",
        "water_volume_liters": 15.0,
        "verification_method": "Swab Test",
        "verification_result": "Pass",
        "residue_limit_ppm": 10.0,
        "residue_found_ppm": 1.8,
        "remarks": "Weighing booth cleaned and swab tested",
    },
    # === TABLET LINE A - SIFTING/MILLING ===
    {
        "record_id": "CLR-003",
        "equipment_id": "WS-TAB-02-01",
        "workstation_id": "WS-TAB-02-01",
        "stage_id": "STAGE-03",
        "line_id": "LINE-TAB-001",
        "cleaning_type": "Changeover",
        "cleaning_method": "Manual",
        "status": "Completed",
        "performed_by": "Milling Operator",
        "previous_product": "Tablet BN-2401",
        "current_product": "Tablet BN-2402",
        "water_type": "Purified Water",
        "water_volume_liters": 25.0,
        "verification_method": "Visual Inspection",
        "verification_result": "Pass",
        "residue_limit_ppm": 15.0,
        "residue_found_ppm": 3.2,
        "remarks": "Sifter cleaned between batches",
    },
    {
        "record_id": "CLR-004",
        "equipment_id": "WS-TAB-02-03",
        "workstation_id": "WS-TAB-02-03",
        "stage_id": "STAGE-03",
        "line_id": "LINE-TAB-001",
        "cleaning_type": "Post-Production",
        "cleaning_method": "Manual",
        "status": "Completed",
        "performed_by": "Milling Operator",
        "previous_product": "Tablet BN-2401",
        "current_product": "Tablet BN-2402",
        "water_type": "Purified Water",
        "water_volume_liters": 10.0,
        "verification_method": "Visual Inspection",
        "verification_result": "Pass",
        "residue_limit_ppm": 10.0,
        "residue_found_ppm": 1.5,
        "remarks": "Vibro sifter cleaned and inspected",
    },
    # === TABLET LINE A - GRANULATION ===
    {
        "record_id": "CLR-005",
        "equipment_id": "WS-TAB-03-01",
        "workstation_id": "WS-TAB-03-01",
        "stage_id": "STAGE-02",
        "line_id": "LINE-TAB-001",
        "cleaning_type": "Post-Production",
        "cleaning_method": "CIP",
        "status": "Completed",
        "performed_by": "Granulation Operator",
        "previous_product": "Tablet BN-2401",
        "current_product": "Tablet BN-2402",
        "water_type": "Purified Water",
        "water_volume_liters": 50.0,
        "verification_method": "Swab Test",
        "verification_result": "Pass",
        "residue_limit_ppm": 10.0,
        "residue_found_ppm": 2.5,
        "remarks": "RMG CIP cycle completed successfully",
    },
    {
        "record_id": "CLR-006",
        "equipment_id": "WS-TAB-03-02",
        "workstation_id": "WS-TAB-03-02",
        "stage_id": "STAGE-02",
        "line_id": "LINE-TAB-001",
        "cleaning_type": "Routine",
        "cleaning_method": "Manual",
        "status": "In Progress",
        "performed_by": "Granulation Operator",
        "previous_product": "Tablet BN-2402",
        "current_product": "Tablet BN-2403",
        "water_type": "Purified Water",
        "water_volume_liters": 10.0,
        "verification_method": "Visual Inspection",
        "verification_result": None,
        "residue_limit_ppm": 10.0,
        "residue_found_ppm": None,
        "remarks": "Binder prep vessel being cleaned",
    },
    # === TABLET LINE A - DRYING ===
    {
        "record_id": "CLR-007",
        "equipment_id": "WS-TAB-04-01",
        "workstation_id": "WS-TAB-04-01",
        "stage_id": "STAGE-09",
        "line_id": "LINE-TAB-001",
        "cleaning_type": "Post-Production",
        "cleaning_method": "Manual",
        "status": "Completed",
        "performed_by": "Drying Operator",
        "previous_product": "Tablet BN-2401",
        "current_product": "Tablet BN-2402",
        "water_type": "Purified Water",
        "water_volume_liters": 30.0,
        "verification_method": "Visual Inspection",
        "verification_result": "Pass",
        "residue_limit_ppm": 10.0,
        "residue_found_ppm": 1.2,
        "remarks": "FBD loading station cleaned",
    },
    {
        "record_id": "CLR-008",
        "equipment_id": "WS-TAB-04-02",
        "workstation_id": "WS-TAB-04-02",
        "stage_id": "STAGE-09",
        "line_id": "LINE-TAB-001",
        "cleaning_type": "Deep Clean",
        "cleaning_method": "CIP",
        "status": "Scheduled",
        "performed_by": "Drying Operator",
        "previous_product": None,
        "current_product": None,
        "water_type": "Purified Water",
        "water_volume_liters": 40.0,
        "verification_method": "Swab Test",
        "verification_result": None,
        "residue_limit_ppm": 5.0,
        "residue_found_ppm": None,
        "remarks": "Scheduled deep clean of FBD unloading station",
    },
    # === TABLET LINE A - BLENDING ===
    {
        "record_id": "CLR-009",
        "equipment_id": "WS-TAB-06-02",
        "workstation_id": "WS-TAB-06-02",
        "stage_id": "STAGE-04",
        "line_id": "LINE-TAB-001",
        "cleaning_type": "Post-Production",
        "cleaning_method": "CIP",
        "status": "Completed",
        "performed_by": "Blending Operator",
        "previous_product": "Tablet BN-2401",
        "current_product": "Tablet BN-2402",
        "water_type": "Purified Water",
        "water_volume_liters": 35.0,
        "verification_method": "Swab Test",
        "verification_result": "Pass",
        "residue_limit_ppm": 8.0,
        "residue_found_ppm": 1.9,
        "remarks": "Blender CIP cycle completed, swab test passed",
    },
    {
        "record_id": "CLR-010",
        "equipment_id": "WS-TAB-06-03",
        "workstation_id": "WS-TAB-06-03",
        "stage_id": "STAGE-04",
        "line_id": "LINE-TAB-001",
        "cleaning_type": "Routine",
        "cleaning_method": "Manual",
        "status": "Completed",
        "performed_by": "Blending Operator",
        "previous_product": "Tablet BN-2402",
        "current_product": "Tablet BN-2403",
        "water_type": "Purified Water",
        "water_volume_liters": 5.0,
        "verification_method": "Visual Inspection",
        "verification_result": "Pass",
        "residue_limit_ppm": 10.0,
        "residue_found_ppm": 0.8,
        "remarks": "Lubrication station quick clean",
    },
    # === TABLET LINE A - COMPRESSION ===
    {
        "record_id": "CLR-011",
        "equipment_id": "WS-TAB-07-01",
        "workstation_id": "WS-TAB-07-01",
        "stage_id": "STAGE-05",
        "line_id": "LINE-TAB-001",
        "cleaning_type": "Changeover",
        "cleaning_method": "Manual",
        "status": "Completed",
        "performed_by": "Compression Operator",
        "previous_product": "Tablet BN-2401",
        "current_product": "Tablet BN-2402",
        "water_type": "Purified Water",
        "water_volume_liters": 20.0,
        "verification_method": "Swab Test",
        "verification_result": "Pass",
        "residue_limit_ppm": 10.0,
        "residue_found_ppm": 2.8,
        "remarks": "Tablet press changeover cleaning completed",
    },
    {
        "record_id": "CLR-012",
        "equipment_id": "WS-TAB-07-03",
        "workstation_id": "WS-TAB-07-03",
        "stage_id": "STAGE-05",
        "line_id": "LINE-TAB-001",
        "cleaning_type": "Routine",
        "cleaning_method": "Manual",
        "status": "Completed",
        "performed_by": "Compression Operator",
        "previous_product": "Tablet BN-2402",
        "current_product": "Tablet BN-2403",
        "water_type": "Purified Water",
        "water_volume_liters": 10.0,
        "verification_method": "Visual Inspection",
        "verification_result": "Pass",
        "residue_limit_ppm": 10.0,
        "residue_found_ppm": 1.0,
        "remarks": "Deduster cleaned and inspected",
    },
    # === TABLET LINE A - COATING ===
    {
        "record_id": "CLR-013",
        "equipment_id": "WS-TAB-08-01",
        "workstation_id": "WS-TAB-08-01",
        "stage_id": "STAGE-06",
        "line_id": "LINE-TAB-001",
        "cleaning_type": "Post-Production",
        "cleaning_method": "CIP",
        "status": "Completed",
        "performed_by": "Coating Operator",
        "previous_product": "Tablet BN-2401",
        "current_product": "Tablet BN-2402",
        "water_type": "Purified Water",
        "water_volume_liters": 60.0,
        "verification_method": "Swab Test",
        "verification_result": "Pass",
        "residue_limit_ppm": 5.0,
        "residue_found_ppm": 0.9,
        "remarks": "Coating pan CIP completed, pan cleaned",
    },
    {
        "record_id": "CLR-014",
        "equipment_id": "WS-TAB-08-02",
        "workstation_id": "WS-TAB-08-02",
        "stage_id": "STAGE-06",
        "line_id": "LINE-TAB-001",
        "cleaning_type": "Routine",
        "cleaning_method": "Manual",
        "status": "Completed",
        "performed_by": "Coating Operator",
        "previous_product": "Tablet BN-2402",
        "current_product": "Tablet BN-2403",
        "water_type": "Purified Water",
        "water_volume_liters": 8.0,
        "verification_method": "Visual Inspection",
        "verification_result": "Pass",
        "residue_limit_ppm": 10.0,
        "residue_found_ppm": 0.5,
        "remarks": "Solution prep vessel cleaned",
    },
    # === TABLET LINE A - INSPECTION ===
    {
        "record_id": "CLR-015",
        "equipment_id": "WS-TAB-09-01",
        "workstation_id": "WS-TAB-09-01",
        "stage_id": "STAGE-07",
        "line_id": "LINE-TAB-001",
        "cleaning_type": "Routine",
        "cleaning_method": "Manual",
        "status": "Completed",
        "performed_by": "Inspection Operator",
        "previous_product": "Tablet BN-2401",
        "current_product": "Tablet BN-2402",
        "water_type": "Purified Water",
        "water_volume_liters": 5.0,
        "verification_method": "Visual Inspection",
        "verification_result": "Pass",
        "residue_limit_ppm": 10.0,
        "residue_found_ppm": 0.3,
        "remarks": "Visual inspection station cleaned",
    },
    {
        "record_id": "CLR-016",
        "equipment_id": "WS-TAB-09-02",
        "workstation_id": "WS-TAB-09-02",
        "stage_id": "STAGE-07",
        "line_id": "LINE-TAB-001",
        "cleaning_type": "Routine",
        "cleaning_method": "Manual",
        "status": "Completed",
        "performed_by": "Inspection Operator",
        "previous_product": "Tablet BN-2402",
        "current_product": "Tablet BN-2403",
        "water_type": "Purified Water",
        "water_volume_liters": 3.0,
        "verification_method": "Visual Inspection",
        "verification_result": "Pass",
        "residue_limit_ppm": 10.0,
        "residue_found_ppm": 0.2,
        "remarks": "Metal detector cleaning completed",
    },
    # === TABLET LINE A - PACKAGING ===
    {
        "record_id": "CLR-017",
        "equipment_id": "WS-TAB-10-01",
        "workstation_id": "WS-TAB-10-01",
        "stage_id": "STAGE-08",
        "line_id": "LINE-TAB-001",
        "cleaning_type": "Changeover",
        "cleaning_method": "Manual",
        "status": "Completed",
        "performed_by": "Packaging Operator",
        "previous_product": "Tablet BN-2401",
        "current_product": "Tablet BN-2402",
        "water_type": "Purified Water",
        "water_volume_liters": 10.0,
        "verification_method": "Visual Inspection",
        "verification_result": "Pass",
        "residue_limit_ppm": 5.0,
        "residue_found_ppm": 0.4,
        "remarks": "Blister machine changeover cleaning",
    },
    {
        "record_id": "CLR-018",
        "equipment_id": "WS-TAB-10-02",
        "workstation_id": "WS-TAB-10-02",
        "stage_id": "STAGE-08",
        "line_id": "LINE-TAB-001",
        "cleaning_type": "Routine",
        "cleaning_method": "Spray Wash",
        "status": "Completed",
        "performed_by": "Packaging Operator",
        "previous_product": "Tablet BN-2402",
        "current_product": "Tablet BN-2403",
        "water_type": "Purified Water",
        "water_volume_liters": 15.0,
        "verification_method": "Visual Inspection",
        "verification_result": "Pass",
        "residue_limit_ppm": 5.0,
        "residue_found_ppm": 0.3,
        "remarks": "Bottle filler cleaned",
    },
    # === CAPSULE LINE B - DISPENSING ===
    {
        "record_id": "CLR-019",
        "equipment_id": "WS-CAP-01-01",
        "workstation_id": "WS-CAP-01-01",
        "stage_id": "STAGE-CAP-01",
        "line_id": "LINE-CAP-001",
        "cleaning_type": "Post-Production",
        "cleaning_method": "Manual",
        "status": "Completed",
        "performed_by": "Dispensing Operator",
        "previous_product": "Capsule BN-2501",
        "current_product": "Capsule BN-2502",
        "water_type": "Purified Water",
        "water_volume_liters": 18.0,
        "verification_method": "Swab Test",
        "verification_result": "Pass",
        "residue_limit_ppm": 10.0,
        "residue_found_ppm": 1.6,
        "remarks": "Capsule line sampling booth cleaned",
    },
    # === CAPSULE LINE B - SIFTING/MILLING ===
    {
        "record_id": "CLR-020",
        "equipment_id": "WS-CAP-02-01",
        "workstation_id": "WS-CAP-02-01",
        "stage_id": "STAGE-CAP-02",
        "line_id": "LINE-CAP-001",
        "cleaning_type": "Post-Production",
        "cleaning_method": "Manual",
        "status": "Completed",
        "performed_by": "Milling Operator",
        "previous_product": "Capsule BN-2501",
        "current_product": "Capsule BN-2502",
        "water_type": "Purified Water",
        "water_volume_liters": 20.0,
        "verification_method": "Visual Inspection",
        "verification_result": "Pass",
        "residue_limit_ppm": 12.0,
        "residue_found_ppm": 2.0,
        "remarks": "Sifter cleaned for capsule line",
    },
    {
        "record_id": "CLR-021",
        "equipment_id": "WS-CAP-02-03",
        "workstation_id": "WS-CAP-02-03",
        "stage_id": "STAGE-CAP-02",
        "line_id": "LINE-CAP-001",
        "cleaning_type": "Post-Production",
        "cleaning_method": "Manual",
        "status": "In Progress",
        "performed_by": "Milling Operator",
        "previous_product": "Capsule BN-2501",
        "current_product": "Capsule BN-2502",
        "water_type": "Purified Water",
        "water_volume_liters": 8.0,
        "verification_method": "Visual Inspection",
        "verification_result": None,
        "residue_limit_ppm": 10.0,
        "residue_found_ppm": None,
        "remarks": "Vibro sifter cleaning in progress",
    },
    # === CAPSULE LINE B - GRANULATION ===
    {
        "record_id": "CLR-022",
        "equipment_id": "WS-CAP-03-01",
        "workstation_id": "WS-CAP-03-01",
        "stage_id": "STAGE-CAP-03",
        "line_id": "LINE-CAP-001",
        "cleaning_type": "Post-Production",
        "cleaning_method": "CIP",
        "status": "Completed",
        "performed_by": "Granulation Operator",
        "previous_product": "Capsule BN-2501",
        "current_product": "Capsule BN-2502",
        "water_type": "Purified Water",
        "water_volume_liters": 45.0,
        "verification_method": "Swab Test",
        "verification_result": "Pass",
        "residue_limit_ppm": 10.0,
        "residue_found_ppm": 2.0,
        "remarks": "RMG CIP completed for capsule line",
    },
    # === CAPSULE LINE B - BLENDING ===
    {
        "record_id": "CLR-023",
        "equipment_id": "WS-CAP-06-02",
        "workstation_id": "WS-CAP-06-02",
        "stage_id": "STAGE-CAP-06",
        "line_id": "LINE-CAP-001",
        "cleaning_type": "Post-Production",
        "cleaning_method": "CIP",
        "status": "Completed",
        "performed_by": "Blending Operator",
        "previous_product": "Capsule BN-2501",
        "current_product": "Capsule BN-2502",
        "water_type": "Purified Water",
        "water_volume_liters": 30.0,
        "verification_method": "Swab Test",
        "verification_result": "Pass",
        "residue_limit_ppm": 8.0,
        "residue_found_ppm": 1.5,
        "remarks": "Blender CIP for capsule line completed",
    },
    # === CAPSULE LINE B - FILLING ===
    {
        "record_id": "CLR-024",
        "equipment_id": "WS-CAP-07-01",
        "workstation_id": "WS-CAP-07-01",
        "stage_id": "STAGE-CAP-07",
        "line_id": "LINE-CAP-001",
        "cleaning_type": "Changeover",
        "cleaning_method": "Manual",
        "status": "Completed",
        "performed_by": "Capsule Filling Operator",
        "previous_product": "Capsule BN-2501",
        "current_product": "Capsule BN-2502",
        "water_type": "Purified Water",
        "water_volume_liters": 15.0,
        "verification_method": "Swab Test",
        "verification_result": "Pass",
        "residue_limit_ppm": 8.0,
        "residue_found_ppm": 1.8,
        "remarks": "Capsule filler changeover cleaning",
    },
    # === CAPSULE LINE B - INSPECTION ===
    {
        "record_id": "CLR-025",
        "equipment_id": "WS-CAP-09-01",
        "workstation_id": "WS-CAP-09-01",
        "stage_id": "STAGE-CAP-09",
        "line_id": "LINE-CAP-001",
        "cleaning_type": "Routine",
        "cleaning_method": "Manual",
        "status": "Completed",
        "performed_by": "Inspection Operator",
        "previous_product": "Capsule BN-2502",
        "current_product": "Capsule BN-2503",
        "water_type": "Purified Water",
        "water_volume_liters": 5.0,
        "verification_method": "Visual Inspection",
        "verification_result": "Pass",
        "residue_limit_ppm": 10.0,
        "residue_found_ppm": 0.4,
        "remarks": "Visual inspection station cleaned",
    },
    # === PLANT LEVEL - HVAC ===
    {
        "record_id": "CLR-026",
        "equipment_id": "WS-TAB-08-03",
        "workstation_id": "WS-TAB-08-03",
        "stage_id": "STAGE-06",
        "line_id": "LINE-TAB-001",
        "cleaning_type": "Deep Clean",
        "cleaning_method": "Manual",
        "status": "Completed",
        "performed_by": "HVAC Technician",
        "previous_product": None,
        "current_product": None,
        "water_type": "Purified Water",
        "water_volume_liters": 100.0,
        "verification_method": "Visual Inspection",
        "verification_result": "Pass",
        "residue_limit_ppm": None,
        "residue_found_ppm": None,
        "remarks": "AHU ductwork deep cleaning completed",
    },
    {
        "record_id": "CLR-027",
        "equipment_id": "WS-TAB-01-01",
        "workstation_id": "WS-TAB-01-01",
        "stage_id": "STAGE-01",
        "line_id": "LINE-TAB-001",
        "cleaning_type": "Sanitization",
        "cleaning_method": "Spray Wash",
        "status": "Scheduled",
        "performed_by": "HVAC Technician",
        "previous_product": None,
        "current_product": None,
        "water_type": "Purified Water",
        "water_volume_liters": 25.0,
        "verification_method": "Swab Test",
        "verification_result": None,
        "residue_limit_ppm": 2.0,
        "residue_found_ppm": None,
        "remarks": "Scheduled monthly sanitization of LAF booth",
    },
    # === CAPSULE LINE B - ADDITIONAL ===
    {
        "record_id": "CLR-028",
        "equipment_id": "WS-CAP-05-01",
        "workstation_id": "WS-CAP-05-01",
        "stage_id": "STAGE-CAP-05",
        "line_id": "LINE-CAP-001",
        "cleaning_type": "Post-Production",
        "cleaning_method": "Manual",
        "status": "Completed",
        "performed_by": "Milling Operator",
        "previous_product": "Capsule BN-2501",
        "current_product": "Capsule BN-2502",
        "water_type": "Purified Water",
        "water_volume_liters": 12.0,
        "verification_method": "Visual Inspection",
        "verification_result": "Pass",
        "residue_limit_ppm": 10.0,
        "residue_found_ppm": 1.1,
        "remarks": "Post-dry co-mill cleaning",
    },
    {
        "record_id": "CLR-029",
        "equipment_id": "WS-CAP-08-01",
        "workstation_id": "WS-CAP-08-01",
        "stage_id": "STAGE-CAP-08",
        "line_id": "LINE-CAP-001",
        "cleaning_type": "Routine",
        "cleaning_method": "Manual",
        "status": "Completed",
        "performed_by": "Capsule Operator",
        "previous_product": "Capsule BN-2502",
        "current_product": "Capsule BN-2503",
        "water_type": "Purified Water",
        "water_volume_liters": 8.0,
        "verification_method": "Visual Inspection",
        "verification_result": "Pass",
        "residue_limit_ppm": 10.0,
        "residue_found_ppm": 0.6,
        "remarks": "Capsule polisher cleaned",
    },
    {
        "record_id": "CLR-030",
        "equipment_id": "WS-CAP-09-02",
        "workstation_id": "WS-CAP-09-02",
        "stage_id": "STAGE-CAP-09",
        "line_id": "LINE-CAP-001",
        "cleaning_type": "Routine",
        "cleaning_method": "Manual",
        "status": "Completed",
        "performed_by": "Inspection Operator",
        "previous_product": "Capsule BN-2502",
        "current_product": "Capsule BN-2503",
        "water_type": "Purified Water",
        "water_volume_liters": 3.0,
        "verification_method": "Visual Inspection",
        "verification_result": "Pass",
        "residue_limit_ppm": 10.0,
        "residue_found_ppm": 0.3,
        "remarks": "Metal detector cleaning completed",
    },
]


def _add_timestamps(record: dict) -> dict:
    """Add created_at/updated_at timestamps."""
    record["created_at"] = NOW
    record["updated_at"] = NOW
    return record


async def seed():
    client = AsyncIOMotorClient(settings.MONGODB_URL)
    db = client[settings.DB_NAME]

    print("Clearing existing cleaning records...")
    await db["cleaning_records"].delete_many({})

    print(f"Inserting {len(CLEANING_RECORDS)} cleaning records...")
    for record in CLEANING_RECORDS:
        record = _add_timestamps(record)
        await db["cleaning_records"].insert_one(dict(record))

    count = await db["cleaning_records"].count_documents({})
    completed = await db["cleaning_records"].count_documents({"status": "Completed"})
    in_progress = await db["cleaning_records"].count_documents({"status": "In Progress"})
    scheduled = await db["cleaning_records"].count_documents({"status": "Scheduled"})
    print(f"\nDone. {count} cleaning records seeded:")
    print(f"  Completed: {completed}")
    print(f"  In Progress: {in_progress}")
    print(f"  Scheduled: {scheduled}")

    # Verify
    sample = await db["cleaning_records"].find_one({"record_id": "CLR-005"})
    print(f"\nSample: {sample.get('cleaning_type')} | {sample.get('cleaning_method')} | {sample.get('equipment_id')}")

    client.close()


if __name__ == "__main__":
    asyncio.run(seed())
