from datetime import datetime
from typing import Optional

from pydantic import BaseModel, Field


class SupplierFinancials(BaseModel):
    supplier_id: str = Field(..., description="Unique identifier for the supplier.")
    annual_revenue: float = Field(
        ..., description="Total revenue generated by the supplier in a financial year."
    )
    currency: str = Field(
        ..., description="Currency in which financial values are reported."
    )
    net_profit_margin: float = Field(
        ..., description="Percentage of revenue that constitutes net profit."
    )
    operating_costs: float = Field(
        ...,
        description="Total operational expenses incurred by the supplier in a year.",
    )
    debt_to_equity_ratio: float = Field(
        ..., description="Ratio of supplier's total debt to its shareholder equity."
    )
    credit_rating: str = Field(
        ..., description="Supplier's creditworthiness as rated by a recognized agency."
    )
    payment_terms: str = Field(
        ...,
        description="Standard payment terms agreed upon with the supplier, for example Net 30 or Net 60.",
    )
    outstanding_balance: float = Field(
        ..., description="Amount currently owed to the supplier."
    )
    overdue_invoices: int = Field(
        ..., description="Number of unpaid invoices that are past their due date."
    )
    average_payment_delay_days: int = Field(
        ..., description="Average delay in payment beyond the agreed payment terms."
    )
    financial_health_score: float = Field(
        ..., description="Composite score reflecting the supplier's financial health."
    )
    bank_name: Optional[str] = Field(
        None, description="Name of the bank used by the supplier for transactions."
    )
    bank_account_number: Optional[str] = Field(
        None, description="Bank account number for supplier payments."
    )
    tax_identification_number: Optional[str] = Field(
        None, description="Tax ID or equivalent identification for compliance purposes."
    )
    audited_financials: bool = Field(
        ...,
        description="Indicates whether the supplier's financial statements are audited.",
    )
    last_audit_date: Optional[datetime] = Field(
        None, description="Date of the supplier's most recent financial audit."
    )
    profitability_trends: str = Field(
        ...,
        description="Summary or description of profitability trends over recent years.",
    )
    liquidity_ratio: float = Field(
        ...,
        description="Ratio of the supplier's liquid assets to its current liabilities.",
    )
    payment_methods_accepted: Optional[list[str]] = Field(
        None,
        description="List of payment methods accepted by the supplier, for example Bank Transfer or Credit.",
    )
    tax_compliance_status: bool = Field(
        ...,
        description="Indicates whether the supplier is compliant with tax regulations.",
    )
    remarks: Optional[str] = Field(
        None,
        description="Additional notes or observations about the supplier's finances.",
    )


class SupplierFinancialsCreate(SupplierFinancials):
    pass


class SupplierFinancialsUpdate(BaseModel):
    annual_revenue: Optional[float] = None
    currency: Optional[str] = None
    net_profit_margin: Optional[float] = None
    operating_costs: Optional[float] = None
    debt_to_equity_ratio: Optional[float] = None
    credit_rating: Optional[str] = None
    payment_terms: Optional[str] = None
    outstanding_balance: Optional[float] = None
    overdue_invoices: Optional[int] = None
    average_payment_delay_days: Optional[int] = None
    financial_health_score: Optional[float] = None
    bank_name: Optional[str] = None
    bank_account_number: Optional[str] = None
    tax_identification_number: Optional[str] = None
    audited_financials: Optional[bool] = None
    last_audit_date: Optional[datetime] = None
    profitability_trends: Optional[str] = None
    liquidity_ratio: Optional[float] = None
    payment_methods_accepted: Optional[list[str]] = None
    tax_compliance_status: Optional[bool] = None
    remarks: Optional[str] = None


class SupplierFinancialsResponse(SupplierFinancials):
    class Config:
        from_attributes = True


class PaginatedSupplierFinancialsResponse(BaseModel):
    total: int
    page: int
    page_size: int
    results: list[SupplierFinancialsResponse]
