"""Domain agents — auto-registered with Broca registry on import."""

from __future__ import annotations

from broca.agents.domains.personal import (
    CalendarAgent,
    EmailAgent,
    NotesAgent,
    ContactAgent,
)
from broca.agents.domains.ecommerce import (
    OrderAgent,
    CartAgent,
    CheckoutAgent,
    PaymentAgent,
    ProductAgent,
    CustomerAgent,
    PricingAgent,
    PromotionAgent,
    InventoryAgent,
    WarehouseAgent,
    ShippingAgent,
    FulfillmentAgent,
    ReturnsAgent,
    RefundAgent,
    SupplierAgent,
)
from broca.agents.domains.manufacturing import (
    ProductionAgent,
    SchedulingAgent,
    PlantAgent,
    LineAgent,
    MachineAgent,
    EquipmentAgent,
    MaintenanceAgent,
    QualityAgent,
    OEEAgent,
    InspectionAgent,
)
from broca.agents.domains.robotics import (
    RobotAgent,
    FleetAgent,
    MissionAgent,
    NavigationAgent,
    LocalizationAgent,
    MappingAgent,
    ChargingAgent,
    SafetyAgent,
    TaskAllocationAgent,
)
from broca.agents.domains.healthcare import (
    PatientAgent,
    AppointmentAgent,
    PharmacyAgent,
    LaboratoryAgent,
    ClinicalWorkflowAgent,
)
from broca.agents.domains.finance import (
    InvoiceAgent,
    AccountingAgent,
    RiskAgent,
    FraudAgent,
)
from broca.agents.domains.banking import (
    AccountAgent,
    TransactionAgent,
    KYCAgent,
    AMLAgent,
    BankingComplianceAgent,
)
from broca.agents.domains.insurance import (
    ClaimAgent,
    InsurancePolicyAgent,
    UnderwritingAgent,
)
from broca.agents.domains.supply_chain import (
    ProcurementAgent,
    PurchaseOrderAgent,
    LogisticsAgent,
    DistributionAgent,
)
from broca.agents.domains.energy import (
    GridAgent,
    UtilityAgent,
    EnergyAssetAgent,
    OutageAgent,
)
from broca.agents.domains.telecom import (
    NetworkAgent,
    FaultAgent,
    ProvisioningAgent,
)
from broca.agents.domains.aviation import (
    FlightAgent,
    CrewAgent,
    AircraftAgent,
)
from broca.agents.domains.automotive import (
    VehicleAgent,
    DealerAgent,
)
from broca.agents.domains.construction import (
    ConstructionAgent,
    SiteAgent,
    EquipmentSchedulingAgent,
)
from broca.agents.domains.government import (
    CitizenAgent,
    PermitAgent,
    CaseManagementAgent,
)
from broca.agents.domains.legal import (
    ContractAgent,
    ClauseAgent,
    LitigationAgent,
    LegalResearchAgent,
    DocumentReviewAgent,
    IPAgent,
    PrivacyAgent,
    RegulatoryAgent,
)
from broca.agents.domains.hr import (
    EmployeeAgent,
    RecruitingAgent,
    InterviewAgent,
    PayrollAgent,
    LeaveAgent,
    BenefitsAgent,
    PerformanceAgent,
    OnboardingAgent,
    OffboardingAgent,
    OrganizationAgent,
)
from broca.agents.domains.sales import (
    LeadAgent,
    OpportunityAgent,
    CRMSearchAgent,
    QuoteAgent,
    ProposalAgent,
    SalesForecastAgent,
    TerritoryAgent,
    CommissionAgent,
)
from broca.agents.domains.marketing import (
    CampaignAgent,
    AudienceAgent,
    ContentAgent,
    SEOAgent,
    MarketingAnalyticsAgent,
    SocialMediaAgent,
    BrandAgent,
    EmailCampaignAgent,
    CustomerJourneyAgent,
)
from broca.agents.domains.customer_success import (
    CustomerSuccessAgent,
    TicketAgent,
    EscalationAgent,
    SLAAgent,
    FeedbackAgent,
    SurveyAgent,
)
from broca.agents.domains.retail import (
    POSAgent,
    LoyaltyAgent,
    StoreAgent,
    ShelfAgent,
    ReplenishmentAgent,
)
from broca.agents.domains.real_estate import (
    PropertyAgent,
    LeaseAgent,
    TenantAgent,
    MortgageAgent,
    FacilityAgent,
)
from broca.agents.domains.hospitality import (
    ReservationAgent,
    GuestAgent,
    HousekeepingAgent,
    ConciergeAgent,
    RoomAgent,
    HospitalityEventAgent,
)
from broca.agents.domains.education import (
    StudentAgent,
    CourseAgent,
    CurriculumAgent,
    AssessmentAgent,
    AttendanceAgent,
    ExaminationAgent,
    LearningPathAgent,
)
from broca.agents.domains.research import (
    LiteratureAgent,
    CitationAgent,
    ExperimentAgent,
    DatasetAgent,
    HypothesisAgent,
    PublicationAgent,
)
from broca.agents.domains.pharma import (
    ClinicalTrialAgent,
    DrugDiscoveryAgent,
    RegulatorySubmissionAgent,
    PharmacovigilanceAgent,
)
from broca.agents.domains.agriculture import (
    FarmAgent,
    CropAgent,
    IrrigationAgent,
    LivestockAgent,
    HarvestAgent,
    WeatherAgent,
)
from broca.agents.domains.mining import (
    MineAgent,
    EquipmentHealthAgent,
    ExtractionAgent,
    MiningSafetyInspectionAgent,
)
from broca.agents.domains.smart_cities import (
    TrafficAgent,
    ParkingAgent,
    UtilityMonitoringAgent,
    EmergencyResponseAgent,
    WasteManagementAgent,
)
from broca.agents.domains.security import (
    SecurityIdentityAgent,
    AccessControlAgent,
    ThreatDetectionAgent,
    IncidentResponseAgent,
    VulnerabilityAgent,
    SecurityAuditAgent,
)
from broca.agents.domains.ai_engineering import (
    AIDatasetAgent,
    TrainingAgent,
    EvaluationAgent,
    PromptAgent,
    ModelAgent,
    FineTuningAgent,
    BenchmarkAgent,
    AIDeploymentAgent,
)
from broca.agents.domains.software_engineering import (
    RequirementsAgent as SERequirementsAgent,
    ArchitectureAgent,
    DesignAgent,
    DomainModelAgent,
    APIDesignAgent,
    ServiceAgent as SEServiceAgent,
    IntegrationAgent,
    DocumentationAgent,
)
from broca.agents.domains.data_engineering import (
    PipelineAgent,
    ETLAGent,
    DataQualityAgent,
    CatalogAgent,
    LineageAgent,
    DataWarehouseAgent,
    StreamingAgent,
)
from broca.agents.domains.analytics import (
    DashboardAgent,
    KPIAgent,
    ForecastAgent,
    ReportingAgent,
    AlertingAgent,
)
from broca.agents.domains.cognitive import (
    CognitivePlannerAgent,
    CognitiveWorkflowAgent,
    CognitiveKnowledgeAgent,
    CognitiveMemoryAgent,
    CognitiveSearchAgent,
    CognitiveDiscoveryAgent,
    CognitiveClassificationAgent,
    CognitiveRetrievalAgent,
    CognitiveReasoningAgent,
    CognitiveSimulationAgent,
    CognitiveLearningAgent,
    CognitiveObservationAgent,
    CognitivePolicyAgent,
    CognitiveGraphAgent,
    CognitiveGraphMutationAgent,
    CognitiveConsensusAgent,
    CognitiveExplanationAgent,
    CognitiveAuditAgent,
    CognitiveValidationAgent,
    CognitiveOptimizationAgent,
    CognitiveSchedulingAgent,
    CognitiveNotificationAgent,
    CognitiveStorageAgent,
    CognitiveSecurityAgent,
    CognitiveIdentityAgent,
    CognitiveQAAgent,
    CognitivePromptAgent,
    CognitiveGraphStoreAgent,
    CognitivePolicyControlAgent,
    CognitiveObservabilityAgent,
    CognitiveDataRoutingAgent,
    CognitiveOQLAgent,
    CognitiveWorkflowOrchestratorAgent,
    CognitiveEvidenceFusionAgent,
)

ALL_DOMAIN_AGENTS = [
    # Personal Productivity
    CalendarAgent,
    EmailAgent,
    NotesAgent,
    ContactAgent,
    # Ecommerce
    OrderAgent,
    CartAgent,
    CheckoutAgent,
    PaymentAgent,
    ProductAgent,
    CustomerAgent,
    PricingAgent,
    PromotionAgent,
    InventoryAgent,
    WarehouseAgent,
    ShippingAgent,
    FulfillmentAgent,
    ReturnsAgent,
    RefundAgent,
    SupplierAgent,
    # Manufacturing
    ProductionAgent,
    SchedulingAgent,
    PlantAgent,
    LineAgent,
    MachineAgent,
    EquipmentAgent,
    MaintenanceAgent,
    QualityAgent,
    OEEAgent,
    InspectionAgent,
    # Robotics
    RobotAgent,
    FleetAgent,
    MissionAgent,
    NavigationAgent,
    LocalizationAgent,
    MappingAgent,
    ChargingAgent,
    SafetyAgent,
    TaskAllocationAgent,
    # Healthcare
    PatientAgent,
    AppointmentAgent,
    PharmacyAgent,
    LaboratoryAgent,
    ClinicalWorkflowAgent,
    # Finance
    InvoiceAgent,
    AccountingAgent,
    RiskAgent,
    FraudAgent,
    # Banking
    AccountAgent,
    TransactionAgent,
    KYCAgent,
    AMLAgent,
    BankingComplianceAgent,
    # Insurance
    ClaimAgent,
    InsurancePolicyAgent,
    UnderwritingAgent,
    # Supply Chain
    ProcurementAgent,
    PurchaseOrderAgent,
    LogisticsAgent,
    DistributionAgent,
    # Energy
    GridAgent,
    UtilityAgent,
    EnergyAssetAgent,
    OutageAgent,
    # Telecom
    NetworkAgent,
    FaultAgent,
    ProvisioningAgent,
    # Aviation
    FlightAgent,
    CrewAgent,
    AircraftAgent,
    # Automotive
    VehicleAgent,
    DealerAgent,
    # Construction
    ConstructionAgent,
    SiteAgent,
    EquipmentSchedulingAgent,
    # Government
    CitizenAgent,
    PermitAgent,
    CaseManagementAgent,
    # Legal
    ContractAgent,
    ClauseAgent,
    LitigationAgent,
    LegalResearchAgent,
    DocumentReviewAgent,
    IPAgent,
    PrivacyAgent,
    RegulatoryAgent,
    # HR
    EmployeeAgent,
    RecruitingAgent,
    InterviewAgent,
    PayrollAgent,
    LeaveAgent,
    BenefitsAgent,
    PerformanceAgent,
    OnboardingAgent,
    OffboardingAgent,
    OrganizationAgent,
    # Sales
    LeadAgent,
    OpportunityAgent,
    CRMSearchAgent,
    QuoteAgent,
    ProposalAgent,
    SalesForecastAgent,
    TerritoryAgent,
    CommissionAgent,
    # Marketing
    CampaignAgent,
    AudienceAgent,
    ContentAgent,
    SEOAgent,
    MarketingAnalyticsAgent,
    SocialMediaAgent,
    BrandAgent,
    EmailCampaignAgent,
    CustomerJourneyAgent,
    # Customer Success
    CustomerSuccessAgent,
    TicketAgent,
    EscalationAgent,
    SLAAgent,
    FeedbackAgent,
    SurveyAgent,
    # Retail
    POSAgent,
    LoyaltyAgent,
    StoreAgent,
    ShelfAgent,
    ReplenishmentAgent,
    # Real Estate
    PropertyAgent,
    LeaseAgent,
    TenantAgent,
    MortgageAgent,
    FacilityAgent,
    # Hospitality
    ReservationAgent,
    GuestAgent,
    HousekeepingAgent,
    ConciergeAgent,
    RoomAgent,
    HospitalityEventAgent,
    # Education
    StudentAgent,
    CourseAgent,
    CurriculumAgent,
    AssessmentAgent,
    AttendanceAgent,
    ExaminationAgent,
    LearningPathAgent,
    # Research
    LiteratureAgent,
    CitationAgent,
    ExperimentAgent,
    DatasetAgent,
    HypothesisAgent,
    PublicationAgent,
    # Pharma
    ClinicalTrialAgent,
    DrugDiscoveryAgent,
    RegulatorySubmissionAgent,
    PharmacovigilanceAgent,
    # Agriculture
    FarmAgent,
    CropAgent,
    IrrigationAgent,
    LivestockAgent,
    HarvestAgent,
    WeatherAgent,
    # Mining
    MineAgent,
    EquipmentHealthAgent,
    ExtractionAgent,
    MiningSafetyInspectionAgent,
    # Smart Cities
    TrafficAgent,
    ParkingAgent,
    UtilityMonitoringAgent,
    EmergencyResponseAgent,
    WasteManagementAgent,
    # Security
    SecurityIdentityAgent,
    AccessControlAgent,
    ThreatDetectionAgent,
    IncidentResponseAgent,
    VulnerabilityAgent,
    SecurityAuditAgent,
    # AI Engineering
    AIDatasetAgent,
    TrainingAgent,
    EvaluationAgent,
    PromptAgent,
    ModelAgent,
    FineTuningAgent,
    BenchmarkAgent,
    AIDeploymentAgent,
    # Software Engineering
    SERequirementsAgent,
    ArchitectureAgent,
    DesignAgent,
    DomainModelAgent,
    APIDesignAgent,
    SEServiceAgent,
    IntegrationAgent,
    DocumentationAgent,
    # Data Engineering
    PipelineAgent,
    ETLAGent,
    DataQualityAgent,
    CatalogAgent,
    LineageAgent,
    DataWarehouseAgent,
    StreamingAgent,
    # Analytics
    DashboardAgent,
    KPIAgent,
    ForecastAgent,
    ReportingAgent,
    AlertingAgent,
    # Cognitive
    CognitivePlannerAgent,
    CognitiveWorkflowAgent,
    CognitiveKnowledgeAgent,
    CognitiveMemoryAgent,
    CognitiveSearchAgent,
    CognitiveDiscoveryAgent,
    CognitiveClassificationAgent,
    CognitiveRetrievalAgent,
    CognitiveReasoningAgent,
    CognitiveSimulationAgent,
    CognitiveLearningAgent,
    CognitiveObservationAgent,
    CognitivePolicyAgent,
    CognitiveGraphAgent,
    CognitiveGraphMutationAgent,
    CognitiveConsensusAgent,
    CognitiveExplanationAgent,
    CognitiveAuditAgent,
    CognitiveValidationAgent,
    CognitiveOptimizationAgent,
    CognitiveSchedulingAgent,
    CognitiveNotificationAgent,
    CognitiveStorageAgent,
    CognitiveSecurityAgent,
    CognitiveIdentityAgent,
    CognitiveQAAgent,
    CognitivePromptAgent,
    CognitiveGraphStoreAgent,
    CognitivePolicyControlAgent,
    CognitiveObservabilityAgent,
    CognitiveDataRoutingAgent,
    CognitiveOQLAgent,
    CognitiveWorkflowOrchestratorAgent,
    CognitiveEvidenceFusionAgent,
]
