"""Tests for BellmanPolicy workload registration — Plan → Register → Retrieve → Execute.

Verifies the lifecycle:
  1. Graph generated by planner
  2. Registered with BellmanPolicy
  3. Retrieved by executor
  4. Q-values NOT updated during registration (only after execution)
"""

import os
import sys

_repo = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
for _p in (_repo, os.path.join(_repo, "src")):
    if _p not in sys.path:
        sys.path.insert(0, _p)

from src.monkey_brain.kernel.fix.policy.policy import BellmanPolicy
from src.monkey_brain.kernel.plan.workload.workload import Workload, WorkloadStep


def _make_policy():
    return BellmanPolicy()


def _make_graph_workload(workload_id="pipe-test-001"):
    steps = [
        WorkloadStep(capability_name="LexerAgent", agent_name="LexerAgent"),
        WorkloadStep(capability_name="ParserAgent", agent_name="ParserAgent"),
        WorkloadStep(capability_name="CodeGeneratorAgent", agent_name="CodeGeneratorAgent"),
    ]
    w = Workload(
        workload_id=workload_id,
        steps=steps,
        metadata={"run_id": "test-run", "graph_delta": {"nodes": [], "edges": []}},
    )
    w.build_dag()
    return w


# ── Registration ──────────────────────────────────────────────────────────


def test_register_and_retrieve_workload():
    """Register a workload and retrieve it by ID."""
    policy = _make_policy()
    workload = _make_graph_workload()

    policy.register_workload(workload)

    retrieved = policy.get_workload(workload.workload_id)
    assert retrieved is not None, "Registered workload should be retrievable"
    assert retrieved.workload_id == workload.workload_id
    assert len(retrieved.steps) == 3
    assert retrieved.steps[0].capability_name == "LexerAgent"
    assert retrieved.steps[2].capability_name == "CodeGeneratorAgent"


def test_get_unknown_workload_returns_none():
    """Unknown workload ID returns None — caller falls back to default."""
    policy = _make_policy()
    assert policy.get_workload("nonexistent-id") is None


def test_register_overwrites_existing():
    """Re-registering the same workload_id replaces the old entry."""
    policy = _make_policy()
    w1 = _make_graph_workload("pipe-overwrite")
    w1.steps = [WorkloadStep(capability_name="OldAgent")]
    policy.register_workload(w1)

    w2 = _make_graph_workload("pipe-overwrite")
    w2.steps = [WorkloadStep(capability_name="NewAgent")]
    policy.register_workload(w2)

    retrieved = policy.get_workload("pipe-overwrite")
    assert retrieved.steps[0].capability_name == "NewAgent"


# ── Q-value isolation ────────────────────────────────────────────────────


def test_registration_does_not_update_q_table():
    """Registration must NOT touch Q-values — those update only after execution."""
    policy = _make_policy()
    q_before = dict(policy._q_table)

    workload = _make_graph_workload()
    policy.register_workload(workload)

    q_after = dict(policy._q_table)
    assert q_before == q_after, "Q-table must not change during registration"


def test_summary_reflects_registration():
    """summary() reports the correct registered_workloads count."""
    policy = _make_policy()
    assert policy.summary()["registered_workloads"] == 0

    policy.register_workload(_make_graph_workload("pipe-a"))
    assert policy.summary()["registered_workloads"] == 1

    policy.register_workload(_make_graph_workload("pipe-b"))
    assert policy.summary()["registered_workloads"] == 2


# ── Multiple registrations ───────────────────────────────────────────────


def test_multiple_workloads_registered_independently():
    """Each workload is stored and retrieved independently."""
    policy = _make_policy()
    wa = _make_graph_workload("pipe-alpha")
    wb = _make_graph_workload("pipe-beta")

    policy.register_workload(wa)
    policy.register_workload(wb)

    assert policy.get_workload("pipe-alpha").steps[0].capability_name == "LexerAgent"
    assert policy.get_workload("pipe-beta").steps[0].capability_name == "LexerAgent"
    assert policy.summary()["registered_workloads"] == 2


# ── DAG attached after registration ──────────────────────────────────────


def test_registered_workload_has_dag():
    """The registered workload carries a built DAG from build_dag()."""
    policy = _make_policy()
    workload = _make_graph_workload()
    assert workload.dag is not None, "build_dag() should have been called"

    policy.register_workload(workload)
    retrieved = policy.get_workload(workload.workload_id)
    assert retrieved.dag is not None


# ── End-to-end lifecycle ─────────────────────────────────────────────────


def test_plan_register_retrieve_lifecycle():
    """Simulate: plan generates graph → register → executor retrieves → execute."""
    policy = _make_policy()

    # 1. Planner generates graph_delta
    graph_delta = {
        "nodes": [
            {"id": "node_1", "name": "LexerAgent", "agent": "LexerAgent"},
            {"id": "node_2", "name": "ParserAgent", "agent": "ParserAgent"},
        ],
        "edges": [{"from": "node_1", "to": "node_2"}],
        "execution_order": [["node_1"], ["node_2"]],
    }

    # 2. Build Workload from graph_delta and register
    workload = Workload(
        workload_id="pipe-e2e-001",
        steps=[
            WorkloadStep(
                capability_name=n.get("name", ""),
                agent_name=n.get("agent", ""),
            )
            for n in graph_delta["nodes"]
        ],
        metadata={"run_id": "e2e-run", "graph_delta": graph_delta},
    )
    workload.build_dag()
    policy.register_workload(workload)

    # 3. Executor retrieves the registered workload
    retrieved = policy.get_workload("pipe-e2e-001")
    assert retrieved is not None
    assert len(retrieved.steps) == 2
    assert retrieved.steps[0].capability_name == "LexerAgent"
    assert retrieved.steps[1].capability_name == "ParserAgent"
    assert retrieved.metadata["graph_delta"]["edges"] == [{"from": "node_1", "to": "node_2"}]

    # 4. Q-table unchanged — no update during planning
    assert len(policy._q_table) == 0
